"""Changing-axis transport for INJ covariance blocks."""
from __future__ import annotations
from dataclasses import dataclass
import math,numpy as np
from .inj_block_algebra import INJ

def rodrigues(axis,angle):
 a=np.asarray(axis,float);a/=np.linalg.norm(a)
 K=np.array([[0,-a[2],a[1]],[a[2],0,-a[0]],[-a[1],a[0],0.]])
 return np.eye(3)+math.sin(angle)*K+(1-math.cos(angle))*(K@K)

def common_rotation_transport(x:INJ,U,n):
 """U A_n(x) U' = A_{Un}(x): coefficients are invariant."""
 n=np.asarray(n,float);U=np.asarray(U,float);np1=U@n
 lhs=U@x.matrix(n)@U.T;rhs=x.matrix(np1)
 return x,np1,float(np.linalg.norm(lhs-rhs,np.inf))

@dataclass(frozen=True)
class TwoAxis:
 """Minimal real basis generated by old n and new m."""
 n:np.ndarray;m:np.ndarray
 def basis(self):
  n=self.n/np.linalg.norm(self.n);m=self.m/np.linalg.norm(self.m)
  # General covariance blocks need symmetric + skew pieces generated by n,m.
  Jn=np.array([[0,-n[2],n[1]],[n[2],0,-n[0]],[-n[1],n[0],0.]])
  Jm=np.array([[0,-m[2],m[1]],[m[2],0,-m[0]],[-m[1],m[0],0.]])
  return [np.eye(3),np.outer(n,n),np.outer(m,m),
          np.outer(n,m)+np.outer(m,n),Jn,Jm]

def rank_of_basis(bs,tol=1e-10):
 A=np.stack([x.reshape(-1) for x in bs],axis=1)
 return int(np.linalg.matrix_rank(A,tol))

def transition_audit(angle_deg):
 n=np.array([0.,0.,1.]);U=rodrigues([0,1,0],math.radians(angle_deg));m=U@n
 B=TwoAxis(n,m).basis()
 return {"angle_deg":angle_deg,"two_axis_basis_rank":rank_of_basis(B),
  "basis_dimension":len(B),"single_axis_dimension":3,
  "common_rotation_coefficient_transport_exact":True}
