"""Same-execution linkage for the three principal OU-III assumptions."""
from __future__ import annotations
from typing import Iterable

from .marine_motion import MarineSample
from .imu_bias import BiasSample
from .magnetic_service import MagneticEvent


def _ids(items: Iterable[object]) -> set[str]:
    out: set[str] = set()
    for item in items:
        value = getattr(item, "history_id", None)
        if not isinstance(value, str) or not value:
            raise ValueError("every physical/proof record must carry a nonempty history_id")
        out.add(value)
    return out


def audit_same_execution(
    marine: Iterable[MarineSample],
    bias: Iterable[BiasSample],
    magnetic: Iterable[MagneticEvent],
) -> dict:
    """Require one persistent physical execution across all principal contracts.

    This is a linkage check, not a proof that independently authored records
    were generated by a physically consistent continuous trajectory.
    """
    groups = {
        "marine_motion": _ids(marine),
        "imu_bias": _ids(bias),
        "magnetic_service": _ids(magnetic),
    }
    populated = [ids for ids in groups.values() if ids]
    all_ids = set().union(*populated) if populated else set()
    failures: list[str] = []
    for name, ids in groups.items():
        if not ids:
            failures.append(f"{name}: missing principal-assumption records")
        elif len(ids) > 1:
            failures.append(f"{name}: multiple execution ids")
    if len(all_ids) != 1:
        failures.append("principal assumptions are not attached to exactly one execution")
    return {
        "same_execution_pass": not failures,
        "execution_id": next(iter(all_ids)) if len(all_ids) == 1 else None,
        "groups": {name: sorted(ids) for name, ids in groups.items()},
        "failures": failures,
        "independent_per_word_reselection_allowed": False,
        "continuous_physical_consistency_proved_by_identifier_alone": False,
    }
