"""FAST signed-primitive bound through the vibration-guard low-pass cascade.

For a discrete one-pole LP y_k=(1-a)u_k+a y_{k-1}, define d_k=y_k-u_k.
Writing u as increments of its signed primitive U and summing by parts gives a
bound depending on the primitive cap C, not on adjacent 2B jumps.

For every placed interval up to H, |integral u|<=C.  Over the guard memory
scale (<<H=60 s), the zero-initialized convolution obeys
 |y_k| <= (1-a) B h + (1-a)^2 C * sum_{j>=1} a^(j-1)
        = (1-a) B h + (1-a) C
for piecewise-held u, while |u_k| itself is not small.  What enters the
conditioned output is w(y-u); its FAST contribution can be treated as
w*(filtered_fast-fast), but w is generated by the same guard and starts at 0.

For cascaded poles we propagate the filtered FAST magnitude recursively using
the same primitive-aware first-pole bound and L-infinity contraction of later
poles. This module records the rigorous finite-window condition H exceeding the
effective truncation horizon.
"""
from __future__ import annotations
import math

def one_pole_filtered_fast_bound(alpha,dt,B,C,H):
 if not(0<=alpha<1 and dt>0 and B>=0 and C>=0 and H>0):raise ValueError("bad FAST/LP parameters")
 # Exact geometric tail beyond H uses pointwise B; inside H use primitive cap.
 n=max(1,int(math.floor(H/dt)))
 tail=(alpha**n)*B
 return (1-alpha)*B+(1-alpha)*C/dt+tail

def cascade_filtered_fast_bound(alpha,dt,B,C,H,poles):
 """Conservative: later positive unit-gain poles cannot increase L-infinity."""
 if poles<1:raise ValueError("positive poles")
 return one_pole_filtered_fast_bound(alpha,dt,B,C,H)

def lp_minus_raw_fast_bound(alpha,dt,B,C,H,poles):
 return B+cascade_filtered_fast_bound(alpha,dt,B,C,H,poles)

def audit(alpha,dt,B,C,H,poles):
 yf=cascade_filtered_fast_bound(alpha,dt,B,C,H,poles)
 return {"filtered_fast_norm_component_upper":yf,
         "lp_minus_raw_fast_component_upper":B+yf,
         "uses_signed_primitive_cap":True,"H_s":H,"C":C,"B":B,
         "tail_pointwise":alpha**max(1,int(math.floor(H/dt)))*B}

def weighted_lp_minus_raw_fast_bound(alpha,dt,B,C,H,poles,w_hi):
 """Use the better of pointwise and primitive convolution, then apply guard w."""
 if not 0<=w_hi<=1:raise ValueError("weight")
 primitive=lp_minus_raw_fast_bound(alpha,dt,B,C,H,poles)
 pointwise=2*B
 return w_hi*min(pointwise,primitive)

def comparison(alpha,dt,B,C,H,poles,w_hi):
 p=lp_minus_raw_fast_bound(alpha,dt,B,C,H,poles);q=2*B
 return {"primitive_unweighted":p,"pointwise_unweighted":q,
         "selected_unweighted":min(p,q),
         "weighted":w_hi*min(p,q),
         "primitive_improves":p<q}
