"""Fail-closed status for the single OU-III stability theorem."""
from __future__ import annotations

def status_report() -> dict:
    obligations={
        "physical_contract_formulation":True,
        "marine_regime_complete_window_contract":True,
        "stationary_observability_structure":True,
        "stationary_gyro_information_bound":True,
        "quiet_zero_residual_nominal_six_column_floor":True,
        "quiet_zero_residual_nominal_historical_covariance_upper":True,
        "quiet_zero_residual_nominal_homogeneous_linear_loss_exists":True,
        "stationary_compatible_class_practical_stability":False,
        "sound_runtime_regime_certification":False,
        "finite_transition_prefix_composition":True,
        "finite_regime_detection_and_transition_retention":False,
        "recurring_regime_storage_budget":False,
        "conditional_chronological_gyro_transport_bound":True,
        "literal_reset_inverse_nonexpansion":True,
        "conditional_inverse_frame_gyro_transport_bound":True,
        "same_prediction_cell_actual_row_factorization":True,
        "same_cell_reset_pulled_field_geometry_implication":True,
        "conditional_two_group_six_column_bound":True,
        "singular_floor_to_all_six_historical_pivots":True,
        "world_frame_historical_row_factorization":True,
        "attitude_invariant_same_cell_geometry":True,
        "literal_injection_covariance_NIS_budget":True,
        "quiet_nominal_six_column_floor_any_attitude_admitted_reference":True,
        "nominal_attitude_column_physical_transfer_given_AW_tracking":True,
        "uniform_AW_tracking_error_bound":False,
        "aggregate_world_frame_six_column_floor":False,
        "marine_attitude_excitation_numeric_qualification":False,
        "marine_attitude_excitation_implies_signed_temporal_separation":False,
        "physical_tilt_span_sampling_implication":True,
        "carried_signed_adjoint_compatibility_criterion":True,
        "source_uniform_signed_adjoint_residual_bound":False,
        "forced_data_adjoint_identity":True,
        "forced_data_adjoint_source_uniform_action_bound":False,
        "temporal_margins_to_six_historical_pivots":False,
        "construction_uniform_gyro_alias_exclusion":True,
        "jerk_to_sampled_acceleration_fidelity":True,
        "constant_attitude_stationary_alias_exclusion":True,
        "joint_physical_vector_information":True,
        "physical_LIN_prediction_metric_supply":True,
        "same_execution_linkage":True,
        "shipping_implementation_provenance":True,
        "constant_nonzero_wave_displacement_rejection":True,
        "same_history_bias_recurrence":True,
        "accepted_magnetic_information_definition":True,
        "no_heading_service_obstruction":True,
        "captured_domain_implies_finite_mag_refinement":True,
        "captured_domain_implies_finite_A21_entry":True,
        "time_varying_A21_translation_observability":True,
        "uniform_gravity_tilt_sensitivity":True,
        "uniform_A21_neutral_quotient_information_exists":False,
        "uniform_A21_controllability_exists":True,
        "A21_covariance_hard_event_compactness":False,
        "local_A21_nonlinear_small_gain_exists":False,
        "physical_qualification_composition":True,
        "assembled_sensor_and_bias_limit_qualification":False,
        "all_time_marine_motion_membership_certificate":False,
        "finite_history_dependent_capture":False,
        "capture_H18_release_retention_composition":True,
        "finite_H18_bridge_retention":False,
        "finite_reference_refinement_and_bias_release":False,
        "H18_to_A21_release_retention":False,
        "source_uniform_A21_linear_dissipativity":False,
        "source_uniform_block_factor_root_coercivity":True,
        "constructive_fixed_coordinate_A21_mu_enclosure":False,
        "LIN_endpoint_matrix_path_action":True,
        "recurring_nuisance_covariance_upper":True,
        "pre_prediction_embedded_nuisance_floor":True,
        "six_column_to_full_contraction_implication":True,
        "six_column_corrected_loss_uniform_bound":False,
        "historical_AG_readout_covariance_implication":True,
        "uniform_historical_AG_readout_action":False,
        "actual_gain_finite_error_word_composition":True,
        "joint_word_prediction_measurement_input_action":True,
        "finite_angle_source_reset_remainder":True,
        "source_covariance_projection_guard":True,
        "full_21_covariance_upper":False,
        "complete_word_covariance_energy_identity":True,
        "factorized_word_exact_reference_parity":True,
        "singular_nuisance_range_elimination":True,
        "full_state_magnetic_information_lifting":False,
        "interval_riccati_kernel_layer":True,
        "maximal_correction_covariance_order":True,
        "constructive_root_covariance_floor":True,
        "constructive_full_A21_mu_rho_enclosure":False,
        "explicit_A21_nonlinear_radius":False,
        "whole_word_float32_supply_composition":True,
        "whole_word_float32_supply_bound":False,
        "capture_release_into_explicit_A21_region":False,
        "finite_error_A21_nonlinear_remainder":False,
        "tail_prefix_retention_composition":True,
        "certified_tail_prefix_retention":False,
        "source_uniform_magnetic_service_certificate_schema":True,
        "source_uniform_magnetic_service_certificate":False,
        "implementation_and_arithmetic_totality":False,
    }
    return {
        "qualification":"OU3_SINGLE_MARINE_IMU_MAGNETIC_STABILITY_ARCHITECTURE_V2",
        "principal_assumptions":["MARINE MOTION","IMU BIAS","MAGNETIC SERVICE"],
        "quantifier":"one persistent physical execution belongs to all three assumption classes simultaneously",
        "proof_path":["construction","startup/capture","finite magnetically informed Live/H18 bridge",
                      "finite reference refinement","H18-to-A21 release",
                      "recurring magnetically informed A21 tail","regional practical stability"],
        "certified_capture_time":None,
        "required_capture_time":"history dependent T_c(h,x_0) < infinity; open under the amended marine-motion domain",
        "parallel_no_magnetometer_stability_path":False,
        "no_heading_service_result_role":"necessity lemma only",
        "shipping_filter_changed_for_proof":False,
        "physical_regimes":["STILL","TRANSITION","MOVING"],
        "regime_role":"qualification of portions of the single carried proof path, not independent estimator restarts",
        "shipping_mode_switch_enabled":False,
        "quiet_nominal_covariance_subcase":{
            "certificate":"stationary-covariance-certificate.json",
            "historical_root_independent_full_upper":True,
            "every_operation_covariance_upper":True,
            "homogeneous_linear_loss_exists":True,
            "physical_compatible_class_practical_stability":False,
            "general_moving_uniform_bound":False,
        },
        "exact_rest_detector_obstruction":{
            "identical_rest_motion_IMU_histories":True,
            "finite_entry_and_universal_finite_exit_simultaneously_possible":False,
            "stationary_robustness_of_compatible_class_refuted":False,
            "certificate":"regime-certificate.json",
        },
        "world_frame_rows":{
            "certificate":"world-frame-certificate.json",
            "source_diagnostic":"world-frame-source-feasibility.json",
            "attitude_estimate_or_error_in_six_column_geometry":False,
            "remaining_attitude_dependence":"reset discrepancies N=R_next' G R and the nominal rotation integral of R_hat' in the gyro columns",
            "same_cell_floor_from_motion_and_bias_bounds_alone":False,
            "collinear_1Hz_witness_magnetic_service_admitted":False,
            "same_cell_floor_requires_magnetic_cadence_coupling":True,
            "same_cell_two_group_uniform_floor_established":False,
            "signed_world_injection_transport_budget":False,
            "aggregate_rows_avoid_magnetic_phase_premise":True,
            "controlling_transfer_quantity":"nominal AW tracking error |a_hat-a| in the estimator world frame",
        },
        "shipping_residual_gyro_bias_hardening":True,
        "implemented_gyro_bias_norm_invariant":True,
        "complete_turn_nominal_gyro_bias_alias_excluded":True,
        "one_prediction_gyro_transport_real_source_floor":True,
        "signed_temporal_Delta_gyr_closed":False,
        "unrestricted_device_timestep_alias_exclusion":False,
        "obligations":obligations,
        "theorem_closed":all(obligations.values()),
        "regional_practical_stability_claimed":False,
        "capture_obstruction":{
            "old_domain_six_degree_capture_refuted":True,
            "old_witness_admitted_by_current_contract":False,
            "both_witness_histories_have_nonzero_motion":True,
            "all_time_real_arithmetic_magnetic_service_verified":True,
            "conditional_local_A21_stability_refuted":False,
            "shipping_divergence_claimed":False,
            "new_physical_assumption_adopted":True,
            "sampling_certificate":"sampling-fidelity.json",
            "certificate":"sampled-capture-obstruction.json",
        },
        "next_controlling_obligation":(
            "Excitation quantifies only over complete T_E windows within one physical moving episode. "
            "No excitation is demanded immediately after rest or across rest boundaries; isolated zero-rate instants do not restart an episode. "
            "T_E/theta_E remain symbolic. Exact rest/motion sensor indistinguishability blocks a sound exact-STILL detector with both finite entry and universal finite exit under the existing assumptions. "
            "Prove stationary practical stability for the whole measurement-compatible class before enabling estimator changes; the quiet attitude/accelerometer-bias ambiguity prevents exact separation and universal V<=36 capture. "
            "The exact zero-residual quiet nominal subcase now has a root-independent historical AG action, every-operation full covariance upper comparison and qualitative homogeneous linear loss, without a nonlinear physical stability conclusion. "
            "Bridge prefix composition is proved conditionally, but finite detection time, source-uniform retention and the cumulative budget across recurring switches remain open. "
            "On complete excited moving windows continue the actual signed forced adjoint with root, rotation/reference, gains, physical bias and OU history retained. "
            "Removing indefinite stillness does not repair the already-excited moving diagnostic's failed rotation and velocity-variation budgets. "
            "Chronological gyro transport plus two actual sensor-row groups now gives a conditional six-column singular floor and all six greedy pivot floors. "
            "Literal reset inverses are nonexpansive, and C=A^-1 B cancels each reset while retaining its effect on later injections; an exact relaxed reset sequence still cancels the inter-anchor gyro block, without proving shipping reachability or all-row rank loss. "
            "Applied acc/mag rows in one prediction cell factor exactly with E=0 after retaining every intervening reset. Uniform group geometry and inter-anchor transport remain open. "
            "Its reset/asynchrony/reference defect budget is not yet bounded uniformly; two temporal margins alone still do not imply six pivots. "
            "In world coordinates every historical AG row is -R_k[f_k]x[A_tilde_k R_0',B_tilde_k]: predictions leave A_tilde invariant, resets multiply it by N=R_next' G R with N'N=I+(|x|^2 I-xx')/4, and B_tilde integrates the nominal R_hat'. "
            "Same-cell geometry therefore depends only on world nominal force, committed reference and the local injection, never on attitude error. "
            "Literal injections satisfy dd'<=NIS K S K'<=NIS P_theta,theta. A 1-Hz collinear history obeys MARINE MOTION and IMU BIAS and degenerates every same-cell group while aggregate rows stay full rank; its single correction per 1-s window has nearly rank-one service information, so MAGNETIC SERVICE excludes that cadence. "
            "Jerk forbids collinearity at every instant of a cadence whose length-weighted mean gap is below 4(g h-2V/L)/J, about .051 s at h=1/5 and L=16 s. A same-cell floor therefore needs a magnetic-cadence coupling, which aggregate rows avoid. "
            "The nominal attitude columns transfer from physical transverse force on 16-s windows when the AW tracking error is below 1.12383 m/s^2; the inherited 156 m/s^2 AW ceiling would restrict sqrt(V) below about .0072. "
            "Next bound the AW tracking error and the signed world injection sum, then prove the aggregate gyro-column floor. "
            "The .5 rad/s invariant, qualified complete-turn exclusion and one-step gyro floor remain proved, not the complete signed Delta_gyr. "
            "Positive source-uniform signed margins, B_*, J_AG, full covariance upper, rho_0<1, capture/H18/release, nonlinear radius, every-prefix retention, applied magnetic-service qualification and float32 totality remain open."
        ),
    }
