"""Fail-closed status for the single OU-III stability theorem."""
from __future__ import annotations

def status_report() -> dict:
    obligations={
        "physical_contract_formulation":True,
        "quiet_absolute_entry_obstruction":True,
        "quiet_constant_record_fibre":True,
        "quiet_centered_slow_fast_source_charge":True,
        "quiet_uniform_covariance_metric_tube":False,
        "moving_constant_bias_sensor_compatibility":True,
        "same_record_full_metric_pair_lower_comparison":True,
        "planar_moving_all_time_magnetic_service_admission":False,
        "planar_admission_cell_transport_algebra":True,
        "planar_guard_inactive_all_time_real_arithmetic":True,
        "planar_generated_tuner_clock_feedback_ports_one_way":True,
        "planar_guard_float32_transfer":False,
        "planar_literal_frontend_interval_binding":False,
        "planar_private_Mahony_tube_source_bound":False,
        "planar_joint_mean_covariance_tuner_clock_cell":False,
        "planar_complete_nonlinear_derivative_certified":False,
        "planar_uniform_quotient_covariance_cross_gains":False,
        "planar_uniform_physical_gauge_amplitude_bound":False,
        "planar_all_future_service_information_perturbation":False,
        "ideal_frontend_reference_recursions_available":True,
        "planar_moving_full_shipping_counterexample_admitted":False,
        "two_timescale_accel_and_gyro_contract_formulation":True,
        "two_epoch_same_history_bias_envelope":True,
        "signed_fast_accumulation_functional_identity":True,
        "fast_accel_temporal_device_qualification":False,
        "fast_gyro_temporal_device_qualification":False,
        "assembled_slow_fast_decomposition_qualification":False,
        "two_timescale_joint_physical_gauge_exclusion":False,
        "displacement_excitation_to_full_moving_compatibility_exclusion":False,
        "two_timescale_source_uniform_finite_error_supply":False,
        "marine_regime_complete_window_contract":True,
        "marine_displacement_excitation_contract":True,
        "marine_displacement_excitation_numeric_qualification":True,
        "zero_translation_moving_alias_excluded":True,
        "displacement_span_signed_kinematic_moment":True,
        "displacement_four_S_boundary_mismatch_identified":True,
        "displacement_boundary_velocity_completion":True,
        "displacement_boundary_velocity_LIN_action_bound":True,
        "held_H18_LIN_structural_detectability":True,
        "held_H18_all_time_covariance_coefficient_compactness":True,
        "held_H18_uniform_homogeneous_LIN_strictness":True,
        "held_H18_uniform_LIN_BIBO":True,
        "held_H18_affine_input_bound":True,
        "stationary_observability_structure":True,
        "stationary_gyro_information_bound":True,
        "quiet_zero_residual_nominal_six_column_floor":True,
        "quiet_zero_residual_nominal_historical_covariance_upper":True,
        "quiet_zero_residual_nominal_homogeneous_linear_loss_exists":True,
        "stationary_compatible_class_practical_stability":False,
        "sound_runtime_regime_certification":False,
        "finite_transition_prefix_composition":True,
        "finite_regime_detection_and_transition_retention":False,
        "recurring_regime_storage_budget":False,
        "conditional_chronological_gyro_transport_bound":True,
        "literal_reset_inverse_nonexpansion":True,
        "conditional_inverse_frame_gyro_transport_bound":True,
        "same_prediction_cell_actual_row_factorization":True,
        "same_cell_reset_pulled_field_geometry_implication":True,
        "conditional_two_group_six_column_bound":True,
        "singular_floor_to_all_six_historical_pivots":True,
        "world_frame_historical_row_factorization":True,
        "attitude_invariant_same_cell_geometry":True,
        "literal_injection_covariance_NIS_budget":True,
        "quiet_nominal_six_column_floor_any_attitude_admitted_reference":True,
        "nominal_attitude_column_physical_transfer_given_AW_tracking":True,
        "sharp_isotropic_sync_AW_covariance_ceiling":True,
        "uniform_AW_tracking_error_bound":False,
        "source_uniform_Astar_real_arithmetic_signed_mean":True,
        "source_uniform_Astar_positive_attitude_gram_exists":True,
        "shipping_closed_persistent_ZG_excluded_real_arithmetic":True,
        "complete_word_zero_dissipation_invariant_set_trivial_on_qualified_moving_superwords":True,
        "complete_regular_word_joint_zero_action_kernel_nullity_at_most_one":True,
        "surviving_joint_kernel_line_has_unique_BA_for_attitude_amplitude":True,
        "literal_event_strata_regressed":True,
        "qualitative_finite_superword_strict_dissipation_exists":True,
        "compact_outer_A21_release_region_exists":True,
        "finite_linked_supply_supremum_on_compact_outer_class_exists":True,
        "finite_practical_outer_absorbing_radius_exists":True,
        "entry_into_local_0p15_ball_proved":False,
        "Astar_plus_magnetic_implies_full_six_column_rank":False,
        "real_arithmetic_AW_source_transfer_closed_for_Astar":True,
        "next_six_column_route":"retired same-cell localization; use aggregate A* plus magnetic-service kernel and word-dependent BA graph",
        "nominal_signed_mean_attitude_columns":True,
        "pointwise_physical_AW_tracking_premise_refuted_on_admitted_history":True,
        "source_uniform_nominal_AW_window_statistics":False,
        "signed_injection_rotation_identity":True,
        "third_order_literal_reset_factor":True,
        "source_uniform_half_angle_injection_transport":False,
        "magnetic_service_tube_monotone_field_axis":True,
        "injection_free_aggregate_six_column_floor_given_nominal_window_premises":True,
        "aggregate_world_frame_six_column_floor":False,
        "practical_rho0_margin_from_six_column_floor":False,
        "marine_attitude_excitation_numeric_qualification":True,
        "marine_attitude_excitation_implies_signed_temporal_separation":False,
        "physical_tilt_span_sampling_implication":True,
        "carried_signed_adjoint_compatibility_criterion":True,
        "source_uniform_signed_adjoint_residual_bound":False,
        "forced_data_adjoint_identity":True,
        "forced_data_adjoint_source_uniform_action_bound":False,
        "temporal_margins_to_six_historical_pivots":False,
        "construction_uniform_gyro_alias_exclusion":True,
        "jerk_to_sampled_acceleration_fidelity":True,
        "constant_attitude_stationary_alias_exclusion":True,
        "joint_physical_vector_information":True,
        "physical_LIN_prediction_metric_supply":True,
        "same_execution_linkage":True,
        "shipping_implementation_provenance":True,
        "shipping_faithfulness_protocol_recorded":True,
        "short_word_scalar_completed_square_failure_class":"D_SUFFICIENT_BOUND_FAILURE",
        "constant_nonzero_wave_displacement_rejection":True,
        "same_history_bias_recurrence":True,
        "accepted_magnetic_information_definition":True,
        "no_heading_service_obstruction":True,
        "captured_domain_implies_finite_mag_refinement":True,
        "captured_domain_implies_finite_A21_entry":True,
        "time_varying_A21_translation_observability":True,
        "uniform_gravity_tilt_sensitivity":True,
        "uniform_A21_neutral_quotient_information_exists":False,
        "uniform_A21_controllability_exists":True,
        "A21_covariance_hard_event_compactness":False,
        "local_A21_nonlinear_small_gain_exists":False,
        "physical_qualification_composition":True,
        "assembled_sensor_and_bias_limit_qualification":False,
        "all_time_marine_motion_membership_certificate":False,
        "finite_history_dependent_capture":False,
        "capture_H18_release_retention_composition":True,
        "finite_H18_bridge_retention":False,
        "finite_reference_refinement_and_bias_release":False,
        "H18_to_A21_release_retention":False,
        "source_uniform_A21_linear_dissipativity":False,
        "shipping_reachable_graph_shaped_storage_identity":True,
        "source_uniform_shaped_homogeneous_margin_exists_conditionally":True,
        "source_uniform_shaped_constructive_margin":False,
        "source_uniform_shaped_physical_supply_numeric":False,
        "dependency_preserving_history_cell_schema":True,
        "joint_shaped_dissipation_supply_identity":True,
        "causal_mahony_variance_tuner_interval_propagator":False,
        "literal_wave_period_interval_propagator":False,
        "sensor_to_joint_tuner_causal_chain_closed":False,
        "literal_covariance_gain_joint_supply_propagator":True,
        "causal_history_interval_propagator_complete":False,
        "verified_full_21_precision_enclosure":True,
        "interval_joint_shaped_quadratic":True,
        "temporal_same_history_source_domain":True,
        "kernel_linked_quotient_primitive":True,
        "verified_direct_temporal_qcqp_solver":True,
        "cellwise_ratio_composer":True,
        "kernel_restricted_interval_action_primitive":True,
        "kernel_line_angle_enclosure_complete":True,
        "kernel_restricted_interval_action_numeric":False,
        "nonlinear_marine_magnetic_qcqp_callbacks":True,
        "history_cell_nonlinear_witness_builder":True,
        "history_leaf_ratio_connector":True,
        "interval_source_coefficients_consumed_by_qcqp":True,
        "marine_existential_window_logic":True,
        "source_uniform_history_cover_generator":True,
        "literal_history_cell_sample_propagator":False,
        "explicit_release_set_gap_audited":True,
        "literal_golive_constructive_seed":True,
        "numeric_release_AG_BG_BA_partial":True,
        "release_one_step_source_uniform_innovation":True,
        "captured_attitude_ball_factor_cover":True,
        "golive_common_rotation_gram_identity":True,
        "golive_direction_free_projector_inverse":True,
        "structured_INJ_block_algebra_closed":True,
        "common_rotation_INJ_transport_exact":True,
        "changing_axis_two_axis_basis_identified":True,
        "literal_axis_transport_frame_cancellation":True,
        "structured_AW_mean_defect_recurrence":True,
        "structured_AW_gain_export_formula":True,
        "structured_source_identity_link":True,
        "structured_release_numeric_iteration":False,
        "structured_Riccati_full_shipping_chronology_numeric":False,
        "release_state_enclosure_connected_to_history_cover":False,
        "aggregate_magnetic_service_operator_connected":True,
        "accepted_magnetic_event_strata_connected_to_history_cover":"NOT_REQUIRED_AGGREGATE_SERVICE_USED",
        "literal_history_cell_to_leaf_propagator":False,
        "constructive_cellwise_supply_dissipation_quotient":False,
        "source_uniform_block_factor_root_coercivity":True,
        "constructive_fixed_coordinate_A21_mu_enclosure":False,
        "LIN_endpoint_matrix_path_action":True,
        "recurring_nuisance_covariance_upper":True,
        "pre_prediction_embedded_nuisance_floor":True,
        "six_column_to_full_contraction_implication":True,
        "six_column_corrected_loss_uniform_bound":False,
        "historical_AG_readout_covariance_implication":True,
        "joint_minimum_action_historical_reader_identity":True,
        "joint_reader_diffuse_limit_full_covariance_domination":True,
        "joint_reader_coercivity_action_reduction":True,
        "source_uniform_joint_reader_AG_information_floor":False,
        "uniform_historical_AG_readout_action":False,
        "first_prediction_relative_process_ceiling":True,
        "word_contraction_smoother_identity":True,
        "separated_information_or_forgetting_bounds_insufficient":True,
        "information_ratio_word_contraction_lemma":True,
        "source_uniform_word_information_ratio_bounds":False,
        "word_riccati_diameter_identity":True,
        "information_ratio_closed_form_supremum":True,
        "word_diameter_composition_and_slow_fast_factorization":True,
        "rank_structured_kernel_contraction_corollary":True,
        "kernel_variance_set_invariance_implication":True,
        "scalar_kernel_ceiling_from_proved_BA_marginal":True,
        "s_chain_neutral_and_aw_root_cancellation":False,
        "causal_aw_full_root_action_ceiling":True,
        "causal_aw_AG_root_cancellation":False,
        "carried_17s_diagnostic_equals_C_port":False,
        "source_uniform_reachable_causal_reader_port_norm":False,
        "exact_sync_slab_physical_bilinear":True,
        "joint_accel_S_schur_quadratic":True,
        "seventeen_second_pre_norm_physical_telescope":True,
        "source_uniform_gyro_bias_persistence_diameter_cap":True,
        "source_uniform_kernel_bounded_word_diameter":False,
        "source_uniform_K17_finite_numeric":False,
        "source_uniform_K17_le_250":False,
        "K17_horizon_mixing_rejected":True,
        "contraction_superword_100s_adopted":True,
        "nuisance_warmup_17s_retained":True,
        "source_uniform_K100_finite_numeric":False,
        "source_uniform_K100_kernel_invariant":False,
        "gamma_S_source_uniform_numeric":False,
        "gamma_M_residualized_numeric":False,
        "beta_rank_loss_numeric":False,
        "rank_loss_interval_factor_propagator_required":True,
        "rank_loss_four_S_source_box_implemented":True,
        "rank_loss_magnetic_nuisance_schur_implemented":True,
        "rank_loss_magnetic_literal_event_box_exporter_implemented":True,
        "rank_loss_magnetic_source_uniform_operation_box_formulas_implemented":True,
        "rank_loss_magnetic_exhaustive_driver_implemented":True,
        "rank_loss_magnetic_seed_audit_implemented":True,
        "rank_loss_magnetic_full_P_seed_available":False,
        "rank_loss_magnetic_finite_event_seed_cover_available":False,
        "rank_loss_magnetic_full_1s_strata_covered":False,
        "same_history_unit_kernel_persistence_excluded":False,
        "source_uniform_tilt_about_field_axis_covariance_ceiling":False,
        "kernel_scalar_fixed_point_reduction":True,
        "actual_gain_finite_error_word_composition":True,
        "joint_word_prediction_measurement_input_action":True,
        "finite_angle_source_reset_remainder":True,
        "source_covariance_projection_guard":True,
        "full_21_covariance_upper":False,
        "complete_word_covariance_energy_identity":True,
        "factorized_word_exact_reference_parity":True,
        "singular_nuisance_range_elimination":True,
        "full_state_magnetic_information_lifting":False,
        "interval_riccati_kernel_layer":True,
        "maximal_correction_covariance_order":True,
        "constructive_root_covariance_floor":True,
        "constructive_full_A21_mu_rho_enclosure":False,
        "explicit_A21_nonlinear_radius":False,
        "whole_word_float32_supply_composition":True,
        "whole_word_float32_supply_bound":False,
        "capture_release_into_explicit_A21_region":False,
        "finite_error_A21_nonlinear_remainder":False,
        "tail_prefix_retention_composition":True,
        "certified_tail_prefix_retention":False,
        "source_uniform_magnetic_service_certificate_schema":True,
        "source_uniform_magnetic_service_certificate":False,
        "implementation_and_arithmetic_totality":False,
    }
    return {
        "qualification":"OU3_SINGLE_MARINE_IMU_MAGNETIC_STABILITY_ARCHITECTURE_V3_SLOW_FAST",
        "principal_assumptions":["MARINE MOTION","IMU BIAS","MAGNETIC SERVICE"],
        "quantifier":"one persistent physical execution belongs to all three assumption classes simultaneously",
        "proof_path":["construction","startup/capture","finite magnetically informed Live/H18 bridge",
                      "finite reference refinement","H18-to-A21 release",
                      "recurring magnetically informed A21 tail","regional practical stability"],
        "certified_capture_time":None,
        "required_capture_time":"history dependent T_c(h,x_0) < infinity; open under the amended marine-motion domain",
        "parallel_no_magnetometer_stability_path":False,
        "no_heading_service_result_role":"necessity lemma only",
        "shipping_filter_changed_for_proof":False,
        "proof_governance":"docs/ou3-shipping-faithfulness-protocol.md",
        "proof_target":"actual shipping OU-III filter; surrogate enlargements must be explicit and failure does not transfer without losslessness",
        "physical_regimes":["STILL","TRANSITION","MOVING"],
        "regime_role":"qualification of portions of the single carried proof path, not independent estimator restarts",
        "shipping_mode_switch_enabled":False,
        "quiet_nominal_covariance_subcase":{
            "certificate":"stationary-covariance-certificate.json",
            "historical_root_independent_full_upper":True,
            "every_operation_covariance_upper":True,
            "homogeneous_linear_loss_exists":True,
            "physical_compatible_class_practical_stability":False,
            "general_moving_uniform_bound":False,
        },
        "exact_rest_detector_obstruction":{
            "identical_rest_motion_IMU_histories":True,
            "finite_entry_and_universal_finite_exit_simultaneously_possible":False,
            "stationary_robustness_of_compatible_class_refuted":False,
            "certificate":"regime-certificate.json",
        },
        "world_frame_rows":{
            "certificate":"world-frame-certificate.json",
            "source_diagnostic":"world-frame-source-feasibility.json",
            "attitude_estimate_or_error_in_six_column_geometry":False,
            "remaining_attitude_dependence":"reset discrepancies N=R_next' G R and the nominal rotation integral of R_hat' in the gyro columns",
            "same_cell_floor_from_motion_and_bias_bounds_alone":False,
            "collinear_1Hz_witness_magnetic_service_admitted":False,
            "same_cell_floor_requires_magnetic_cadence_coupling":True,
            "same_cell_two_group_uniform_floor_established":False,
            "signed_world_injection_transport_budget":False,
            "aggregate_rows_avoid_magnetic_phase_premise":True,
            "aw_covariance_certificate":"aw-covariance-ceiling-certificate.json",
            "aw_covariance_ceiling_tight_at_sync":True,
            "uniform_storage_route_ratio_above_one_on_carried_collinear_words":True,
            "aw_tracking_certificate":"aw-tracking-certificate.json",
            "aw_tracking_source_diagnostic":"aw-tracking-source-feasibility.json",
            "pointwise_physical_AW_premise_refuted_ratio":"6.80",
            "attitude_columns_need_only_nominal_signed_mean":True,
            "nominal_transverse_mean_threshold_mps2":"196133/100000",
            "signed_injection_certificate":"signed-injection-certificate.json",
            "aggregate_floor_certificate":"aggregate-floor-certificate.json",
            "injection_free_six_column_floor_squared_lower":"297357352751/200000000000000",
            "injection_free_floor_premises":["nominal transverse AW mean <= 2/5 m/s^2 on two separated 16-s windows","nominal L1 force mean <= 6/5","A_tilde=I"],
            "controlling_transfer_quantity":"source bound on the nominal AW window statistics of the literal loop, and the injection frame in Theorem G0",
        },
        "imu_bias_model":{
            "certificate":"imu-two-timescale-certificate.json",
            "model":"e_a=b_a_s+b_a_f; e_g=b_g_s+b_g_f",
            "fast_rule":"amplitude plus every-placed-window signed accumulation of delivered calibrated samples",
            "temporal_numerical_qualification":"user-specified H_a=H_g=60,C_a=.05,C_g=.002; assembled validation OPEN",
            "six_limits_status":"inherited candidate budgets, not newly measured guarantees",
            "independent_residual_box_admission":False,
            "finite_capture_can_certify_all_time":False,
            "decomposition_reselection_at_release_or_regime_boundary":False,
            "oscillatory_0p01_sin_0p5t_admissibility":"OPEN",
            "all_slow_sin_cubed_ambiguity_survives":False,
            "all_slow_sin_cubed_status":"historical attitude-only MARINE witness; excluded from MOVING by P_E>0",
            "stronger_EXCITED_MOVING_adopted":False,
        },
        "a21_contraction_route":{
            "method":"path-complete covariance-metric dissipativity and LaSalle on one carried history",
            "chronology":"literal prediction, S, accel, mag, PSD synchronization, resets; coupled (tau,sigma_aw,R_S,T_S)",
            "contraction_certificate":"corrected-word-certificate.json",
            "finite_supply_identity":"linked_supply.py: e_N=M e_0+b, linked chi_gamma on jointly reachable histories",
            "local_field_axis_radius":0.15,
            "local_radius_implies_release_or_outer_entry":False,
            "zero_homogeneous_action_implies_zero_base_innovations":False,
            "O1_O2_kernel_ceiling_architecture_controlling":False,
            "legacy_word_diameter_results_role":"retained algebra/history only, not the controlling architecture",
            "open_source_premises":[
                "qualify both slow/fast physical histories and derive the MARINE+MAGNETIC same-history compatibility margin",
                "prove quiet-compatible boundedness and settle the planar MOVING all-time magnetic-service admission before claiming absolute inner entry; retain the same H18/A21 state and covariance"
            ],
        },
        "shipping_residual_gyro_bias_hardening":True,
        "implemented_gyro_bias_norm_invariant":True,
        "complete_turn_nominal_gyro_bias_alias_excluded":True,
        "one_prediction_gyro_transport_real_source_floor":True,
        "signed_temporal_Delta_gyr_closed":False,
        "unrestricted_device_timestep_alias_exclusion":False,
        "obligations":obligations,
        "theorem_closed":all(obligations.values()),
        "regional_practical_stability_claimed":False,
        "capture_obstruction":{
            "old_domain_six_degree_capture_refuted":True,
            "old_witness_admitted_by_current_contract":False,
            "both_witness_histories_have_nonzero_motion":True,
            "all_time_real_arithmetic_magnetic_service_verified":True,
            "conditional_local_A21_stability_refuted":False,
            "shipping_divergence_claimed":False,
            "new_physical_assumption_adopted":True,
            "sampling_certificate":"sampling-fidelity.json",
            "certificate":"sampled-capture-obstruction.json",
        },
        "moving_quiet_compatibility":{
            "certificate":"moving-quiet-compatibility-certificate.json",
            "carried_diagnostic":"moving-compatibility-carried.json",
            "quiet_universal_absolute_entry_refuted":True,
            "moving_two_epoch_span_bias_separation_refuted":True,
            "moving_full_premise_absolute_entry_refuted":False,
            "planar_mean_invariant_manifold":True,
            "reduced_periodic_service_recurrence_formulated":True,
            "planar_covariance_parity_factorization":True,
            "tail_all_sample_phase_service_min_gt_one_diagnostic":True,
            "twenty_second_point_poincare_invalid_due_scheduler_phase":True,
            "scheduler_phase_coordinate_invariant":True,
            "oracle_rational_service_margin":True,
            "paired_correction_storage_invariant":False,
            "paired_correction_storage_loss_identity":True,
            "paired_prediction_loss_identity":True,
            "planar_anisotropic_root_factors":True,
            "matrix_lower_factor_correction_transport":True,
            "planar_same_history_covariance_lower_cell":False,
            "scheduler_phase_augmented_invariant_cell":False,
            "all_time_actual_magnetic_service_for_planar_pair":False,
            "finite_replay_is_all_time_certificate":False,
            "finite_homogeneous_quotient_diagnostic":"planar-quotient-mean-diagnostic.json",
            "finite_complete_native_secants":"planar-native-secants-diagnostic.json",
            "continuous_same_record_physical_arc_verified":True,
            "physical_angle_cap_is_precision_gauge_bound":False,
            "nonlinear_fibre_remainder_requires_metric_bound":True,
            "finite_conditional_moving_center":"planar-moving-center-diagnostic.json",
            "conditional_center_is_autonomous_future_enclosure":False,
            "causal_center_recurrence_defined":True,
            "causal_center_compact_domain_verified":False,
            "linked_noise_and_held_gain_differentials_verified":True,
            "raw_mahony_local_normalization_certificate":"mahony-raw-normalization-certificate.json",
            "raw_mahony_all_time_input_domain_verified":False,
            "qualified_private_frontend_domain_certificate":"planar-frontend-domain-certificate.json",
            "private_frontend_source_derived_error_caps":True,
            "private_frontend_target_libm_qualification_verified":False,
            "real_reference_cone_angle_cap":"11/5000",
            "reference_float_accumulation_and_acquisition_verified":False,
            "complete_word_storage_identity_certificate":"planar-complete-word-storage-certificate.json",
            "same_operation_covariance_residual_loss_bound":True,
            "innovation_storage_certificate":"planar-innovation-storage-certificate.json",
            "innovation_variational_identity":True,
            "qualified_first_handoff_real_comparison_bound":"21/1000",
            "qualified_first_handoff_bound_is_prefix_invariant":False,
            "held_BA_reachable_active_block_reduction":True,
            "fixed_row_information_shear_residual_cancellation":True,
            "information_shear_complete_word_gap_verified":False,
            "information_shear_word_balance_certificate":"information-shear-word-certificate.json",
            "information_shear_word_action_kernel_characterized":True,
            "linked_suffix_score_normal_form_verified":True,
            "generated_covariance_suffix_score_retained":True,
            "score_range_aware_Fisher_loss_bound_verified":True,
            "uniform_linked_suffix_score_charge":None,
            "inherited_comparison_score_supply_identity_verified":True,
            "uniform_signed_comparison_supply_bound":None,
            "general_service_conditioned_theorem_waits_for_planar_admission":False,
            "general_compatible_strata_and_uniform_transverse_gap_verified":False,
            "measurement_frame_loss_certificate":"measurement-frame-loss-certificate.json",
            "exact_moving_frame_measurement_feedback_reduction":True,
            "AW_shear_constant_acc_row_verified":True,
            "AW_row_covariance_port_coboundary_verified":True,
            "AW_shear_applied_increment_frame_derivative_retained":True,
            "AW_shear_combined_port_absorption_verified":False,
            "AW_internal_frame_word_cancellation_verified":True,
            "AW_frame_endpoint_quadratic_verified":True,
            "AW_frame_endpoint_absorption_verified":False,
            "actual_AW_sync_conditional_precision_nonincrease":True,
            "conditional_AW_storage_split_verified":True,
            "mag_S_conditional_AW_storage_invariant":True,
            "qualified_conditional_AW_precision_upper":"15942618",
            "qualified_conditional_AW_base_process_loss_lower":"1/100000000000000",
            "conditional_AW_base_loss_is_complete_gap":False,
            "conditional_mixed_word_completion_verified":True,
            "conditional_mixed_reader_AW_frame_invariant":True,
            "conditional_directional_score_reader_verified":True,
            "conditional_linked_half_loss_bound_verified":True,
            "complementary_base_packet_Schur_absorption_verified":True,
            "fixed_half_charge_domination_is_necessary":False,
            "isotropic_score_cancellation_extends_to_anisotropic_loss":False,
            "supported_process_source_score_identity_verified":True,
            "combined_process_word_directional_budget_verified":True,
            "causal_generated_process_augmented_balance_verified":True,
            "generated_process_square_Fisher_charge_verified":True,
            "generated_process_cross_absorbed":False,
            "uniform_combined_process_source_budget":None,
            "held_BA_unsupported_score_uniform_boundary_bound":True,
            "held_BA_unsupported_score_active_component_zero":True,
            "uniform_active_comparison_loss_energy":None,
            "uniform_conditional_score_margin_verified":False,
            "uniform_generated_packet_absorption_verified":False,
            "central_planar_acc_physical_curvature_charge_verified":True,
            "central_planar_acc_charge_uses_nominal_AW_BA_boxes":False,
            "qualified_planar_magnetic_coupled_loss_fraction":"9/10",
            "qualified_planar_magnetic_loss_is_complete_word_contraction":False,
            "qualified_service_pitch_variance_upper":"3/5000",
            "qualified_service_BG_y_variance_upper":"1/4000",
            "qualified_planar_pitch_row_loss_coefficients":["1125","1260"],
            "magnetic_loss_activation_domain_forward_invariant":False,
            "source_uniform_nominal_NIS_cap":None,
            "uniform_complete_word_storage_margin":None,
            "uniform_center_service_floor":None,
            "analytical_invariant_radius":None,
            "homogeneous_factor_product_is_complete_nonlinear_derivative":False,
            "private_Mahony_gain_is_complete_mean_gain":False,
            "scalar_radius_solver_can_certify_admission":False,
            "homogeneous_kernel_results_imply_physical_identifiability":False,
            "physical_bias_OU_mismatch_retained":True,
            "shipping_instability_claimed":False,
            "extra_physical_assumptions_adopted":False,
        },
        "next_controlling_obligation":(
            "Follow docs/ou3-information-shear-strategy.md: identify symmetry/kernels, justify compatible strata/tubes, "
            "derive linked dissipation, bound actual forcing, then prove only necessary activation facts. "
            "The exact information-shear word balance and action kernel are proved, with reset/AW/projection and moving-projector ports retained. "
            "The moving-frame planar magnetic substep retains 9/10 of linked mean/covariance loss on its stated activation domain; "
            "prior-observation readers derive pitch/BG covariance ceilings and quantitative pitch-row loss. "
            "The exact suffix-score normal form cancels optimal additive local scores and retains all generated covariance suffix ports. "
            "Its loss-generated score charge is bounded by inherited root comparison energy plus signed source work minus realized NIS; physical/kernel forcing remains. "
            "The AW shear makes the accelerometer row constant and cancels its covariance row port as an exact connection difference, preserving qualified magnetic loss. "
            "Internal frame connections now cancel in the complete suffix word, leaving an exact three-dimensional signed AW endpoint quadratic. "
            "Conditional AW storage is invariant under optimal additive mag/S rows; literal integrated OU noise gives a qualified positive base-action block loss greater than 1e-14. "
            "The existing LIN path gives conditional AW precision below 15942618 on its qualified regular A21 domain. "
            "The actual conditional root score block now has an explicit three-row Schur reader in C,T,q, and exact completion bounds generated mixed work by one linked packet while retaining half the net conditional root form. "
            "The state-dependent AW frame preserves the conditional storage and score reader; endpoint frame work stays in transformed complementary packets without double counting. "
            "Use the exact complementary base Schur absorption; the fixed half-charge domination is sufficient, not necessary, and fails a strictly contractive formal base specialization. Use the combined supported process/source score budget and causal augmented process balance, retaining unsupported scores and the unabsorbed feedback cross term. Prove a uniform directional score margin and domination of the remaining grouped signed work, retaining generated covariance suffix scores and endpoint gauge. "
            "These net comparisons, not conditional precision finiteness, remain unproved; no uniform complete margin is certified. "
            "Prove the single linked transverse gap uniformly under existing MAGNETIC SERVICE: compare its actual physical probes "
            "to the complete coupled sheared action, retain process/S action, and absorb signed endogenous work and gauge transport. "
            "The physical same-record tangent is forced and is not automatically the homogeneous or action kernel. "
            "A positive uniform c, branchwise compatibility relation, required metric/reference/chart bounds and actual source/gauge/arithmetic charges remain OPEN. "
            "Only after those dependencies close may radius and every-prefix practical stability be established. "
            "General service-conditioned dissipativity does not wait for special planar admission. Separately prove or disprove the planar family's "
            "all-time applied magnetic service; finite floors near 7.02 do not certify it. Full admission rules out eventual retention "
            "in the specified absolute V<.0225 ball, not divergence or every larger absolute practical bound. "
            "Preserve construction/H18/refinement/release, physical S, held BA, reference/gates and S/AW clocks without restart. "
            "Qualified first-Live bounds are boundary implications only. No replay, secant, sampled grid or empirical contraction campaign. "
            "Nonlinear retention, target arithmetic and STILL/TRANSITION/MOVING composition remain OPEN."

        ),
    }
