"""Source-uniform BIAS0/BIAS1/BIAS2 physical-driver recurrences.

The three families are separate mandatory drivers.  These tests check that
each is bound to its own module, that the declared driver-increment enclosures
actually dominate admitted sample paths and are not vacuous, and that binding
the families changes no promotion bit: P4 stays fail-closed.
"""
from __future__ import annotations

import math
from pathlib import Path
import sys
import unittest

TOOLS = Path(__file__).resolve().parents[2] / "tools" / "stability"
sys.path.insert(0, str(TOOLS))

import ou3_p4_all_bias_families_contract as CONTRACT
import ou3_p4_bias0_family as BIAS0
import ou3_p4_bias1_family as BIAS1
import ou3_p4_bias2_family as BIAS2
import ou3_p4_bias_family_joint_iss_supply as SUPPLY

DT = 0.005


def clipped_ramp(cap, rate, steps):
    """Channel that arrives at its cap at max rate and then holds it.

    The largest |c_i-phi*c_{i-1}| of any admitted magnitude/rate-bounded
    channel is attained here, up to the (1-phi)*rate*dt second-order term.
    """
    return [min(cap, cap - rate * DT * (steps - i)) for i in range(steps + 1)]


class Bias0FamilyTests(unittest.TestCase):
    def test_family_is_conditional_and_never_hardware_qualified(self):
        d = BIAS0.build()
        self.assertEqual(BIAS0.validate(d), [])
        self.assertTrue(d["conditional_theorem_family"])
        self.assertFalse(d["assembled_sensor_hardware_qualified"])
        self.assertFalse(d["deployment_hardware_admission_pass"])
        self.assertFalse(d["inferred_from_BIAS1"])
        self.assertFalse(d["may_be_substituted_by_BIAS1"])

    def test_gauss_markov_pathwise_cap_stays_a_declared_hypothesis(self):
        d = BIAS0.build()
        self.assertTrue(d["gauss_markov_pathwise_increment_cap_is_declared_hypothesis"])
        self.assertFalse(d["stationary_OU_PSD_used_to_derive_pathwise_cap"])
        # The sigma multiple is descriptive: it may be reported, never used to
        # justify the cap.  It must at least be a conservative multiple.
        self.assertGreater(d["descriptive_pathwise_cap_sigma_multiple"], 3.0)

    def test_driver_increment_dominates_an_admitted_extremal_path(self):
        d = BIAS0.build()
        phi = d["phi_true_interval"][0]
        steps = 8
        gm_w = d["gauss_markov_pathwise_increment_component_abs_upper_mps2"]
        # The Gauss-Markov channel is generated by its own recurrence at the
        # declared pathwise cap, so its exact contribution to the increment is
        # the cap itself.  It starts low enough to stay inside its magnitude.
        gm = [d["gauss_markov_component_abs_upper_mps2"] - gm_w * steps]
        for _ in range(steps):
            gm.append(phi * gm[-1] + gm_w)
        b0 = [d["turn_on_offset_component_abs_upper_mps2"]] * (steps + 1)
        thermal = clipped_ramp(d["thermal_component_abs_upper_mps2"], d["thermal_component_rate_abs_upper_mps3"], steps)
        strain = clipped_ramp(d["strain_component_abs_upper_mps2"], d["strain_component_rate_abs_upper_mps3"], steps)
        non_gm = clipped_ramp(d["non_gauss_markov_component_abs_upper_mps2"], d["non_gauss_markov_rate_abs_upper_mps3"], steps)
        path = [g + o + t + s + n for g, o, t, s, n in zip(gm, b0, thermal, strain, non_gm)]

        self.assertLessEqual(max(abs(x) for x in path), d["true_bias_component_abs_upper_mps2"])
        # The excess over the cap is this test's own binary64 reconstruction of
        # phi*gm, not a family violation; the family bound is outward-rounded.
        self.assertLessEqual(max(abs(gm[i] - phi * gm[i - 1]) for i in range(1, steps + 1)), gm_w * (1 + 1e-12))
        self.assertLessEqual(max(abs(x) for x in gm), d["gauss_markov_component_abs_upper_mps2"])
        worst = max(abs(path[i] - phi * path[i - 1]) for i in range(1, steps + 1))
        bound = d["driver_increment_component_abs_upper_mps2"]
        self.assertLessEqual(worst, bound)
        self.assertGreater(worst, 0.999 * bound)

    def test_channels_are_all_retained_in_the_increment(self):
        d = BIAS0.build()
        channels = d["channel_driver_increment_components_mps2"]
        self.assertEqual(
            set(channels),
            {"gauss_markov", "turn_on_offset", "thermal", "strain", "non_gauss_markov"},
        )
        self.assertGreaterEqual(d["driver_increment_component_abs_upper_mps2"], sum(channels.values()))
        self.assertEqual(max(channels, key=channels.get), "gauss_markov")


class Bias2FamilyTests(unittest.TestCase):
    def test_non_relaxing_limit_is_admitted_and_separation_stays_unproved(self):
        d = BIAS2.build()
        self.assertEqual(BIAS2.validate(d), [])
        self.assertTrue(d["non_relaxing_limit_admitted"])
        self.assertEqual(d["phi_true_interval"][1], 1.0)
        self.assertTrue(d["tau_true_upper_is_infinite"])
        self.assertIsNone(d["uniform_separation_constant_lower"])
        self.assertFalse(d["source_uniform_separation_closed"])

    def test_compactness_comes_from_projection_not_from_separation(self):
        d = BIAS2.build()
        # A non-relaxing truth still has a bounded error, because the deployed
        # radial projection holds the estimate in its ball.  Separation would
        # only sharpen the motion gains, so it is not a prerequisite.
        self.assertFalse(d["separation_sector_required_for_bounded_bias_objective"])
        self.assertTrue(d["separation_sector_sharpens_motion_gains_only"])
        self.assertTrue(d["bias_compactness_needs_no_relaxation_root"])
        self.assertTrue(d["bias_compactness_needs_no_separation_constant"])
        self.assertAlmostEqual(d["bias_error_compactness_upper_mps2"],
                               d["deployed_projection_radius_mps2"] + d["true_bias_norm_upper_mps2"],
                               places=12)

    def test_driver_increment_dominates_admitted_drift_paths(self):
        d = BIAS2.build()
        cap = d["true_bias_component_abs_upper_mps2"]
        rate = d["variation_rate_abs_upper_mps3"]
        bound = d["driver_increment_component_abs_upper_mps2"]
        steps = 8
        path = clipped_ramp(cap, rate, steps)
        for phi in (d["phi_true_interval"][0], 1.0):
            worst = max(abs(path[i] - phi * path[i - 1]) for i in range(1, steps + 1))
            self.assertLessEqual(worst, bound)
        # The relaxing end of the admitted interval is the binding one.
        phi_lo = d["phi_true_interval"][0]
        worst_lo = max(abs(path[i] - phi_lo * path[i - 1]) for i in range(1, steps + 1))
        self.assertGreater(worst_lo, 0.999 * bound)

    def test_family_is_not_a_relabelled_BIAS1(self):
        b1, b2 = BIAS1.build(), BIAS2.build()
        self.assertGreater(b2["phi_true_interval"][1], b1["phi_true_interval"][1])
        self.assertFalse(b2["inferred_from_BIAS0_or_BIAS1"])
        self.assertFalse(b2["may_be_substituted_by_BIAS1"])


class JointSupplyTests(unittest.TestCase):
    def test_every_family_reaches_the_deployed_24state_event_lift(self):
        d = SUPPLY.build()
        self.assertEqual(SUPPLY.validate(d), [])
        for name in SUPPLY.REQUIRED_BIAS_FAMILIES:
            lift = d["family_supply"][name]["event_lift"]
            self.assertTrue(lift["prediction_lift_accepts_family_interval"], name)
            self.assertTrue(lift["supply_injection_available"], name)
            self.assertTrue(lift["same_w_column_shared_by_error_and_truth"], name)
            self.assertTrue(lift["physical_factor_carried_in_truth_block"], name)
        self.assertFalse(d["independent_per_sample_bias_state_slots_used"])

    def test_joint_supply_is_the_hypotenuse_of_driver_and_tau_mismatch(self):
        d = SUPPLY.build()
        for name in SUPPLY.REQUIRED_BIAS_FAMILIES:
            s = d["family_supply"][name]
            expected = math.hypot(
                s["driver_increment_norm_upper_mps2"], s["tau_mismatch_forcing_norm_upper_mps2"]
            )
            self.assertGreaterEqual(s["joint_supply_norm_upper_per_prediction_mps2"], expected)
            self.assertLess(s["joint_supply_norm_upper_per_prediction_mps2"], 1.0000001 * expected)

    def test_BIAS1_does_not_carry_the_other_families(self):
        d = SUPPLY.build()
        self.assertTrue(d["BIAS1_class_contains_no_other_family"])
        self.assertTrue(d["no_single_family_covers_the_other_two"])
        self.assertFalse(d["BIAS0_inferred_from_BIAS1"])
        self.assertFalse(d["BIAS2_inferred_from_BIAS1"])
        self.assertFalse(d["generic_bias_box_replaces_three_families"])
        # BIAS2 admits phi_true=1, which no other family's interval reaches.
        self.assertFalse(d["relaxation_class_containment"]["BIAS0"]["BIAS2"])

    def test_BIAS1_numbers_are_delegated_not_restated(self):
        d = SUPPLY.build()
        self.assertTrue(d["BIAS1_supply_delegated_to_authoritative_module"])

    def test_the_three_families_share_one_true_bias_envelope(self):
        d = SUPPLY.build()
        # This is what makes the projection/Joseph prerequisites family-
        # parametric: they see a family only through |b_true|, and that is one
        # number here, so the compactness bound is one number too.
        self.assertTrue(d["families_share_one_true_bias_envelope"])
        self.assertTrue(d["bias_compactness_is_family_uniform"])
        self.assertTrue(d["radial_projection_sector_closed_for_every_family"])
        self.assertTrue(d["projection_sector_sees_no_bias_driver"])
        self.assertFalse(d["BIAS2_separation_required_for_bounded_bias_objective"])
        compact = set(d["bias_error_compactness_upper_mps2"].values())
        self.assertEqual(len(compact), 1)
        self.assertAlmostEqual(compact.pop(),
                               d["deployed_projection_radius_mps2"]
                               + max(s["true_bias_norm_upper_mps2"] for s in d["family_supply"].values()),
                               places=12)

    def test_declared_truth_stays_inside_the_hard_entry_envelope(self):
        d = SUPPLY.build()
        self.assertTrue(d["every_family_true_bias_within_hard_entry_envelope"])
        radius = d["hard_entry_accelerometer_bias_error_radius_mps2"]
        for name in SUPPLY.REQUIRED_BIAS_FAMILIES:
            self.assertLessEqual(d["family_supply"][name]["true_bias_norm_upper_mps2"], radius)

    def test_supply_materialization_promotes_nothing(self):
        d = SUPPLY.build()
        self.assertFalse(d["endpoint_augmented_LDLT_closed_here"])
        self.assertFalse(d["every_prefix_augmented_LDLT_closed_here"])
        self.assertFalse(d["P4_promoted_here"])
        self.assertFalse(d["filter_changed"])
        self.assertFalse(d["declared_domain_changed"])
        self.assertFalse(d["trajectory_replay_used"])


class AllBiasFamilyContractTests(unittest.TestCase):
    def test_all_three_families_are_semantically_bound(self):
        d = CONTRACT.build()
        self.assertEqual(CONTRACT.validate(d), [])
        self.assertEqual(d["semantic_bindings"], {"BIAS0": True, "BIAS1": True, "BIAS2": True})
        self.assertTrue(d["all_three_semantically_bound_here"])
        self.assertTrue(d["BIAS0_authoritative_family_module_bound"])
        self.assertTrue(d["BIAS2_authoritative_family_module_bound"])

    def test_binding_does_not_close_the_downstream_obligations(self):
        d = CONTRACT.build()
        self.assertFalse(d["all_three_source_cover_closed_here"])
        self.assertFalse(d["all_three_projection_transport_closed_here"])
        self.assertFalse(d["all_three_every_prefix_ISS_LDLT_closed_here"])
        self.assertFalse(d["all_bias_promotion_gate_closed"])
        self.assertFalse(d["BIAS0_assembled_sensor_hardware_qualified"])
        self.assertFalse(d["BIAS2_uniform_separation_sector_closed"])
        self.assertFalse(d["P4_MOTION_PASS"])
        self.assertFalse(d["P4_PASS"])
        self.assertFalse(d["P5_MAY_START"])

    def test_subset_attempts_are_still_rejected(self):
        for omitted in (("BIAS1", "BIAS2"), ("BIAS0", "BIAS2"), ("BIAS0", "BIAS1")):
            self.assertFalse(CONTRACT.attempt_coverage(omitted)["closed"])
            with self.assertRaises(RuntimeError):
                CONTRACT.require_all_bias_families(omitted)

    def test_promotion_gate_needs_every_family_in_every_table(self):
        full = dict.fromkeys(CONTRACT.REQUIRED_BIAS_FAMILIES, True)
        self.assertTrue(
            CONTRACT.promotion_bias_gate(
                families=CONTRACT.REQUIRED_BIAS_FAMILIES,
                semantic_bindings=full,
                source_cover=full,
                projection_transport=full,
                prefix_iss_ldlt=full,
            )
        )
        for missing in CONTRACT.REQUIRED_BIAS_FAMILIES:
            partial = dict(full, **{missing: False})
            self.assertFalse(
                CONTRACT.promotion_bias_gate(
                    families=CONTRACT.REQUIRED_BIAS_FAMILIES,
                    semantic_bindings=full,
                    source_cover=partial,
                    projection_transport=full,
                    prefix_iss_ldlt=full,
                )
            )


if __name__ == "__main__":
    unittest.main()
