"""Publication contract for the componentwise/direct OU--III stability widening."""

import re
import unittest
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[2]
DOC = REPO_ROOT / "doc" / "kalman_ou_iii"


def _read(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def _flat(text: str) -> str:
    return re.sub(r"\s+", " ", text)


class OUIIIStructuredStabilityWideningContractTests(unittest.TestCase):
    def test_structured_refinement_is_wired_after_phase_c(self):
        phase_c = _read(DOC / "w3d-stability-widening-phase-c.tex-part")
        self.assertIn(r"\input{w3d-stability-widening-structured.tex-part}", phase_c)

    def test_velocity_and_position_leave_instantaneous_nonlinear_budget(self):
        proof = _read(DOC / "w3d-stability-widening-structured.tex-part")
        for marker in (
            r"\label{eq:widen-component-split}",
            r"\label{eq:widen-component-tube}",
            r"\label{eq:widen-component-correction}",
            r"\label{eq:widen-component-load}",
            r"\label{thm:widen-component-iss}",
        ):
            self.assertIn(marker, proof)
        flat = _flat(proof)
        self.assertIn("neither $\\delta\\vct v$ nor $\\delta\\vct p$ appears", flat)
        self.assertIn("contains $r_\\theta,r_{bg},r_{aw},r_{ba},r_S$ but no $r_{vp}$", flat)
        self.assertIn("old two-block cylinder remains a valid fallback", flat)

    def test_componentwise_load_preserves_actual_nonlinear_structure(self):
        proof = _read(DOC / "w3d-stability-widening-structured.tex-part")
        for marker in (
            r"\label{eq:widen-component-h}",
            r"\label{eq:widen-component-geometry-load}",
            r"\label{eq:widen-component-correction-load}",
            r"\label{eq:widen-component-condition}",
        ):
            self.assertIn(marker, proof)
        flat = _flat(proof)
        self.assertIn("attitude--acceleration product", flat)
        self.assertIn("charged only through its correction path", flat)
        self.assertIn("velocity and position incur no instantaneous nonlinear penalty", flat)

    def test_gain_extrema_are_kept_joint_and_mode_consistent(self):
        proof = _read(DOC / "w3d-stability-widening-structured.tex-part")
        for marker in (
            r"\label{eq:widen-joint-family}",
            r"\label{eq:widen-joint-load}",
        ):
            self.assertIn(marker, proof)
        flat = _flat(proof)
        self.assertIn("generated by the same admitted", flat)
        self.assertIn("joint supremum is never larger", flat)
        self.assertIn("fictitious tuple", flat)

    def test_direct_decrease_is_primary_less_conservative_route(self):
        proof = _read(DOC / "w3d-stability-widening-structured.tex-part")
        for marker in (
            r"\label{eq:widen-direct-decrement}",
            r"\label{eq:widen-direct-margin}",
            r"\label{thm:widen-direct-iss}",
            r"\label{eq:widen-direct-condition}",
            r"\label{eq:widen-direct-enclosure}",
        ):
            self.assertIn(marker, proof)
        flat = _flat(proof)
        self.assertIn("logically no more restrictive than the scalar Lipschitz route", flat)
        self.assertIn("The converse need not hold", flat)
        self.assertIn("Sampling alone is not a proof", flat)
        self.assertIn("without claiming an unverified deployed radius", flat)

    def test_refinement_does_not_change_estimator_or_tuner(self):
        flat = _flat(_read(DOC / "w3d-stability-widening-structured.tex-part"))
        self.assertIn("None of these changes alters the estimator", flat)
        self.assertIn("adaptation law", flat)
        self.assertIn("pseudo-measurement", flat)


if __name__ == "__main__":
    unittest.main()
