"""Publication-contract overrides for the standalone wave-direction paper.

The historical OU validation suite predates the publication split and therefore
pins direction/tracker material to the OU--III manuscript.  These late-sorted
overrides keep the numerical evidence checks while asserting the new document
ownership: OU--III owns navigation/regularization, while ``kalman-wave-dir.tex``
owns carrier tracking, propagation axis, and travel sense.
"""

import re
import unittest
from pathlib import Path

import test_ou_validation as core


REPO_ROOT = Path(__file__).resolve().parents[2]
DOC = REPO_ROOT / "doc" / "kalman_ou_iii"


def _the_deterministic_table_is_generated_not_typed(self):
    ou_protocol = self.read("w3d-sim-charts.tex-part")
    generated = self.read("w3d-sim-results-generated.tex-part")
    wave_article = (DOC / "kalman-wave-dir.tex").read_text(encoding="utf-8")
    wave_results = (DOC / "w3d-wave-direction-results.tex-part").read_text(
        encoding="utf-8"
    )

    # The historical generated table remains archived evidence, but the OU
    # publication no longer imports its direction columns.
    self.assertIn("Generated by tools/ou_sim_table.py", generated)
    self.assertIn("tab:sim_results_rms_dir_basic", generated)
    self.assertNotIn("w3d-sim-results-generated.tex-part", ou_protocol)

    self.assertIn(r"\input{w3d-wave-direction-results.tex-part}", wave_article)
    self.assertIn("OUValidationDirectionAbsError", wave_results)
    self.assertIn("OUValidationTravelCorrect", wave_results)


def _transition_and_secondary_ensembles_are_rescored(self):
    protocol = self.read_flat("w3d-sim-charts.tex-part")
    results = self.read_flat("w3d-baseline-comparison.tex-part")
    generated = self.read_flat("w3d-ou-validation-results-generated.tex-part")
    wave_results = (DOC / "w3d-wave-direction-results.tex-part").read_text(
        encoding="utf-8"
    )

    # OU--III still owns its transition and second-spectrum motion evidence.
    self.assertIn("pure-start, crossfade, and pure-endpoint intervals", protocol)
    self.assertIn("whole-window transition percentages", results)
    self.assertIn("tab:ou_transition_segments", generated)
    self.assertIn("tab:ou_mc_pmstokes", generated)
    self.assertIn("OUValidationPMStokesDifference", results)
    self.assertIn("rather than pooled", results)

    # Direction evidence is retained in the committed numerical bundle but is
    # now interpreted and claimed only by the standalone direction article.
    self.assertNotIn("OUValidationDirectionAbsError", results)
    self.assertNotIn("OUValidationTravelCorrect", results)
    self.assertIn("OUValidationDirectionAbsError", wave_results)
    self.assertIn("OUValidationDirectionWorstAbsError", wave_results)
    self.assertIn("OUValidationTravelCorrect", wave_results)
    self.assertIn("truth", wave_results.lower())
    self.assertIn("FORWARD/BACKWARD", wave_results)


def _tracker_and_heel_material_are_scoped_as_unevaluated_appendices(self):
    ou_manuscript = self.read("kalman_ou-w3d.tex")
    fusion = self.read("w3d-fus-methods.tex-part")
    trackers = self.read("w3d-tracker-alternatives.tex-part")
    heel = self.read("w3d-wind-heel.tex-part")
    wave_article = (DOC / "kalman-wave-dir.tex").read_text(encoding="utf-8")
    frequency = (DOC / "w3d-frequency-tracking.tex-part").read_text(
        encoding="utf-8"
    )

    self.assertNotIn(r"\input{w3d-tracker-alternatives.tex-part}", ou_manuscript)
    self.assertNotIn("Frequency Tracking from Vertical Specific Force", fusion)
    self.assertNotIn(r"\input{w3d-direction-methods.tex-part}", fusion)
    self.assertNotIn("KalmANF policy for reported OU results", fusion)

    self.assertIn(r"\input{w3d-frequency-tracking.tex-part}", wave_article)
    self.assertIn(r"\input{w3d-direction-methods.tex-part}", wave_article)
    self.assertIn(r"\input{w3d-tracker-alternatives.tex-part}", wave_article)
    self.assertLess(
        wave_article.index(r"\appendices"),
        wave_article.index(r"\input{w3d-tracker-alternatives.tex-part}"),
    )
    self.assertIn("KalmANF", frequency)
    self.assertIn("not evaluated as direction-estimator tracker ablations", trackers)

    # Steady heel remains companion material and is still outside the scored OU
    # configuration; this split does not promote it into either publication.
    self.assertIn("disabled in every deterministic simulation", heel)


def _baseline_fairness_thresholds_and_hardware_limits_are_recorded(self):
    baseline = self.read_flat("w3d-baseline-comparison.tex-part")
    fusion = self.read("w3d-fus-methods.tex-part")
    simulation = self.read_flat("w3d-sim-charts.tex-part")

    self.assertIn("Parameters are frozen before evaluation", baseline)
    self.assertIn("reference displacement is never used to select gains", baseline)
    self.assertIn("same timestamped synthetic motion and inertial records", baseline)
    self.assertIn("tab:baseline-tuning-policy", baseline)
    self.assertIn("tab:implementation-gates", fusion)

    header = (
        REPO_ROOT / "src" / "kalman_ou_iii" / "SeaStateFusionFilter_OU_III.h"
    ).read_text(encoding="utf-8")

    def clamp(name):
        match = re.search(rf"{name}\s*=\s*([0-9.]+)f", header)
        self.assertIsNotNone(match, name)
        return float(match.group(1))

    def tabulated(label):
        match = re.search(
            re.escape(label) + r".*?\$\[([0-9.]+),([0-9.]+)\]\$",
            fusion,
            re.S,
        )
        self.assertIsNotNone(match, label)
        return float(match.group(1)), float(match.group(2))

    self.assertEqual(
        tabulated(r"[\tau_{\min},\tau_{\max}]$"),
        (clamp("MIN_TAU_S"), clamp("MAX_TAU_S")),
    )
    self.assertEqual(
        tabulated(r"[r_{S,\min},r_{S,\max}]$"),
        (clamp("MIN_R_S"), clamp("MAX_R_S")),
    )

    # Direction/tracker thresholds no longer belong to the OU implementation
    # table; the remaining attitude reset is an OU startup/recovery safeguard.
    self.assertNotIn("direction-axis validity", fusion)
    self.assertNotIn("sense coherence", fusion)
    self.assertNotIn("tracker band", fusion)
    self.assertIn("70^\\circ", fusion)

    self.assertIn("functional source portability only", simulation)
    self.assertIn("timing, processor load, memory use, power, deadline margin", simulation)
    self.assertIn("were not measured", simulation)
    self.assertIn("outside the claims of this study", simulation)


core.ManuscriptMethodologyTests.test_the_deterministic_table_is_generated_not_typed = (
    _the_deterministic_table_is_generated_not_typed
)
core.ManuscriptMethodologyTests.test_transition_and_secondary_ensembles_are_rescored = (
    _transition_and_secondary_ensembles_are_rescored
)
core.ManuscriptMethodologyTests.test_tracker_and_heel_material_are_scoped_as_unevaluated_appendices = (
    _tracker_and_heel_material_are_scoped_as_unevaluated_appendices
)
core.ManuscriptMethodologyTests.test_baseline_fairness_thresholds_and_hardware_limits_are_recorded = (
    _baseline_fairness_thresholds_and_hardware_limits_are_recorded
)


class WaveDirectionPublicationSplitTests(unittest.TestCase):
    def test_split_files_are_owned_by_the_new_article(self):
        wave_article = (DOC / "kalman-wave-dir.tex").read_text(encoding="utf-8")
        ou_article = (DOC / "kalman_ou-w3d.tex").read_text(encoding="utf-8")
        fusion = (DOC / "w3d-fus-methods.tex-part").read_text(encoding="utf-8")

        self.assertIn("Single-IMU Wave-Direction", wave_article)
        self.assertIn(r"\input{w3d-frequency-tracking.tex-part}", wave_article)
        self.assertIn(r"\input{w3d-direction-methods.tex-part}", wave_article)
        self.assertIn(r"\input{w3d-wave-direction-results.tex-part}", wave_article)
        self.assertNotIn("OUValidationDirectionAbsError", ou_article)
        self.assertNotIn("w3d-direction-methods.tex-part", fusion)

    def test_overrides_are_installed(self):
        self.assertIs(
            core.ManuscriptMethodologyTests.test_the_deterministic_table_is_generated_not_typed,
            _the_deterministic_table_is_generated_not_typed,
        )
        self.assertIs(
            core.ManuscriptMethodologyTests.test_transition_and_secondary_ensembles_are_rescored,
            _transition_and_secondary_ensembles_are_rescored,
        )
        self.assertIs(
            core.ManuscriptMethodologyTests.test_tracker_and_heel_material_are_scoped_as_unevaluated_appendices,
            _tracker_and_heel_material_are_scoped_as_unevaluated_appendices,
        )
