"""Compatibility overrides for manuscript tests made obsolete by the reorganization.

These keep the underlying scientific/publication contracts while dropping
requirements that existed only because the old paper embedded a deterministic
table, carried unevaluated appendices, or used one exact novelty sentence.
"""

import re
from pathlib import Path

import test_ou_validation as core


REPO_ROOT = Path(__file__).resolve().parents[2]
DOC = REPO_ROOT / "doc" / "kalman_ou_iii"


def _deterministic_table_remains_generated_evidence(self):
    methodology = self.read("w3d-sim-charts.tex-part")
    generated = self.read("w3d-sim-results-generated.tex-part")
    self.assertIn("tab:sim_results_rms_dir_basic", generated)
    self.assertIn("Generated by tools/ou_sim_table.py", generated)
    body = re.compile(r"^\s*(JONSWAP|PM--Stokes)\s*&", re.M)
    self.assertFalse(
        body.search(methodology),
        "Evaluation Methodology must not contain a hand-typed deterministic table",
    )
    self.assertEqual(len(body.findall(generated)), 8)


def _singer_relationship_and_contribution_boundary(self):
    intro = self.read("w3d-intro.tex-part")
    bibliography = self.read("w3d.bib")
    self.assertIn("Singer1970_ManeuverModel", intro)
    self.assertIn("Ornstein--Uhlenbeck process itself", intro)
    self.assertIn("classical", intro)
    self.assertIn("doi     = {10.1109/TAES.1970.310128}", bibliography)
    self.assertNotIn("novel", intro.lower())


def _unevaluated_tracker_and_heel_material_stays_out_of_main_claims(self):
    manuscript = self.read("kalman_ou-w3d.tex")
    fusion = self.read("w3d-fus-methods.tex-part")
    conclusion = self.read("w3d-conclusion-summary.tex-part")
    # Alternative acceleration carriers and the wind-heel model are not part of
    # the evaluated OU-III main-paper algorithm. The former remains direction
    # telemetry; the latter is explicitly future work.
    self.assertNotIn("w3d-tracker-alternatives.tex-part", manuscript)
    self.assertNotIn("w3d-wind-heel.tex-part", manuscript)
    self.assertNotIn("Aranovskiy Frequency Tracker", fusion)
    self.assertIn("Wind-heel separation", conclusion)


core.ManuscriptMethodologyTests.test_the_deterministic_table_is_generated_not_typed = (
    _deterministic_table_remains_generated_evidence
)
core.ManuscriptMethodologyTests.test_singer_relationship_and_contribution_wording = (
    _singer_relationship_and_contribution_boundary
)
core.ManuscriptMethodologyTests.test_tracker_and_heel_material_are_scoped_as_unevaluated_appendices = (
    _unevaluated_tracker_and_heel_material_stays_out_of_main_claims
)
