#!/usr/bin/env python3
"""Generate and independently verify a common quadratic contraction witness.

The input matrices are finite-difference Jacobians produced by
`generate_jacobians.cpp` from the actual OU-III predict/correct implementation.
The SDP uses a deterministic design subset; every generated matrix is then
checked independently against the returned witness.  The output deliberately
calls this a certificate for the declared finite implementation envelope.  It
is not presented as an interval proof for every point of a continuous box.
"""
from __future__ import annotations

import argparse
import json
import math
from pathlib import Path
from typing import Any

import cvxpy as cp
import numpy as np


def read_matrices(path: Path) -> tuple[list[dict[str, float]], list[np.ndarray]]:
    with path.open("r", encoding="utf-8") as fh:
        header = fh.readline().split()
        if len(header) != 3 or header[0] != "OCEAN_IMU_ISS_JACOBIANS_V1":
            raise ValueError("invalid Jacobian file header")
        n, count = int(header[1]), int(header[2])
        meta: list[dict[str, float]] = []
        matrices: list[np.ndarray] = []
        for expected in range(count):
            fields = fh.readline().split()
            if len(fields) != 11 or fields[0] != "POINT" or int(fields[1]) != expected:
                raise ValueError(f"invalid point record {expected}")
            names = ["dt", "tau", "sigma_aw", "sigma_s", "roll", "pitch", "wx", "wy", "wz"]
            meta.append(dict(zip(names, map(float, fields[2:]), strict=True)))
            rows = [[float(x) for x in fh.readline().split()] for _ in range(n)]
            F = np.asarray(rows, dtype=float)
            if F.shape != (n, n) or not np.isfinite(F).all():
                raise ValueError(f"invalid matrix {expected}")
            matrices.append(F)
    return meta, matrices


def generalized_contraction(F: np.ndarray, P: np.ndarray) -> float:
    # Largest generalized eigenvalue of (F'PF, P), computed through a
    # symmetric similarity transformation to avoid explicit P^{-1}.
    eig, U = np.linalg.eigh(P)
    if eig[0] <= 0.0:
        raise ValueError("P is not positive definite")
    Pinvhalf = (U * (1.0 / np.sqrt(eig))) @ U.T
    M = Pinvhalf @ (F.T @ P @ F) @ Pinvhalf
    M = 0.5 * (M + M.T)
    return float(np.linalg.eigvalsh(M)[-1])


def design_indices(count: int, limit: int) -> np.ndarray:
    if count <= limit:
        return np.arange(count, dtype=int)
    # Deterministic coverage of the ordered Cartesian product.
    return np.unique(np.linspace(0, count - 1, limit, dtype=int))


def solve_common_p(matrices: list[np.ndarray], indices: np.ndarray, rho: float) -> np.ndarray | None:
    n = matrices[0].shape[0]
    P = cp.Variable((n, n), symmetric=True)
    eps = 2.0e-7
    constraints: list[Any] = [P >> eps * np.eye(n), cp.trace(P) == float(n)]
    r2 = rho * rho
    for i in indices:
        F = matrices[int(i)]
        constraints.append(F.T @ P @ F - r2 * P << -eps * np.eye(n))
    problem = cp.Problem(cp.Minimize(cp.norm(P, "fro")), constraints)
    try:
        problem.solve(solver="CLARABEL", tol_gap_abs=1e-8, tol_feas=1e-8,
                      tol_gap_rel=1e-8, max_iter=500, verbose=False)
    except Exception:
        return None
    if problem.status not in {cp.OPTIMAL, cp.OPTIMAL_INACCURATE} or P.value is None:
        return None
    out = np.asarray(P.value, dtype=float)
    return 0.5 * (out + out.T)


def find_witness(matrices: list[np.ndarray], indices: np.ndarray) -> tuple[np.ndarray, float]:
    # The one-sample map is expected to contract slowly at 200--240 Hz, so the
    # useful range is close to one.  Bisection still reports the tightest value
    # supported by the design set.
    lo, hi = 0.90, 0.999999999
    best: tuple[np.ndarray, float] | None = None
    for _ in range(28):
        mid = 0.5 * (lo + hi)
        P = solve_common_p(matrices, indices, mid)
        if P is None:
            lo = mid
        else:
            best = (P, mid)
            hi = mid
    if best is None:
        raise RuntimeError("common quadratic SDP is infeasible on the design set")
    return best


def write_tex(path: Path, result: dict[str, Any]) -> None:
    worst = result["worst_point"]
    text = rf"""% Generated by tools/iss_certificate/verify_certificate.py; do not edit.
\begin{{table}}[t]
\centering
\caption{{Implementation-generated common quadratic contraction certificate on the declared finite OU--III operating envelope.}}
\label{{tab:iss-certificate}}
\begin{{tabular}}{{ll}}
\toprule
Quantity & Certified value \\
\midrule
State dimension & {result['state_dimension']} \\
Generated Jacobians & {result['matrix_count']} \\
SDP design Jacobians & {result['design_count']} \\
Worst verified $\sqrt{{\lambda_{{\max}}}}$ & {result['rho_verified']:.9f} \\
Strict contraction margin $1-\lambda_{{\max}}$ & {result['margin']:.3e} \\
$\lambda_{{\min}}(L)$ & {result['p_eigen_min']:.3e} \\
$\lambda_{{\max}}(L)$ & {result['p_eigen_max']:.3e} \\
Worst point $(\Delta t,\tau,\sigma_a,\sigma_S)$ &
({worst['dt']:.6f}, {worst['tau']:.3f}, {worst['sigma_aw']:.3f}, {worst['sigma_s']:.3f}) \\
Worst point $(\phi,\theta,\omega_x,\omega_y,\omega_z)$ &
({worst['roll']:.3f}, {worst['pitch']:.3f}, {worst['wx']:.3f}, {worst['wy']:.3f}, {worst['wz']:.3f}) \\
\bottomrule
\end{{tabular}}
\end{{table}}
"""
    path.write_text(text, encoding="utf-8")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("jacobians", type=Path)
    ap.add_argument("--json", type=Path, required=True)
    ap.add_argument("--tex", type=Path, required=True)
    ap.add_argument("--design-count", type=int, default=96)
    args = ap.parse_args()

    meta, matrices = read_matrices(args.jacobians)
    indices = design_indices(len(matrices), args.design_count)
    P, rho_design = find_witness(matrices, indices)

    p_eig = np.linalg.eigvalsh(P)
    if p_eig[0] <= 1.0e-9:
        raise RuntimeError("returned witness is not numerically positive definite")

    values = np.asarray([generalized_contraction(F, P) for F in matrices])
    worst_index = int(np.argmax(values))
    worst_value = float(values[worst_index])
    margin = 1.0 - worst_value
    # Independent post-solve acceptance test.  This is intentionally stricter
    # than accepting the solver status alone.
    if not math.isfinite(worst_value) or margin <= 1.0e-8:
        raise RuntimeError(
            f"witness does not strictly contract the full generated set: "
            f"lambda_max={worst_value:.12g}, margin={margin:.12g}"
        )

    result: dict[str, Any] = {
        "schema": "ocean-imu-iss-certificate-v1",
        "scope": "finite implementation-generated operating envelope",
        "state_dimension": int(P.shape[0]),
        "matrix_count": len(matrices),
        "design_count": int(len(indices)),
        "rho_design": rho_design,
        "rho_verified": math.sqrt(worst_value),
        "lambda_verified": worst_value,
        "margin": margin,
        "p_eigen_min": float(p_eig[0]),
        "p_eigen_max": float(p_eig[-1]),
        "p_condition": float(p_eig[-1] / p_eig[0]),
        "worst_index": worst_index,
        "worst_point": meta[worst_index],
        "design_indices": indices.tolist(),
        "P": P.tolist(),
    }
    args.json.parent.mkdir(parents=True, exist_ok=True)
    args.tex.parent.mkdir(parents=True, exist_ok=True)
    args.json.write_text(json.dumps(result, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    write_tex(args.tex, result)
    print(json.dumps({k: result[k] for k in (
        "matrix_count", "design_count", "rho_verified", "margin",
        "p_eigen_min", "p_eigen_max", "worst_index")}, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
