#!/usr/bin/env python3
"""Verify reduced-state local stability of the implemented OU-III cycle.

The implementation Jacobian is partitioned as

    [ e+ ]   [F_ee F_eb] [ e ]
    [ b+ ] = [F_be F_bb] [ b ],

where e is the 18-dimensional performance error and b is the three-dimensional
accelerometer-bias nuisance error.  The certificate verifies every F_ee is
strictly Schur stable, constructs its discrete Lyapunov matrix, independently
checks the Lyapunov residual, and reports the F_eb input-channel norm.
"""
from __future__ import annotations

import argparse
import json
import math
from pathlib import Path
from typing import Any

import numpy as np
from scipy.linalg import solve_discrete_lyapunov

PERFORMANCE_IDX = np.arange(18, dtype=int)
ACCEL_BIAS_IDX = np.arange(18, 21, dtype=int)


def read_matrices(path: Path) -> tuple[list[dict[str, float]], list[np.ndarray]]:
    with path.open("r", encoding="utf-8") as fh:
        header = fh.readline().split()
        if len(header) != 3 or header[0] != "OCEAN_IMU_ISS_JACOBIANS_V1":
            raise ValueError("invalid Jacobian file header")
        n, count = int(header[1]), int(header[2])
        meta: list[dict[str, float]] = []
        matrices: list[np.ndarray] = []
        for expected in range(count):
            fields = fh.readline().split()
            if len(fields) != 11 or fields[0] != "POINT" or int(fields[1]) != expected:
                raise ValueError(f"invalid point record {expected}")
            names = ["dt", "tau", "sigma_aw", "sigma_s", "roll", "pitch", "wx", "wy", "wz"]
            meta.append(dict(zip(names, map(float, fields[2:]), strict=True)))
            rows = [[float(x) for x in fh.readline().split()] for _ in range(n)]
            F = np.asarray(rows, dtype=float)
            if F.shape != (n, n) or not np.isfinite(F).all():
                raise ValueError(f"invalid matrix {expected}")
            matrices.append(F)
    return meta, matrices


def lyapunov_metrics(A: np.ndarray) -> dict[str, float]:
    n = A.shape[0]
    P = solve_discrete_lyapunov(A.T, np.eye(n))
    P = 0.5 * (P + P.T)
    eig = np.linalg.eigvalsh(P)
    if eig[0] <= 0.0 or not np.isfinite(eig).all():
        raise RuntimeError("discrete Lyapunov solution is not positive definite")

    residual = A.T @ P @ A - P + np.eye(n)
    residual_norm = float(np.linalg.norm(residual, ord=2))
    residual_relative = residual_norm / max(1.0, float(eig[-1]))

    # From A' P A = P - I, the squared contraction factor in the P metric is
    # lambda_max(P^{-1/2}(P-I)P^{-1/2}) = 1 - 1/lambda_max(P).
    lambda_metric = max(0.0, 1.0 - 1.0 / float(eig[-1]))
    return {
        "p_eigen_min": float(eig[0]),
        "p_eigen_max": float(eig[-1]),
        "p_condition": float(eig[-1] / eig[0]),
        "lambda_metric": lambda_metric,
        "rho_metric": math.sqrt(lambda_metric),
        "residual_norm": residual_norm,
        "residual_relative": residual_relative,
    }


def write_tex(path: Path, result: dict[str, Any]) -> None:
    worst = result["worst_spectral_point"]
    text = rf"""% Generated by tools/iss_certificate/verify_certificate.py; do not edit.
\begin{{table}}[t]
\centering
\caption{{Implementation-generated reduced-state stability certificate for the OU--III performance error. Accelerometer bias is excluded from the certified error and retained as a bounded input channel.}}
\label{{tab:iss-certificate}}
\begin{{tabular}}{{ll}}
\toprule
Quantity & Verified value \\
\midrule
Performance-state dimension & {result['state_dimension']} \\
Excluded nuisance-state dimension & {result['excluded_state_dimension']} \\
Generated operating points & {result['matrix_count']} \\
Maximum spectral radius of $F_{{ee}}$ & {result['spectral_radius_max']:.9f} \\
Minimum Schur margin $1-\rho(F_{{ee}})$ & {result['spectral_margin_min']:.3e} \\
Worst pointwise Lyapunov $\rho_L$ & {result['rho_metric_max']:.9f} \\
Maximum relative Lyapunov residual & {result['lyapunov_residual_relative_max']:.3e} \\
Worst $\|F_{{e b_a}}\|_2$ & {result['max_bias_coupling_2norm']:.3e} \\
Worst point $(\Delta t,\tau,\sigma_a,\sigma_S)$ &
({worst['dt']:.6f}, {worst['tau']:.3f}, {worst['sigma_aw']:.3f}, {worst['sigma_s']:.3f}) \\
Worst point $(\phi,\theta,\omega_x,\omega_y,\omega_z)$ &
({worst['roll']:.3f}, {worst['pitch']:.3f}, {worst['wx']:.3f}, {worst['wy']:.3f}, {worst['wz']:.3f}) \\
\bottomrule
\end{{tabular}}
\end{{table}}
"""
    path.write_text(text, encoding="utf-8")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("jacobians", type=Path)
    ap.add_argument("--json", type=Path, required=True)
    ap.add_argument("--tex", type=Path, required=True)
    args = ap.parse_args()

    meta, full_matrices = read_matrices(args.jacobians)
    performance_matrices = [F[np.ix_(PERFORMANCE_IDX, PERFORMANCE_IDX)] for F in full_matrices]
    bias_channels = [F[np.ix_(PERFORMANCE_IDX, ACCEL_BIAS_IDX)] for F in full_matrices]

    spectral_radii = np.asarray([
        float(np.max(np.abs(np.linalg.eigvals(A)))) for A in performance_matrices
    ])
    worst_spectral_index = int(np.argmax(spectral_radii))
    spectral_radius_max = float(spectral_radii[worst_spectral_index])
    spectral_margin_min = 1.0 - spectral_radius_max
    if not math.isfinite(spectral_radius_max) or spectral_margin_min <= 1.0e-8:
        raise RuntimeError(
            "reduced performance-state Jacobian is not strictly Schur stable: "
            f"rho={spectral_radius_max:.12g}, margin={spectral_margin_min:.12g}"
        )

    metrics = [lyapunov_metrics(A) for A in performance_matrices]
    residual_relative_max = max(m["residual_relative"] for m in metrics)
    if residual_relative_max > 1.0e-10:
        raise RuntimeError(
            "pointwise Lyapunov residual check failed: "
            f"max_relative_residual={residual_relative_max:.12g}"
        )

    bias_norms = np.asarray([np.linalg.norm(B, ord=2) for B in bias_channels])
    max_bias_index = int(np.argmax(bias_norms))
    rho_metric_values = np.asarray([m["rho_metric"] for m in metrics])
    worst_metric_index = int(np.argmax(rho_metric_values))

    result: dict[str, Any] = {
        "schema": "ocean-imu-iss-certificate-v3",
        "scope": "finite implementation-generated reduced performance-state envelope",
        "certificate_type": "pointwise discrete Lyapunov family",
        "state_definition": ["dtheta", "bg", "v", "p", "S", "aw"],
        "excluded_nuisance_state": ["ba"],
        "state_dimension": 18,
        "excluded_state_dimension": 3,
        "matrix_count": len(performance_matrices),
        "spectral_radius_min": float(np.min(spectral_radii)),
        "spectral_radius_max": spectral_radius_max,
        "spectral_margin_min": spectral_margin_min,
        "worst_spectral_index": worst_spectral_index,
        "worst_spectral_point": meta[worst_spectral_index],
        "rho_metric_max": float(rho_metric_values[worst_metric_index]),
        "worst_metric_index": worst_metric_index,
        "worst_metric_point": meta[worst_metric_index],
        "p_eigen_min_global": min(m["p_eigen_min"] for m in metrics),
        "p_eigen_max_global": max(m["p_eigen_max"] for m in metrics),
        "p_condition_max": max(m["p_condition"] for m in metrics),
        "lyapunov_residual_relative_max": residual_relative_max,
        "max_bias_coupling_2norm": float(bias_norms[max_bias_index]),
        "max_bias_coupling_index": max_bias_index,
        "max_bias_coupling_point": meta[max_bias_index],
    }

    args.json.parent.mkdir(parents=True, exist_ok=True)
    args.tex.parent.mkdir(parents=True, exist_ok=True)
    args.json.write_text(json.dumps(result, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    write_tex(args.tex, result)
    print(json.dumps(result, indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
