#!/usr/bin/env python3
"""Generate and independently verify a common quadratic contraction witness.

The input matrices are finite-difference Jacobians produced by
`generate_jacobians.cpp` from the actual OU-III predict/correct implementation.
The certified performance state excludes accelerometer bias, which is an
auxiliary nuisance state rather than a performance output. Its coupling into
the performance state is retained and reported as a bounded input channel.
"""
from __future__ import annotations

import argparse
import json
import math
from pathlib import Path
from typing import Any

import cvxpy as cp
import numpy as np

PERFORMANCE_IDX = np.arange(18, dtype=int)
ACCEL_BIAS_IDX = np.arange(18, 21, dtype=int)


def read_matrices(path: Path) -> tuple[list[dict[str, float]], list[np.ndarray]]:
    with path.open("r", encoding="utf-8") as fh:
        header = fh.readline().split()
        if len(header) != 3 or header[0] != "OCEAN_IMU_ISS_JACOBIANS_V1":
            raise ValueError("invalid Jacobian file header")
        n, count = int(header[1]), int(header[2])
        meta: list[dict[str, float]] = []
        matrices: list[np.ndarray] = []
        for expected in range(count):
            fields = fh.readline().split()
            if len(fields) != 11 or fields[0] != "POINT" or int(fields[1]) != expected:
                raise ValueError(f"invalid point record {expected}")
            names = ["dt", "tau", "sigma_aw", "sigma_s", "roll", "pitch", "wx", "wy", "wz"]
            meta.append(dict(zip(names, map(float, fields[2:]), strict=True)))
            rows = [[float(x) for x in fh.readline().split()] for _ in range(n)]
            F = np.asarray(rows, dtype=float)
            if F.shape != (n, n) or not np.isfinite(F).all():
                raise ValueError(f"invalid matrix {expected}")
            matrices.append(F)
    return meta, matrices


def generalized_contraction(F: np.ndarray, P: np.ndarray) -> float:
    eig, U = np.linalg.eigh(P)
    if eig[0] <= 0.0:
        raise ValueError("P is not positive definite")
    Pinvhalf = (U * (1.0 / np.sqrt(eig))) @ U.T
    M = Pinvhalf @ (F.T @ P @ F) @ Pinvhalf
    M = 0.5 * (M + M.T)
    return float(np.linalg.eigvalsh(M)[-1])


def design_indices(count: int, limit: int) -> np.ndarray:
    if count <= limit:
        return np.arange(count, dtype=int)
    return np.unique(np.linspace(0, count - 1, limit, dtype=int))


def solve_common_p(matrices: list[np.ndarray], indices: np.ndarray, rho: float) -> np.ndarray | None:
    n = matrices[0].shape[0]
    P = cp.Variable((n, n), symmetric=True)
    # The one-step contraction margin at 200--240 Hz is around 1e-6. Keep the
    # solver regularization well below that physical margin; acceptance is based
    # on the independent post-solve eigenvalue check, not this epsilon.
    eps = 1.0e-10
    constraints: list[Any] = [P >> eps * np.eye(n), cp.trace(P) == float(n)]
    r2 = rho * rho
    for i in indices:
        F = matrices[int(i)]
        constraints.append(F.T @ P @ F - r2 * P << -eps * np.eye(n))
    problem = cp.Problem(cp.Minimize(cp.norm(P, "fro")), constraints)
    try:
        problem.solve(solver="CLARABEL", tol_gap_abs=1e-9, tol_feas=1e-9,
                      tol_gap_rel=1e-9, max_iter=700, verbose=False)
    except Exception:
        return None
    if problem.status not in {cp.OPTIMAL, cp.OPTIMAL_INACCURATE} or P.value is None:
        return None
    out = np.asarray(P.value, dtype=float)
    return 0.5 * (out + out.T)


def find_witness(matrices: list[np.ndarray], indices: np.ndarray) -> tuple[np.ndarray, float]:
    lo, hi = 0.90, 0.9999999999
    best: tuple[np.ndarray, float] | None = None
    for _ in range(24):
        mid = 0.5 * (lo + hi)
        P = solve_common_p(matrices, indices, mid)
        if P is None:
            lo = mid
        else:
            best = (P, mid)
            hi = mid
    if best is None:
        raise RuntimeError("common quadratic SDP is infeasible on the performance-state design set")
    return best


def write_tex(path: Path, result: dict[str, Any]) -> None:
    worst = result["worst_point"]
    text = rf"""% Generated by tools/iss_certificate/verify_certificate.py; do not edit.
\begin{{table}}[t]
\centering
\caption{{Implementation-generated contraction certificate for the OU--III performance-error state. Accelerometer bias is excluded from the Lyapunov state and retained as a bounded input channel.}}
\label{{tab:iss-certificate}}
\begin{{tabular}}{{ll}}
\toprule
Quantity & Certified value \\
\midrule
Performance-state dimension & {result['state_dimension']} \\
Excluded nuisance-state dimension & {result['excluded_state_dimension']} \\
Generated Jacobians & {result['matrix_count']} \\
SDP design Jacobians & {result['design_count']} \\
Worst verified $\sqrt{{\lambda_{{\max}}}}$ & {result['rho_verified']:.9f} \\
Strict contraction margin $1-\lambda_{{\max}}$ & {result['margin']:.3e} \\
Worst $\|F_{{e b_a}}\|_2$ & {result['max_bias_coupling_2norm']:.3e} \\
$\lambda_{{\min}}(L)$ & {result['p_eigen_min']:.3e} \\
$\lambda_{{\max}}(L)$ & {result['p_eigen_max']:.3e} \\
Worst point $(\Delta t,\tau,\sigma_a,\sigma_S)$ &
({worst['dt']:.6f}, {worst['tau']:.3f}, {worst['sigma_aw']:.3f}, {worst['sigma_s']:.3f}) \\
Worst point $(\phi,\theta,\omega_x,\omega_y,\omega_z)$ &
({worst['roll']:.3f}, {worst['pitch']:.3f}, {worst['wx']:.3f}, {worst['wy']:.3f}, {worst['wz']:.3f}) \\
\bottomrule
\end{{tabular}}
\end{{table}}
"""
    path.write_text(text, encoding="utf-8")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("jacobians", type=Path)
    ap.add_argument("--json", type=Path, required=True)
    ap.add_argument("--tex", type=Path, required=True)
    ap.add_argument("--design-count", type=int, default=32)
    args = ap.parse_args()

    meta, full_matrices = read_matrices(args.jacobians)
    performance_matrices = [F[np.ix_(PERFORMANCE_IDX, PERFORMANCE_IDX)] for F in full_matrices]
    bias_channels = [F[np.ix_(PERFORMANCE_IDX, ACCEL_BIAS_IDX)] for F in full_matrices]

    spectral_radii = np.asarray([
        float(np.max(np.abs(np.linalg.eigvals(F)))) for F in performance_matrices
    ])
    if float(np.max(spectral_radii)) >= 1.0:
        raise RuntimeError(
            "at least one performance-state Jacobian is not Schur stable: "
            f"max_rho={float(np.max(spectral_radii)):.12g}"
        )

    indices = design_indices(len(performance_matrices), args.design_count)
    P, rho_design = find_witness(performance_matrices, indices)

    p_eig = np.linalg.eigvalsh(P)
    if p_eig[0] <= 1.0e-9:
        raise RuntimeError("returned witness is not numerically positive definite")

    values = np.asarray([generalized_contraction(F, P) for F in performance_matrices])
    worst_index = int(np.argmax(values))
    worst_value = float(values[worst_index])
    margin = 1.0 - worst_value
    if not math.isfinite(worst_value) or margin <= 1.0e-8:
        raise RuntimeError(
            "witness does not strictly contract the full generated performance-state set: "
            f"lambda_max={worst_value:.12g}, margin={margin:.12g}"
        )

    bias_norms = np.asarray([np.linalg.norm(B, ord=2) for B in bias_channels])
    max_bias_index = int(np.argmax(bias_norms))

    result: dict[str, Any] = {
        "schema": "ocean-imu-iss-certificate-v2",
        "scope": "finite implementation-generated performance-state envelope",
        "state_definition": ["dtheta", "bg", "v", "p", "S", "aw"],
        "excluded_nuisance_state": ["ba"],
        "state_dimension": int(P.shape[0]),
        "excluded_state_dimension": 3,
        "matrix_count": len(performance_matrices),
        "design_count": int(len(indices)),
        "spectral_radius_min": float(np.min(spectral_radii)),
        "spectral_radius_max": float(np.max(spectral_radii)),
        "rho_design": rho_design,
        "rho_verified": math.sqrt(worst_value),
        "lambda_verified": worst_value,
        "margin": margin,
        "max_bias_coupling_2norm": float(bias_norms[max_bias_index]),
        "max_bias_coupling_index": max_bias_index,
        "max_bias_coupling_point": meta[max_bias_index],
        "p_eigen_min": float(p_eig[0]),
        "p_eigen_max": float(p_eig[-1]),
        "p_condition": float(p_eig[-1] / p_eig[0]),
        "worst_index": worst_index,
        "worst_point": meta[worst_index],
        "design_indices": indices.tolist(),
        "P": P.tolist(),
    }
    args.json.parent.mkdir(parents=True, exist_ok=True)
    args.tex.parent.mkdir(parents=True, exist_ok=True)
    args.json.write_text(json.dumps(result, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    write_tex(args.tex, result)
    print(json.dumps({k: result[k] for k in (
        "matrix_count", "design_count", "state_dimension", "spectral_radius_max",
        "rho_verified", "margin", "max_bias_coupling_2norm",
        "p_eigen_min", "p_eigen_max", "worst_index")}, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
