#!/usr/bin/env python3
"""Non-promoting 18-state motion feasibility for H18 and A21 shipping words.

P4's declared objective is bounded accelerometer-bias error plus practical ISS
of the other 18 coordinates. A full 21-state A21 contraction is therefore a
stronger statement than the theorem requires and is known to fail at finite
amplitude in the current full-product storage.

This diagnostic keeps the complete 21-state shipping word composition but sets
the *entrance* accelerometer-bias perturbation to zero and measures only the
18 motion coordinates at the endpoint. Thus M[:18,:18] retains all within-word
motion -> b_a -> motion feedback generated by the real A21 factors. The endpoint
metric is the 18x18 marginal shipping covariance block. Bias uncertainty is not
silently deleted from the theorem: it belongs to the separate bounded-bias ISS
supply/projection argument. This point diagnostic merely asks whether the
motion part has a feasible contracting complete-word backbone before rigorous
source-uniform enclosure is attempted.
"""
from __future__ import annotations

import argparse,json,math
from pathlib import Path

import ou3_p4_complete_brmm_word_feasibility as WORD

EXPECTED_STRIDE=600
EXPECTED_HORIZON_S=3.0


def analyze(map_path:Path,cov_path:Path)->dict:
    ms,maps=WORD.read_maps(map_path);cs,covs=WORD.read_covariances(cov_path)
    if ms!=cs or ms!=EXPECTED_STRIDE:
        raise RuntimeError(f'map/cov stride mismatch or non-3s word: {ms} {cs}')
    n=min(len(maps),len(covs));rows=[];rejected={}
    for i in range(n):
        m,c=maps[i],covs[i]
        if abs(m['t0']-c['t0'])>2e-4 or abs(m['t1']-c['t1'])>2e-4:
            raise RuntimeError(f'map/cov alignment lost at record {i}')
        flags=int(m['flags']);reasons=[]
        if not(flags&1):reasons.append('map_invalid')
        if flags&(1<<7):reasons.append('hybrid_jump')
        if not(flags&(1<<1)) or not(flags&(1<<2)):reasons.append('not_live')
        mode=WORD._mode(flags)
        if mode=='HYBRID':reasons.append('mode_change')
        if abs(float(m['t1']-m['t0'])-EXPECTED_HORIZON_S)>0.02:reasons.append('not_3s')
        if int(m['acc_count'])!=EXPECTED_STRIDE:reasons.append('missing_accelerometer_update')
        if int(m['pseudo_count'])<20:reasons.append('missing_due_S_regularization')
        if reasons:
            for r in reasons:rejected[r]=rejected.get(r,0)+1
            continue
        # Always use the complete 21-state composed map's motion principal block.
        # In A21 this retains the round-trip coupling through b_a when the root
        # b_a perturbation is zero; it is not a product of 18x18 subevent blocks.
        rho,d18=WORD._linear_ratio(m['M'][:18,:18],c['P0'][:18,:18],c['P1'][:18,:18])
        rows.append({
          'record':i,'mode':mode,'t0':float(m['t0']),'t1':float(m['t1']),
          'rho_linear':rho,'distance_to_one':1.0-rho,
          'acc_count':int(m['acc_count']),'mag_count':int(m['mag_count']),'S_update_count':int(m['pseudo_count']),
          'tau_start':float(m['tau0']),'tau_end':float(m['tau1']),'sigma_start':float(m['sigma0']),'sigma_end':float(m['sigma1']),
          'RS_scalar_start':float(m['rs0']),'RS_scalar_end':float(m['rs1']),
          'exact_map_linearization_recovery_residual':float(m['linearization_residual']),
          'maximizing_direction':WORD._direction_json(d18,18)})
    modes={}
    for mode in ('H18','A21'):
        rr=[x for x in rows if x['mode']==mode]
        if not rr:modes[mode]={'legal_blocks':0,'worst':None};continue
        worst=max(rr,key=lambda x:x['rho_linear'])
        modes[mode]={'legal_blocks':len(rr),'rho_min':min(x['rho_linear'] for x in rr),'rho_max':worst['rho_linear'],'worst':worst}
    return {
      'qualification':'NON_PROMOTING_COMPLETE_BRMM_P4_BOUNDED_BIAS_MOTION18_FEASIBILITY_V1',
      'canonical_source':'COMPLETE_BRMM_NORMAL_LIVE_WORD','point_same_history_diagnostic_only':True,
      'P4_promoted':False,'P4_MOTION_PASS':False,'source_family_materialized':False,
      'filter_changed':False,'declared_domain_changed':False,
      'theorem_objective':'bounded accelerometer-bias error plus practical ISS of other 18 coordinates',
      'full_21_state_word_composed_before_motion_selection':True,
      'A21_root_accelerometer_bias_perturbation_zero_for_backbone_test':True,
      'A21_within_word_motion_bias_motion_feedback_retained':True,
      'bounded_bias_supply_still_required_separately':True,
      'covariance_membership_used_as_true_error_set':False,
      'map_stride_samples':ms,'word_horizon_s':EXPECTED_HORIZON_S,
      'actual_applied_RS_used_inside_each_S_gain':True,'all_valid_accelerometer_updates_required':True,
      'all_due_S_updates_required':True,'records_seen':n,'records_rejected':rejected,'modes':modes,
      'next_experiment':'run the existing exact-Cayley frozen-gain nonlinear shadow on these motion-only maximizing directions; if A21 still crosses rho=1, abandon this motion-storage backbone'}

def validate(d):
    f=[]
    for k in ('point_same_history_diagnostic_only','full_21_state_word_composed_before_motion_selection','A21_root_accelerometer_bias_perturbation_zero_for_backbone_test','A21_within_word_motion_bias_motion_feedback_retained','bounded_bias_supply_still_required_separately','actual_applied_RS_used_inside_each_S_gain','all_valid_accelerometer_updates_required','all_due_S_updates_required'):
        if d.get(k) is not True:f.append(k+' not true')
    for k in ('P4_promoted','P4_MOTION_PASS','source_family_materialized','filter_changed','declared_domain_changed','covariance_membership_used_as_true_error_set'):
        if d.get(k) is not False:f.append(k+' not false')
    for mode in ('H18','A21'):
        if d.get('modes',{}).get(mode,{}).get('legal_blocks',0)<=0:f.append(mode+' has no legal block')
        w=d.get('modes',{}).get(mode,{}).get('worst')
        if w and float(w['maximizing_direction']['group_euclidean_norms']['ba'])!=0.0:f.append(mode+' motion direction has nonzero root ba')
    return f

def main()->int:
    ap=argparse.ArgumentParser();ap.add_argument('--map',type=Path,required=True);ap.add_argument('--cov',type=Path,required=True);ap.add_argument('--output',type=Path,required=True);a=ap.parse_args()
    d=analyze(a.map,a.cov);f=validate(d);d['validation_pass']=not f;d['validation_failures']=f
    a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(d,indent=2,sort_keys=True)+'\n')
    print(json.dumps({'H18':d['modes']['H18'],'A21':d['modes']['A21'],'failures':f},indent=2,sort_keys=True));return int(bool(f))
if __name__=='__main__':raise SystemExit(main())
