#!/usr/bin/env python3
"""Correlated deployed tuner target cell for the complete-BRMM P4 cover.

This remains a coarse sanity/admissibility enclosure only.  The theorem-facing
coefficient family is generated by the same-signal estimator transition.

Given one SAME-SOURCE cell for frequency and raw sigma, construct the dependent
shipping tuple

    (f_tune, tau_target, sigma_target_raw, T_S(tau_target), R_S_target)

without independently selecting tau, T_S or R_S.  Validation of derived
coordinates is against the outward image of the stored frequency/sigma source
enclosure itself, rather than a separately rounded scalar endpoint invariant.
That avoids one-ulp disagreement between two mathematically identical outward
computations without widening the physical shipping clamps.
"""
from __future__ import annotations
from dataclasses import dataclass
import argparse,json,math,re
from pathlib import Path
from ou3_interval import Interval
import ou3_source_domain_contract as SOURCE
import ou3_brmm_dynamic_source_certificate as DYNAMIC
import ou3_validated_positive_roots as ROOTS

REPO=Path(__file__).resolve().parents[2]
WRAPPER=REPO/'src'/'kalman_ou_iii'/'SeaStateFusionFilter_OU_III.h'
DEFAULT_DOMAIN=REPO/'tools'/'stability'/'ou3_proof_operating_domain.json'
SCHEMA=3
QUALIFICATION='OU3_P4_COMPLETE_BRMM_CORRELATED_TARGET_CELL_V3'

def I(x):return Interval.point(float(x))
def finite(x,positive=False):return isinstance(x,Interval) and math.isfinite(x.lo) and math.isfinite(x.hi) and x.lo<=x.hi and (not positive or x.lo>0.0)
def subset(x,bounds):
    lo,hi=map(float,bounds);return x.lo>=lo and x.hi<=hi
def interval_subset(x,outer):return x.lo>=outer.lo and x.hi<=outer.hi

def clamp_interval(x,lo,hi):
    if not finite(x) or not(math.isfinite(lo) and math.isfinite(hi) and lo<=hi):raise ValueError('invalid clamp')
    return Interval(max(lo,min(hi,x.lo)),max(lo,min(hi,x.hi)))
def member_float(text,name):
    m=re.search(rf'\b{name}\s*=\s*([0-9.eE+-]+)f\b',text)
    if not m:raise RuntimeError('cannot extract deployed member '+name)
    return float(m.group(1))
def constants():
    text=WRAPPER.read_text(encoding='utf-8')
    names=('MIN_TUNE_FREQ_HZ','MAX_TUNE_FREQ_HZ','MIN_TAU_S','MAX_TAU_S','MIN_R_S','MAX_R_S','MAX_SIGMA_A','PSEUDO_UPDATE_TAU_RATIO_DEFAULT','PSEUDO_UPDATE_PERIOD_MIN_S_DEFAULT','PSEUDO_UPDATE_PERIOD_MAX_S_DEFAULT','R_S_ACCEL_NOISE_DENSITY_DEFAULT','R_S_MSE_COEFF_DEFAULT')
    c={n:float(SOURCE.parse_const(text,n)) for n in names};c['tau_coeff']=member_float(text,'tau_coeff_');c['sigma_coeff']=member_float(text,'sigma_coeff_');return c

def clamped_frequency(freq,c):
    if not finite(freq,True):raise ValueError('frequency interval must be positive')
    return clamp_interval(freq,c['MIN_TUNE_FREQ_HZ'],c['MAX_TUNE_FREQ_HZ'])
def tau_from_frequency(freq,c):
    f=clamped_frequency(freq,c);raw=I(.5*c['tau_coeff'])/f
    return clamp_interval(raw,c['MIN_TAU_S'],c['MAX_TAU_S'])
def pseudo_period_from_tau(tau,c):
    if not finite(tau,True):raise ValueError('tau interval must be positive')
    return clamp_interval(I(c['PSEUDO_UPDATE_TAU_RATIO_DEFAULT'])*tau,c['PSEUDO_UPDATE_PERIOD_MIN_S_DEFAULT'],c['PSEUDO_UPDATE_PERIOD_MAX_S_DEFAULT'])
def spectral_mse_rs(tau,sigma_raw,c):
    if not finite(tau,True) or not finite(sigma_raw,True):raise ValueError('positive tau/sigma intervals required')
    if not c['sigma_coeff']>0:raise ValueError('deployed sigma_coeff must be positive')
    ts=pseudo_period_from_tau(tau,c);sigma_aB=sigma_raw/I(c['sigma_coeff']);sigma_aB=Interval(max(1e-6,sigma_aB.lo),max(1e-6,sigma_aB.hi))
    tau2=tau*tau;u=sigma_aB*tau2*tau2;u67=ROOTS.pow_6_7_interval(u);qroot=ROOTS.root_14_interval(I(2*c['R_S_ACCEL_NOISE_DENSITY_DEFAULT']));root_ts=ROOTS.sqrt_interval(ts)
    raw=I(c['R_S_MSE_COEFF_DEFAULT'])*qroot*u67/root_ts
    return clamp_interval(raw,c['MIN_R_S'],c['MAX_R_S'])

@dataclass(frozen=True)
class TargetCell:
    source_token:str;predecessor_token:str|None;frequency_hz:Interval;sigma_target_raw_mps2:Interval;tau_target_s:Interval;pseudo_period_s:Interval;rs_target:Interval

def _dependent_outer_envelopes(dynamic,c):
    inv=dynamic['dynamic_invariant']
    f=Interval(*map(float,inv['tuning_frequency_hz']));s=Interval(*map(float,inv['sigma_target_raw_mps2']))
    tau=tau_from_frequency(f,c);ts=pseudo_period_from_tau(tau,c);rs=spectral_mse_rs(tau,s,c)
    return tau,ts,rs

def make_target_cell(source_token,predecessor_token,frequency_hz,sigma_target_raw_mps2,dynamic):
    if not isinstance(source_token,str) or not source_token:raise ValueError('source token required')
    inv=dynamic['dynamic_invariant']
    if not subset(frequency_hz,inv['tuning_frequency_hz']):raise ValueError('frequency outside dynamic invariant')
    if not subset(sigma_target_raw_mps2,inv['sigma_target_raw_mps2']):raise ValueError('raw sigma target outside dynamic invariant')
    c=constants();tau=tau_from_frequency(frequency_hz,c);ts=pseudo_period_from_tau(tau,c);rs=spectral_mse_rs(tau,sigma_target_raw_mps2,c)
    cell=TargetCell(source_token,predecessor_token,frequency_hz,sigma_target_raw_mps2,tau,ts,rs);failures=validate_target_cell(cell,dynamic)
    if failures:raise ValueError('constructed target cell invalid: '+repr(failures))
    return cell

def validate_target_cell(cell,dynamic):
    f=[];inv=dynamic['dynamic_invariant'];c=constants();tau_outer,ts_outer,rs_outer=_dependent_outer_envelopes(dynamic,c)
    if not isinstance(cell.source_token,str) or not cell.source_token:f.append('missing source token')
    if not finite(cell.frequency_hz,True) or not subset(cell.frequency_hz,inv['tuning_frequency_hz']):f.append('frequency outside invariant')
    if not finite(cell.sigma_target_raw_mps2,True) or not subset(cell.sigma_target_raw_mps2,inv['sigma_target_raw_mps2']):f.append('sigma_target_raw outside invariant')
    # Derived coordinates are checked against the rigorously recomputed image of
    # those source invariants. They are not independent source coordinates.
    for x,o,name in ((cell.tau_target_s,tau_outer,'tau_target'),(cell.pseudo_period_s,ts_outer,'pseudo_period'),(cell.rs_target,rs_outer,'R_S_target')):
        if not finite(x,True) or not interval_subset(x,o):f.append(name+' outside dependent source image')
    for actual,recomputed,name in ((cell.tau_target_s,tau_from_frequency(cell.frequency_hz,c),'tau'),(cell.pseudo_period_s,pseudo_period_from_tau(cell.tau_target_s,c),'T_S'),(cell.rs_target,spectral_mse_rs(cell.tau_target_s,cell.sigma_target_raw_mps2,c),'R_S')):
        if not actual.contains_interval(recomputed):f.append(name+' detached from same-cell map')
    return list(dict.fromkeys(f))

def build(domain_path=DEFAULT_DOMAIN):
    dynamic=DYNAMIC.build(domain_path);df=DYNAMIC.validate(dynamic)
    if df:raise RuntimeError('dynamic source prerequisite failed: '+repr(df))
    rf=ROOTS.validate_self_test()
    if rf:raise RuntimeError('validated-root self test failed: '+repr(rf))
    inv=dynamic['dynamic_invariant']
    def mid(bounds):a,b=map(float,bounds);return I(.5*(a+b))
    smoke=make_target_cell('TARGET_CELL_SMOKE',None,mid(inv['tuning_frequency_hz']),mid(inv['sigma_target_raw_mps2']),dynamic)
    full=make_target_cell('TARGET_CELL_FULL',None,Interval(*map(float,inv['tuning_frequency_hz'])),Interval(*map(float,inv['sigma_target_raw_mps2'])),dynamic)
    c=constants();fclamp=clamped_frequency(full.frequency_hz,c);tau_outer,ts_outer,rs_outer=_dependent_outer_envelopes(dynamic,c)
    return {'schema':SCHEMA,'qualification':QUALIFICATION,'canonical_source':'COMPLETE_BRMM_NORMAL_LIVE_WORD','same_source_frequency_sigma_inputs_required':True,'shipping_frequency_clamp_reapplied_before_reciprocal':True,'proof_slack_outside_hard_frequency_clamp_removed_before_tau_image':True,'derived_coordinates_validated_against_outward_source_image':True,'tau_target_is_shipping_frequency_image':True,'pseudo_period_is_same_tau_image':True,'SpectralMSE_RS_is_same_tau_sigma_image':True,'validated_positive_roots_used':True,'independent_RS_target_forbidden':True,'independent_pseudo_period_forbidden':True,'quiet_sigma_target_admitted':float(inv['sigma_target_raw_mps2'][0])<.05,'full_dynamic_target_rectangle_image_valid':not validate_target_cell(full,dynamic),'point_smoke_valid':not validate_target_cell(smoke,dynamic),'full_frequency_enclosure_hz':full.frequency_hz.as_list(),'full_frequency_after_shipping_clamp_hz':fclamp.as_list(),'full_sigma_target_raw_mps2':full.sigma_target_raw_mps2.as_list(),'full_tau_target_s':full.tau_target_s.as_list(),'full_pseudo_period_s':full.pseudo_period_s.as_list(),'full_RS_target':full.rs_target.as_list(),'dependent_tau_outer':tau_outer.as_list(),'dependent_TS_outer':ts_outer.as_list(),'dependent_RS_outer':rs_outer.as_list(),'coarse_rectangle_is_nonpromoting_sanity_only':True,'physical_frontend_frequency_sigma_relation_materialized_here':False,'complete_BRMM_target_source_cover_closed_here':False,'P4_promoted_here':False}
def validate(d):
    f=[]
    if d.get('schema')!=SCHEMA or d.get('qualification')!=QUALIFICATION:f.append('schema/qualification mismatch')
    for k in ('same_source_frequency_sigma_inputs_required','shipping_frequency_clamp_reapplied_before_reciprocal','proof_slack_outside_hard_frequency_clamp_removed_before_tau_image','derived_coordinates_validated_against_outward_source_image','tau_target_is_shipping_frequency_image','pseudo_period_is_same_tau_image','SpectralMSE_RS_is_same_tau_sigma_image','validated_positive_roots_used','independent_RS_target_forbidden','independent_pseudo_period_forbidden','quiet_sigma_target_admitted','full_dynamic_target_rectangle_image_valid','point_smoke_valid','coarse_rectangle_is_nonpromoting_sanity_only'):
        if d.get(k) is not True:f.append(k+' not true')
    for k in ('physical_frontend_frequency_sigma_relation_materialized_here','complete_BRMM_target_source_cover_closed_here','P4_promoted_here'):
        if d.get(k) is not False:f.append(k+' not false')
    return f
def main():
    p=argparse.ArgumentParser();p.add_argument('--domain',type=Path,default=DEFAULT_DOMAIN);p.add_argument('--output',type=Path,required=True);a=p.parse_args();d=build(a.domain);f=validate(d);d['validation_pass']=not f;d['validation_failures']=f;a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(d,indent=2,sort_keys=True)+'\n');print(json.dumps({'target_cell':d['full_dynamic_target_rectangle_image_valid'],'f_clamped':d['full_frequency_after_shipping_clamp_hz'],'rs':d['full_RS_target'],'quiet_sigma':d['quiet_sigma_target_admitted'],'failures':f},sort_keys=True));return int(bool(f))
if __name__=='__main__':raise SystemExit(main())