#!/usr/bin/env python3
"""Rigorous same-history IQC for BRMM acceleration moments J0/J1/J2.

The exact centered primitive transition uses, on one h-long physical segment,

    J0 = int a(s) ds,
    J1 = int (h-s) a(s) ds,
    J2 = int (h-s)^2 a(s)/2 ds.

Bounding these three vectors independently destroys the dependence created by
one acceleration history.  Normalize

    x0 = J0/h,
    x1 = J1/h^2,
    x2 = J2/h^3.

With r=s/h and basis b=(1, 1-r, (1-r)^2/2), x_i=<b_i,a> on [0,1].  Its exact
Gram matrix is

    G = [[1,1/2,1/6],[1/2,1/3,1/8],[1/6,1/8,1/20]],

and G^{-1}=[[9,-36,60],[-36,192,-360],[60,-360,720]].  Bessel/projection
energy gives, for the THREE spatial axes jointly,

    sum_axis x_axis^T G^{-1} x_axis <= int_0^1 ||a(r)||^2 dr <= A_max^2.

Thus this is a rigorous source-uniform outer IQC implied by the declared
pointwise vector acceleration cap.  It keeps J0/J1/J2 and all axes correlated;
no replay and no Cartesian moment box is used.  It is an outer relation, not a
claim that every point in the ellipsoid is generated by an L-infinity-bounded
BRMM history.
"""
from __future__ import annotations

import argparse
import json
from fractions import Fraction as F
from pathlib import Path

import ou3_brmm_contract as BRMM
import ou3_brmm_centered_primitive_transition as PRIM

SCHEMA = 1
QUALIFICATION = "OU3_BRMM_ACCELERATION_MOMENT_IQC_V1"

G = (
    (F(1), F(1,2), F(1,6)),
    (F(1,2), F(1,3), F(1,8)),
    (F(1,6), F(1,8), F(1,20)),
)
GINV = (
    (F(9), F(-36), F(60)),
    (F(-36), F(192), F(-360)),
    (F(60), F(-360), F(720)),
)


def _matmul(A, B):
    return tuple(tuple(sum(A[i][k]*B[k][j] for k in range(len(B)))
                       for j in range(len(B[0]))) for i in range(len(A)))


def _identity(n):
    return tuple(tuple(F(1 if i==j else 0) for j in range(n)) for i in range(n))


def quadratic(v, M):
    if len(v) != len(M):
        raise ValueError("dimension mismatch")
    return sum(v[i]*M[i][j]*v[j] for i in range(len(v)) for j in range(len(v)))


def joint_normalized_moment_energy(moment_axes):
    """Exact sum over x/y/z of [x0,x1,x2]^T G^-1 [x0,x1,x2]."""
    if len(moment_axes) != 3 or any(len(v) != 3 for v in moment_axes):
        raise ValueError("three axes of three normalized moments required")
    return sum(quadratic(tuple(F(x) for x in v), GINV) for v in moment_axes)


def build() -> dict:
    source = BRMM.build()
    primitive = PRIM.build()
    if BRMM.validate(source):
        raise RuntimeError("BRMM source prerequisite failed")
    if PRIM.validate(primitive):
        raise RuntimeError("primitive transition prerequisite failed")
    if _matmul(G, GINV) != _identity(3):
        raise RuntimeError("exact Gram inverse identity failed")
    A = F(str(source["hard_caps"]["acceleration_norm_mps2"]))

    # Show quantitatively why an independent interval box is not equivalent.
    # Constant +A realizes (+A,+A/2,+A/6) and lies on the IQC boundary.
    aligned = (A, A/F(2), A/F(6))
    # A detached sign corner obeys every scalar individual cap yet violates the
    # same-history IQC by a factor 193, hence cannot be retained as equivalent.
    detached = (A, -A/F(2), A/F(6))
    aligned_ratio = quadratic(aligned, GINV)/(A*A)
    detached_ratio = quadratic(detached, GINV)/(A*A)
    if aligned_ratio != 1 or detached_ratio != 193:
        raise RuntimeError("moment-IQC diagnostic identities changed")

    # 10x10 augmented quadratic in q=[x0_xyz,x1_xyz,x2_xyz,1] is intentionally
    # not emitted in interleaved order because theorem consumers may choose a
    # better-conditioned coordinate permutation.  The exact 3x3 block and the
    # joint-axis sum are the canonical source object.
    return {
        "schema": SCHEMA,
        "qualification": QUALIFICATION,
        "canonical_source": "COMPLETE_BRMM_NORMAL_LIVE_WORD",
        "normalized_coordinates": {
            "x0": "J0/h",
            "x1": "J1/h^2",
            "x2": "J2/h^3",
            "axes_coupled_by_one_vector_acceleration_cap": True,
        },
        "gram": [[str(x) for x in row] for row in G],
        "gram_inverse": [[str(x) for x in row] for row in GINV],
        "gram_inverse_exact": True,
        "source_iqc": "sum_axis x_axis^T*Ginv*x_axis <= A_max^2",
        "derivation": "orthogonal projection/Bessel inequality in L2([0,1];R^3)",
        "pointwise_vector_cap_implies_L2_supply": True,
        "A_max_mps2": str(A),
        "J0_J1_J2_same_history_dependency_retained": True,
        "all_three_spatial_axes_jointly_coupled": True,
        "independent_moment_boxes_used": False,
        "independent_axis_boxes_used": False,
        "trajectory_replay_used": False,
        "iqc_is_outer_not_surjectivity_claim": True,
        "aligned_constant_acceleration_iqc_ratio": str(aligned_ratio),
        "detached_scalar_box_corner_iqc_ratio": str(detached_ratio),
        "detached_scalar_box_corner_excluded": detached_ratio > 1,
        "shipping_filter_changed": False,
        "P3_delta": 1e-18,
        "P4_PASS": False,
        "P5_MAY_START": False,
        "acceleration_moment_iqc_materialized": True,
        "next_obligation": (
            "lift this exact joint moment IQC through the centered primitive map and the same "
            "provider/frontend/Riccati event cell; use it as a signed source sector in the "
            "joint24 endpoint and literal-prefix augmented positivity certificates"
        ),
    }


def validate(d: dict) -> list[str]:
    f=[]
    if d.get("schema") != SCHEMA or d.get("qualification") != QUALIFICATION:
        f.append("schema/qualification mismatch")
    if d.get("gram") != [[str(x) for x in row] for row in G]:
        f.append("Gram changed")
    if d.get("gram_inverse") != [[str(x) for x in row] for row in GINV]:
        f.append("Gram inverse changed")
    for k in (
        "gram_inverse_exact",
        "pointwise_vector_cap_implies_L2_supply",
        "J0_J1_J2_same_history_dependency_retained",
        "all_three_spatial_axes_jointly_coupled",
        "iqc_is_outer_not_surjectivity_claim",
        "detached_scalar_box_corner_excluded",
        "acceleration_moment_iqc_materialized",
    ):
        if d.get(k) is not True:
            f.append(k+" not true")
    for k in (
        "independent_moment_boxes_used",
        "independent_axis_boxes_used",
        "trajectory_replay_used",
        "shipping_filter_changed",
        "P4_PASS",
        "P5_MAY_START",
    ):
        if d.get(k) is not False:
            f.append(k+" not false")
    if d.get("aligned_constant_acceleration_iqc_ratio") != "1":
        f.append("constant acceleration no longer saturates IQC")
    if d.get("detached_scalar_box_corner_iqc_ratio") != "193":
        f.append("detached box-corner ratio changed")
    if d.get("P3_delta") != 1e-18:
        f.append("P3 changed")
    return list(dict.fromkeys(f))


def main() -> int:
    ap=argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--output",required=True,type=Path)
    a=ap.parse_args(); d=build(); f=validate(d)
    d["validation_pass"]=not f; d["validation_failures"]=f
    a.output.parent.mkdir(parents=True,exist_ok=True)
    a.output.write_text(json.dumps(d,indent=2,sort_keys=True)+"\n")
    print(json.dumps({"iqc":d["acceleration_moment_iqc_materialized"],
                      "detached_corner_ratio":d["detached_scalar_box_corner_iqc_ratio"],
                      "P4":d["P4_PASS"],"failures":f},sort_keys=True))
    return int(bool(f))


if __name__=="__main__":
    raise SystemExit(main())
