#!/usr/bin/env python3
"""Estimator-owned BRMM event-prefix -> augmented every-prefix LDLT.

Each literal prefix retains estimator ancestry, source/binary32 maps, and every
physical acceleration-witness sector generated by transitions already contained
in the prefix.

Physical sea forcing is independently quantified from initial error. Production
moment sectors therefore use a homogeneous physical-source scale h_s=1, not the
SourceCoverCell hard-entry radial r_e. The historical single-transition
``source_radial_scale_map`` field remains only as a backward-compatible legacy
diagnostic interface; production cumulative MomentSectorBinding uses the
explicit ``physical_source_scale_map`` and rejects any declaration that it is
the hard-entry radial.
"""
from __future__ import annotations
from dataclasses import dataclass
import argparse,json,math
from pathlib import Path
from typing import Sequence
from ou3_interval import Interval
import ou3_p4_joint_brmm_frontend_transition as JOINT
import ou3_p4_complete_brmm_source_cover_contract as COVER
import ou3_p4_joint_iss_augmented_master as ISS
import ou3_p4_acceleration_moment_iqc_sector as MOMSECTOR
import ou3_brmm_acceleration_moment_iqc as MOM

SCHEMA=5
QUALIFICATION='OU3_P4_JOINT_BRMM_EVENT_PREFIX_AUGMENTED_LDLT_V5'

@dataclass(frozen=True)
class MomentSectorBinding:
    witness_id:str
    normalized_acceleration_moment_map:Sequence[Sequence[Interval]]
    physical_source_scale_map:Sequence[Sequence[Interval]]
    multiplier:float
    hard_entry_radial_used_as_source_scale:bool=False

@dataclass(frozen=True)
class PrefixInput:
    image:JOINT.Image
    source_cell:COVER.SourceCoverCell
    master:Sequence[Sequence[Interval]]
    sectors:Sequence[Sequence[Sequence[Interval]]]
    multipliers:Sequence[float]
    source_map:Sequence[Sequence[Interval]]|None=None
    gamma_s:float=0.0
    fp_map:Sequence[Sequence[Interval]]|None=None
    gamma_n:float=0.0
    moment_sector_bindings:Sequence[MomentSectorBinding]|None=None
    # Legacy one-transition interface. Historical name is retained only so old
    # diagnostics deserialize; production must use moment_sector_bindings.
    normalized_acceleration_moment_map:Sequence[Sequence[Interval]]|None=None
    source_radial_scale_map:Sequence[Sequence[Interval]]|None=None
    moment_multiplier:float|None=None

def _shape(A):
    r=len(A);c=len(A[0]) if r else 0
    if any(len(row)!=c for row in A):raise ValueError('ragged matrix')
    return r,c
def _same_interval(a,b):return isinstance(a,Interval) and isinstance(b,Interval) and a.lo==b.lo and a.hi==b.hi

def _bindings(c:PrefixInput,prefix:int):
    explicit=list(c.moment_sector_bindings or ())
    legacy=(c.normalized_acceleration_moment_map,c.source_radial_scale_map,c.moment_multiplier)
    supplied=tuple(x is not None for x in legacy)
    if explicit and any(supplied):raise ValueError(f'prefix {prefix}: cumulative and legacy moment bindings both supplied')
    if explicit:return explicit
    if any(supplied) and not all(supplied):raise ValueError(f'prefix {prefix}: legacy moment/source-scale/multiplier binding incomplete')
    if all(supplied):return [MomentSectorBinding(f'legacy-prefix-{prefix}',legacy[0],legacy[1],float(legacy[2]),False)]
    return []
def _moment_binding_failures(c:PrefixInput,n:int,prefix:int,*,production:bool=False)->list[str]:
    f=[]
    try:bs=_bindings(c,prefix)
    except ValueError as e:return [str(e)]
    seen=set()
    for j,b in enumerate(bs):
        if not isinstance(b.witness_id,str) or not b.witness_id:f.append(f'prefix {prefix}: moment binding {j} missing witness id')
        elif b.witness_id in seen:f.append(f'prefix {prefix}: duplicate moment witness {b.witness_id}')
        seen.add(b.witness_id)
        if _shape(b.normalized_acceleration_moment_map)!=(9,n):f.append(f'prefix {prefix}: moment binding {j} map must be 9x{n}')
        if _shape(b.physical_source_scale_map)!=(1,n):f.append(f'prefix {prefix}: moment binding {j} physical source scale map must be 1x{n}')
        if b.hard_entry_radial_used_as_source_scale is not False:f.append(f'prefix {prefix}: moment binding {j} illegally identifies physical source scale with hard-entry radial')
        try:
            x=float(b.multiplier)
            if not(x>=0.0 and x<math.inf):f.append(f'prefix {prefix}: moment binding {j} multiplier invalid')
        except Exception:f.append(f'prefix {prefix}: moment binding {j} multiplier invalid')
    if production and c.moment_sector_bindings is None:f.append(f'prefix {prefix}: production cannot use legacy source_radial_scale_map interface')
    return f
def moment_binding_count(c:PrefixInput)->int:return len(_bindings(c,-1))

def validate_sequence(cells,*,require_physical_moment_sector=False,require_cumulative_moment_ancestry=False):
    f=[]
    if not cells:return ['nonempty literal prefix sequence required']
    seen=set();previous_witnesses:set[str]=set()
    production=require_physical_moment_sector or require_cumulative_moment_ancestry
    for i,c in enumerate(cells):
        im=c.image;sc=c.source_cell;vf=COVER.validate_cell(sc,require_estimator_provenance=True)
        if vf:f.extend(f'prefix {i}: '+x for x in vf)
        if not sc.source_token or sc.source_token in seen:f.append(f'prefix {i}: duplicate/missing event token')
        seen.add(sc.source_token)
        if i>0 and sc.predecessor_token!=cells[i-1].source_cell.source_token:f.append(f'prefix {i}: not literal previous-event ancestry')
        if sc.estimator_source_token!=im.source_token:f.append(f'prefix {i}: event coefficients detached from estimator image')
        if sc.estimator_predecessor_token!=im.predecessor_token:f.append(f'prefix {i}: estimator predecessor detached')
        if im.state.source_token!=im.source_token:f.append(f'prefix {i}: estimator state/image token detached')
        for name,x in (('f',im.frequency_hz),('tau',im.tau_target),('sigma',im.sigma_target_raw),('TS',im.pseudo_period_target),('RS',im.rs_target)):
            if not isinstance(x,Interval) or x.lo<=0:f.append(f'prefix {i}: invalid joint {name}')
        active=im.active_schedule_for_current_riccati
        if active.tau.lo<=0 or active.sigma.lo<=0 or active.rs_base.lo<=0:f.append(f'prefix {i}: invalid current active schedule')
        if not _same_interval(sc.tau_applied_s,active.tau):f.append(f'prefix {i}: cell tau detached from current active schedule')
        if not _same_interval(sc.sigma_aw_mps2,active.sigma):f.append(f'prefix {i}: cell sigma detached from current active schedule')
        if any(r.lo<=0 for r in im.actual_rs_std_xyz_for_current_riccati):f.append(f'prefix {i}: invalid actual per-axis RS')
        n,m=_shape(c.master)
        if n==0 or n!=m:f.append(f'prefix {i}: master must be nonempty square')
        if not c.sectors or len(c.sectors)!=len(c.multipliers):f.append(f'prefix {i}: sectors/multipliers missing')
        if c.source_map is None:f.append(f'prefix {i}: source/bias map missing')
        if c.fp_map is None:f.append(f'prefix {i}: binary32 finite-precision map missing')
        f.extend(_moment_binding_failures(c,n,i,production=production))
        try:bs=_bindings(c,i)
        except ValueError:bs=[]
        if require_physical_moment_sector and not bs:f.append(f'prefix {i}: production same-history acceleration moment sectors missing')
        if require_cumulative_moment_ancestry:
            ids={b.witness_id for b in bs}
            if not previous_witnesses.issubset(ids):f.append(f'prefix {i}: cumulative moment ancestry dropped an earlier physical transition')
            previous_witnesses=ids
    return list(dict.fromkeys(f))

def _sectors_with_physical_moments(c:PrefixInput,prefix:int):
    sectors=list(c.sectors);multipliers=list(c.multipliers);Amax=float(MOM.build()['A_max_mps2'])
    for b in _bindings(c,prefix):
        sectors.append(MOMSECTOR.moment_sector(b.normalized_acceleration_moment_map,b.physical_source_scale_map,Amax));multipliers.append(float(b.multiplier))
    return sectors,multipliers

def certify(cells,*,require_physical_moment_sector=False,require_cumulative_moment_ancestry=False):
    f=validate_sequence(cells,require_physical_moment_sector=require_physical_moment_sector,require_cumulative_moment_ancestry=require_cumulative_moment_ancestry)
    if f:return {'closed':False,'validation_failures':f,'endpoint_closed':False,'every_prefix_closed':False,'prefixes':[]}
    rec=[]
    for i,c in enumerate(cells):
        sectors,multipliers=_sectors_with_physical_moments(c,i)
        ok,piv=ISS.certify_iss(c.master,sectors,multipliers,c.source_map,c.gamma_s,c.fp_map,c.gamma_n)
        rec.append({'prefix_length':i+1,'event_token':c.source_cell.source_token,'event_predecessor_token':c.source_cell.predecessor_token,'estimator_token':c.image.source_token,'physical_moment_sector_count':moment_binding_count(c),'ldlt_closed':bool(ok),'pivot_lowers':piv})
    every=all(x['ldlt_closed'] for x in rec);endpoint=bool(rec[-1]['ldlt_closed'])
    return {'closed':bool(every and endpoint),'validation_failures':[],'endpoint_closed':endpoint,'every_prefix_closed':every,'prefixes':rec}

def build():
    j=JOINT.build();jf=JOINT.validate(j);c=COVER.build();cf=COVER.validate(c);q=MOM.build();qf=MOM.validate(q);s=MOMSECTOR.build();sf=MOMSECTOR.validate(s)
    bad={k:v for k,v in (('joint',jf),('cover',cf),('moment_iqc',qf),('moment_sector',sf)) if v}
    if bad:raise RuntimeError('BRMM event-prefix prerequisite failed: '+repr(bad))
    return {'schema':SCHEMA,'qualification':QUALIFICATION,'canonical_source':'COMPLETE_BRMM_NORMAL_LIVE_WORD',
      'BRMM_attached_joint_image_required_at_every_prefix':True,'estimator_owned_source_cell_required_at_every_prefix':True,'literal_previous_prefix_ancestry_required':True,
      'multiple_events_may_share_one_estimator_image':True,'current_applied_schedule_retained_at_every_prefix':True,'raw_joint_f_tau_sigma_TS_RS_retained_at_every_prefix':True,
      'same_cell_augmented_master_sector_source_fp_maps_required':True,'same_history_acceleration_moment_joint_sector_consumable':True,
      'physical_source_scale_distinct_from_hard_entry_radial':True,'zero_initial_error_nonzero_physical_source_allowed':True,'production_legacy_radial_source_scale_interface_forbidden':True,
      'cumulative_prefix_retains_all_prior_physical_moment_sectors':True,'duplicate_physical_moment_witnesses_forbidden':True,'legacy_single_transition_moment_binding_supported_for_nonproduction_diagnostics':True,
      'independent_J0_J1_J2_or_axis_boxes_forbidden':True,'physical_moment_sector_required_for_production_prefix_certificate':True,'full_interval_ISS_LDLT_backend_reused':True,'endpoint_cannot_substitute_for_every_prefix':True,
      'source_map_required_for_production':True,'binary32_fp_map_required_for_production':True,
      'production_complete_source_lineages_supplied_here':False,'production_physical_moment_maps_bound_here':False,'production_endpoint_closed_here':False,'production_every_prefix_closed_here':False,
      'P4_MOTION_PASS':False,'P4_PASS':False,'P5_MAY_START':False,
      'next_obligation':'assemble each cumulative prefix with physical-source h_s=1 moment bindings, same-history source/bias and binary32 maps, then run certify(...,require_physical_moment_sector=True,require_cumulative_moment_ancestry=True)'}
def validate(d):
    f=[]
    if d.get('schema')!=SCHEMA or d.get('qualification')!=QUALIFICATION:f.append('schema/qualification mismatch')
    for k in ('BRMM_attached_joint_image_required_at_every_prefix','estimator_owned_source_cell_required_at_every_prefix','literal_previous_prefix_ancestry_required','multiple_events_may_share_one_estimator_image','current_applied_schedule_retained_at_every_prefix','raw_joint_f_tau_sigma_TS_RS_retained_at_every_prefix','same_cell_augmented_master_sector_source_fp_maps_required','same_history_acceleration_moment_joint_sector_consumable','physical_source_scale_distinct_from_hard_entry_radial','zero_initial_error_nonzero_physical_source_allowed','production_legacy_radial_source_scale_interface_forbidden','cumulative_prefix_retains_all_prior_physical_moment_sectors','duplicate_physical_moment_witnesses_forbidden','legacy_single_transition_moment_binding_supported_for_nonproduction_diagnostics','independent_J0_J1_J2_or_axis_boxes_forbidden','physical_moment_sector_required_for_production_prefix_certificate','full_interval_ISS_LDLT_backend_reused','endpoint_cannot_substitute_for_every_prefix','source_map_required_for_production','binary32_fp_map_required_for_production'):
        if d.get(k) is not True:f.append(k+' not true')
    for k in ('production_complete_source_lineages_supplied_here','production_physical_moment_maps_bound_here','production_endpoint_closed_here','production_every_prefix_closed_here','P4_MOTION_PASS','P4_PASS','P5_MAY_START'):
        if d.get(k) is not False:f.append(k+' not false')
    return f

def main():
    ap=argparse.ArgumentParser();ap.add_argument('--output',type=Path,required=True);a=ap.parse_args();d=build();f=validate(d);d['validation_pass']=not f;d['validation_failures']=f;a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(d,indent=2,sort_keys=True)+'\n');print(json.dumps({'event_prefix_bridge':d['estimator_owned_source_cell_required_at_every_prefix'],'source_scale_separate':d['physical_source_scale_distinct_from_hard_entry_radial'],'production_prefix':d['production_every_prefix_closed_here'],'P4':d['P4_PASS'],'failures':f},sort_keys=True));return int(bool(f))
if __name__=='__main__':raise SystemExit(main())
