#!/usr/bin/env python3
"""Compact source-uniform predecessor invariant for the COMPLETE-BRMM frontend.

This is a state-family induction, not a source generator. Scalar outer bounds
below prove compactness only; P4 coefficients must still be generated by the
same-history joint frontend transition. In particular f/sigma/tau/T_S/R_S are
never admitted as independent coordinates.

For each shipping high-pass stage
    y_n=d(y_{n-1}+x_n-x_{n-1}), 0<d<1,
the reset-to-n impulse response has l1 norm 2d. Thus bounded input gives
|y|<=2d||x||_inf without inventing an independent jump/jerk input. The leaky
integrator has exact induced gain q/(1-d)=1/lambda. EW moments are convex
recurrences. Tuner/stillness states are stable, clamped or saturated.

WavePeriodEstimator::elapsed_sec_ is intentionally not claimed bounded forever.
It is quotiented by shipping guard equivalence: before the one-way usable latch,
a finite representative dominates every possible valid-period age comparison;
after the latch, larger elapsed values do not change the coefficient-producing
state. This avoids a false indefinite-time compactness claim for a wall clock.
"""
from __future__ import annotations
import argparse,json,math
from pathlib import Path

import ou3_brmm_contract as BRMM
import ou3_brmm_finite_window_primitive_qualification as PRIM
import ou3_brmm_private_mahony_live_invariant as MAHONY
import ou3_brmm_private_mahony_discrete_invariant as MAHONY32
import ou3_fast_inv_sqrt_interval as FINV
import ou3_brmm_wpe_state_step as WPE
import ou3_brmm_tuner_scheduler_step as TUNER
import ou3_brmm_sigma_stillness_step as STILL
import ou3_startup_timeout_capture as CAPTURE
import ou3_validated_transcendentals as VT
from ou3_interval import Interval

REPO=Path(__file__).resolve().parents[2]
DOMAIN=REPO/'tools/stability/ou3_proof_operating_domain.json'
WPE_HEADER=REPO/'src/tuner/WavePeriodEstimator.h'
SCHEMA=2
QUALIFICATION='OU3_P4_COMPLETE_BRMM_FRONTEND_PREDECESSOR_INVARIANT_V2'

def I(x): return Interval.outward_bounds(float(x),float(x))
def up(x): return math.nextafter(float(x),math.inf)

def _decay(lam,dt):
    d=VT.exp_interval(-(lam*I(dt)))
    if not (0<d.lo<=d.hi<1): raise RuntimeError('WPE decay is not strictly Schur')
    return d

def _band_covariance_outer(c):
    pi=Interval.outward_bounds(3.141592653589793,3.141592653589794)
    al=(I(1)-VT.exp_interval(-(I(2)*pi*I(c.band_min_hz)*I(c.dt)))).lo
    high_min=1.05*c.band_min_hz
    ah=(I(1)-VT.exp_interval(-(I(2)*pi*I(high_min)*I(c.dt)))).lo
    if not (0<al<1 and 0<ah<1): raise RuntimeError('band filter lost Schur gap')
    ql=1-al; qh=1-ah
    p00=up(1/(1-ql*ql)); p01=up((p00+1)/(1-ql*qh)); p11=up((p00+2*qh*p01+1)/(1-qh*qh))
    return {'alpha_low_uniform_lower':al,'alpha_high_uniform_lower':ah,
            'p00_abs_upper':p00,'p01_abs_upper':p01,'p11_abs_upper':p11,
            'finite_covariance_outer':all(map(math.isfinite,(p00,p01,p11)))}

def build():
    domain=json.loads(DOMAIN.read_text())
    brmm=BRMM.build(); prim=PRIM.build(); mah=MAHONY.build(); m32=MAHONY32.build(); cap=CAPTURE.build()
    bad={'BRMM':BRMM.validate(brmm),'primitive':PRIM.validate(prim),'Mahony':MAHONY.validate(mah),
         'Mahony32':MAHONY32.validate(m32),'capture':CAPTURE.validate(cap)}
    bad={k:v for k,v in bad.items() if v}
    if bad: raise RuntimeError('predecessor invariant prerequisite failed: '+repr(bad))
    wc=WPE.constants(); tc=TUNER.constants(); sc=STILL.constants()

    g=float(domain['startup']['gravity_mps2'])
    am=float(prim['uniform_physical_primitives']['acceleration_norm_upper_mps2'])
    q2=FINV.all_positive_normal_normalized_norm2_enclosure()
    vertical=up(q2.hi*(g+am)+g)

    pi=Interval.outward_bounds(3.141592653589793,3.141592653589794)
    lam=I(2)*pi*I(wc.high_pass_hz); d=_decay(lam,wc.dt)
    hp_gain=up(2*d.hi); hp1=up(hp_gain*vertical); hp2=up(hp_gain*hp1)
    vel=up(hp2/lam.lo); elev=up(vel/lam.lo)

    # Startup/pre-usable states retain weight=0. Only the ratio branch has the
    # strict >1e-3 shipping guard.
    weight_interval=[0.0,1.0]; valid_weight_floor=math.nextafter(1e-3,math.inf)
    vel_sq=up(vel*vel); elev_sq=up(elev*elev)
    vvar_upper=up(vel_sq/valid_weight_floor)
    evar_floor=math.nextafter(1e-12,math.inf); omega2_floor=math.nextafter(1e-8,math.inf)
    omega2_upper=up(vvar_upper/evar_floor)
    raw_min=math.nextafter(2*math.pi/math.sqrt(omega2_upper),0.0)
    raw_max=up(2*math.pi/math.sqrt(omega2_floor))
    if not (0<raw_min<raw_max<math.inf): raise RuntimeError('raw-period compactness failed')
    log_min=math.nextafter(math.log(raw_min),-math.inf); log_max=math.nextafter(math.log(raw_max),math.inf)
    freq_min=math.nextafter(math.exp(-log_max),0.0); freq_max=up(math.exp(-log_min))

    text=WPE_HEADER.read_text()
    elapsed_parity=all(s in text for s in (
      'elapsed_sec_ += dt_sec;', 'if (elapsed_sec_ < moment_start_sec) return;',
      'elapsed_sec_ >= settled_floor_sec', 'const float moment_history_sec = elapsed_sec_ - moment_start_sec;',
      'if (elapsed_sec_ >= usable_floor_sec && moment_history_sec >= period)', 'if (usable_period_) return;'))
    elapsed_cap=up(3/lam.lo+raw_max)

    band=up(2*vertical); bcov=_band_covariance_outer(tc); still_energy=up((vertical/sc.gravity)**2)
    scheduler_max=up(tc.adapt_every_s+tc.dt)
    strict={
      'WPE_decay_strict':d.hi<1,'WPE_telescoping_gain_finite':hp_gain<2,
      'WPE_leaky_gain_finite':math.isfinite(1/lam.lo),'WPE_startup_zero_weight_retained':weight_interval[0]==0.0,
      'WPE_ratio_branch_has_positive_weight_floor':valid_weight_floor>1e-3,
      'WPE_valid_period_compact':0<raw_min<raw_max<math.inf,'WPE_frequency_compact':0<freq_min<=freq_max<math.inf,
      'WPE_elapsed_guard_quotient_parity':elapsed_parity,
      'adaptive_band_uniform_Schur_gap':bcov['alpha_low_uniform_lower']>0 and bcov['alpha_high_uniform_lower']>0,
      'adaptive_band_covariance_compact':bcov['finite_covariance_outer'],
      'candidate_active_clamps_compact':tc.tau_min>0 and tc.tau_max>=tc.tau_min and tc.sigma_max>0 and tc.rs_min>0 and tc.rs_max>=tc.rs_min,
      'scheduler_guard_class_compact':math.isfinite(scheduler_max),'stillness_timer_saturated':sc.still_max_s==60.0,
      'startup_handoff_closed':cap['QUALIFIED_LIVE_HANDOFF_BY_150S_CLOSED'],
      'Mahony_all_live_invariant_closed':mah['continuous_all_live_PI_invariant_closed'],
      'Mahony_source_order_binary32_closed':m32['shipping_binary32_discrete_invariant_closed_conditionally_on_source_order']}
    closed=all(strict.values())
    return {'schema':SCHEMA,'qualification':QUALIFICATION,'canonical_source':'COMPLETE_BRMM_NORMAL_LIVE_WORD',
      'source_generator':False,'trajectory_replay_used':False,'independent_sample_boxes_used_to_generate_coefficients':False,
      'same_history_BRMM_ancestry_required_downstream':True,'source_order_binary32_model_consumed':True,
      'vertical_acceleration_abs_upper_mps2':vertical,
      'WPE_invariant':{'decay':d.as_list(),'single_highpass_linf_gain_upper':hp_gain,'highpass1_abs_upper_mps2':hp1,
        'highpass2_abs_upper_mps2':hp2,'velocity_abs_upper_mps':vel,'elevation_abs_upper_m':elev,'weight_interval':weight_interval,
        'valid_ratio_weight_lower':valid_weight_floor,'velocity_mean_abs_upper':vel,'velocity_sq_upper':vel_sq,
        'elevation_mean_abs_upper':elev,'elevation_sq_upper':elev_sq,'valid_raw_period_s':[raw_min,raw_max],
        'canonical_log_period':[log_min,log_max],'canonical_frequency_hz':[freq_min,freq_max],
        'elapsed_guard_quotient_cap_s':elapsed_cap,'actual_elapsed_need_not_be_bounded':True,
        'elapsed_quotient_preserves_all_shipping_guards':elapsed_parity},
      'adaptive_band_invariant':{'lowpass_abs_upper_mps2':vertical,'band_abs_upper_mps2':band,**bcov},
      'tuner_invariant':{'mean_value_abs_upper':band,'sq_value_upper':up(band*band),'weights_interval':[0.0,1.0],
        'frequency_after_shipping_clamp_hz':[tc.tune_freq_min,tc.tune_freq_max],
        'candidate':{'tau_s':[tc.tau_min,tc.tau_max],'sigma_mps2':[0.0,tc.sigma_max],'rs':[tc.rs_min,tc.rs_max]},
        'active':{'tau_s':[tc.tau_min,tc.tau_max],'sigma_mps2':[0.0,tc.sigma_max],'rs':[tc.rs_min,tc.rs_max],
                  'pseudo_period_s':[tc.pseudo_min_s,tc.pseudo_max_s]},'scheduler_elapsed_guard_upper_s':scheduler_max},
      'stillness_invariant':{'lpf_abs_upper_mps2':vertical,'energy_ema_upper':still_energy,'still_time_s':[0.0,sc.still_max_s],'attenuation':[0.0,1.0]},
      'strict_invariance_checks':strict,'all_component_predecessor_invariants_closed':closed,
      'complete_BRMM_predecessor_family_compact_modulo_elapsed_guard_quotient':closed,'complete_BRMM_predecessor_state_family_covered':closed,
      'coefficient_history_still_must_come_from_joint_transition':True,'outer_bounds_may_not_generate_independent_f_sigma_tau_TS_RS':True,
      'P4_promoted_here':False,'next_obligation':'attach this induction to same-history joint transition and literal source cells; run endpoint/every-prefix augmented LDLT'}

def validate(d):
    f=[]
    if d.get('schema')!=SCHEMA or d.get('qualification')!=QUALIFICATION:f.append('schema/qualification mismatch')
    for k in ('same_history_BRMM_ancestry_required_downstream','source_order_binary32_model_consumed','all_component_predecessor_invariants_closed',
              'complete_BRMM_predecessor_family_compact_modulo_elapsed_guard_quotient','complete_BRMM_predecessor_state_family_covered',
              'coefficient_history_still_must_come_from_joint_transition','outer_bounds_may_not_generate_independent_f_sigma_tau_TS_RS'):
        if d.get(k) is not True:f.append(k+' not true')
    for k in ('source_generator','trajectory_replay_used','independent_sample_boxes_used_to_generate_coefficients','P4_promoted_here'):
        if d.get(k) is not False:f.append(k+' not false')
    if not all(d.get('strict_invariance_checks',{}).values()):f.append('strict invariant check failed')
    return f

def main():
    p=argparse.ArgumentParser();p.add_argument('--output',type=Path,required=True);a=p.parse_args();d=build();f=validate(d)
    d['validation_pass']=not f;d['validation_failures']=f;a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(d,indent=2,sort_keys=True)+'\n')
    print(json.dumps({'closed':d['complete_BRMM_predecessor_state_family_covered'],'vertical':d['vertical_acceleration_abs_upper_mps2'],
      'wpe_velocity':d['WPE_invariant']['velocity_abs_upper_mps'],'wpe_elevation':d['WPE_invariant']['elevation_abs_upper_m'],
      'period':d['WPE_invariant']['valid_raw_period_s'],'frequency':d['WPE_invariant']['canonical_frequency_hz'],'checks':d['strict_invariance_checks'],'failures':f},sort_keys=True))
    return int(bool(f))
if __name__=='__main__':raise SystemExit(main())
