#!/usr/bin/env python3
"""Shipping-reachable deterministic P4 entry fiber.

P4 has two distinct domains:

* ENTRANCE: states/errors the shipping startup/early-Live path can actually
  present at the instant P4 membership is claimed;
* WORKING/PREFIX: larger bounds that may be visited inside a certified P4 word.

The legacy proof conflated them and admitted independent position and
integral-displacement error balls (including ||e_S|| <= 300 m*s) at entrance.
That product factor is not generated by shipping startup.  Before goLive the
MEKF is held and its linear states remain at their constructor zeros.  In the
handoff-local translation gauge

    p_true^h(t_h)=0,  S_true^h(t_h)=0,

so p_hat=S_hat=0 gives e_p=e_S=0 at the handoff.  Velocity and latent
acceleration are different: e_v=v_true(t_h), e_aw=a_w,true(t_h), and must be
bounded by the same COMPLETE-BRMM history rather than set to zero.

The historical 20 m / 300 m*s values remain available only as conservative
working/prefix capacities until tighter source-correlated retention is proved.
Covariance is never used as true-error membership.
"""
from __future__ import annotations
import argparse, json, math
from pathlib import Path

import ou3_startup_p4_reachable_handoff as HANDOFF

REPO=Path(__file__).resolve().parents[2]
CLOSURE=REPO/'tools/stability/ou3_p4_closure_domain.json'


def build(path: Path=CLOSURE):
    c=json.loads(Path(path).read_text())['hard_entry_search']
    scale=float(c['minimum_certified_scale'])
    b={k:float(v) for k,v in c['base_coordinate_radii'].items()}
    if scale != 1.0 or list(map(float,c['candidate_scale_factors'])) != [1.0]:
        raise RuntimeError('P4 hard entry search may not silently fractionally shrink the declared non-translation coordinates')

    h=HANDOFF.build()
    hf=HANDOFF.validate(h)
    if hf:
        raise RuntimeError(f'shipping handoff fiber invalid: {hf}')

    # The old radii are retained as working/prefix capacities.  Entry is a
    # correlated fiber, not the Cartesian product of these coordinates.
    working={k:math.nextafter(v,math.inf) for k,v in b.items()}
    entry=dict(working)
    entry['position_norm_m']=0.0
    entry['integral_displacement_norm_m_s']=0.0

    return {
      'qualification':'OU3_P4_SHIPPING_REACHABLE_HARD_ENTRY_FIBER_V3',
      'source':'shipping startup/early-Live reachable handoff fiber on one COMPLETE-BRMM history',
      'trajectory_fit':False,
      'covariance_ellipsoid_used':False,
      'shipping_covariance_membership_used':False,
      'hard_state_error_membership_required':True,
      'entry_is_correlated_fiber_not_cartesian_box':True,
      # Kept for downstream gate compatibility.  It now means no fractional
      # shrink of the remaining declared coordinates; p/S are exact fiber
      # equalities, not shrunken legacy balls.
      'scale_of_declared_handoff_envelope':scale,
      'full_declared_scale_enforced':True,
      'coordinate_radii':entry,
      'working_prefix_coordinate_radii':working,
      'entry_exact_constraints':{
          'position_error_norm_m':0.0,
          'integral_displacement_error_norm_m_s':0.0,
          'velocity_error':'e_v=v_true(t_capture), source-correlated COMPLETE-BRMM coordinate',
          'latent_acceleration_error':'e_aw=a_w,true(t_capture)-a_w,hat(t_capture), same-history coordinate',
      },
      'legacy_independent_integral_displacement_entry_radius_m_s':b['integral_displacement_norm_m_s'],
      'legacy_independent_position_entry_radius_m':b['position_norm_m'],
      'legacy_independent_S_entry_ball_promotable':False,
      'legacy_independent_position_entry_ball_promotable':False,
      'working_prefix_may_be_larger_than_entry':True,
      'H18_groups':['attitude_cayley_norm','gyro_bias_norm_rad_s','velocity_norm_mps','position_norm_m','integral_displacement_norm_m_s','latent_acceleration_norm_mps2'],
      'A21_additional_group':'accelerometer_bias_error_norm_mps2',
      'non_translation_declared_scale_enforced':True,
      'entry_set_declared_and_membership_checkable':True,
      'startup_reachability_proved_here':False,
      'P4_may_use_as_regional_entry_hypothesis':True,
      'P4_may_promote_only_on_same_history_reachability':True,
      'proof_domain_shrunk':False,
    }


def validate(d):
    f=[]
    for k in ('hard_state_error_membership_required','entry_is_correlated_fiber_not_cartesian_box',
              'working_prefix_may_be_larger_than_entry','non_translation_declared_scale_enforced',
              'full_declared_scale_enforced','entry_set_declared_and_membership_checkable',
              'P4_may_use_as_regional_entry_hypothesis','P4_may_promote_only_on_same_history_reachability'):
        if d.get(k) is not True:f.append(k+' not true')
    for k in ('trajectory_fit','covariance_ellipsoid_used','shipping_covariance_membership_used',
              'startup_reachability_proved_here','proof_domain_shrunk',
              'legacy_independent_S_entry_ball_promotable','legacy_independent_position_entry_ball_promotable'):
        if d.get(k) is not False:f.append(k+' not false')
    if float(d.get('scale_of_declared_handoff_envelope',0)) != 1.0:f.append('remaining hard-entry scale is not full declared scale')
    r=d.get('coordinate_radii',{})
    if float(r.get('position_norm_m',-1)) != 0.0:f.append('entry position radius is not exact zero')
    if float(r.get('integral_displacement_norm_m_s',-1)) != 0.0:f.append('entry S radius is not exact zero')
    w=d.get('working_prefix_coordinate_radii',{})
    if not (float(w.get('position_norm_m',0)) > 0.0 and float(w.get('integral_displacement_norm_m_s',0)) >= 300.0):
        f.append('working/prefix translation capacity was lost')
    return f


def main():
    ap=argparse.ArgumentParser();ap.add_argument('--output',type=Path,required=True);a=ap.parse_args()
    d=build();f=validate(d);d['validation_pass']=not f;d['validation_failures']=f
    a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(d,indent=2,sort_keys=True)+'\n')
    print(json.dumps(d,sort_keys=True));return int(bool(f))
if __name__=='__main__':raise SystemExit(main())