"""Source-angle trig enclosure regressions; not deployment/stability evidence."""
from fractions import Fraction as F
import unittest

from tools.stability.ou3_alt_contraction import finite_attitude_runtime as ATT
from tools.stability.ou3_alt_contraction import finite_source_bound_attitude_trig as X


class Tests(unittest.TestCase):
    def test_global_enclosure_contains_close_rational_unit_circle_witnesses(self):
        # Rational unit-circle points generated by u=tan(theta/2) rational
        # approximants. They are exact unit-circle witnesses and lie inside the
        # rigorous global Taylor/Lagrange boxes at theta=1 and theta=1/2.
        full=ATT.TrigWitness(F(1),F(791207820,940267501),F(508028699,940267501),F(1))
        half=ATT.TrigWitness(F(1,2),F(349510960,729020321),F(639775521,729020321),F(1))
        r=ATT.AngularRuntime((1,0,0),F(1),full,half)
        self.assertIs(X.validate(r),r)
        self.assertEqual(X.validate_witness(r.w,full),F(1))
        self.assertEqual(X.validate_witness(r.w,half),F(1,2))

    def test_detached_unit_circle_point_is_rejected(self):
        full=ATT.TrigWitness(F(1),F(0),F(1),F(1))
        half=ATT.TrigWitness(F(1,2),F(0),F(1),F(1))
        r=ATT.AngularRuntime((1,0,0),F(1),full,half)
        with self.assertRaisesRegex(ValueError,'sine witness detached'):
            X.validate(r)

    def test_angle_two_radians_no_longer_needs_local_retention_assumption(self):
        full=ATT.TrigWitness(F(1),F(8968856869,9863501869),F(-4104665100,9863501869),F(1,2))
        # theta=1 for the half call, using the same exact rational unit-circle
        # witness as above but inv_omega=1/2.
        half=ATT.TrigWitness(F(1,2),F(791207820,940267501),F(508028699,940267501),F(1,2))
        r=ATT.AngularRuntime((2,0,0),F(1),full,half)
        self.assertIs(X.validate(r),r)
        self.assertEqual(X.validate_witness(r.w,full),F(2))
        self.assertEqual(X.validate_witness(r.w,half),F(1))

    def test_global_enclosure_has_rigorous_small_width_at_large_concrete_angle(self):
        slo,shi,clo,chi=X.trig_enclosure(F(10))
        self.assertLessEqual(shi-slo,2*X.TRIG_TOL)
        self.assertLessEqual(chi-clo,2*X.TRIG_TOL)

    def test_small_rate_branch_consumes_no_trig_and_passes(self):
        r=ATT.AngularRuntime((0,0,0),F(1,200))
        self.assertIs(X.validate(r),r)

    def test_readiness_removes_local_guard_but_keeps_binary32_blocker(self):
        r=X.readiness()
        self.assertTrue(r['trig_full_half_angles_derived_from_same_angular_rate_and_step'])
        self.assertTrue(r['detached_unit_circle_points_rejected'])
        self.assertTrue(r['global_finite_rational_angle_enclosure_available'])
        self.assertFalse(r['one_radian_local_angle_guard_required'])
        self.assertTrue(r['one_radian_guard_retained_for_every_admitted_prefix'])
        self.assertFalse(r['binary32_sqrt_div_sin_cos_correspondence_closed'])
        self.assertFalse(r['ALT_LIVE_PASS'])


if __name__=='__main__': unittest.main()
