#!/usr/bin/env python3
"""Summarize the paired direction study, including availability and isolation."""
from pathlib import Path
import csv
import hashlib
import json
import math
import statistics

ROOT = Path(__file__).resolve().parents[1]
METRICS = ('dir_axis_abs_error_deg', 'dir_travel_rmse_deg',
           'dir_travel_correct_pct', 'dir_travel_wrong_pct',
           'dir_travel_unresolved_pct')


def main():
    out = ROOT / 'reports/results/direction_rao_ablation'
    with (out / 'direction_runs.csv').open() as f:
        rows = list(csv.DictReader(f))
    assert len(rows) == 96
    lookup = {(r['family'], r['rpm'], r['arm'], r['input']): r for r in rows}
    upstream = ('roll_rms_deg', 'pitch_rms_deg', 'yaw_rms_deg', 'disp_3d_rms_m')
    for r in rows:
        if r['arm'] == 'guard-only':
            other = lookup[(r['family'], r['rpm'], 'guard-and-rao', r['input'])]
            assert all(r[k] == other[k] for k in upstream), 'RAO affected upstream state'
            if r['rpm'] == '0':
                quiet = lookup[(r['family'], '0', 'unconditioned', r['input'])]
                assert all(r[k] == quiet[k] for k in (*upstream, *METRICS)), 'Quiet guard changed output'
    summary = []
    for family in ('OU-II', 'OU-III'):
        for rpm in ('0', '2400'):
            for arm in ('unconditioned', 'guard-only', 'guard-and-rao'):
                group = [r for r in rows if (r['family'], r['rpm'], r['arm']) == (family, rpm, arm)]
                summary.append(dict(family=family, rpm=rpm, arm=arm,
                    **{k: statistics.fmean(float(r[k]) for r in group) for k in METRICS}))
    with (out / 'direction_summary.csv').open('w', newline='') as f:
        w = csv.DictWriter(f, fieldnames=list(summary[0])); w.writeheader(); w.writerows(summary)
    md = '# Direction RAO and engine-guard ablation\n\n'
    md += 'Each row is an unweighted mean across eight full-record replays, scored over the final 900 seconds. Directed RMS uses samples where direction is resolved; unresolved fractions must be considered alongside it. A dash means at least one record has no finite angular score, so the eight-record mean is undefined; missing records are not silently excluded.\n\n'
    md += '| Family | RPM | Arm | Axis error ° | Directed RMS ° | Correct % | Wrong % | Unresolved % |\n|---|---:|---|---:|---:|---:|---:|---:|\n'
    tex = r'''% Generated by tools/direction_rao_report.py.
\begin{table*}[t]\centering\footnotesize
\caption{Direction conditioning ablation. Entries average eight stationary vessel records
(default draw, final 900 s). Angular errors are degrees; correct/wrong/unresolved
fractions are percentages. Directed RMS is conditional on a resolved estimate.
A dash denotes an undefined eight-record mean when a record has no finite angular score.}
\label{tab:direction-rao-ablation}
\begin{tabular}{@{}llrrrrrr@{}}\toprule
Family & Arm & RPM & Axis error & Directed RMS & Correct & Wrong & Unresolved \\
\midrule
'''
    for r in summary:
        values = [f'{r[k]:.2f}' if math.isfinite(r[k]) else '--' for k in METRICS]
        md += '| ' + ' | '.join([r['family'], r['rpm'], r['arm'], *values]) + ' |\n'
        tex += ' & '.join([r['family'].replace('-', '--'), r['arm'], r['rpm'], *values]) + r' \\' + '\n'
    tex += r'\bottomrule\end{tabular}\end{table*}' + '\n'
    conclusion = ('Quiet guard-on/off measurements are identical. RAO-on/off attitude and displacement measurements are identical in every matched pair. '
                  'The equalizer improves average angular accuracy, while quiet-water unresolved fractions increase. Engine vibration substantially reduces availability without the guard; correction cannot recover direction from absent or weak motion. '
                  'Quality and confidence thresholds are unchanged. The unconditioned arm disables both the guard and its covariance inflation, so that comparison measures their combined effect.\n')
    (out / 'direction_report.md').write_text(md + '\n' + conclusion)
    tex += conclusion.replace('%', r'\%').replace('RAO-on/off', 'RAO on/off').replace('guard-on/off', 'guard on/off')
    (out / 'direction_ablation.tex').write_text(tex)
    (ROOT / 'doc/kalman_ou_iii/w3d-direction-rao-generated.tex-part').write_text(tex)
    manifest_path = out / 'manifest.json'
    manifest = json.loads(manifest_path.read_text())
    manifest['report_producer_sha256'] = hashlib.sha256(Path(__file__).read_bytes()).hexdigest()
    manifest['files'].update({p.name: hashlib.sha256(p.read_bytes()).hexdigest() for p in out.iterdir() if p.suffix in ('.csv', '.md', '.tex')})
    manifest_path.write_text(json.dumps(manifest, indent=2) + '\n')


if __name__ == '__main__':
    main()
