#!/usr/bin/env python3
"""Validated algebraic backend for the canonical OU-III SEA3 P3 word.

This module is *not* a reduced P3 route. It implements exact full-matrix
bookkeeping for one already-enclosed source/event word. The word assembler must
supply the actual interval F, Q, H, R and covariance-floor events generated by
the complete Normal-Live source.

The direct joint recursion propagates

    P_k = Psi_k P_0 Psi_k^T + Omega_k.

Prediction:

    P-     = F P F^T + Q
    Psi-   = F Psi
    Omega- = F Omega F^T + Q

Joseph measurement correction:

    S  = H P- H^T + R
    K  = P- H^T S^-1
    A  = I - K H
    P+     = A P- A^T + K R K^T
    Psi+   = A Psi-
    Omega+ = A Omega- A^T + K R K^T.

For M_delta = Omega-delta P and 0<=delta<=1, every shipping event preserves an
already-established inequality M_delta>=0:

    prediction: M' = F M F^T + (1-delta) Q,
    Joseph:      M' = A M A^T + (1-delta) K R K^T,
    PSD floor:   M' = M + (1-delta) Delta.

This identity may shorten post-closure propagation but never permits omission
of events needed to establish the first closure.

The same complete word also admits an exact *prior-free batch factorization*.
Condition on all measurements processed so far while treating the word-start
error x0 as an unknown deterministic parameter. Carry

    D   accumulated information about x0,
    T   conditional map x0 -> current state,
    Qc  conditional covariance of process/measurement noise.

Start with D=0,T=I,Qc=0. For prediction,

    T <- F T,
    Qc <- F Qc F^T + Q.

For a Joseph measurement, with J=H T and S0=H Qc H^T+R,

    D  <- D + J^T S0^-1 J,
    K0  = Qc H^T S0^-1,
    T  <- (I-K0 H)T,
    Qc <- (I-K0 H)Qc(I-K0 H)^T + K0 R K0^T.

These are the innovation factorization of the *same* stacked linear-Gaussian
word; there is no zero-start concavity argument. At the endpoint, for every SPD
word-start covariance P0,

    Z = (P0^-1 + D)^-1,
    P_W     = T Z T^T + Qc,
    Psi_W   = T Z P0^-1,
    Omega_W = T Z D Z T^T + Qc.

Therefore

    Omega_W-delta P_W
      = T (Z D Z-delta Z) T^T + (1-delta)Qc.

Completing the square exactly gives

    Z D Z-delta Z >= -(delta^2/4) D^-1,

so the single full-matrix condition

    (1-delta) Qc - (delta^2/4) T D^-1 T^T >= 0

is sufficient for the canonical contraction **for every SPD P0**. This is not
a D_W/L_W product: D,T,Qc are produced jointly by the same event word and the
condition is one full matrix inequality. The complete-word assembler must still
include all source-required events. A covariance-floor increment can enter the
prior-free recursion exactly only when the supplied increment is independent
of P0; source floors whose magnitude depends on the actual Riccati covariance
must be enclosed by the assembler rather than silently treated as independent.

The theorem-level contraction test remains full-matrix interval LDL^T. No
one-step ratio, determinant/trace scalarization, scalar beta, blockwise minimum,
or source-history graph can promote through this backend.
"""
from __future__ import annotations

from dataclasses import dataclass
import math
from pathlib import Path
from typing import Sequence

from ou3_interval import (
    Interval,
    IntervalMatrix,
    matrix_add,
    matrix_identity,
    matrix_mul,
    matrix_point,
    matrix_sub,
    matrix_transpose,
    symmetric_positive_definite_ldlt,
)
from ou3_interval_linear_algebra import (
    matrix_inverse_gauss_jordan,
    matrix_symmetric_hull,
)

REPO = Path(__file__).resolve().parents[1]
MEKF = REPO / "src" / "kalman_ou_iii" / "Kalman3D_Wave_OU_III.h"
USEFUL_GATE = 1.0e-18


def _shape(A: Sequence[Sequence[Interval]]) -> tuple[int, int]:
    rows = len(A)
    cols = len(A[0]) if rows else 0
    if any(len(row) != cols for row in A):
        raise ValueError("ragged interval matrix")
    return rows, cols


def _zero(rows: int, cols: int) -> IntervalMatrix:
    z = Interval.point(0.0)
    return [[z for _ in range(cols)] for _ in range(rows)]


def _scale(A: Sequence[Sequence[Interval]], c: float) -> IntervalMatrix:
    ci = Interval.outward_bounds(float(c), float(c))
    return [[ci * A[i][j] for j in range(len(A[i]))] for i in range(len(A))]


def _contains_zero(A: Sequence[Sequence[Interval]]) -> bool:
    return all(x.lo <= 0.0 <= x.hi for row in A for x in row)


def _copy(A: Sequence[Sequence[Interval]]) -> IntervalMatrix:
    return [[x for x in row] for row in A]


def shipping_source_parity() -> dict[str, bool]:
    """Bind the algebraic event recursions to the retained shipping source."""
    text = MEKF.read_text(encoding="utf-8")
    return {
        "prediction_adds_attitude_process_Q": (
            "Pext.template block<NA,NA>(0,0).noalias() += Q_AA;" in text
        ),
        "prediction_adds_translation_process_Q": "T sum = Q_LL(i,j);" in text,
        "active_bias_exact_GM_process_present": (
            "const T qd_scale = -T(0.5) * tau_b * std::expm1(-T(2) * Ts / tau_b);" in text
            and "P_BB.noalias() += Q_bacc_ * qd_scale;" in text
        ),
        "pending_aw_floor_applied_before_S_due_check": (
            text.find("apply_pending_aw_covariance_inflation_();") >= 0
            and text.find(
                "applyIntegralZeroPseudoMeas();",
                text.find("apply_pending_aw_covariance_inflation_();"),
            ) > text.find("apply_pending_aw_covariance_inflation_();")
        ),
        "aw_floor_is_PSD_addition": (
            "Pext.template block<3,3>(OFF_AW, OFF_AW) += Delta;" in text
        ),
        "accelerometer_uses_full_Joseph_update": (
            "joseph_update3_(K, S_mat, PCt);" in text
        ),
        "S_zero_update_uses_full_Joseph_update": (
            text.count("joseph_update3_(K, S_mat, PCt);") >= 2
        ),
        "magnetometer_covariance_update_is_Joseph_form": (
            "Pext(i,j) += delta;" in text
            and "KSK_ij += Kia * S(a,b) * Kjb;" in text
        ),
    }


def contraction_preservation_identities() -> dict[str, str | bool]:
    return {
        "definition": "M_delta = Omega - delta P",
        "delta_domain": "0 <= delta <= 1",
        "prediction": "M_delta' = F M_delta F^T + (1-delta) Q",
        "Joseph": "M_delta' = A M_delta A^T + (1-delta) K R K^T",
        "PSD_floor": "M_delta' = M_delta + (1-delta) Delta",
        "positive_semidefinite_inputs_preserve_M_delta": True,
        "may_omit_events_needed_to_first_establish_delta": False,
        "is_exact_algebra_inside_joint_P_Psi_Omega_object": True,
    }


def prior_free_batch_identities() -> dict[str, str | bool]:
    return {
        "state": "(D,T,Qc)",
        "prediction": "T'=F T; Qc'=F Qc F^T+Q; D'=D",
        "measurement": (
            "J=H T; S0=H Qc H^T+R; D'=D+J^T S0^-1 J; "
            "K0=Qc H^T S0^-1; T'=(I-K0 H)T; "
            "Qc'=(I-K0 H)Qc(I-K0 H)^T+K0 R K0^T"
        ),
        "endpoint": (
            "Z=(P0^-1+D)^-1; P=T Z T^T+Qc; "
            "Psi=T Z P0^-1; Omega=T Z D Z T^T+Qc"
        ),
        "uniform_prior_completion": (
            "(1-delta)Qc-(delta^2/4)T D^-1 T^T >= 0"
        ),
        "zero_start_Riccati_concavity_used": False,
        "D_and_Qc_built_from_same_event_word": True,
        "works_for_every_SPD_P0_when_full_matrix_condition_passes": True,
        "P0_dependent_covariance_floor_may_be_treated_as_independent": False,
    }


@dataclass
class JointWordState:
    P0: IntervalMatrix
    P: IntervalMatrix
    Psi: IntervalMatrix
    Omega: IntervalMatrix
    events: int = 0
    predictions: int = 0
    measurements: int = 0
    floors: int = 0

    @property
    def dimension(self) -> int:
        return len(self.P)


@dataclass
class PriorFreeBatchState:
    D: IntervalMatrix
    T: IntervalMatrix
    Qc: IntervalMatrix
    events: int = 0
    predictions: int = 0
    measurements: int = 0
    floors: int = 0

    @property
    def dimension(self) -> int:
        return len(self.D)


def initialize(P0: Sequence[Sequence[Interval]]) -> JointWordState:
    n, m = _shape(P0)
    if n == 0 or n != m:
        raise ValueError("P0 must be nonempty square")
    P0s = matrix_symmetric_hull(_copy(P0))
    return JointWordState(
        P0=P0s,
        P=_copy(P0s),
        Psi=matrix_identity(n),
        Omega=_zero(n, n),
    )


def initialize_prior_free(dimension: int) -> PriorFreeBatchState:
    if not isinstance(dimension, int) or dimension <= 0:
        raise ValueError("positive batch dimension required")
    return PriorFreeBatchState(
        D=_zero(dimension, dimension),
        T=matrix_identity(dimension),
        Qc=_zero(dimension, dimension),
    )


def decomposition_residual(state: JointWordState) -> IntervalMatrix:
    rhs = matrix_add(
        matrix_mul(matrix_mul(state.Psi, state.P0), matrix_transpose(state.Psi)),
        state.Omega,
    )
    return matrix_sub(state.P, rhs)


def decomposition_identity_enclosed(state: JointWordState) -> bool:
    return _contains_zero(decomposition_residual(state))


def contraction_matrix(
    state: JointWordState,
    delta: float = USEFUL_GATE,
) -> IntervalMatrix:
    if not (math.isfinite(delta) and 0.0 <= delta <= 1.0):
        raise ValueError("delta must be finite in [0,1]")
    return matrix_symmetric_hull(matrix_sub(state.Omega, _scale(state.P, delta)))


def prediction_contraction_image(
    M_before: Sequence[Sequence[Interval]],
    F: Sequence[Sequence[Interval]],
    Q: Sequence[Sequence[Interval]],
    delta: float,
) -> IntervalMatrix:
    if not (math.isfinite(delta) and 0.0 <= delta <= 1.0):
        raise ValueError("delta must be finite in [0,1]")
    Ft = matrix_transpose(F)
    return matrix_symmetric_hull(
        matrix_add(
            matrix_mul(matrix_mul(F, M_before), Ft),
            _scale(Q, 1.0 - delta),
        )
    )


def joseph_contraction_image(
    M_before: Sequence[Sequence[Interval]],
    A: Sequence[Sequence[Interval]],
    K: Sequence[Sequence[Interval]],
    R: Sequence[Sequence[Interval]],
    delta: float,
) -> IntervalMatrix:
    if not (math.isfinite(delta) and 0.0 <= delta <= 1.0):
        raise ValueError("delta must be finite in [0,1]")
    At = matrix_transpose(A)
    KRKt = matrix_mul(matrix_mul(K, R), matrix_transpose(K))
    return matrix_symmetric_hull(
        matrix_add(
            matrix_mul(matrix_mul(A, M_before), At),
            _scale(KRKt, 1.0 - delta),
        )
    )


def floor_contraction_image(
    M_before: Sequence[Sequence[Interval]],
    Delta_full: Sequence[Sequence[Interval]],
    delta: float,
) -> IntervalMatrix:
    if not (math.isfinite(delta) and 0.0 <= delta <= 1.0):
        raise ValueError("delta must be finite in [0,1]")
    return matrix_symmetric_hull(
        matrix_add(M_before, _scale(Delta_full, 1.0 - delta))
    )


def contraction_identity_enclosed(
    actual: Sequence[Sequence[Interval]],
    expected: Sequence[Sequence[Interval]],
) -> bool:
    if _shape(actual) != _shape(expected):
        return False
    return _contains_zero(matrix_sub(actual, expected))


def predict(
    state: JointWordState,
    F: Sequence[Sequence[Interval]],
    Q: Sequence[Sequence[Interval]],
) -> None:
    n = state.dimension
    if _shape(F) != (n, n) or _shape(Q) != (n, n):
        raise ValueError("prediction F/Q dimension mismatch")
    Ft = matrix_transpose(F)
    state.P = matrix_symmetric_hull(
        matrix_add(matrix_mul(matrix_mul(F, state.P), Ft), Q)
    )
    state.Psi = matrix_mul(F, state.Psi)
    state.Omega = matrix_symmetric_hull(
        matrix_add(matrix_mul(matrix_mul(F, state.Omega), Ft), Q)
    )
    state.events += 1
    state.predictions += 1
    if not decomposition_identity_enclosed(state):
        raise RuntimeError("P/Psi/Omega identity lost after prediction")


def prior_free_predict(
    state: PriorFreeBatchState,
    F: Sequence[Sequence[Interval]],
    Q: Sequence[Sequence[Interval]],
) -> None:
    n = state.dimension
    if _shape(F) != (n, n) or _shape(Q) != (n, n):
        raise ValueError("prior-free prediction F/Q dimension mismatch")
    Ft = matrix_transpose(F)
    state.T = matrix_mul(F, state.T)
    state.Qc = matrix_symmetric_hull(
        matrix_add(matrix_mul(matrix_mul(F, state.Qc), Ft), Q)
    )
    state.events += 1
    state.predictions += 1


def joseph_measurement(
    state: JointWordState,
    H: Sequence[Sequence[Interval]],
    R: Sequence[Sequence[Interval]],
) -> dict:
    n = state.dimension
    rows, cols = _shape(H)
    if cols != n or rows == 0 or _shape(R) != (rows, rows):
        raise ValueError("measurement H/R dimension mismatch")

    Ht = matrix_transpose(H)
    PHt = matrix_mul(state.P, Ht)
    S = matrix_symmetric_hull(matrix_add(matrix_mul(H, PHt), R))
    Sinv = matrix_inverse_gauss_jordan(S)
    K = matrix_mul(PHt, Sinv)
    A = matrix_sub(matrix_identity(n), matrix_mul(K, H))
    At = matrix_transpose(A)
    KRKt = matrix_mul(matrix_mul(K, R), matrix_transpose(K))

    state.P = matrix_symmetric_hull(
        matrix_add(matrix_mul(matrix_mul(A, state.P), At), KRKt)
    )
    state.Psi = matrix_mul(A, state.Psi)
    state.Omega = matrix_symmetric_hull(
        matrix_add(matrix_mul(matrix_mul(A, state.Omega), At), KRKt)
    )
    state.events += 1
    state.measurements += 1
    if not decomposition_identity_enclosed(state):
        raise RuntimeError("P/Psi/Omega identity lost after Joseph measurement")
    return {"S": S, "K": K, "A": A}


def prior_free_measurement(
    state: PriorFreeBatchState,
    H: Sequence[Sequence[Interval]],
    R: Sequence[Sequence[Interval]],
) -> dict:
    n = state.dimension
    rows, cols = _shape(H)
    if cols != n or rows == 0 or _shape(R) != (rows, rows):
        raise ValueError("prior-free measurement H/R dimension mismatch")

    Ht = matrix_transpose(H)
    QcHt = matrix_mul(state.Qc, Ht)
    S0 = matrix_symmetric_hull(matrix_add(matrix_mul(H, QcHt), R))
    S0inv = matrix_inverse_gauss_jordan(S0)
    J = matrix_mul(H, state.T)
    state.D = matrix_symmetric_hull(
        matrix_add(
            state.D,
            matrix_mul(matrix_mul(matrix_transpose(J), S0inv), J),
        )
    )
    K0 = matrix_mul(QcHt, S0inv)
    A0 = matrix_sub(matrix_identity(n), matrix_mul(K0, H))
    A0t = matrix_transpose(A0)
    K0RK0t = matrix_mul(matrix_mul(K0, R), matrix_transpose(K0))
    state.T = matrix_mul(A0, state.T)
    state.Qc = matrix_symmetric_hull(
        matrix_add(matrix_mul(matrix_mul(A0, state.Qc), A0t), K0RK0t)
    )
    state.events += 1
    state.measurements += 1
    return {"S0": S0, "K0": K0, "A0": A0, "J": J}


def add_psd_floor(
    state: JointWordState,
    Delta_full: Sequence[Sequence[Interval]],
) -> None:
    n = state.dimension
    if _shape(Delta_full) != (n, n):
        raise ValueError("floor increment dimension mismatch")
    Dlt = matrix_symmetric_hull(Delta_full)
    state.P = matrix_symmetric_hull(matrix_add(state.P, Dlt))
    state.Omega = matrix_symmetric_hull(matrix_add(state.Omega, Dlt))
    state.events += 1
    state.floors += 1
    if not decomposition_identity_enclosed(state):
        raise RuntimeError("P/Psi/Omega identity lost after covariance-floor event")


def prior_free_add_prior_independent_psd_floor(
    state: PriorFreeBatchState,
    Delta_full: Sequence[Sequence[Interval]],
) -> None:
    """Add a floor only when its supplied Delta is independent of word-start P0."""
    n = state.dimension
    if _shape(Delta_full) != (n, n):
        raise ValueError("prior-free floor increment dimension mismatch")
    state.Qc = matrix_symmetric_hull(matrix_add(state.Qc, Delta_full))
    state.events += 1
    state.floors += 1


def reconstruct_joint_from_prior_free(
    state: PriorFreeBatchState,
    P0: Sequence[Sequence[Interval]],
) -> JointWordState:
    n = state.dimension
    if _shape(P0) != (n, n):
        raise ValueError("P0 dimension mismatch for prior-free reconstruction")
    P0s = matrix_symmetric_hull(_copy(P0))
    P0inv = matrix_inverse_gauss_jordan(P0s)
    Z = matrix_inverse_gauss_jordan(
        matrix_symmetric_hull(matrix_add(P0inv, state.D))
    )
    Tt = matrix_transpose(state.T)
    P = matrix_symmetric_hull(
        matrix_add(matrix_mul(matrix_mul(state.T, Z), Tt), state.Qc)
    )
    Psi = matrix_mul(matrix_mul(state.T, Z), P0inv)
    ZDZ = matrix_mul(matrix_mul(Z, state.D), Z)
    Omega = matrix_symmetric_hull(
        matrix_add(matrix_mul(matrix_mul(state.T, ZDZ), Tt), state.Qc)
    )
    out = JointWordState(
        P0=P0s,
        P=P,
        Psi=Psi,
        Omega=Omega,
        events=state.events,
        predictions=state.predictions,
        measurements=state.measurements,
        floors=state.floors,
    )
    if not decomposition_identity_enclosed(out):
        raise RuntimeError("prior-free reconstruction lost P/Psi/Omega identity")
    return out


def uniform_prior_completion_matrix(
    state: PriorFreeBatchState,
    delta: float = USEFUL_GATE,
) -> IntervalMatrix:
    if not (math.isfinite(delta) and 0.0 < delta <= 1.0):
        raise ValueError("uniform-prior delta must be finite in (0,1]")
    Dspd, _ = symmetric_positive_definite_ldlt(
        matrix_symmetric_hull(state.D)
    )
    if not Dspd:
        raise RuntimeError("prior-free accumulated information D is not SPD")
    Dinv = matrix_inverse_gauss_jordan(matrix_symmetric_hull(state.D))
    penalty = matrix_mul(
        matrix_mul(state.T, Dinv), matrix_transpose(state.T)
    )
    return matrix_symmetric_hull(
        matrix_sub(
            _scale(state.Qc, 1.0 - delta),
            _scale(penalty, 0.25 * delta * delta),
        )
    )


def certify_uniform_prior_contraction(
    state: PriorFreeBatchState,
    delta: float = USEFUL_GATE,
) -> dict:
    M = uniform_prior_completion_matrix(state, delta)
    passed, pivots = symmetric_positive_definite_ldlt(M)
    return {
        "dimension": state.dimension,
        "delta": float(delta),
        "condition": "(1-delta)Qc-(delta^2/4)T D^-1 T^T >= 0",
        "full_matrix_LDLT_closed": bool(passed),
        "ldlt_pivots": [x.as_list() for x in pivots],
        "events": state.events,
        "predictions": state.predictions,
        "measurements": state.measurements,
        "floors": state.floors,
        "works_for_every_SPD_P0": True,
        "D_and_Qc_built_from_same_event_word": True,
        "zero_start_Riccati_concavity_used": False,
        "pass": bool(passed),
    }


def certify_contraction(
    state: JointWordState,
    delta: float = USEFUL_GATE,
) -> dict:
    if not (math.isfinite(delta) and delta > 0.0):
        raise ValueError("theorem contraction delta must be finite positive")
    M = contraction_matrix(state, delta)
    passed, pivots = symmetric_positive_definite_ldlt(M)
    return {
        "dimension": state.dimension,
        "delta": float(delta),
        "Omega_minus_delta_P_ldlt_closed": bool(passed),
        "ldlt_pivots": [x.as_list() for x in pivots],
        "events": state.events,
        "predictions": state.predictions,
        "measurements": state.measurements,
        "floors": state.floors,
        "decomposition_identity_enclosed": decomposition_identity_enclosed(state),
        "pass": bool(passed and decomposition_identity_enclosed(state)),
    }


def _preservation_self_test() -> dict:
    """Check the three M_delta event identities on point matrices."""
    delta = 0.2
    state = initialize(matrix_point([[2.0, 0.1], [0.1, 3.0]]))

    F = matrix_point([[1.0, 0.1], [0.0, 1.0]])
    Q = matrix_point([[0.02, 0.0], [0.0, 0.01]])
    M0 = contraction_matrix(state, delta)
    expected_pred = prediction_contraction_image(M0, F, Q, delta)
    predict(state, F, Q)
    actual_pred = contraction_matrix(state, delta)
    pred_ok = contraction_identity_enclosed(actual_pred, expected_pred)

    H = matrix_point([[1.0, 0.0]])
    R = matrix_point([[0.5]])
    M1 = contraction_matrix(state, delta)
    info = joseph_measurement(state, H, R)
    expected_meas = joseph_contraction_image(
        M1, info["A"], info["K"], R, delta
    )
    actual_meas = contraction_matrix(state, delta)
    meas_ok = contraction_identity_enclosed(actual_meas, expected_meas)

    Dlt = matrix_point([[0.0, 0.0], [0.0, 0.03]])
    M2 = contraction_matrix(state, delta)
    expected_floor = floor_contraction_image(M2, Dlt, delta)
    add_psd_floor(state, Dlt)
    actual_floor = contraction_matrix(state, delta)
    floor_ok = contraction_identity_enclosed(actual_floor, expected_floor)

    return {
        "delta": delta,
        "prediction_identity_enclosed": pred_ok,
        "Joseph_identity_enclosed": meas_ok,
        "PSD_floor_identity_enclosed": floor_ok,
        "all_event_identities_enclosed": pred_ok and meas_ok and floor_ok,
        "preservation_identities": contraction_preservation_identities(),
        "kernel_identity_test_only_not_P3": True,
    }


def _prior_free_self_test() -> dict:
    """Compare prior-free factorization with direct sequential joint recursion."""
    P0 = matrix_point([[2.0, 0.1], [0.1, 3.0]])
    direct = initialize(P0)
    batch = initialize_prior_free(2)

    F = matrix_point([[1.0, 0.1], [0.0, 1.0]])
    Q = matrix_point([[0.2, 0.0], [0.0, 0.1]])
    predict(direct, F, Q)
    prior_free_predict(batch, F, Q)

    R1 = matrix_point([[0.5]])
    H1 = matrix_point([[1.0, 0.0]])
    joseph_measurement(direct, H1, R1)
    prior_free_measurement(batch, H1, R1)

    R2 = matrix_point([[0.7]])
    H2 = matrix_point([[0.0, 1.0]])
    joseph_measurement(direct, H2, R2)
    prior_free_measurement(batch, H2, R2)

    Dlt = matrix_point([[0.03, 0.0], [0.0, 0.02]])
    add_psd_floor(direct, Dlt)
    prior_free_add_prior_independent_psd_floor(batch, Dlt)

    reconstructed = reconstruct_joint_from_prior_free(batch, P0)
    P_ok = contraction_identity_enclosed(direct.P, reconstructed.P)
    Psi_ok = contraction_identity_enclosed(direct.Psi, reconstructed.Psi)
    Omega_ok = contraction_identity_enclosed(direct.Omega, reconstructed.Omega)
    uniform = certify_uniform_prior_contraction(batch, USEFUL_GATE)
    return {
        "direct_vs_batch_P_identity_enclosed": P_ok,
        "direct_vs_batch_Psi_identity_enclosed": Psi_ok,
        "direct_vs_batch_Omega_identity_enclosed": Omega_ok,
        "all_endpoint_identities_enclosed": P_ok and Psi_ok and Omega_ok,
        "uniform_prior_completion": uniform,
        "identities": prior_free_batch_identities(),
        "kernel_identity_test_only_not_P3": True,
    }


def _self_test() -> dict:
    """Arithmetic-kernel test only; this is not an OU-III theorem witness."""
    P0 = matrix_point([[2.0, 0.1], [0.1, 3.0]])
    state = initialize(P0)
    F = matrix_point([[1.0, 0.1], [0.0, 1.0]])
    Q = matrix_point([[0.02, 0.0], [0.0, 0.01]])
    predict(state, F, Q)
    H = matrix_point([[1.0, 0.0]])
    R = matrix_point([[0.5]])
    joseph_measurement(state, H, R)
    add_psd_floor(state, matrix_point([[0.0, 0.0], [0.0, 0.03]]))
    cert = certify_contraction(state, USEFUL_GATE)
    cert["shipping_source_parity"] = shipping_source_parity()
    cert["shipping_source_parity_pass"] = all(cert["shipping_source_parity"].values())
    cert["kernel_self_test_only_not_P3"] = True
    cert["contraction_preservation"] = _preservation_self_test()
    cert["prior_free_batch"] = _prior_free_self_test()
    return cert


def validate_backend() -> list[str]:
    f: list[str] = []
    parity = shipping_source_parity()
    for name, ok in parity.items():
        if not ok:
            f.append(f"shipping source parity failed: {name}")
    ids = contraction_preservation_identities()
    if ids.get("positive_semidefinite_inputs_preserve_M_delta") is not True:
        f.append("contraction preservation identity missing")
    if ids.get("may_omit_events_needed_to_first_establish_delta") is not False:
        f.append("preservation theorem was incorrectly turned into event omission")
    batch_ids = prior_free_batch_identities()
    if batch_ids.get("zero_start_Riccati_concavity_used") is not False:
        f.append("prior-free factorization reintroduced zero-start concavity")
    if batch_ids.get("D_and_Qc_built_from_same_event_word") is not True:
        f.append("prior-free factorization split D from Qc")
    if batch_ids.get("P0_dependent_covariance_floor_may_be_treated_as_independent") is not False:
        f.append("prior-free factorization hid P0-dependent floor semantics")
    try:
        test = _self_test()
    except Exception as exc:
        f.append(f"joint algebra self-test failed: {type(exc).__name__}: {exc}")
        return f
    if test.get("decomposition_identity_enclosed") is not True:
        f.append("joint algebra self-test lost covariance decomposition")
    if test.get("Omega_minus_delta_P_ldlt_closed") is not True:
        f.append("joint algebra self-test did not close positive test matrix")
    if test.get("kernel_self_test_only_not_P3") is not True:
        f.append("kernel self-test was misclassified")
    preserve = test.get("contraction_preservation", {})
    if preserve.get("all_event_identities_enclosed") is not True:
        f.append("M_delta preservation self-test failed")
    if preserve.get("kernel_identity_test_only_not_P3") is not True:
        f.append("M_delta identity test was misclassified")
    batch = test.get("prior_free_batch", {})
    if batch.get("all_endpoint_identities_enclosed") is not True:
        f.append("prior-free batch factorization does not reproduce direct joint endpoint")
    if batch.get("uniform_prior_completion", {}).get("pass") is not True:
        f.append("prior-free uniform-prior completion self-test did not close")
    if batch.get("kernel_identity_test_only_not_P3") is not True:
        f.append("prior-free batch test was misclassified")
    return list(dict.fromkeys(f))


if __name__ == "__main__":
    failures = validate_backend()
    print({
        "qualification": "OU3_SEA3_JOINT_P_PSI_OMEGA_ALGEBRA_BACKEND",
        "useful_gate": USEFUL_GATE,
        "contraction_preservation_identities": contraction_preservation_identities(),
        "prior_free_batch_identities": prior_free_batch_identities(),
        "failures": failures,
        "self_test": _self_test() if not failures else None,
        "P3_promoted": False,
    })
    raise SystemExit(0 if not failures else 2)