#!/usr/bin/env python3
"""Fail-closed contract for the deterministic complete-SEA3 shaping state.

SEA3 is already the compact theorem-domain sea family.  This module does not
re-open that compactness question.  It isolates the still-missing *executable*
SEA0 ingredient required to propagate the complete compact family over the
canonical 3 s word.

The manuscript gives the continuous directional JONSWAP/PM spectrum and now
makes the deterministic realization coordinate explicit as

    (x^s_{0:N_W}, w_{0:N_W-1}) in X^s_SEA3(lambda_{0:N_W}),

with X^s_SEA3 compact and phase-continuous.  SEA0 must provide either a
validated oscillator/shaping realization of that set or an equivalent hard
finite-window dynamic constraint.  A power spectrum is a statistical
second-order object; it does not by itself provide the missing executable
pathwise phase/driver enclosure.  The paper states that a probabilistic
random-sea statement is only a later corollary and that no pointwise hard bound
may be inferred merely from a Gaussian spectrum.

The repository's v1.1.3 simulation records are generated by a finite seeded
harmonic sampler.  That sampler is useful for falsification/diagnostics but is
not the continuum SEA3 theorem source, and a finite frequency/RAO catalog may
not promote this certificate.

This module therefore remains false until a code-owned validated construction
provides all of:
  * a machine-readable outward representation of the compact
    X^s_SEA3(lambda_{0:N_W}) set (or equivalent hard-window quadratic/dynamic
    constraint),
  * phase-continuous propagation for every admissible lambda transition,
  * a proof that the construction encloses the complete SEA3 deterministic
    theorem family rather than a replay/seed/grid subset,
  * a joint output map ready to feed the continuum response certificate.

It is intentionally impossible for an input JSON to self-assert closure.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
THEOREM = REPO / "doc" / "kalman_ou_iii" / "w3d-sea3-stability-theorem.tex-part"
COMPLETE_SOURCE = REPO / "tools" / "ou3_sea3_complete_source.py"
SCHEMA = 2
QUALIFICATION = "OU3_SEA3_HARD_SHAPING_STATE_CONTRACT_V2"

# Code-owned executable gates.  These are *not* statements about SEA3 set
# compactness; they describe whether the compact theorem family has been made
# executable for canonical SEA0.
HARD_COMPACT_PHASE_OR_DRIVER_SET_CLOSED = False
PHASE_CONTINUOUS_PROPAGATION_CLOSED = False
COMPLETE_SEA3_LEFT_INCLUSION_CLOSED = False
JOINT_SOURCE_OUTPUT_MAP_CLOSED = False

HARD_SHAPING_STATE_OR_EXCITATION_BOUND_CLOSED = all((
    HARD_COMPACT_PHASE_OR_DRIVER_SET_CLOSED,
    PHASE_CONTINUOUS_PROPAGATION_CLOSED,
    COMPLETE_SEA3_LEFT_INCLUSION_CLOSED,
    JOINT_SOURCE_OUTPUT_MAP_CLOSED,
))


def _normalized_text(text: str) -> str:
    return " ".join(text.split())


def build() -> dict:
    theorem = THEOREM.read_text(encoding="utf-8")
    theorem_flat = _normalized_text(theorem)
    complete = COMPLETE_SOURCE.read_text(encoding="utf-8")

    theorem_has_shaping_system = (
        "x^s_{k+1}&=A_s" in theorem
        and "u^s_k&=C_s" in theorem
        and "oscillator/shaping state or an equivalent hard finite-window" in theorem_flat
    )
    theorem_has_explicit_hard_realization_set = (
        "\\mathcal X^s_{\\rm SEA3}(\\lambda_{0:N_W})" in theorem
        and "eq:sea3-hard-realization-set" in theorem
        and "does not reopen SEA3 compactness" in theorem_flat
        and "machine-readable outward representation" in theorem_flat
    )
    theorem_separates_probabilistic_corollary = (
        "A probabilistic statement for random sea realizations is a later corollary" in theorem_flat
        and "no infinite-time pointwise bound is inferred merely from a Gaussian spectrum" in theorem_flat
    )
    theorem_rejects_finite_or_statistical_surrogates = (
        "neither a Gaussian confidence event" in theorem_flat
        and "spectral moments alone" in theorem_flat
        and "finite seeded harmonic" in theorem_flat
    )
    source_rejects_gaussian_generator = (
        '"used_to_generate_P3_source_words": False' in complete
        and '"used_to_prune_homogeneous_P3_family": False' in complete
    )

    executable = {
        "hard_compact_phase_or_driver_set_closed": HARD_COMPACT_PHASE_OR_DRIVER_SET_CLOSED,
        "phase_continuous_propagation_closed": PHASE_CONTINUOUS_PROPAGATION_CLOSED,
        "complete_SEA3_left_inclusion_closed": COMPLETE_SEA3_LEFT_INCLUSION_CLOSED,
        "joint_source_output_map_closed": JOINT_SOURCE_OUTPUT_MAP_CLOSED,
    }
    return {
        "schema": SCHEMA,
        "qualification": QUALIFICATION,
        "SEA3_parameter_domain_compact": True,
        "compactness_is_not_an_open_obligation": True,
        "theorem_has_deterministic_shaping_contract": theorem_has_shaping_system,
        "theorem_has_explicit_hard_realization_set": theorem_has_explicit_hard_realization_set,
        "theorem_rejects_statistical_or_seeded_surrogates": theorem_rejects_finite_or_statistical_surrogates,
        "theorem_separates_probabilistic_random_sea_corollary": theorem_separates_probabilistic_corollary,
        "complete_source_rejects_gaussian_word_generator": source_rejects_gaussian_generator,
        "hard_realization_set_symbol": "X^s_SEA3(lambda_{0:N_W})",
        "power_spectrum_alone_is_hard_pathwise_bound": False,
        "spectral_moments_alone_may_close_xs": False,
        "gaussian_good_event_may_close_xs": False,
        "replay_may_close_xs": False,
        "seeded_128_frequency_generator_may_close_xs": False,
        "finite_RAO_grid_may_close_xs": False,
        "arbitrary_bounded_input_box_may_close_xs": False,
        "allowed_closure_forms": [
            "validated_compact_oscillator_or_shaping_state_with_hard_driver_set",
            "validated_equivalent_hard_finite_window_dynamic_constraint",
        ],
        "executable_ingredients": executable,
        "hard_shaping_state_or_excitation_bound_closed": HARD_SHAPING_STATE_OR_EXCITATION_BOUND_CLOSED,
        "complete_SEA3_family_materialized_here": False,
        "P3_promoted": False,
        "next_obligation": (
            "construct a machine-readable outward representation of X^s_SEA3(lambda_{0:N_W}) for the complete compact SEA3 continuum, with phase-continuous propagation and a proved physical left inclusion; do not infer it from PSD moments or the finite seeded simulation generator"
        ),
    }


def validate(d: dict) -> list[str]:
    failures: list[str] = []
    if d.get("schema") != SCHEMA or d.get("qualification") != QUALIFICATION:
        failures.append("schema/qualification mismatch")
    for key in (
        "SEA3_parameter_domain_compact",
        "compactness_is_not_an_open_obligation",
        "theorem_has_deterministic_shaping_contract",
        "theorem_has_explicit_hard_realization_set",
        "theorem_rejects_statistical_or_seeded_surrogates",
        "theorem_separates_probabilistic_random_sea_corollary",
        "complete_source_rejects_gaussian_word_generator",
    ):
        if d.get(key) is not True:
            failures.append(f"{key} is not true")
    if d.get("hard_realization_set_symbol") != "X^s_SEA3(lambda_{0:N_W})":
        failures.append("hard realization set symbol drifted")
    for key in (
        "power_spectrum_alone_is_hard_pathwise_bound",
        "spectral_moments_alone_may_close_xs",
        "gaussian_good_event_may_close_xs",
        "replay_may_close_xs",
        "seeded_128_frequency_generator_may_close_xs",
        "finite_RAO_grid_may_close_xs",
        "arbitrary_bounded_input_box_may_close_xs",
        "hard_shaping_state_or_excitation_bound_closed",
        "complete_SEA3_family_materialized_here",
        "P3_promoted",
    ):
        if d.get(key) is not False:
            failures.append(f"{key} is not false")
    expected = {
        "hard_compact_phase_or_driver_set_closed": HARD_COMPACT_PHASE_OR_DRIVER_SET_CLOSED,
        "phase_continuous_propagation_closed": PHASE_CONTINUOUS_PROPAGATION_CLOSED,
        "complete_SEA3_left_inclusion_closed": COMPLETE_SEA3_LEFT_INCLUSION_CLOSED,
        "joint_source_output_map_closed": JOINT_SOURCE_OUTPUT_MAP_CLOSED,
    }
    if d.get("executable_ingredients") != expected:
        failures.append("hard shaping executable ingredient gates drifted")
    return list(dict.fromkeys(failures))


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--output", type=Path, required=True)
    args = ap.parse_args()
    d = build()
    failures = validate(d)
    d["validation_pass"] = not failures
    d["validation_failures"] = failures
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json.dumps(d, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(json.dumps({
        "SEA3_compact": d["SEA3_parameter_domain_compact"],
        "hard_realization_set": d["hard_realization_set_symbol"],
        "executable_ingredients": d["executable_ingredients"],
        "hard_shaping_closed": d["hard_shaping_state_or_excitation_bound_closed"],
        "next_obligation": d["next_obligation"],
        "failures": failures,
    }, indent=2, sort_keys=True))
    return 0 if not failures else 2


if __name__ == "__main__":
    raise SystemExit(main())
