#!/usr/bin/env python3
"""Source-complete stage/phase full-matrix translation P3 candidate.

This is the first numerical P3 consumer that uses the frozen
``OU3_P2_CORRELATED_STAGE_TRANSFER_V1`` interface over the complete source
history instead of the flat 800-node ancestor hull.

Three monotonicity/numerical reductions keep the finite-stage proof small without
discarding source semantics:

1. At every certified stage boundary, selected process covariance is at least
   the covariance generated by the immediately preceding complete V1 segment
   starting from zero. Earlier covariance is positive semidefinite and the
   prediction/measurement Riccati map is order preserving. For a fixed source
   realization, P_0=0 and P_1=F(P_0)>=P_0 imply P_{k+1}>=P_k. Therefore the
   zero-start 13-sample image lower-bounds every allowed 14..26-sample segment.
   Scanning all 800 source cells at the minimum gap is sufficient to obtain one
   common boundary lower ``rho_b I`` valid for the complete 13..26 gap alphabet.

2. The older history is needed only for the finite-memory covariance ceiling.
   ``ou3_p3_p2_v1_history_frontier`` enumerates the exact gap-labelled V1
   history family at the four monotone same-history sufficient statistics and
   Pareto-prunes only continuation-equivalent labels. Each label is converted
   to a covariance upper first; only then are those covariance results enveloped
   for one current source endpoint.

3. The canonical theorem only needs a certified lower large enough to survive
   the fixed 1/2 precision-block join and the unchanged 1e-18 useful gate. For
   each translation source/phase cell we therefore first test one conservative
   4e-18 lower with the same outward interval LDL^T predicate. If that strict
   test passes, no near-maximal eigenvalue search is needed for that cell. Cells
   that do not pass the gate-directed trial fall back to the existing rigorous
   determinant/trace seed plus geometric refinement. The auxiliary z-coordinate
   identity floor used only to start the frozen-clock branch uses the rigorous
   determinant/trace lower directly. No source cell, matrix inequality, gate,
   arithmetic trust boundary, or theorem conclusion is relaxed.

From a boundary lower ``rho_b I`` we propagate the full 4x4 interval covariance
through 0..25 samples of the current staged source node in the fixed physical
scaling z=[v/h,p/h^2,S/h^3,a_w]. This covers every finite-clock sample phase
because the certified next-stage gap is in 13..26 samples; phase 26 is the next
boundary whenever the floating clock continues to advance.

The P2 clock theorem also has a separate infinite-time branch: after binary64
clock stagnation the committed source tuple freezes and no further stage edge
occurs. That branch is covered explicitly rather than hidden in the finite
phase alphabet. The covariance immediately before the first stalled sample is
bounded below by the worst finite-stage phase floor. We propagate that floor
through the first 12 held samples. From held sample 13 onward, the last 13
constant-source samples alone give a fresh zero-start lower bound; earlier
covariance can again be discarded by Riccati order monotonicity. Thus the
absorbing hold is covered for arbitrary duration with a finite calculation.

The resulting comparison is already post-measurement for the translation block:
we condition on accepted accelerometer and S=0 packets at every sample, which is
stronger than every shipping branch. Magnetometer has no translation Jacobian
on the declared zero-lever-arm branch.

This file certifies only the translation part of canonical P3. It deliberately
does not set the canonical P3 flag; H/A attitude/bias blocks must still be joined
without changing the frozen 1e-18 gate.
"""
from __future__ import annotations

import argparse
import functools
import json
import math
from pathlib import Path

from ou3_interval import Interval, symmetric_positive_definite_ldlt
import ou3_p2_correlation_path_memory as CORR
import ou3_p3_correlated_translation_segment as SEG
import ou3_p3_frozen_full_matrix_translation as FROZEN
import ou3_p3_p2_v1_history_frontier as HIST
import ou3_source_reachable_matrix_p3 as BASE

REPO = Path(__file__).resolve().parents[1]
DEFAULT_DOMAIN = REPO / "tools" / "ou3_proof_operating_domain.json"
SCHEMA = 2
PHASES = tuple(range(26))
FROZEN_FRESH_HISTORY_SAMPLES = 13
FROZEN_TRANSIENT_SAMPLES = tuple(range(1, FROZEN_FRESH_HISTORY_SAMPLES))
LOG_MARGIN_REFINEMENT_STEPS = 20
# The full H/A precision join multiplies the weakest conditional block by 1/2.
# A certified translation lower near 4e-18 therefore leaves roughly a factor of
# two above the frozen 1e-18 canonical gate even after outward downward rounding.
GATE_DIRECTED_TRANSLATION_LOWER = math.nextafter(
    4.0 * float(BASE.MIN_USEFUL_DELTA), math.inf
)


def I(x: float) -> Interval:
    return Interval.outward_bounds(float(x), float(x))


def _identity_floor(rho: float):
    if not (math.isfinite(rho) and rho > 0.0):
        raise ValueError("strict positive boundary covariance floor required")
    return [
        [I(rho if i == j else 0.0) for j in range(4)]
        for i in range(4)
    ]


def _minus_identity(A, rho: float):
    return [
        [A[i][j] - I(rho if i == j else 0.0) for j in range(len(A))]
        for i in range(len(A))
    ]


def _det_trace_seed(A) -> float:
    """Strict common eigenvalue lower from one interval LDLT factorization.

    For every represented SPD matrix, det(A) is the product of its positive
    LDLT pivots and every eigenvalue is at most trace(A). Hence

        lambda_min >= det(A) / trace(A)^(n-1).

    The pivot product is rounded downward and the trace power upward. The seed
    is used only after the interval LDLT has certified the whole family SPD.
    """
    ok, pivots = symmetric_positive_definite_ldlt(A)
    if not ok or not pivots:
        return 0.0
    det_lo = 1.0
    for pivot in pivots:
        det_lo = BASE.down(det_lo * float(pivot.lo))
        if not det_lo > 0.0:
            return 0.0
    trace_hi = 0.0
    for i in range(len(A)):
        trace_hi = BASE.up(trace_hi + float(A[i][i].hi))
    if not (math.isfinite(trace_hi) and trace_hi > 0.0):
        return 0.0
    denom = 1.0
    for _ in range(len(A) - 1):
        denom = BASE.up(denom * trace_hi)
        if not math.isfinite(denom):
            return 0.0
    seed = BASE.down(det_lo / denom)
    return seed if math.isfinite(seed) and seed > 0.0 else 0.0


def _certified_identity_floor(A) -> float:
    """Validated near-maximal rho with A >= rho I, using log-scale refinement.

    The old linear bisection starts at zero. When rho is microscopic it spends
    almost all of its 48--52 LDLT calls merely finding the right exponent. A
    positive determinant/trace lower gives a rigorous nonzero starting scale.
    We first make that seed pass the same interval LDLT subtraction predicate,
    then refine geometrically between the passing lower and the diagonal upper.
    Returned values are therefore certified by exactly the same SPD predicate
    as before, with much less work and no floating eigensolver.
    """
    seed = _det_trace_seed(A)
    if not seed > 0.0:
        return 0.0

    lo = seed
    for _ in range(64):
        if symmetric_positive_definite_ldlt(_minus_identity(A, lo))[0]:
            break
        lo = BASE.down(0.5 * lo)
        if not lo > 0.0:
            return 0.0
    else:
        return 0.0

    hi = min(float(A[i][i].lo) for i in range(len(A)))
    if not (math.isfinite(hi) and hi > lo):
        return BASE.down(lo)

    for _ in range(LOG_MARGIN_REFINEMENT_STEPS):
        mid = math.sqrt(lo * hi)
        if not (math.isfinite(mid) and lo < mid < hi):
            break
        if symmetric_positive_definite_ldlt(_minus_identity(A, mid))[0]:
            lo = BASE.down(mid)
        else:
            hi = mid

    # Keep the returned lower tied directly to the subtraction certificate.
    while lo > 0.0 and not symmetric_positive_definite_ldlt(_minus_identity(A, lo))[0]:
        lo = math.nextafter(lo, 0.0)
    return BASE.down(lo) if lo > 0.0 else 0.0


def _physical_gate_matrix(Pz, h: float, upper: list[float], delta: float):
    # z=[v/h,p/h^2,S/h^3,a], so physical translation covariance is D Pz D'.
    d = [h, h * h, h * h * h, 1.0]
    A = [
        [I(d[i]) * Pz[i][j] * I(d[j]) for j in range(4)]
        for i in range(4)
    ]
    for i in range(4):
        A[i][i] = A[i][i] - I(delta) * I(float(upper[i]))
    return FROZEN._sym(A)


def _normalized_physical_matrix(Pz, h: float, upper: list[float]):
    """Congruence-normalize D Pz D' against diag(upper).

    A >= delta*diag(upper) is equivalent to
    U^-1/2 A U^-1/2 >= delta I. Outward intervals around sqrt(upper) preserve
    the complete family under this positive diagonal congruence.
    """
    d = [h, h * h, h * h * h, 1.0]
    scales = [I(d[i]) / I(math.sqrt(float(upper[i]))) for i in range(4)]
    return FROZEN._sym([
        [scales[i] * Pz[i][j] * scales[j] for j in range(4)]
        for i in range(4)
    ])


def _certified_delta(Pz, h: float, upper: list[float]) -> float:
    if len(upper) != 4 or any(not (math.isfinite(float(x)) and float(x) > 0.0) for x in upper):
        raise ValueError("positive finite translation covariance upper required")
    return _certified_identity_floor(_normalized_physical_matrix(Pz, h, upper))


def _certified_delta_for_gate(Pz, h: float, upper: list[float]) -> float:
    """Certify a join-safe translation lower with one SPD test when possible.

    Canonical P3 uses the translation result only through a fixed 1/2 precision
    join and the frozen 1e-18 gate. A near-maximal per-cell eigenvalue lower is
    therefore unnecessary when the same interval predicate already proves a
    conservative lower comfortably above 2e-18. The exact/refined route remains
    the fail-closed fallback for any cell that does not pass this trial.
    """
    if len(upper) != 4 or any(not (math.isfinite(float(x)) and float(x) > 0.0) for x in upper):
        raise ValueError("positive finite translation covariance upper required")
    A = _normalized_physical_matrix(Pz, h, upper)
    target = float(GATE_DIRECTED_TRANSLATION_LOWER)
    if symmetric_positive_definite_ldlt(_minus_identity(A, target))[0]:
        return BASE.down(target)
    return _certified_identity_floor(A)


@functools.lru_cache(maxsize=4)
def common_boundary_floor(domain_path: Path = DEFAULT_DOMAIN) -> dict:
    """Worst complete-segment floor over all sources and the full gap alphabet.

    For each concrete fixed-source realization, the strongest-measurement
    Riccati map F is order preserving and F(0)>=0. Therefore the zero-start
    sequence is Loewner nondecreasing and its 13-sample covariance lower-bounds
    every 14..26-sample endpoint. We evaluate every source node at the minimum
    legal gap; no longer-gap source word is removed from the theorem language.
    """
    path = Path(domain_path).resolve()
    rt = CORR.runtime(path)
    zero = FROZEN._mat_zero()
    gaps = tuple(map(int, rt["gaps"]))
    if gaps != tuple(range(13, 27)):
        raise RuntimeError("P2 V1 gap alphabet changed from 13..26")
    min_gap = min(gaps)
    worst = math.inf
    limiting = None
    checked = 0
    for s in range(len(rt["nodes"])):
        images = SEG.segment_images(zero, s, min_gap, rt, path)
        local = math.inf
        for row in images:
            rho = _certified_identity_floor(row["posterior"])
            if not rho > 0.0:
                raise RuntimeError(
                    f"minimum-gap selected covariance lost strict SPD at source {s}, gap {min_gap}"
                )
            local = min(local, rho)
        checked += 1
        if local < worst:
            worst = local
            limiting = {
                "source_node": s,
                "gap_samples": min_gap,
                "rho_z_identity_lower": local,
            }
    if not (math.isfinite(worst) and worst > 0.0 and limiting is not None):
        raise RuntimeError("failed to establish common one-segment boundary floor")
    return {
        "rho_z_identity_lower": BASE.down(worst),
        "limiting_segment": limiting,
        "gap_alphabet_samples": list(gaps),
        "minimum_gap_samples_evaluated": min_gap,
        "source_gap_kernels_checked": checked,
        "source_gap_kernels_covered": len(rt["nodes"]) * len(gaps),
        "longer_gap_kernels_eliminated_by_order_monotonicity": len(rt["nodes"]) * (len(gaps) - 1),
        "all_800_sources_checked": checked == 800,
        "all_13_26_gaps_covered_by_min_gap_monotonicity": True,
        "zero_start_covariance_nondecreasing_with_fixed_source_gap": True,
        "older_process_covariance_discarded": True,
        "Riccati_order_monotonicity_used": True,
        "validated_log_scale_eigenvalue_search_used": True,
    }


@functools.lru_cache(maxsize=1024)
def _phase_sequence_cached(source_node: int, rho_key: float,
                           domain_path: Path = DEFAULT_DOMAIN):
    """Propagate all finite-clock prefixes once for one source/x partition.

    The previous phase cache restarted from the same boundary for every phase,
    so one x subcell performed 1+...+25=325 one-step recursions. During a
    staged source segment both the source node and the x subcell are fixed, so
    the r-sample state is exactly the prefix of the (r+1)-sample state. Build
    the same recursion once through sample 25 and retain every prefix. No
    enclosure, source partition, measurement assumption, or theorem inequality
    changes here.
    """
    path = Path(domain_path).resolve()
    rt = CORR.runtime(path)
    t = int(source_node)
    h = float(rt["clock"]["dt_binary32_s"])
    P0 = _identity_floor(float(rho_key))
    node = rt["nodes"][t]
    xcells = SEG._node_x_subcells(node, h, SEG.X_SUBCELLS)
    phases = [(P0,)]
    states = [
        [[P0[i][j] for j in range(4)] for i in range(4)]
        for _ in xcells
    ]
    for _sample in range(1, max(PHASES) + 1):
        states = [
            SEG.one_step(states[j], node, x, h)
            for j, x in enumerate(xcells)
        ]
        phases.append(tuple(states))
    return tuple(phases)


def phase_row(source_node: int, phase_samples: int, fr: dict, boundary: dict,
              upper_row: dict | None = None) -> dict:
    t = int(source_node)
    r = int(phase_samples)
    if upper_row is None:
        upper_row = HIST.endpoint_phase_upper(t, 0 if r == 0 else 1, fr)
    upper = list(map(float, upper_row["Sigma_translation_diagonal_upper_envelope"]))
    rho = float(boundary["rho_z_identity_lower"])
    path = Path(fr["path"]).resolve()
    h = float(fr["rt"]["clock"]["dt_binary32_s"])
    images = _phase_sequence_cached(t, rho, path)[r]
    deltas = [_certified_delta_for_gate(P, h, upper) for P in images]
    # This auxiliary floor is used only to seed the frozen-clock branch. The
    # determinant/trace theorem is already a strict certified eigenvalue lower,
    # so refining it toward the maximal floor for all 20,800 cells is needless.
    phase_rhos = [_det_trace_seed(P) for P in images]
    delta = min(deltas) if deltas else 0.0
    phase_rho = min(phase_rhos) if phase_rhos else 0.0
    return {
        "source_node": t,
        "phase_samples_after_stage_boundary": r,
        "phase_time_s": BASE.down(r * h),
        "x_subcells": len(images),
        "same_history_covariance_labels": upper_row["phase_pareto_labels"],
        "Sigma_translation_diagonal_upper_envelope": upper,
        "translation_relative_Riccati_injection_margin_lower": delta,
        "phase_z_identity_floor_lower": phase_rho,
        "useful_gate": BASE.MIN_USEFUL_DELTA,
        "useful": delta >= BASE.MIN_USEFUL_DELTA,
        "same_history_upper_evaluated_before_endpoint_envelope": True,
    }


def _frozen_clock_branch(fr: dict, finite_rows: list[dict],
                         upper_cache: dict[int, dict[int, dict]]) -> dict:
    """Cover arbitrary post-stagnation source hold with a finite calculation."""
    rt = fr["rt"]
    clock = rt["clock"]
    if clock.get("floating_clock_stagnation_verified") is not True:
        raise RuntimeError("P2 clock stagnation theorem is not verified")
    if "freeze" not in str(clock.get("floating_clock_stagnation_semantics", "")).lower():
        raise RuntimeError("P2 clock stagnation semantics no longer freeze the source schedule")

    phase_floor = min(float(r["phase_z_identity_floor_lower"]) for r in finite_rows)
    if not (math.isfinite(phase_floor) and phase_floor > 0.0):
        return {
            "included": True,
            "numerically_evaluated": False,
            "clock_stagnation_verified": True,
            "freeze_start_z_identity_floor_lower": max(0.0, phase_floor),
            "transient_samples_checked": 0,
            "tail_source_nodes_checked": 0,
            "worst_margin_lower": 0.0,
            "useful_gate": BASE.MIN_USEFUL_DELTA,
            "established": False,
            "failure": "finite-stage interval covariance did not retain a strict common identity floor",
        }

    path = Path(fr["path"]).resolve()
    h = float(clock["dt_binary32_s"])
    P0 = _identity_floor(phase_floor)
    zero = FROZEN._mat_zero()
    worst = None
    transient_rows = 0
    tail_nodes = 0
    useful = True

    for t in fr["endpoint_nodes"]:
        t = int(t)
        node = rt["nodes"][t]
        upper_row = upper_cache[t][1]
        upper = list(map(float, upper_row["Sigma_translation_diagonal_upper_envelope"]))
        xcells = SEG._node_x_subcells(node, h, SEG.X_SUBCELLS)
        states = [
            [[P0[i][j] for j in range(4)] for i in range(4)]
            for _ in xcells
        ]
        # Before 13 held samples are available, retain only the universal
        # pre-stagnation identity floor and propagate the constant held source.
        for k in FROZEN_TRANSIENT_SAMPLES:
            for j, x in enumerate(xcells):
                states[j] = SEG.one_step(states[j], node, x, h)
            delta = min(_certified_delta_for_gate(P, h, upper) for P in states)
            transient_rows += 1
            row = {
                "kind": "frozen_clock_transient",
                "source_node": t,
                "held_samples": int(k),
                "translation_relative_Riccati_injection_margin_lower": delta,
            }
            useful = useful and delta >= BASE.MIN_USEFUL_DELTA
            if worst is None or delta < worst["translation_relative_Riccati_injection_margin_lower"]:
                worst = row

        # Once 13 held samples exist, discard everything before them. The
        # final covariance is at least the zero-start 13-sample constant-source
        # image. The same argument can be reapplied to the last 13 samples at
        # every later time, so this single row covers the infinite tail.
        tail_images = SEG.segment_images(
            zero, t, FROZEN_FRESH_HISTORY_SAMPLES, rt, path
        )
        tail_delta = min(
            _certified_delta_for_gate(row["posterior"], h, upper)
            for row in tail_images
        )
        tail_nodes += 1
        useful = useful and tail_delta >= BASE.MIN_USEFUL_DELTA
        row = {
            "kind": "frozen_clock_infinite_tail",
            "source_node": t,
            "held_samples_lower": FROZEN_FRESH_HISTORY_SAMPLES,
            "fresh_last_samples_used": FROZEN_FRESH_HISTORY_SAMPLES,
            "translation_relative_Riccati_injection_margin_lower": tail_delta,
        }
        if worst is None or tail_delta < worst["translation_relative_Riccati_injection_margin_lower"]:
            worst = row

    if worst is None:
        raise RuntimeError("frozen-clock branch emitted no source rows")
    return {
        "included": True,
        "numerically_evaluated": True,
        "clock_stagnation_verified": True,
        "stagnation_semantics": clock["floating_clock_stagnation_semantics"],
        "freeze_start_z_identity_floor_lower": phase_floor,
        "transient_held_sample_set": list(FROZEN_TRANSIENT_SAMPLES),
        "transient_samples_checked": transient_rows,
        "tail_fresh_history_samples": FROZEN_FRESH_HISTORY_SAMPLES,
        "tail_source_nodes_checked": tail_nodes,
        "tail_reapplied_to_last_13_samples_for_arbitrary_duration": True,
        "older_covariance_discarded_in_tail": True,
        "same_history_endpoint_upper_used": True,
        "worst": worst,
        "worst_margin_lower": float(worst["translation_relative_Riccati_injection_margin_lower"]),
        "useful_gate": BASE.MIN_USEFUL_DELTA,
        "established": bool(useful),
    }


def build(domain_path: Path = DEFAULT_DOMAIN) -> dict:
    path = Path(domain_path).resolve()
    domain = json.loads(path.read_text(encoding="utf-8"))
    if domain.get("trajectory_fit") is not False:
        raise RuntimeError("source-complete matrix P3 translation candidate must not be trajectory fitted")
    runtime = domain.get("configured_runtime", {})
    if runtime.get("imu_lever_arm_enabled") is not False:
        raise RuntimeError("translation P3 requires declared zero-lever-arm branch")
    if runtime.get("accelerometer_vibration_guard_proof_branch") != "dormant_transparent":
        raise RuntimeError("translation P3 requires dormant transparent vibration guard")
    if float(BASE.MIN_USEFUL_DELTA) != 1.0e-18:
        raise RuntimeError("canonical useful gate changed")

    fr = HIST.frontier_runtime(path)
    boundary = common_boundary_floor(path)
    rows = []
    worst = None
    pass_count = 0
    # Same-history covariance path maxima change when the current source has
    # appeared at least once, but not with the number of current-source samples.
    # Evaluate only boundary (r=0) and positive-phase (r>0) envelopes per node.
    upper_cache = {
        int(t): {
            0: HIST.endpoint_phase_upper(int(t), 0, fr),
            1: HIST.endpoint_phase_upper(int(t), 1, fr),
        }
        for t in fr["endpoint_nodes"]
    }
    for t in fr["endpoint_nodes"]:
        for r in PHASES:
            row = phase_row(int(t), int(r), fr, boundary, upper_cache[int(t)][0 if r == 0 else 1])
            rows.append(row)
            pass_count += int(row["useful"])
            if worst is None or row["translation_relative_Riccati_injection_margin_lower"] < worst["translation_relative_Riccati_injection_margin_lower"]:
                worst = row

    if worst is None:
        raise RuntimeError("source-complete translation P3 emitted no endpoint phases")
    finite_useful = pass_count == len(rows)
    frozen = _frozen_clock_branch(fr, rows, upper_cache)
    all_useful = finite_useful and frozen.get("established") is True
    combined_worst = min(
        float(worst["translation_relative_Riccati_injection_margin_lower"]),
        float(frozen.get("worst_margin_lower", 0.0)),
    )
    return {
        "schema": SCHEMA,
        "qualification": "OU3_P3_P2_V1_SOURCE_COMPLETE_STAGE_PHASE_TRANSLATION_MATRIX",
        "source_only": True,
        "trajectory_replay_used": False,
        "filter_changed": False,
        "declared_domain_changed": False,
        "zero_lever_arm_branch": True,
        "dormant_transparent_vibration_guard_branch": True,
        "P2_correlation_interface_consumed": True,
        "P2_correlation_interface_version": CORR.INTERFACE_VERSION,
        "full_word_history_sufficient_quotient_consumed": True,
        "flat_800_node_ancestor_hull_used": False,
        "independent_cartesian_tau_sigma_R_S_extrema_used": False,
        "process_covariance_measurement_bounds_same_source_history": True,
        "same_history_covariance_evaluated_before_uniform_endpoint_envelope": True,
        "full_4x4_translation_matrix_retained_inside_source_segments": True,
        "fixed_physical_scaling": "z=[v/h,p/h^2,S/h^3,a_w]",
        "sigma_dependent_metric_switching_used": False,
        "one_complete_segment_common_boundary_floor_used": True,
        "minimum_gap_monotonicity_reduction_used": True,
        "validated_log_scale_margin_search_used": True,
        "gate_directed_translation_margin_fast_path_used": True,
        "gate_directed_translation_margin_trial_lower": BASE.down(GATE_DIRECTED_TRANSLATION_LOWER),
        "phase_identity_floor_det_trace_seed_used": True,
        "older_process_covariance_discarded_at_each_boundary": True,
        "Riccati_order_monotonicity_used": True,
        "all_finite_clock_sample_phases_covered": True,
        "phase_samples": list(PHASES),
        "phase_26_is_next_stage_boundary_when_clock_advances": True,
        "finite_phase_prefixes_propagated_once_per_source_x_cell": True,
        "frozen_clock_absorbing_hold_branch_included": True,
        "frozen_clock_branch": frozen,
        "strongest_accelerometer_and_S_measurements_applied_every_sample": True,
        "magnetometer_translation_jacobian_zero_on_declared_branch": True,
        "useful_gate": BASE.MIN_USEFUL_DELTA,
        "boundary_floor": boundary,
        "full_word_frontier_digest_sha256": fr["frontier_digest_sha256"],
        "endpoint_phase_rows": rows,
        "endpoint_phase_count": len(rows),
        "endpoint_phase_useful_count": pass_count,
        "worst_finite_translation_endpoint_phase": worst,
        "worst_finite_translation_margin_lower": float(worst["translation_relative_Riccati_injection_margin_lower"]),
        "worst_translation_margin_lower": combined_worst,
        "P3_TRANSLATION_CERTIFICATE_ESTABLISHED": all_useful,
        "P3_CANONICAL_PROMOTED": False,
        "P4_PROMOTED": False,
        "next_obligation": (
            "join this source-complete post-measurement translation margin with the retained "
            "source-generated H/A attitude, gyro-bias and accelerometer-bias floors; canonical "
            "P3 remains frozen and may pass only when the worst full H/A margin is >=1e-18"
        ) if all_useful else (
            "retain the same P2 V1/full-matrix theorem interface and refine only the common "
            "boundary lower or endpoint covariance envelope; do not relax the 1e-18 gate"
        ),
        "failures": [],
    }


def validate(d: dict) -> list[str]:
    f = list(d.get("failures", []))
    if d.get("schema") != SCHEMA:
        f.append("schema mismatch")
    if d.get("qualification") != "OU3_P3_P2_V1_SOURCE_COMPLETE_STAGE_PHASE_TRANSLATION_MATRIX":
        f.append("wrong qualification")
    for key in (
        "source_only", "zero_lever_arm_branch", "dormant_transparent_vibration_guard_branch",
        "P2_correlation_interface_consumed", "full_word_history_sufficient_quotient_consumed",
        "process_covariance_measurement_bounds_same_source_history",
        "same_history_covariance_evaluated_before_uniform_endpoint_envelope",
        "full_4x4_translation_matrix_retained_inside_source_segments",
        "one_complete_segment_common_boundary_floor_used",
        "minimum_gap_monotonicity_reduction_used", "validated_log_scale_margin_search_used",
        "older_process_covariance_discarded_at_each_boundary", "Riccati_order_monotonicity_used",
        "all_finite_clock_sample_phases_covered",
        "phase_26_is_next_stage_boundary_when_clock_advances",
        "finite_phase_prefixes_propagated_once_per_source_x_cell",
        "frozen_clock_absorbing_hold_branch_included",
        "strongest_accelerometer_and_S_measurements_applied_every_sample",
        "magnetometer_translation_jacobian_zero_on_declared_branch",
    ):
        if d.get(key) is not True:
            f.append(f"{key} is not true")
    for key in (
        "trajectory_replay_used", "filter_changed", "declared_domain_changed",
        "flat_800_node_ancestor_hull_used", "independent_cartesian_tau_sigma_R_S_extrema_used",
        "sigma_dependent_metric_switching_used", "P3_CANONICAL_PROMOTED", "P4_PROMOTED",
    ):
        if d.get(key) is not False:
            f.append(f"{key} is not false")
    if d.get("P2_correlation_interface_version") != CORR.INTERFACE_VERSION:
        f.append("translation P3 lost frozen P2 V1 binding")
    if float(d.get("useful_gate", math.nan)) != 1.0e-18:
        f.append("translation P3 useful gate changed")
    if d.get("phase_samples") != list(range(26)):
        f.append("translation P3 does not cover exact 0..25 finite-clock source phases")
    if int(d.get("endpoint_phase_count", 0)) != 800 * 26:
        f.append("translation P3 does not cover all 800 x 26 endpoint/phase classes")
    b = d.get("boundary_floor", {})
    if b.get("all_800_sources_checked") is not True:
        f.append("common boundary floor did not scan all 800 source nodes")
    if b.get("gap_alphabet_samples") != list(range(13, 27)):
        f.append("common boundary floor lost the 13..26 gap alphabet")
    if int(b.get("minimum_gap_samples_evaluated", 0)) != 13:
        f.append("common boundary floor did not evaluate the minimum 13-sample gap")
    if b.get("all_13_26_gaps_covered_by_min_gap_monotonicity") is not True:
        f.append("longer stage gaps are not covered by Riccati monotonicity")
    if b.get("zero_start_covariance_nondecreasing_with_fixed_source_gap") is not True:
        f.append("zero-start fixed-source covariance monotonicity contract disappeared")
    if int(b.get("source_gap_kernels_covered", 0)) != 800 * 14:
        f.append("common boundary floor no longer covers all 800x14 source/gap kernels")
    if int(b.get("source_gap_kernels_checked", 0)) != 800:
        f.append("minimum-gap boundary evaluation no longer checks all 800 sources")
    if not float(b.get("rho_z_identity_lower", 0.0)) > 0.0:
        f.append("common boundary floor is not strict")
    frozen = d.get("frozen_clock_branch", {})
    if frozen.get("included") is not True or frozen.get("clock_stagnation_verified") is not True:
        f.append("frozen-clock source branch is not structurally included")
    if frozen.get("numerically_evaluated") is True:
        if int(frozen.get("transient_samples_checked", 0)) != 800 * len(FROZEN_TRANSIENT_SAMPLES):
            f.append("frozen-clock transient did not cover all source/sample classes")
        if int(frozen.get("tail_source_nodes_checked", 0)) != 800:
            f.append("frozen-clock infinite tail did not cover all 800 source nodes")
        if frozen.get("tail_reapplied_to_last_13_samples_for_arbitrary_duration") is not True:
            f.append("frozen-clock infinite tail is not closed by fresh last-13-sample argument")
        if frozen.get("older_covariance_discarded_in_tail") is not True:
            f.append("frozen-clock tail did not use Riccati monotonicity")
        if int(frozen.get("tail_fresh_history_samples", 0)) != FROZEN_FRESH_HISTORY_SAMPLES:
            f.append("frozen-clock fresh-history length changed")
    worst = float(d.get("worst_translation_margin_lower", math.nan))
    if not (math.isfinite(worst) and worst >= 0.0):
        f.append("invalid worst translation margin")
    established = bool(
        int(d.get("endpoint_phase_useful_count", -1)) == int(d.get("endpoint_phase_count", 0))
        and frozen.get("established") is True
        and worst >= BASE.MIN_USEFUL_DELTA
    )
    if d.get("P3_TRANSLATION_CERTIFICATE_ESTABLISHED") is not established:
        f.append("translation promotion flag does not match unchanged useful gate and complete source branches")
    return list(dict.fromkeys(f))


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--domain", type=Path, default=DEFAULT_DOMAIN)
    ap.add_argument("--output", type=Path, required=True)
    args = ap.parse_args()
    d = build(args.domain)
    vf = validate(d)
    d["validation_pass"] = not vf
    d["validation_failures"] = vf
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json.dumps(d, indent=2, sort_keys=True), encoding="utf-8")
    print(json.dumps({
        "boundary_floor": d["boundary_floor"],
        "endpoint_phase_count": d["endpoint_phase_count"],
        "endpoint_phase_useful_count": d["endpoint_phase_useful_count"],
        "worst_finite_translation_margin_lower": d["worst_finite_translation_margin_lower"],
        "worst_finite_translation_endpoint_phase": d["worst_finite_translation_endpoint_phase"],
        "frozen_clock_branch": d["frozen_clock_branch"],
        "worst_translation_margin_lower": d["worst_translation_margin_lower"],
        "translation_established": d["P3_TRANSLATION_CERTIFICATE_ESTABLISHED"],
        "validation_failures": vf,
    }, indent=2, sort_keys=True))
    return 0 if not vf else 2


if __name__ == "__main__":
    raise SystemExit(main())