#!/usr/bin/env python3
"""Complete SEA3 source family consumed by canonical OU-III P3.

This producer is the single source-side prerequisite for the literal 3 s H18/A21
Riccati word.  It composes the complete SEA3 theorem assumptions already present
in the repository instead of replacing them by tuner rectangles.

Primitive SEA3 coordinates
--------------------------
* up to three JONSWAP/PM directional partitions;
* H_r,T_p,r,gamma_r,directional density with exact H_s^2=sum H_r^2 coupling;
* per-partition DNV peak-steepness admissibility;
* continuum complex translational RAO h(f,theta) under the declared envelope;
* an admitted rotational response envelope satisfying the body-rate coupling;
* finite-horizon Gaussian good-event budget over the actual 3 s sample count;
* response-weighted WavePeriodEstimator/front-end state and all Normal-Live PE
  assumptions.

Derived filter coordinates
--------------------------
The following are *not* primitive independent perturbations:

    tau, sigma_aw, R_S, T_S, F_k, Q_k, S-update times.

They are generated by the shipping front end, target laws, EMAs, staged commit,
and scheduler from the same admitted SEA3 word.  In particular every due S=0
Joseph update must use the actual committed SpectralMSE R_S of that source word,
with the deployed per-axis factors [0.72,0.72,1].

The broad dynamic boxes remain safety invariants only.  They may check that a
derived source path stayed inside implementation limits, but may not generate a
canonical P3 word and may not be Cartesian-producted into F/Q/R/timing extrema.

This is still a conditional SEA3 theorem source: the global statement that every
physical deployment lies in the declared sea/response family is a separate left-
inclusion obligation.  Conditional P3 is nevertheless allowed to use *all* SEA3
conditions on every admitted word; failing to do so would prove the wrong,
strictly larger perturbation family.
"""
from __future__ import annotations

import argparse
import json
import math
from pathlib import Path

from ou3_interval import Interval, down, up
import ou3_validated_transcendentals as VT
import ou3_sea3_physical_admissibility as PHYSICAL
import ou3_sea3_p1_compatibility as P1COMPAT
import ou3_sea3_directional_response_family as RESPONSE
import ou3_sea3_wave_period_spectral_identity as PERIOD_ID
import ou3_sea3_spectral_moment_bridge as MOMENT
import ou3_sea3_wave_period_frontend as FRONTEND
import ou3_sea3_dynamic_source_certificate as DYNAMIC
import ou3_p3_pseudo_scheduler_progress_certificate as SCHED

REPO = Path(__file__).resolve().parents[1]
DEFAULT_DOMAIN = REPO / "tools" / "ou3_proof_operating_domain.json"
DEFAULT_RESPONSE_DOMAIN = REPO / "tools" / "ou3_sea3_directional_response_domain.json"
WRAPPER = REPO / "src" / "kalman_ou_iii" / "SeaStateFusionFilter_OU_III.h"
SCHEMA = 1
QUALIFICATION = "OU3_SEA3_COMPLETE_NORMAL_LIVE_SOURCE_V1"
DIM = 3
DEGREE_COEFF = 8100.0


def _exp_minus_integer(t: int) -> Interval:
    if not isinstance(t, int) or isinstance(t, bool) or t < 0:
        raise ValueError("tail exponent must be a nonnegative integer")
    base = VT.exp_point(-0.5)
    out = Interval.point(1.0)
    for _ in range(2 * t):
        out = out * base
    return out


def _select_tail_exponent(samples: int, budget: float) -> dict:
    if samples <= 0:
        raise ValueError("samples must be positive")
    blo = down(float(budget))
    for t in range(1, 257):
        e = _exp_minus_integer(t)
        prob = up(float(2 * DIM * samples) * e.hi)
        if prob <= blo:
            return {
                "integer_tail_exponent": t,
                "validated_exp_minus_t": e.as_list(),
                "failure_probability_upper": prob,
                "allocated_budget_lower": blo,
            }
    raise RuntimeError("finite-horizon SEA3 concentration exponent exceeded 256")


def _trace_threshold(cap: float, t: int) -> float:
    cap2 = down(float(cap) * float(cap))
    return down(cap2 / float(2 * DIM * t))


def _accel_covariance_upper(hs: float, gain: float, corner: float) -> float:
    # tr Cov[a] <= pi^4 Hs^2 G^2 fc^4, all factors outward enclosed.
    pi = Interval.outward_bounds(math.pi, math.pi)
    H = Interval.outward_bounds(hs, hs)
    G = Interval.outward_bounds(gain, gain)
    fc = Interval.outward_bounds(corner, corner)
    return (pi.square() * pi.square() * H.square() * G.square() * fc.square() * fc.square()).hi


def _body_rate_covariance_upper(hs: float, gain_rad_per_m: float, corner: float) -> float:
    H = Interval.outward_bounds(hs, hs)
    K = Interval.outward_bounds(gain_rad_per_m, gain_rad_per_m)
    fc = Interval.outward_bounds(corner, corner)
    return (Interval.point(DEGREE_COEFF) * H.square() * K.square() * fc.square()).hi


def _source_rs_parity() -> dict[str, bool]:
    text = WRAPPER.read_text(encoding="utf-8")
    return {
        "deployed_law_is_SpectralMSE": (
            "RSAdaptationLaw rs_law_ = RSAdaptationLaw::SpectralMSE;" in text
        ),
        "SpectralMSE_target_uses_realized_TS": (
            "const float TS = pseudo_update_period_for_(tau);" in text
            and "return rs_mse_coeff_ * rs_qeff_pow_" in text
            and "/ std::sqrt(TS);" in text
        ),
        "SpectralMSE_skips_extra_information_rate_scale": (
            "if (rs_law_ != RSAdaptationLaw::Cubic) return 1.0f;" in text
        ),
        "applied_RS_is_clamped_then_sent_to_filter": (
            "const float RSbase = std::min(std::max(tune_.RS_applied, min_R_S_), max_R_S_);" in text
            and "const float RSb = RSbase * pseudo_update_information_rate_scale_();" in text
            and "mekf_->set_RS_noise(Eigen::Vector3f(" in text
        ),
        "horizontal_RS_factors_are_0p72": (
            "float R_S_x_factor_ = 0.72f;" in text
            and "float R_S_y_factor_ = 0.72f;" in text
        ),
        "pseudo_period_is_committed_tau_function": (
            "const float requested = pseudo_update_tau_ratio_ * tau;" in text
            and "mekf_->set_pseudo_update_period_s(period);" in text
        ),
        "candidate_RS_has_own_EMA": "tune_.RS_applied    += alpha_RS" in text,
        "tau_sigma_share_common_EMA": (
            "tune_.tau_applied   += alpha" in text
            and "tune_.sigma_applied += alpha" in text
        ),
        "staged_commit_runs_before_current_innovation": (
            "void apply_pending_online_tune_()" in text
            and "apply_ou_tune_(false);" in text
            and "apply_RS_tune_();" in text
        ),
    }


def build(
    domain_path: Path = DEFAULT_DOMAIN,
    response_domain_path: Path = DEFAULT_RESPONSE_DOMAIN,
) -> dict:
    domain_path = Path(domain_path).resolve()
    response_domain_path = Path(response_domain_path).resolve()
    domain = json.loads(domain_path.read_text(encoding="utf-8"))
    if domain.get("trajectory_fit") is not False:
        raise RuntimeError("complete SEA3 source cannot be replay fitted")

    physical = PHYSICAL.build(domain_path)
    p1compat = P1COMPAT.build(domain_path, response_domain_path)
    response = RESPONSE.directional_response_enclosure(REPO, response_domain_path)
    period_id = PERIOD_ID.build()
    moment = MOMENT.build()
    frontend = FRONTEND.build(REPO)
    dynamic = DYNAMIC.build(domain_path)
    scheduler = SCHED.build(domain_path)

    prereq = {
        "physical": PHYSICAL.validate(physical),
        "p1_compatibility": P1COMPAT.validate(p1compat),
        "response": RESPONSE.validate(response),
        "period_identity": PERIOD_ID.validate(period_id),
        "spectral_moment": MOMENT.validate(moment),
        "frontend": FRONTEND.validate(frontend),
        "dynamic_source": DYNAMIC.validate(dynamic),
        "scheduler": SCHED.validate(scheduler),
    }
    bad = {k: v for k, v in prereq.items() if v}
    if bad:
        raise RuntimeError(f"complete SEA3 prerequisite failure: {bad}")

    dt = float(domain["configured_runtime"]["imu_dt_s"])
    dt_cpp = float(dynamic["validated_rate_and_jump_bounds"]["dt_s"])
    # 3 s theorem word, include the first sample at/after 3 s under source float dt.
    samples = int(math.ceil(3.0 / dt_cpp))
    if samples * dt_cpp < 3.0:
        samples += 1

    total_budget = float(domain["stochastic"]["finite_horizon_failure_probability_budget"])
    per_event_budget = down(total_budget / 2.0)
    acc_tail = _select_tail_exponent(samples, per_event_budget)
    rate_tail = _select_tail_exponent(samples, per_event_budget)
    live = domain["normal_live"]
    acc_cap = float(live["non_gravitational_cog_acceleration_norm_upper_mps2"])
    rate_cap = float(live["body_rate_norm_upper_deg_s"])
    acc_trace_threshold = _trace_threshold(acc_cap, acc_tail["integer_tail_exponent"])
    rate_trace_threshold = _trace_threshold(rate_cap, rate_tail["integer_tail_exponent"])
    combined_failure = up(
        float(acc_tail["failure_probability_upper"])
        + float(rate_tail["failure_probability_upper"])
    )

    rbox = response["rao_envelope_parameter_box"]
    G_range = list(map(float, rbox["peak_translation_gain"]))
    fc_range = list(map(float, rbox["rolloff_corner_hz"]))
    pmin = float(rbox["high_frequency_rolloff_power_min"])
    hs_upper = float(physical["repository_total_Hs_upper_m"])

    # The independent worst corner is retained only as a rejection diagnostic.
    cartesian_acc = _accel_covariance_upper(hs_upper, G_range[1], fc_range[1])
    cartesian_acc_pass = cartesian_acc <= acc_trace_threshold

    rs_parity = _source_rs_parity()
    rs_failures = [k for k, ok in rs_parity.items() if not ok]

    sea = moment["sea_family"]
    directional = json.loads(response_domain_path.read_text(encoding="utf-8"))[
        "directional_spectrum_contract"
    ]

    return {
        "schema": SCHEMA,
        "qualification": QUALIFICATION,
        "canonical_P3_source": "COMPLETE_SEA3_NORMAL_LIVE_WORD",
        "trajectory_replay_used": False,
        "filter_changed": False,
        "declared_filter_domain_shrunk": False,
        "theorem_conditional_on_admitted_complete_SEA3_word": True,
        "global_physical_left_inclusion_closed_here": False,
        "retired_P2_stack_consumed": False,
        "word_horizon_s": 3.0,
        "word_samples": samples,
        "runtime_dt_declared_s": dt,
        "runtime_dt_source_s": dt_cpp,
        "SEA3_surface_family": {
            "modes_max": int(sea["m_max"]),
            "partition_spectrum": sea["partition_frequency_shape"],
            "gamma_interval": sea["declared_gamma_interval"],
            "directional_density": directional["directional_density"],
            "mean_direction_rad": directional["mean_direction_rad"],
            "spreading_parameter": directional["spreading_parameter"],
            "partition_energy_coordinate": sea["partition_energy_coordinate"],
            "total_energy_coupling": sea["total_energy_coupling"],
            "partition_peak_steepness_constraint": physical["three_partition_contract"][
                "active_partition_constraint"
            ],
            "total_Hs_upper_m": hs_upper,
            "independent_H_T_extrema_forbidden": True,
            "independent_partition_height_maxima_forbidden": True,
        },
        "SEA3_translational_response_family": response,
        "SEA3_coupled_domain": {
            "independent_sea_x_RAO_cartesian_product_forbidden": bool(
                p1compat["coupled_SEA3_domain_required"]
            ),
            "acceleration_covariance_coupling": (
                "pi^4 * Hs^2 * G^2 * fc^4 <= acceleration_trace_threshold"
            ),
            "acceleration_trace_threshold_m2_s4": acc_trace_threshold,
            "RAO_rolloff_power_min": pmin,
            "rotational_response_coupling": (
                "8100 * Hs^2 * K_rot^2 * fc_rot^2 <= body_rate_trace_threshold, q_rot>=1"
            ),
            "body_rate_trace_threshold_deg2_s2": rate_trace_threshold,
            "rotational_RAO_parameters_are_part_of_complete_SEA3_word": True,
            "cartesian_worst_corner_acceleration_covariance_diagnostic": cartesian_acc,
            "cartesian_worst_corner_passes_coupling": cartesian_acc_pass,
            "cartesian_worst_corner_may_generate_P3_word": False,
            "only_tuples_satisfying_both_response_couplings_may_generate_P3_word": True,
        },
        "SEA3_finite_horizon_good_event": {
            "centered_Gaussian_response_hypothesis": True,
            "temporal_independence_required": False,
            "cross_axis_independence_required": False,
            "samples": samples,
            "total_failure_budget": total_budget,
            "acceleration_tail": acc_tail,
            "body_rate_tail": rate_tail,
            "combined_failure_probability_upper": combined_failure,
            "combined_within_budget": combined_failure <= down(total_budget),
            "conditional_homogeneous_P3_word_uses_good_event_not_noise_realization": True,
        },
        "SEA3_period_and_frontend": {
            "steady_response_weighted_period_identity": period_id[
                "continuous_time_steady_state_identity"
            ],
            "surface_multimodal_identity": moment["analytical_lemmas"][
                "multimodal_zero_crossing_identity"
            ],
            "surface_Tz_substituted_for_tuner_Tz": False,
            "exact_discrete_frontend_source_parity_pass": all(
                frontend["source_parity"].values()
            ),
            "finite_frontend_state_must_be_propagated_in_full_word": True,
            "front_end_state_may_be_frozen_to_replay_value": False,
        },
        "derived_adaptive_source": {
            "primitive_independent_tau_sigma_RS_TS": False,
            "same_SEA3_frontend_path_generates_tau_sigma_RS_targets": True,
            "same_candidate_snapshot_commits_tau_sigma_RS": True,
            "T_S_is_function_of_same_committed_tau": True,
            "Q_uses_same_committed_tau_sigma": True,
            "dynamic_rectangular_invariant_role": "SAFETY_CHECK_ONLY",
            "dynamic_rectangular_invariant_may_generate_P3_words": False,
            "dynamic_rectangular_target_jump_full_box_may_generate_P3_words": False,
            "safety_invariant": dynamic["dynamic_invariant"],
            "rate_and_commit_bounds": dynamic["validated_rate_and_jump_bounds"],
        },
        "R_S_regularizer": {
            "source_parity": rs_parity,
            "source_parity_failures": rs_failures,
            "deployed_law": "SpectralMSE",
            "actual_applied_R_S_required_at_every_due_S_update": True,
            "axis_std_factors": [0.72, 0.72, 1.0],
            "extra_information_rate_rescale": 1.0,
            "pseudo_scheduler_recurrence_certificate": bool(
                scheduler["scheduler_recurrence_certificate"]
            ),
            "certified_uniform_max_gap_s": scheduler["certified_uniform_max_gap_s"],
            "four_selected_S_updates_are_only_rank_witness": True,
            "all_due_S_updates_remain_in_full_word": True,
            "full_P_column_S_cross_covariance_action_required": True,
            "R_S_may_not_be_replaced_by_process_strictness": True,
        },
        "Normal_Live_nonsea_conditions": {
            "all_valid_accelerometer_updates_required": bool(
                live["accelerometer_update_required_each_valid_imu_sample_after_live_entry"]
            ),
            "accelerometer_rejection_in_scope": bool(
                live["accelerometer_rejection_in_normal_live_scope"]
            ),
            "magnetic_norm_uT": [
                float(live["magnetic_vector_norm_lower_uT"]),
                float(live["magnetic_vector_norm_upper_uT"]),
            ],
            "vector_sine_separation_lower": float(
                live["vector_sine_separation_lower"]
            ),
            "vector_PE_recurrence_window_s": float(
                live["vector_pe_recurrence_window_s"]
            ),
            "hard_attitude_rewrite_inside_word": bool(
                live["hard_attitude_rewrite_inside_word"]
            ),
        },
        "P3_source_family_ready": (
            not rs_failures
            and combined_failure <= down(total_budget)
            and bool(p1compat["coupled_SEA3_domain_required"])
            and all(frontend["source_parity"].values())
        ),
        "P3_promoted": False,
        "next_obligation": (
            "drive the literal 3 s H18/A21 assembler from a validated cover of this complete coupled SEA3 source; derive tuner/commit/scheduler/R_S from each SEA3 cell and never inject an independent tau/sigma/R_S/T_S box"
        ),
    }


def validate(d: dict) -> list[str]:
    f: list[str] = []
    if d.get("schema") != SCHEMA or d.get("qualification") != QUALIFICATION:
        f.append("schema/qualification mismatch")
    if d.get("canonical_P3_source") != "COMPLETE_SEA3_NORMAL_LIVE_WORD":
        f.append("canonical P3 source is not complete SEA3")
    for key in (
        "theorem_conditional_on_admitted_complete_SEA3_word",
        "P3_source_family_ready",
    ):
        if d.get(key) is not True:
            f.append(f"{key} is not true")
    for key in (
        "trajectory_replay_used", "filter_changed", "declared_filter_domain_shrunk",
        "global_physical_left_inclusion_closed_here", "retired_P2_stack_consumed",
        "P3_promoted",
    ):
        if d.get(key) is not False:
            f.append(f"{key} is not false")
    if int(d.get("word_samples", 0)) < 600:
        f.append("complete SEA3 word does not cover 3 s at 200 Hz")
    sea = d.get("SEA3_surface_family", {})
    if sea.get("modes_max") != 3 or sea.get("gamma_interval") != [1.0, 7.0]:
        f.append("SEA3 surface family changed")
    if sea.get("independent_H_T_extrema_forbidden") is not True:
        f.append("SEA3 H/T Cartesian product re-entered")
    coupled = d.get("SEA3_coupled_domain", {})
    for key in (
        "independent_sea_x_RAO_cartesian_product_forbidden",
        "rotational_RAO_parameters_are_part_of_complete_SEA3_word",
        "only_tuples_satisfying_both_response_couplings_may_generate_P3_word",
    ):
        if coupled.get(key) is not True:
            f.append(f"SEA3 coupled domain lost {key}")
    if coupled.get("cartesian_worst_corner_may_generate_P3_word") is not False:
        f.append("independent worst SEA3/RAO corner was allowed into P3")
    finite = d.get("SEA3_finite_horizon_good_event", {})
    if finite.get("combined_within_budget") is not True:
        f.append("SEA3 finite-horizon good-event budget does not close")
    if finite.get("temporal_independence_required") is not False:
        f.append("SEA3 concentration incorrectly assumed temporal independence")
    adapt = d.get("derived_adaptive_source", {})
    if adapt.get("primitive_independent_tau_sigma_RS_TS") is not False:
        f.append("tuner coordinates became primitive perturbations")
    if adapt.get("dynamic_rectangular_invariant_may_generate_P3_words") is not False:
        f.append("dynamic rectangle regained P3 source role")
    if adapt.get("dynamic_rectangular_target_jump_full_box_may_generate_P3_words") is not False:
        f.append("full-box target jumps regained P3 source role")
    rs = d.get("R_S_regularizer", {})
    if rs.get("source_parity_failures"):
        f.extend(f"R_S source parity failed: {x}" for x in rs["source_parity_failures"])
    for key in (
        "actual_applied_R_S_required_at_every_due_S_update",
        "pseudo_scheduler_recurrence_certificate",
        "four_selected_S_updates_are_only_rank_witness",
        "all_due_S_updates_remain_in_full_word",
        "full_P_column_S_cross_covariance_action_required",
        "R_S_may_not_be_replaced_by_process_strictness",
    ):
        if rs.get(key) is not True:
            f.append(f"R_S regularizer lost {key}")
    if rs.get("axis_std_factors") != [0.72, 0.72, 1.0]:
        f.append("R_S axis factors changed")
    if float(rs.get("extra_information_rate_rescale", math.nan)) != 1.0:
        f.append("SpectralMSE R_S incorrectly received cadence rescale")
    return list(dict.fromkeys(f))


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--domain", type=Path, default=DEFAULT_DOMAIN)
    ap.add_argument("--response-domain", type=Path, default=DEFAULT_RESPONSE_DOMAIN)
    ap.add_argument("--output", type=Path, required=True)
    args = ap.parse_args()
    d = build(args.domain, args.response_domain)
    failures = validate(d)
    d["validation_pass"] = not failures
    d["validation_failures"] = failures
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json.dumps(d, indent=2, sort_keys=True), encoding="utf-8")
    print(json.dumps({
        "source": d["canonical_P3_source"],
        "samples": d["word_samples"],
        "coupled_SEA3": d["SEA3_coupled_domain"],
        "finite_horizon": d["SEA3_finite_horizon_good_event"],
        "R_S": d["R_S_regularizer"],
        "P3_source_family_ready": d["P3_source_family_ready"],
        "failures": failures,
    }, indent=2, sort_keys=True))
    return 0 if not failures else 2


if __name__ == "__main__":
    raise SystemExit(main())
