#!/usr/bin/env python3
"""V21: source-correlated effective-input correction audit at the first q8 witness.

V20 proves that a first-residual-row direction audit is useful for many source
rows, but the actual first V18B/V19 q8 witness (p=0,tangent=0,axial=19) admits
all startup Cayley direction boxes.  The missing dependency is later: V13E
constructs the sample-1 correction from a norm-only residual ball, while the
current Cayley state and that correction are generated by the same
accelerometer residual.

In V7's un-Rx proof gauge the nominal sample-1 force is f=[0,f_y,f_z] and the
shipping attitude Jacobian is H_theta=-[f]_x.  For current Cayley vector c,

    H_theta c = [ f_z c_y-f_y c_z, -f_z c_x, f_y c_x ].

The exact effective-vector-input lemma already certified in P5 rewrites the
finite-angle accelerometer defect into the a_w coordinate.  Thus the nominal
sample-1 residual can be enclosed as

    r = H_theta c + n,

where n contains the physical a_w error, accelerometer-bias error, exact
finite-angle attitude defect, and rotated latent-error cross term.  V7's exact
one-plus-two attitude gain then gives a source-correlated correction box:

    d_x  = K_xy r_y + K_xz r_z,
    d_yz = [g_y,g_z] r_x.

V21 builds this box from the V18B current component chart and intersects it with
the historical V13E signed correction subcell at the first q8 witness.  The
existing V12D PSD/S residual and gain perturbations are retained unchanged as
an additive correction ball.  It then asks whether the refined correction
closes q<8 by either the existing SO(3) geodesic route or the signed-product
current-y/z support route.

This is a focused diagnostic only.  It does not promote sample 1, a complete
word, or N_H_words, and it changes no estimator, source domain, six-radian
shipping correction limit, or q<8 target.
"""
from __future__ import annotations

import argparse
import json
import math
from pathlib import Path

from ou3_interval import Interval
import ou3_p5_effective_vector_input as EFF
import ou3_p5_sample1_signed_cayley_q8_v14 as V14
import ou3_p5_sample1_signed_cayley_q8_v15 as V15
import ou3_p5_sample1_signed_cayley_q8_v16 as V16
import ou3_p5_sample1_signed_cayley_q8_v17 as V17
import ou3_p5_sample1_signed_cayley_q8_v18 as V18
import ou3_p5_sample1_signed_radial_subcells_v13 as V13
import ou3_p5_sample1_structured_full_gain_v12d as V12D

DEFAULT_DOMAIN = V12D.DEFAULT_DOMAIN
SCHEMA = 2100
FULL = V14.FULL
Q_TARGET = V14.Q_TARGET
WITNESS_P_CELL = 0
WITNESS_TANGENT_CELL = 0
WITNESS_AXIAL_CELL = 19
WITNESS_RX_CELL = 0
WITNESS_PARALLEL_CELL = 0


def _norm2_upper(a: float, b: float) -> float:
    return FULL.up(math.sqrt(FULL.up(FULL.up(a * a) + FULL.up(b * b))))


def _current_component_chart(*, first: dict, base: dict, vr: dict,
                             dom: dict, src: dict,
                             sample1_s_angle: float) -> dict:
    """V18B current component chart, exposed here for the focused witness."""
    parent = dict(V14._sample1_current_chart(
        first=first, base=base, vr=vr, dom=dom, src=src,
        sample1_s_angle=sample1_s_angle))
    qpre = float(first["post_prediction_full_cayley_norm_upper"])
    ctan = float(first["post_prediction_cayley_tangent_norm_upper"])
    d0 = Interval.outward_bounds(*map(float, base["first_attitude_correction_rad"]))
    dd = float(vr["first_offaxis_attitude_correction_upper_rad"])
    e = Interval.outward_bounds(-dd, dd)
    dbox0 = [d0 + e, e, e]
    d0_hi = FULL.up(max(0.0, d0.hi) + dd)
    d0_lo = max(0.0, FULL.down(max(0.0, d0.lo) - dd))

    cpre = [
        Interval.outward_bounds(-ctan, ctan),
        Interval.outward_bounds(-ctan, ctan),
        Interval.outward_bounds(-qpre, qpre),
    ]
    w0, v0, branches0 = V14._normalized_shipping_quaternion(
        dbox0, radial_lower=d0_lo, radial_upper=d0_hi)
    W0 = FULL.I(2.0) * w0 - V14.CAYLEY1._dot(v0, cpre)
    if W0.lo <= 0.0 <= W0.hi:
        raise RuntimeError("V21 sample-0 product scalar crosses zero")
    cross0 = V14.CAYLEY1._cross(v0, cpre)
    V0 = [w0 * cpre[i] + FULL.I(2.0) * v0[i] + cross0[i]
          for i in range(3)]
    c0 = [FULL.I(2.0) * V0[i] / W0 for i in range(3)]
    cy0, cz0 = V18._rotate_yz_rx_transpose(c0[1], c0[2], d0)
    comps = [c0[0], cy0, cz0]

    q0_triangle = V14.PREFIX2._post_correction_q_upper(qpre, d0_hi)
    q0_product = V17._q_upper_from_product_scalar(qpre, W0)
    q0 = min(q0_triangle, q0_product)
    if not math.isfinite(q0):
        raise RuntimeError("V21 sample-0 current chart left Cayley coordinates")

    transport = float(first["first_prediction_transport_angle_upper_rad"])
    comps = [V14._widen_cx_by_unknown_rotation(x, q0, transport) for x in comps]
    qpred = V14.RG._q_after_first_prediction(q0, dom, float(src["dt_s"]))
    if not math.isfinite(qpred):
        raise RuntimeError("V21 sample-1 prediction left Cayley coordinates")

    ds = max(0.0, float(sample1_s_angle))
    comps = [V14._widen_cx_by_unknown_rotation(x, qpred, ds) for x in comps]
    q1_new = V14.PREFIX2._post_correction_q_upper(qpred, ds)
    q1 = min(float(parent["q1"]), q1_new)
    comps = [V17._clip_component_to_radius(x, q1) for x in comps]
    comps[0] = V18._intersect(comps[0], parent["cx"])

    cx_min = V14._minimum_abs(comps[0])
    yz2 = max(0.0, FULL.up(q1 * q1) - FULL.down(cx_min * cx_min))
    sphere_cyz = FULL.up(math.sqrt(yz2))
    cyz = min(float(parent["cyz_norm_upper"]), sphere_cyz,
              V18._yz_norm_upper(comps[1], comps[2]))
    return {
        "cx": comps[0], "cy": comps[1], "cz": comps[2],
        "q1": q1, "cyz_norm_upper": cyz,
        "sample0_product_scalar": W0,
        "sample0_quaternion_branches": branches0,
    }


def _post_prediction_aw_error_upper(*, first: dict, fr: dict, p: Interval,
                                    rt: Interval, rz: Interval,
                                    alpha: Interval, r: Interval,
                                    gravity: float, bias_upper: float) -> float:
    """Reproduce V7's source-correlated physical a_w error upper."""
    D = FULL.I(gravity * gravity) * Interval.outward_bounds(
        *map(float, first["attitude_covariance_seed_tilt_interval"])) + p + r \
        if "attitude_covariance_seed_tilt_interval" in first else None
    # V7 computes this quantity from the first gravity cosine and the canonical
    # first a_w gains.  Reconstruct those gains directly from source covariance.
    # The caller patches in the canonical tilt interval through _eaw_from_source
    # below; this branch is never used directly.
    if D is not None:
        raise RuntimeError("unexpected legacy V21 a_w helper branch")
    raise RuntimeError("use _eaw_from_source")


def _eaw_from_source(*, first: dict, fr: dict, p: Interval,
                     t: Interval, r: Interval, rt: Interval, rz: Interval,
                     alpha: Interval, gravity: float, bias_upper: float) -> float:
    D = FULL.I(gravity * gravity) * t + p + r
    kaw_t = p / D
    kz = p / (p + r)
    cos0 = float(first["post_prediction_true_gravity_cosine_lower"])
    sin0 = 1.0 if cos0 < 0.0 else FULL.up(math.sqrt(max(
        0.0, FULL.up(1.0 - FULL.down(cos0 * cos0)))))
    yRt = FULL.up(gravity * sin0)
    yRz = FULL.up(gravity * max(0.0, FULL.up(1.0 - cos0)))
    one_t = FULL.I(1.0) - kaw_t
    one_z = FULL.I(1.0) - kz
    left_t = (one_t * rt).abs_upper()
    left_z = (one_z * rz).abs_upper()
    post_from_residual = FULL.up(_norm2_upper(
        FULL.up(left_t + yRt), FULL.up(left_z + yRz)) + bias_upper)
    awt = kaw_t * rt
    az = kz * rz
    dxaw = _norm2_upper(awt.abs_upper(), az.abs_upper())
    aw_pre = float(fr["predicted_aw_error_norm_upper_mps2"])
    post_from_triangle = FULL.up(aw_pre + dxaw)
    post_aw = min(post_from_residual, post_from_triangle)
    return FULL.up(alpha.hi * post_aw)


def _intersect_boxes(a, b):
    if len(a) != len(b):
        raise ValueError("equal correction dimensions required")
    out = []
    for x, y in zip(a, b):
        lo = max(x.lo, y.lo); hi = min(x.hi, y.hi)
        if hi < lo:
            return None
        out.append(Interval(lo, hi))
    return out


def build(domain_path: Path = DEFAULT_DOMAIN, *, source_pieces: int = 4,
          source_cell_index: int = 0, p_pieces: int = 24,
          tangent_pieces: int = 24, axial_pieces: int = 24,
          residual_x_pieces: int = 6, parallel_pieces: int = 6) -> dict:
    path = Path(domain_path).resolve()
    dom = json.loads(path.read_text(encoding="utf-8"))
    v12 = V12D.build(path, source_pieces=source_pieces,
                     source_cell_index=source_cell_index, p_pieces=p_pieces,
                     tangent_pieces=tangent_pieces, axial_pieces=axial_pieces)
    core = V12D.V11.V10.build(path, source_pieces=source_pieces,
                              source_cell_index=source_cell_index,
                              p_pieces=p_pieces,
                              tangent_pieces=tangent_pieces,
                              axial_pieces=axial_pieces)
    first = V12D.V11.FIRST.build(path, source_pieces=source_pieces)
    eff = EFF.build(path)
    failures = [f"V12D: {x}" for x in V12D.validate(v12)]
    failures += [f"V10: {x}" for x in V12D.V11.V10.validate(core)]
    failures += [f"first: {x}" for x in V12D.V11.FIRST.validate(first)]
    failures += [f"effective-input: {x}" for x in EFF.validate(eff)]
    if v12.get("P5_SAMPLE1_FIRST_PSD_TANGENT_REFINEMENT_V12D") != "PASS":
        failures.append("V12D prerequisite did not pass")
    if eff.get("P5_EFFECTIVE_VECTOR_INPUT_CERTIFICATE") != "PASS":
        failures.append("effective-vector-input prerequisite did not pass")
    if len(core.get("rows", [])) != len(v12.get("rows", [])):
        failures.append("V10/V12D row count mismatch")

    src_children = V14.RG._source_phase_children(source_pieces)
    if source_cell_index < 0 or source_cell_index >= len(src_children):
        raise ValueError("invalid V21 source cell index")
    src, phase = src_children[source_cell_index]
    if phase != "due":
        failures.append("V21 focused witness requires first-due source cell")

    base = vr = None
    for b, v in zip(core.get("rows", []), v12.get("rows", [])):
        ids = (int(b["p_cell"]), int(b["tangent_residual_cell"]),
               int(b["axial_residual_cell"]))
        if ids == (WITNESS_P_CELL, WITNESS_TANGENT_CELL, WITNESS_AXIAL_CELL):
            base, vr = b, v
            break
    if base is None or vr is None:
        failures.append("V21 first-q8-witness V10/V12D row not found")
        return {
            "schema": SCHEMA,
            "qualification": "OU3_P5_SAMPLE1_EFFECTIVE_INPUT_CORRECTION_WITNESS_V21",
            "source_generated_not_trajectory_fit": True,
            "source_replay_used": False,
            "filter_changed": False,
            "deployed_correction_limit_rad": 6.0,
            "deployed_correction_limit_increased": False,
            "q_target": Q_TARGET,
            "q8_composed_here": False,
            "q8_word_promoted_here": False,
            "whole_word_promoted_here": False,
            "N_H_words_set_here": False,
            "P5_SAMPLE1_EFFECTIVE_INPUT_CORRECTION_WITNESS_V21": "NOT_ESTABLISHED",
            "next_obligation": "REPAIR_V21_WITNESS_ROW_LOOKUP",
            "failures": failures,
        }

    fr = first["source_cells"][source_cell_index]
    p_all = Interval.outward_bounds(*map(float, fr["P_aw_variance_interval"]))
    pcells = V12D.V11.SUB.parts(p_all.lo, p_all.hi, p_pieces)
    p = pcells[WITNESS_P_CELL]
    hstep = float(src["dt_s"]); g = float(dom["startup"]["gravity_mps2"])
    tilt, yaw, eps = V14.RG._attitude_covariance_epsilon(path, hstep)
    t = Interval.outward_bounds(tilt, FULL.up(tilt + eps))
    Y = Interval.outward_bounds(yaw, FULL.up(yaw + eps))
    vec = V12D.V11.VECTOR.build()
    r = FULL._R_diag(float(vec["configured_measurement_bounds"]["acc_measurement_std_mps2"]))[0][0]
    F, Q, _ = FULL._transition_and_Q(src, dom)
    alpha = F[15][15]; qaw = Q[15][15]
    rt = Interval.outward_bounds(*map(float, base["first_tangent_residual_magnitude_mps2"]))
    rz = Interval.outward_bounds(*map(float, base["first_axial_residual_mps2"]))
    d0 = Interval.outward_bounds(*map(float, base["first_attitude_correction_rad"]))
    D = FULL.I(g * g) * t + p + r
    a = t * (p + r) / D
    c0 = -(FULL.I(g) * t * p / D)
    b = p * (FULL.I(g * g) * t + r) / D
    bz = p * r / (p + r)
    det_first = t * p * r / D
    fy = -(alpha * (p / D) * rt)
    fz = FULL.I(g) + alpha * (p / (p + r)) * rz
    (gy, gz), (kxy, kxz), gain_detail = V13._signed_gain_components(
        a=a, Y=Y, c0=c0, alpha=alpha, qaw=qaw, b=b, bz=bz,
        det_first=det_first, d=d0, fy=fy, fz=fz, r=r)

    sb = v12.get("sample1_S_perturbation_bounds", {})
    ds = float(sb.get("sample1_S_attitude_correction_upper_rad", 0.0))
    chart = _current_component_chart(
        first=first, base=base, vr=vr, dom=dom, src=src,
        sample1_s_angle=ds)
    q1 = float(chart["q1"])

    ba = float(dom["startup"]["physical_handoff_coordinate_bounds"]["accelerometer_bias_error_norm_upper_mps2"])
    eaw = _eaw_from_source(first=first, fr=fr, p=p, t=t, r=r, rt=rt, rz=rz,
                           alpha=alpha, gravity=g, bias_upper=ba)
    force = float(base["sample1_force_norm_upper_mps2"])
    att_eta = FULL.up(EFF.accel_attitude_eta_per_vector_norm_upper(q1) * force)
    latent_eta = FULL.up(EFF.accel_latent_cross_gain_upper(q1) * eaw)
    nuisance = FULL.up(FULL.up(eaw + ba) + FULL.up(att_eta + latent_eta))

    cx, cy, cz = chart["cx"], chart["cy"], chart["cz"]
    rx_att = fz * cy - fy * cz
    ry_att = -(fz * cx)
    rz_att = fy * cx
    dx_att = kxy * ry_att + kxz * rz_att
    dy_att = gy * rx_att
    dz_att = gz * rx_att

    kperp = float(base["Ktheta_perpendicular_block_upper"])
    kpar = float(base["Ktheta_parallel_block_upper"])
    drho = float(vr["total_residual_perturbation_upper_mps2"])
    dk = float(vr["sample1_attitude_gain_operator_perturbation_upper"])
    rho = float(base["sample1_full_residual_norm_upper_mps2"])
    rho_x = min(rho, float(base["sample1_combined_source_x_residual_upper_mps2"]))
    k0 = max(kperp, kpar)
    correction_perturb = FULL.up(
        FULL.up(k0 * drho) + FULL.up(dk * FULL.up(rho + drho)))
    ep = Interval.outward_bounds(-FULL.up(kpar * nuisance), FULL.up(kpar * nuisance))
    et = Interval.outward_bounds(-FULL.up(kperp * nuisance), FULL.up(kperp * nuisance))
    ec = Interval.outward_bounds(-correction_perturb, correction_perturb)
    source_box = [dx_att + ep + ec, dy_att + et + ec, dz_att + et + ec]

    rx_cells = V12D.V11.SUB.parts(-rho_x, rho_x, residual_x_pieces)
    rxc = rx_cells[WITNESS_RX_CELL]
    rx_min = V14._minimum_abs(rxc)
    rem2 = max(0.0, FULL.up(rho * rho) - FULL.down(rx_min * rx_min))
    ryz_hi = FULL.up(math.sqrt(rem2))
    ux_hi = FULL.up(kpar * ryz_hi)
    u_cells = V12D.V11.SUB.parts(-ux_hi, ux_hi, parallel_pieces)
    uc = u_cells[WITNESS_PARALLEL_CELL]
    baseline_box = [uc + ec, gy * rxc + ec, gz * rxc + ec]
    baseline_nominal_hi = FULL.up(math.sqrt(FULL.up(
        FULL.up(uc.abs_upper() ** 2) + FULL.up((kperp * rxc.abs_upper()) ** 2))))
    baseline_radial_hi = min(float(vr["V12C_correction_norm_upper_rad"]),
                             FULL.up(baseline_nominal_hi + correction_perturb))
    baseline_radial_lo = min(V14.CAYLEY2._norm_lower(baseline_box), baseline_radial_hi)

    joint_box = _intersect_boxes(baseline_box, source_box)
    source_incompatible = joint_box is None
    if source_incompatible:
        refined_radial_hi = 0.0
        refined_radial_lo = 0.0
        geo_q = product_q = 0.0
        product_w = math.inf
        closes = True
    else:
        refined_radial_hi = min(
            baseline_radial_hi, V14.CAYLEY1._norm_upper(joint_box))
        refined_radial_lo = min(V14.CAYLEY2._norm_lower(joint_box), refined_radial_hi)
        geo = V15._geodesic_q_and_scalar_lower(
            q1, refined_radial_lo, refined_radial_hi)
        geo_q = math.inf if geo is None else float(geo[0])
        parent_q = V14._normalized_shipping_quaternion(
            joint_box, radial_lower=refined_radial_lo,
            radial_upper=refined_radial_hi)
        wd, vd, _branches = parent_q
        W, _yz_box, _yz_joint = V18._support_product_scalar(
            FULL.I(2.0) * wd - V14.CAYLEY1._dot(vd, [cx, cy, cz]),
            wd, vd, chart)
        product_w, product_q = V14._qplus_from_product_scalar(q1, W)
        closes = ((math.isfinite(geo_q) and geo_q < Q_TARGET)
                  or (math.isfinite(product_q) and product_q < Q_TARGET
                      and product_w > 0.0))

    baseline_geo = V15._geodesic_q_and_scalar_lower(
        q1, baseline_radial_lo, baseline_radial_hi)
    baseline_geo_q = math.inf if baseline_geo is None else float(baseline_geo[0])
    refined = source_incompatible or refined_radial_hi < baseline_radial_hi
    next_obligation = (
        "LIFT_V21_EFFECTIVE_INPUT_CORRECTION_INTERSECTION_INTO_FULL_V18B_Q8_COVER"
        if closes else
        "SUBDIVIDE_JOINT_CURRENT_EFFECTIVE_INPUT_MAP_AT_FIRST_Q8_WITNESS"
        if refined else
        "DERIVE_SOURCE_CORRELATED_SAMPLE1_AW_ERROR_COMPONENTS_AT_FIRST_Q8_WITNESS"
    )

    status = "PASS" if not failures else "NOT_ESTABLISHED"
    return {
        "schema": SCHEMA,
        "qualification": "OU3_P5_SAMPLE1_EFFECTIVE_INPUT_CORRECTION_WITNESS_V21",
        "source_generated_not_trajectory_fit": True,
        "source_replay_used": False,
        "filter_changed": False,
        "V12D_PSD_S_perturbation_retained": True,
        "V10_one_plus_two_gain_retained": True,
        "exact_accelerometer_effective_input_lemma_used": True,
        "current_cayley_and_sample1_correction_jointly_mapped": True,
        "V13E_signed_subcell_intersected_not_replaced": True,
        "witness_ids": {
            "p_cell": WITNESS_P_CELL,
            "tangent_residual_cell": WITNESS_TANGENT_CELL,
            "axial_residual_cell": WITNESS_AXIAL_CELL,
            "residual_x_cell": WITNESS_RX_CELL,
            "parallel_correction_cell": WITNESS_PARALLEL_CELL,
        },
        "sample1_current_cayley_norm_upper": q1,
        "sample1_current_component_box": [cx.as_list(), cy.as_list(), cz.as_list()],
        "sample1_force_components_yz_mps2": [fy.as_list(), fz.as_list()],
        "sample1_force_norm_upper_mps2": force,
        "post_prediction_physical_aw_error_norm_upper_mps2": eaw,
        "accelerometer_bias_error_norm_upper_mps2": ba,
        "effective_attitude_defect_norm_upper_mps2": att_eta,
        "effective_latent_cross_norm_upper_mps2": latent_eta,
        "nominal_effective_residual_nuisance_norm_upper_mps2": nuisance,
        "V12D_correction_perturbation_norm_upper_rad": correction_perturb,
        "gain_detail": gain_detail,
        "nominal_attitude_residual_box_mps2": [rx_att.as_list(), ry_att.as_list(), rz_att.as_list()],
        "source_correlated_correction_box_rad": [x.as_list() for x in source_box],
        "baseline_nominal_rx_subcell_mps2": rxc.as_list(),
        "baseline_nominal_parallel_correction_subcell_rad": uc.as_list(),
        "baseline_correction_box_rad": [x.as_list() for x in baseline_box],
        "joint_correction_box_rad": None if joint_box is None else [x.as_list() for x in joint_box],
        "source_subcell_incompatible": source_incompatible,
        "baseline_correction_radial_lower_rad": baseline_radial_lo,
        "baseline_correction_radial_upper_rad": baseline_radial_hi,
        "refined_correction_radial_lower_rad": refined_radial_lo,
        "refined_correction_radial_upper_rad": refined_radial_hi,
        "correction_radial_strictly_refined": refined,
        "baseline_geodesic_q_upper": baseline_geo_q,
        "refined_geodesic_q_upper": geo_q,
        "refined_product_abs_W_lower": product_w,
        "refined_product_q_upper": product_q,
        "first_witness_closed_inside_q8": closes,
        "deployed_correction_limit_rad": 6.0,
        "deployed_correction_limit_increased": False,
        "q_target": Q_TARGET,
        "q8_composed_here": False,
        "q8_word_promoted_here": False,
        "whole_word_promoted_here": False,
        "N_H_words_set_here": False,
        "P5_SAMPLE1_EFFECTIVE_INPUT_CORRECTION_WITNESS_V21": status,
        "next_obligation": next_obligation,
        "failures": list(dict.fromkeys(failures)),
    }


def validate(d: dict) -> list[str]:
    f = list(d.get("failures", []))
    if d.get("schema") != SCHEMA:
        f.append("schema mismatch")
    if d.get("qualification") != "OU3_P5_SAMPLE1_EFFECTIVE_INPUT_CORRECTION_WITNESS_V21":
        f.append("qualification mismatch")
    for key in (
        "source_generated_not_trajectory_fit", "V12D_PSD_S_perturbation_retained",
        "V10_one_plus_two_gain_retained", "exact_accelerometer_effective_input_lemma_used",
        "current_cayley_and_sample1_correction_jointly_mapped",
        "V13E_signed_subcell_intersected_not_replaced",
    ):
        if d.get(key) is not True:
            f.append(f"{key} is not true")
    for key in (
        "source_replay_used", "filter_changed", "deployed_correction_limit_increased",
        "q8_composed_here", "q8_word_promoted_here", "whole_word_promoted_here",
        "N_H_words_set_here",
    ):
        if d.get(key) is not False:
            f.append(f"{key} is not false")
    if float(d.get("deployed_correction_limit_rad", 0.0)) != 6.0:
        f.append("deployed correction limit changed")
    if float(d.get("q_target", 0.0)) != Q_TARGET:
        f.append("q target changed")
    for key in (
        "sample1_current_cayley_norm_upper",
        "nominal_effective_residual_nuisance_norm_upper_mps2",
        "V12D_correction_perturbation_norm_upper_rad",
        "baseline_correction_radial_upper_rad",
        "refined_correction_radial_upper_rad",
    ):
        x = d.get(key)
        if not isinstance(x, (int, float)) or not math.isfinite(float(x)) or float(x) < 0.0:
            f.append(f"invalid {key}")
    if (not d.get("source_subcell_incompatible")
            and float(d.get("refined_correction_radial_upper_rad", math.inf))
            > float(d.get("baseline_correction_radial_upper_rad", -math.inf))):
        f.append("source intersection worsened correction radial upper")
    st = d.get("P5_SAMPLE1_EFFECTIVE_INPUT_CORRECTION_WITNESS_V21")
    if st not in ("PASS", "NOT_ESTABLISHED"):
        f.append("invalid V21 status")
    if st == "PASS" and d.get("joint_correction_box_rad") is None \
            and d.get("source_subcell_incompatible") is not True:
        f.append("V21 PASS lost joint correction box without proving incompatibility")
    return list(dict.fromkeys(f))


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--domain", type=Path, default=DEFAULT_DOMAIN)
    ap.add_argument("--source-pieces", type=int, default=4)
    ap.add_argument("--source-cell-index", type=int, default=0)
    ap.add_argument("--p-pieces", type=int, default=24)
    ap.add_argument("--tangent-pieces", type=int, default=24)
    ap.add_argument("--axial-pieces", type=int, default=24)
    ap.add_argument("--residual-x-pieces", type=int, default=6)
    ap.add_argument("--parallel-pieces", type=int, default=6)
    ap.add_argument("--output", type=Path, required=True)
    x = ap.parse_args()
    d = build(x.domain, source_pieces=x.source_pieces,
              source_cell_index=x.source_cell_index, p_pieces=x.pieces if hasattr(x, 'pieces') else x.p_pieces,
              tangent_pieces=x.tangent_pieces, axial_pieces=x.axial_pieces,
              residual_x_pieces=x.residual_x_pieces,
              parallel_pieces=x.parallel_pieces)
    vf = validate(d)
    d["validation_failures"] = vf
    x.output.parent.mkdir(parents=True, exist_ok=True)
    x.output.write_text(json.dumps(d, indent=2, sort_keys=True), encoding="utf-8")
    print(json.dumps({
        "status": d["P5_SAMPLE1_EFFECTIVE_INPUT_CORRECTION_WITNESS_V21"],
        "q_current": d.get("sample1_current_cayley_norm_upper"),
        "nuisance": d.get("nominal_effective_residual_nuisance_norm_upper_mps2"),
        "baseline_radial_upper": d.get("baseline_correction_radial_upper_rad"),
        "refined_radial_upper": d.get("refined_correction_radial_upper_rad"),
        "baseline_geodesic_q": d.get("baseline_geodesic_q_upper"),
        "refined_geodesic_q": d.get("refined_geodesic_q_upper"),
        "refined_product_q": d.get("refined_product_q_upper"),
        "refined_product_W": d.get("refined_product_abs_W_lower"),
        "source_incompatible": d.get("source_subcell_incompatible"),
        "closed_q8": d.get("first_witness_closed_inside_q8"),
        "next": d.get("next_obligation"),
        "validation_failures": vf,
    }, indent=2, sort_keys=True))
    return 0 if not vf else 2


if __name__ == "__main__":
    raise SystemExit(main())
