#!/usr/bin/env python3
"""V23: subdivide the authoritative current Cayley box at the first q8 witness.

V22 removes the independent finite-angle attitude/latent double charges and
cuts the first-witness nominal residual nuisance by more than half, but it still
evaluates the exact nonlinear residual over the entire V18B current component
box.  The resulting interval dependency is wide enough that the V13E correction
radial upper remains unchanged at 2.0878269 rad.

V23 partitions each component of that same authoritative current Cayley box.
For every current subbox it

  * projects the Cartesian subbox onto the already certified current q ball;
  * evaluates the exact V22 nonlinear accelerometer residual on that box;
  * maps it through the same signed V10 one-plus-two attitude gain;
  * adds the unchanged V12D PSD/S correction perturbation ball;
  * intersects with the same V13E first-witness signed correction subcell;
  * evaluates the existing V16 axis cone, V15 geodesic q bound, and V18
    current-y/z signed-product support using that *same* current subbox.

Thus current direction and the correction generated by that current direction
remain correlated until the q8 test.  This is not V19's late subdivision of two
already-independent y/z boxes.  A subbox is discarded only when the current q
ball or independently rigorous correction/radial enclosures prove it
unreachable.

This remains a focused first-witness diagnostic.  It does not promote the q8
word, sample 1, the complete word, P5, or N_H_words.
"""
from __future__ import annotations

import argparse
import json
import math
from pathlib import Path

from ou3_interval import Interval
import ou3_p5_sample1_exact_nonlinear_residual_v22 as V22
import ou3_p5_sample1_rotation_gauge_refinement_v2 as SUB
import ou3_p5_sample1_signed_cayley_q8_v14 as V14
import ou3_p5_sample1_signed_cayley_q8_v14d as V14D
import ou3_p5_sample1_signed_cayley_q8_v15 as V15
import ou3_p5_sample1_signed_cayley_q8_v16 as V16
import ou3_p5_sample1_signed_cayley_q8_v18 as V18

DEFAULT_DOMAIN = V22.DEFAULT_DOMAIN
SCHEMA = 2300
FULL = V14.FULL
Q_TARGET = V14.Q_TARGET


def _source_correction_box(c, parent: dict):
    fyz = parent["sample1_force_components_yz_mps2"]
    force = [FULL.I(0.0), V22._I(fyz[0]), V22._I(fyz[1])]
    yR = V22.exact_rotation_residual(c, force)

    gain = parent["gain_detail"]
    gy, gz = [V22._I(x) for x in gain["perpendicular_gain_components"]]
    kxy, kxz = [V22._I(x) for x in gain["parallel_gain_components"]]
    eaw = float(parent["post_prediction_physical_aw_error_norm_upper_mps2"])
    ba = float(parent["accelerometer_bias_error_norm_upper_mps2"])
    nuisance = FULL.up(eaw + ba)
    corr_perturb = float(parent["V12D_correction_perturbation_norm_upper_rad"])
    n = Interval.outward_bounds(-nuisance, nuisance)
    ec = Interval.outward_bounds(-corr_perturb, corr_perturb)
    kx_norm = V22._norm2_upper(kxy, kxz)
    nx = FULL.up(kx_norm * nuisance)
    enx = Interval.outward_bounds(-nx, nx)
    return [
        kxy * yR[1] + kxz * yR[2] + enx + ec,
        gy * yR[0] + gy * n + ec,
        gz * yR[0] + gz * n + ec,
    ], yR, nuisance


def _current_subboxes(parent_box, pieces: int):
    if pieces < 2:
        raise ValueError("current component subdivision pieces must be >=2")
    if len(parent_box) != 3:
        raise ValueError("three current Cayley components required")
    parts = [SUB.parts(x.lo, x.hi, pieces) for x in parent_box]
    return [(x, y, z) for x in parts[0] for y in parts[1] for z in parts[2]]


def _clip_box_to_q_ball(box, q: float):
    """Coordinatewise projection enclosure of box intersected with ||c||<=q."""
    if len(box) != 3:
        raise ValueError("three current Cayley components required")
    q = float(q)
    if not (math.isfinite(q) and q >= 0.0):
        raise ValueError("finite nonnegative current q upper required")
    out = [Interval(x.lo, x.hi) for x in box]
    if V14.CAYLEY2._norm_lower(out) > q:
        return None
    q2 = FULL.up(q * q)
    # Repeated coordinate projections propagate tightening between axes while
    # remaining a Cartesian outer enclosure of box intersected with the ball.
    for _ in range(3):
        changed = False
        for i in range(3):
            j, k = (i + 1) % 3, (i + 2) % 3
            aj = V14._minimum_abs(out[j]); ak = V14._minimum_abs(out[k])
            rest_lo = FULL.down(FULL.down(aj * aj) + FULL.down(ak * ak))
            rem_hi = FULL.up(q2 - rest_lo)
            if rem_hi < 0.0:
                return None
            cap = FULL.up(math.sqrt(max(0.0, rem_hi)))
            lo = max(out[i].lo, FULL.down(-cap))
            hi = min(out[i].hi, FULL.up(cap))
            if hi < lo:
                return None
            if lo > out[i].lo or hi < out[i].hi:
                changed = True
                out[i] = Interval(lo, hi)
        if not changed:
            break
    if V14.CAYLEY2._norm_lower(out) > q:
        return None
    return tuple(out)


def build(domain_path: Path = DEFAULT_DOMAIN, *, source_pieces: int = 4,
          source_cell_index: int = 0, p_pieces: int = 24,
          tangent_pieces: int = 24, axial_pieces: int = 24,
          residual_x_pieces: int = 6, parallel_pieces: int = 6,
          current_component_pieces: int = 4) -> dict:
    parent = V22.build(
        Path(domain_path).resolve(),
        source_pieces=source_pieces,
        source_cell_index=source_cell_index,
        p_pieces=p_pieces,
        tangent_pieces=tangent_pieces,
        axial_pieces=axial_pieces,
        residual_x_pieces=residual_x_pieces,
        parallel_pieces=parallel_pieces,
    )
    failures = [f"V22: {x}" for x in V22.validate(parent)]
    if parent.get("P5_SAMPLE1_EXACT_NONLINEAR_RESIDUAL_WITNESS_V22") != "PASS":
        failures.append("V22 exact-residual witness prerequisite did not pass")

    q_parent = float(parent.get("sample1_current_cayley_norm_upper", math.inf))
    c_parent = [V22._I(x) for x in parent.get("sample1_current_component_box", [])]
    baseline_box = [V22._I(x) for x in parent.get("baseline_correction_box_rad", [])]
    if len(c_parent) != 3 or len(baseline_box) != 3:
        failures.append("V23 parent current/correction box missing")
        return {
            **parent,
            "schema": SCHEMA,
            "qualification": "OU3_P5_SAMPLE1_CURRENT_EXACT_RESIDUAL_SUBDIVISION_V23",
            "P5_SAMPLE1_CURRENT_EXACT_RESIDUAL_SUBDIVISION_V23": "NOT_ESTABLISHED",
            "failures": list(dict.fromkeys(failures)),
        }
    if not (math.isfinite(q_parent) and q_parent >= 0.0):
        failures.append("invalid V23 parent current q upper")

    baseline_lo = float(parent["baseline_correction_radial_lower_rad"])
    baseline_hi = float(parent["baseline_correction_radial_upper_rad"])
    subboxes = _current_subboxes(c_parent, current_component_pieces)
    evaluated = q_rejected = correction_rejected = radial_rejected = closed = open_count = 0
    first_open = worst_open = first_closed = None
    min_qbest = math.inf
    max_qbest = 0.0
    max_radial_hi = 0.0
    min_radial_hi = math.inf

    for idx, raw_c in enumerate(subboxes):
        c = _clip_box_to_q_ball(raw_c, q_parent)
        if c is None:
            q_rejected += 1
            continue
        evaluated += 1
        q_sub = min(q_parent, V14.CAYLEY1._norm_upper(c))
        source_box, yR, nuisance = _source_correction_box(c, parent)
        joint = V22._intersect_boxes(baseline_box, source_box)
        if joint is None:
            correction_rejected += 1
            continue

        box_hi = V14.CAYLEY1._norm_upper(joint)
        box_lo = V14.CAYLEY2._norm_lower(joint)
        radial_hi = min(baseline_hi, box_hi)
        radial_lo = max(baseline_lo, box_lo)
        if radial_lo > radial_hi:
            radial_rejected += 1
            continue
        min_radial_hi = min(min_radial_hi, radial_hi)
        max_radial_hi = max(max_radial_hi, radial_hi)

        geo = V15._geodesic_q_and_scalar_lower(q_sub, radial_lo, radial_hi)
        geo_q = math.inf if geo is None else float(geo[0])
        wd, vd, branches, narrowed = V16.axis_cone_normalized_shipping_quaternion(
            joint,
            radial_lower=radial_lo,
            radial_upper=radial_hi,
            parent=V14D.radial_sinc_normalized_shipping_quaternion,
        )
        cx_min = V14._minimum_abs(c[0])
        yz2 = max(0.0, FULL.up(q_sub * q_sub) - FULL.down(cx_min * cx_min))
        sphere_cyz = FULL.up(math.sqrt(yz2))
        cyz = min(sphere_cyz, V18._yz_norm_upper(c[1], c[2]))
        chart = {"cx": c[0], "cy": c[1], "cz": c[2], "cyz_norm_upper": cyz}
        parent_W = FULL.I(2.0) * wd - V14.CAYLEY1._dot(vd, c)
        W, _yb, _yj = V18._support_product_scalar(parent_W, wd, vd, chart)
        product_w, product_q = V14._qplus_from_product_scalar(q_sub, W)
        qbest = min(geo_q, product_q)
        is_closed = ((math.isfinite(geo_q) and geo_q < Q_TARGET)
                     or (math.isfinite(product_q) and product_q < Q_TARGET
                         and product_w > 0.0))
        row = {
            "subbox_index": idx,
            "raw_current_component_box": [x.as_list() for x in raw_c],
            "q_ball_projected_current_component_box": [x.as_list() for x in c],
            "current_q_upper": q_sub,
            "exact_rotation_residual_box_mps2": [x.as_list() for x in yR],
            "nuisance_norm_upper_mps2": nuisance,
            "source_correction_box_rad": [x.as_list() for x in source_box],
            "joint_correction_box_rad": [x.as_list() for x in joint],
            "correction_radial_lower_rad": radial_lo,
            "correction_radial_upper_rad": radial_hi,
            "axis_cone_narrowed": narrowed,
            "quaternion_branches": branches,
            "geodesic_q_upper": geo_q,
            "product_abs_W_lower": product_w,
            "product_q_upper": product_q,
            "best_q_upper": qbest,
            "closed_inside_q8": is_closed,
        }
        if math.isfinite(qbest):
            min_qbest = min(min_qbest, qbest)
            if math.isfinite(max_qbest):
                max_qbest = max(max_qbest, qbest)
        else:
            max_qbest = math.inf
        if is_closed:
            closed += 1
            if first_closed is None:
                first_closed = row
        else:
            open_count += 1
            if first_open is None:
                first_open = row
            if worst_open is None or qbest > worst_open["best_q_upper"]:
                worst_open = row

    compatible = evaluated - correction_rejected - radial_rejected
    all_accounted = len(subboxes) == q_rejected + correction_rejected + radial_rejected + closed + open_count
    witness_closed = bool(not failures and all_accounted and open_count == 0)
    next_obligation = (
        "LIFT_V23_CURRENT_EXACT_RESIDUAL_SUBDIVISION_INTO_FULL_V18B_Q8_COVER"
        if witness_closed else
        "INCREASE_CURRENT_EXACT_RESIDUAL_SUBDIVISION_OR_DERIVE_AW_COMPONENTS_AT_FIRST_OPEN_SUBBOX"
    )
    return {
        **parent,
        "schema": SCHEMA,
        "qualification": "OU3_P5_SAMPLE1_CURRENT_EXACT_RESIDUAL_SUBDIVISION_V23",
        "V22_exact_nonlinear_residual_parent_retained": True,
        "authoritative_current_component_box_partitioned": True,
        "current_q_ball_projected_per_subbox": True,
        "current_subbox_and_exact_residual_kept_joint_through_q8_test": True,
        "V13E_signed_correction_subcell_intersected_per_current_subbox": True,
        "V16_axis_cone_V15_geodesic_V18_yz_support_retained": True,
        "current_component_pieces": int(current_component_pieces),
        "candidate_current_subboxes": len(subboxes),
        "q_ball_rejected_current_subboxes": q_rejected,
        "evaluated_q_compatible_current_subboxes": evaluated,
        "source_correction_rejected_current_subboxes": correction_rejected,
        "radial_constraint_rejected_current_subboxes": radial_rejected,
        "compatible_current_subboxes": compatible,
        "closed_current_subboxes": closed,
        "open_current_subboxes": open_count,
        "all_candidate_current_subboxes_accounted": all_accounted,
        "minimum_compatible_radial_upper_rad": None if math.isinf(min_radial_hi) else min_radial_hi,
        "maximum_compatible_radial_upper_rad": max_radial_hi,
        "minimum_best_q_upper": None if math.isinf(min_qbest) else min_qbest,
        "maximum_best_q_upper": max_qbest,
        "first_closed_current_subbox": first_closed,
        "first_open_current_subbox": first_open,
        "worst_open_current_subbox": worst_open,
        "focused_first_witness_signed_subcell_closed_by_subdivision": witness_closed,
        "deployed_correction_limit_rad": 6.0,
        "deployed_correction_limit_increased": False,
        "q_target": Q_TARGET,
        "q8_composed_here": False,
        "q8_word_promoted_here": False,
        "whole_word_promoted_here": False,
        "N_H_words_set_here": False,
        "P5_SAMPLE1_CURRENT_EXACT_RESIDUAL_SUBDIVISION_V23": (
            "PASS" if not failures else "NOT_ESTABLISHED"),
        "next_obligation": next_obligation,
        "failures": list(dict.fromkeys(failures)),
    }


def validate(d: dict) -> list[str]:
    f = list(d.get("failures", []))
    if d.get("schema") != SCHEMA:
        f.append("schema mismatch")
    if d.get("qualification") != "OU3_P5_SAMPLE1_CURRENT_EXACT_RESIDUAL_SUBDIVISION_V23":
        f.append("qualification mismatch")
    for key in (
        "source_generated_not_trajectory_fit",
        "V22_exact_nonlinear_residual_parent_retained",
        "authoritative_current_component_box_partitioned",
        "current_q_ball_projected_per_subbox",
        "current_subbox_and_exact_residual_kept_joint_through_q8_test",
        "V13E_signed_correction_subcell_intersected_per_current_subbox",
        "V16_axis_cone_V15_geodesic_V18_yz_support_retained",
        "all_candidate_current_subboxes_accounted",
    ):
        if d.get(key) is not True:
            f.append(f"{key} is not true")
    for key in (
        "source_replay_used", "filter_changed", "deployed_correction_limit_increased",
        "q8_composed_here", "q8_word_promoted_here", "whole_word_promoted_here",
        "N_H_words_set_here",
    ):
        if d.get(key) is not False:
            f.append(f"{key} is not false")
    if float(d.get("deployed_correction_limit_rad", 0.0)) != 6.0:
        f.append("deployed correction limit changed")
    if float(d.get("q_target", 0.0)) != Q_TARGET:
        f.append("q target changed")
    candidate = int(d.get("candidate_current_subboxes", -1))
    qrej = int(d.get("q_ball_rejected_current_subboxes", -1))
    evaluated = int(d.get("evaluated_q_compatible_current_subboxes", -1))
    crej = int(d.get("source_correction_rejected_current_subboxes", -1))
    rrej = int(d.get("radial_constraint_rejected_current_subboxes", -1))
    compatible = int(d.get("compatible_current_subboxes", -1))
    closed = int(d.get("closed_current_subboxes", -1))
    open_count = int(d.get("open_current_subboxes", -1))
    if not (candidate >= 1 and candidate == qrej + evaluated):
        f.append("invalid V23 current-subbox q accounting")
    if not (evaluated == crej + rrej + compatible):
        f.append("invalid V23 compatibility accounting")
    if not (compatible == closed + open_count):
        f.append("invalid V23 closure accounting")
    if candidate != qrej + crej + rrej + closed + open_count:
        f.append("V23 candidate subboxes are not fully accounted")
    if d.get("focused_first_witness_signed_subcell_closed_by_subdivision") is True and open_count != 0:
        f.append("V23 claims focused closure with open subboxes")
    st = d.get("P5_SAMPLE1_CURRENT_EXACT_RESIDUAL_SUBDIVISION_V23")
    if st not in ("PASS", "NOT_ESTABLISHED"):
        f.append("invalid V23 status")
    return list(dict.fromkeys(f))


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--domain", type=Path, default=DEFAULT_DOMAIN)
    ap.add_argument("--source-pieces", type=int, default=4)
    ap.add_argument("--source-cell-index", type=int, default=0)
    ap.add_argument("--p-pieces", type=int, default=24)
    ap.add_argument("--tangent-pieces", type=int, default=24)
    ap.add_argument("--axial-pieces", type=int, default=24)
    ap.add_argument("--residual-x-pieces", type=int, default=6)
    ap.add_argument("--parallel-pieces", type=int, default=6)
    ap.add_argument("--current-component-pieces", type=int, default=4)
    ap.add_argument("--output", type=Path, required=True)
    x = ap.parse_args()
    d = build(
        x.domain,
        source_pieces=x.source_pieces,
        source_cell_index=x.source_cell_index,
        p_pieces=x.p_pieces,
        tangent_pieces=x.tangent_pieces,
        axial_pieces=x.axial_pieces,
        residual_x_pieces=x.residual_x_pieces,
        parallel_pieces=x.parallel_pieces,
        current_component_pieces=x.current_component_pieces,
    )
    vf = validate(d)
    d["validation_failures"] = vf
    x.output.parent.mkdir(parents=True, exist_ok=True)
    x.output.write_text(json.dumps(d, indent=2, sort_keys=True), encoding="utf-8")
    print(json.dumps({
        "status": d["P5_SAMPLE1_CURRENT_EXACT_RESIDUAL_SUBDIVISION_V23"],
        "pieces": d["current_component_pieces"],
        "candidate": d["candidate_current_subboxes"],
        "q_rejected": d["q_ball_rejected_current_subboxes"],
        "evaluated": d["evaluated_q_compatible_current_subboxes"],
        "correction_rejected": d["source_correction_rejected_current_subboxes"],
        "radial_rejected": d["radial_constraint_rejected_current_subboxes"],
        "compatible": d["compatible_current_subboxes"],
        "closed": d["closed_current_subboxes"],
        "open": d["open_current_subboxes"],
        "min_radial_upper": d["minimum_compatible_radial_upper_rad"],
        "max_radial_upper": d["maximum_compatible_radial_upper_rad"],
        "min_best_q": d["minimum_best_q_upper"],
        "max_best_q": d["maximum_best_q_upper"],
        "focused_closed": d["focused_first_witness_signed_subcell_closed_by_subdivision"],
        "first_open": d["first_open_current_subbox"],
        "worst_open": d["worst_open_current_subbox"],
        "next": d["next_obligation"],
        "validation_failures": vf,
    }, indent=2, sort_keys=True))
    return 0 if not vf else 2


if __name__ == "__main__":
    raise SystemExit(main())
