#!/usr/bin/env python3
"""Canonical hard finite-window SEA3 provider contract.

This module owns the *only* artifact shape that may materialize the 3 s source
family consumed by canonical P3.  It does not create a second source.  The
provider must certify one compact, phase-continuous SEA3 realization family

    zeta_k = (x^s_k, lambda_k, z^t_k, q_k)

for all 601 samples.  The same x^s/lambda history must generate the physical
translation/rotation, the private measurement-only front end, the tuner and
scheduler, and hence the complete H18/A21 Riccati word.

The SEA3 theorem permits either an oscillator/shaping realization or an
equivalent hard finite-window dynamic constraint.  Both are represented by the
same transition-witness contract below.  A replay, a Gaussian good event,
spectral moments alone, arbitrary per-sample boxes, a fixed-lambda word, a
finite RAO grid, or an independently selected tuner schedule cannot satisfy
this provider.

SEA3 compactness is already a theorem-domain fact.  The machine-readable
parameter transition is now closed conservatively without inventing the
manuscript's missing numerical rate constants: the theorem's rate-bounded
R_lambda is enclosed by the full coupled compact SEA3 endpoint relation.  The
remaining open obligations are the hard phase-continuous shaping state (or an
equivalent hard finite-window dynamic constraint) and the joint translational/
rotational response generated by that same history.

The transition payload is also the sole bridge to the connected H18/A21
executor.  Raw gyro measurement and MEKF bias-corrected body rate are distinct
coordinates of the same source transition witness.  The source may request an
a_w covariance-floor synchronization, but it may not serialize the numerical
floor increment: shipping computes Pi_+(Sigma_aw-P_awaw^-) from each mode's
current Riccati covariance after prediction.

``PROVIDER_IMPLEMENTATION_CLOSED`` is code-owned and remains false until all
SEA0 executable obligations are implemented and validated.  An input JSON
cannot self-assert its way into P3.
"""
from __future__ import annotations

import argparse
import json
import math
from pathlib import Path
from typing import Any

import ou3_sea3_complete_source as COMPLETE
import ou3_sea3_directional_response_family as RESPONSE
import ou3_sea3_physical_admissibility as PHYSICAL
import ou3_sea3_rlambda_transition as RLAMBDA

REPO = Path(__file__).resolve().parents[1]
DEFAULT_DOMAIN = REPO / "tools" / "ou3_proof_operating_domain.json"
SCHEMA = 3
QUALIFICATION = "OU3_SEA3_HARD_FINITE_WINDOW_REALIZATION_V3"
CANONICAL_SOURCE = "COMPLETE_SEA3_NORMAL_LIVE_WORD"
HORIZON_S = 3.0
DT_S = 0.005
SAMPLES = 601

# These gates describe executable proof machinery, not SEA3 set compactness.
MACHINE_READABLE_R_LAMBDA_CLOSED = True
HARD_SHAPING_STATE_OR_EXCITATION_BOUND_CLOSED = False
JOINT_TRANSLATIONAL_ROTATIONAL_SHAPING_CLOSED = False
PROVIDER_IMPLEMENTATION_CLOSED = (
    MACHINE_READABLE_R_LAMBDA_CLOSED
    and HARD_SHAPING_STATE_OR_EXCITATION_BOUND_CLOSED
    and JOINT_TRANSLATIONAL_ROTATIONAL_SHAPING_CLOSED
)

_FORBIDDEN_TRUE_FLAGS = (
    "trajectory_replay_used",
    "gaussian_good_event_used",
    "spectral_moment_only_source_used",
    "arbitrary_bounded_input_source_used",
    "fixed_lambda_word_used",
    "independent_axis_boxes_used",
    "independent_SEA_RAO_cartesian_product_used",
    "finite_RAO_grid_used",
    "independent_tuner_schedule_used",
    "retired_P2_graph_used",
    "selected_four_S_word_used",
)

_REQUIRED_TRUE_FLAGS = (
    "SEA3_parameter_domain_compact",
    "compact_transition_relation_is_theorem_domain",
    "phase_continuous",
    "same_xs_lambda_history_for_all_channels",
    "same_realization_drives_translation_rotation_frontend_tuner_geometry",
    "all_valid_accelerometer_samples_retained",
    "all_due_S_updates_retained",
    "actual_applied_per_axis_RS_retained",
    "asynchronous_vector_PE_events_retained",
    "covariance_floor_events_retained",
)

_PHYSICAL_FIELDS = (
    "gyro_measurement_interval",
    "omega_body_corrected_interval",
    "specific_force_body_interval",
    "f_cog_body_interval",
    "R_wb_interval",
)

_EVENT_FIELDS = (
    "magnetometer_events_after_imu",
    "aw_covariance_floor_requested",
    "S_zero_due",
)


def _payload_failures(k: int, sample: dict[str, Any]) -> list[str]:
    f: list[str] = []
    transition_id = sample.get("source_transition_witness_id")
    response_id = sample.get("joint_response_witness_id")
    physical = sample.get("joint_physical_output")
    events = sample.get("source_events")

    if not isinstance(physical, dict):
        f.append(f"sample {k} missing joint_physical_output")
    else:
        for key in _PHYSICAL_FIELDS:
            if key not in physical:
                f.append(f"sample {k} missing physical field {key}")
        if physical.get("source_transition_witness_id") != transition_id:
            f.append(f"sample {k} physical output detached from source transition witness")
        if physical.get("joint_response_witness_id") != response_id:
            f.append(f"sample {k} physical output detached from joint response witness")

    if not isinstance(events, dict):
        f.append(f"sample {k} missing source_events")
    else:
        for key in _EVENT_FIELDS:
            if key not in events:
                f.append(f"sample {k} missing source event field {key}")
        if events.get("source_transition_witness_id") != transition_id:
            f.append(f"sample {k} source events detached from source transition witness")
        if not isinstance(events.get("aw_covariance_floor_requested"), bool):
            f.append(f"sample {k} a_w floor request is not boolean")
        if not isinstance(events.get("S_zero_due"), bool):
            f.append(f"sample {k} S_zero_due is not boolean")
        if not isinstance(events.get("magnetometer_events_after_imu"), list):
            f.append(f"sample {k} magnetometer event family is not a list")
        if "aw_covariance_floor_increment" in events:
            f.append(f"sample {k} illegally serializes covariance-dependent a_w floor increment")
    return f


def _continuity_failures(samples: Any) -> list[str]:
    f: list[str] = []
    if not isinstance(samples, list) or len(samples) != SAMPLES:
        return [f"window must contain exactly {SAMPLES} source transitions"]
    previous: dict[str, Any] | None = None
    source_id: str | None = None
    for k, sample in enumerate(samples):
        if not isinstance(sample, dict):
            f.append(f"sample {k} is not an object")
            continue
        if sample.get("k") != k:
            f.append(f"sample {k} index mismatch")
        sid = sample.get("source_identity")
        if not isinstance(sid, str) or not sid:
            f.append(f"sample {k} missing source_identity")
        elif source_id is None:
            source_id = sid
        elif sid != source_id:
            f.append(f"sample {k} changed source_identity")
        for key in (
            "xs_in_id", "xs_out_id", "lambda_in_id", "lambda_out_id",
            "source_transition_witness_id", "joint_response_witness_id",
        ):
            if not isinstance(sample.get(key), str) or not sample[key]:
                f.append(f"sample {k} missing {key}")
        if previous is not None:
            if previous.get("xs_out_id") != sample.get("xs_in_id"):
                f.append(f"sample {k} broke x^s phase continuity")
            if previous.get("lambda_out_id") != sample.get("lambda_in_id"):
                f.append(f"sample {k} broke lambda transition continuity")
        f.extend(_payload_failures(k, sample))
        previous = sample
    return f


def validate_candidate_structure(d: dict[str, Any]) -> list[str]:
    """Validate artifact shape and anti-shortcut semantics, but not SEA0 math."""
    f: list[str] = []
    if d.get("schema") != SCHEMA or d.get("qualification") != QUALIFICATION:
        f.append("schema/qualification mismatch")
    if d.get("canonical_source") != CANONICAL_SOURCE:
        f.append("wrong canonical source")
    if not math.isclose(float(d.get("window_horizon_s", math.nan)), HORIZON_S, rel_tol=0.0, abs_tol=1e-12):
        f.append("window horizon must be the canonical 3 s P3 horizon")
    if not math.isclose(float(d.get("sample_period_s", math.nan)), DT_S, rel_tol=0.0, abs_tol=1e-12):
        f.append("sample period must be the canonical 5 ms source period")
    if d.get("complete_window_samples") != SAMPLES:
        f.append(f"complete_window_samples must equal {SAMPLES}")
    for key in _REQUIRED_TRUE_FLAGS:
        if d.get(key) is not True:
            f.append(f"{key} is not true")
    for key in _FORBIDDEN_TRUE_FLAGS:
        if d.get(key) is not False:
            f.append(f"{key} is not false")
    representation = d.get("finite_window_representation")
    if representation not in ("oscillator_shaping_state", "equivalent_hard_finite_window_constraint"):
        f.append("finite-window representation is not an allowed SEA3 theorem representation")
    if d.get("provider_generated_source_family") is not True:
        f.append("provider_generated_source_family is not true")
    if d.get("front_end_entry_witness_id") in (None, ""):
        f.append("missing same-history front-end entry witness")
    if d.get("live_covariance_seed_witness_id") in (None, ""):
        f.append("missing same-history Live covariance seed witness")
    if not isinstance(d.get("front_end_entry"), dict):
        f.append("missing provider-certified front_end_entry payload")
    if not isinstance(d.get("live_covariance_seed"), dict):
        f.append("missing provider-certified live_covariance_seed payload")
    f.extend(_continuity_failures(d.get("transitions")))
    return list(dict.fromkeys(f))


def validate_artifact(d: dict[str, Any]) -> list[str]:
    """Canonical P3 acceptance gate for a finite SEA3 window artifact."""
    f = validate_candidate_structure(d)
    if not PROVIDER_IMPLEMENTATION_CLOSED:
        f.append("validated SEA0 hard finite-window provider is not implemented")
    return list(dict.fromkeys(f))


def build(domain_path: Path = DEFAULT_DOMAIN) -> dict[str, Any]:
    path = Path(domain_path).resolve()
    complete = COMPLETE.build(path)
    physical = PHYSICAL.build(path)
    response = RESPONSE.directional_response_enclosure(REPO)
    rlambda = RLAMBDA.build(path)
    prerequisite_failures = {
        "complete": COMPLETE.validate(complete),
        "physical": PHYSICAL.validate(physical),
        "response": RESPONSE.validate(response),
        "R_lambda": RLAMBDA.validate(rlambda),
    }
    prerequisite_failures = {k: v for k, v in prerequisite_failures.items() if v}
    if prerequisite_failures:
        raise RuntimeError(f"SEA3 hard-window prerequisites failed: {prerequisite_failures}")
    if rlambda.get("machine_readable_R_lambda_closed") is not True:
        raise RuntimeError("machine-readable conservative SEA3 R_lambda relation did not close")

    executable = {
        "machine_readable_R_lambda_closed": MACHINE_READABLE_R_LAMBDA_CLOSED,
        "hard_shaping_state_or_excitation_bound_closed": HARD_SHAPING_STATE_OR_EXCITATION_BOUND_CLOSED,
        "joint_translational_rotational_shaping_closed": JOINT_TRANSLATIONAL_ROTATIONAL_SHAPING_CLOSED,
    }
    return {
        "schema": SCHEMA,
        "qualification": QUALIFICATION,
        "canonical_source": CANONICAL_SOURCE,
        "SEA3_parameter_domain_compact": True,
        "compact_transition_relation_is_theorem_domain": True,
        "compactness_is_not_an_open_obligation": True,
        "R_lambda_certificate": {
            "qualification": rlambda["qualification"],
            "machine_readable_R_lambda_closed": True,
            "conservative_outer_relation_used": True,
            "actual_rate_bounded_R_lambda_subset_Rhat": rlambda[
                "actual_rate_bounded_R_lambda_subset_Rhat"
            ],
            "rate_constants_fitted_or_invented": rlambda[
                "rate_constants_fitted_or_invented"
            ],
            "fixed_lambda_word_used": rlambda["fixed_lambda_word_used"],
            "coupled_partition_energy_retained": rlambda[
                "coupled_partition_energy_retained"
            ],
            "coupled_peak_steepness_retained": rlambda[
                "coupled_peak_steepness_retained"
            ],
        },
        "allowed_finite_window_representations": [
            "oscillator_shaping_state",
            "equivalent_hard_finite_window_constraint",
        ],
        "window_horizon_s": HORIZON_S,
        "sample_period_s": DT_S,
        "complete_window_samples": SAMPLES,
        "executor_payload_contract": {
            "physical_fields": list(_PHYSICAL_FIELDS),
            "event_fields": list(_EVENT_FIELDS),
            "raw_gyro_and_corrected_rate_are_distinct_coordinates": True,
            "payloads_must_repeat_same_transition_witness_id": True,
            "physical_payload_must_repeat_same_joint_response_witness_id": True,
            "precomputed_aw_covariance_floor_increment_allowed": False,
        },
        "executable_provider_ingredients": executable,
        "provider_implementation_closed": PROVIDER_IMPLEMENTATION_CLOSED,
        "finite_window_realization_certificate_closed": False,
        "source_reachable_event_family_materialized": False,
        "continuum_RAO_set_theorem_retained": True,
        "continuum_RAO_set_theorem_is_not_finite_window_generator": True,
        "trajectory_replay_used": False,
        "gaussian_good_event_used": False,
        "spectral_moment_only_source_used": False,
        "arbitrary_bounded_input_source_used": False,
        "fixed_lambda_word_used": False,
        "independent_axis_boxes_used": False,
        "independent_SEA_RAO_cartesian_product_used": False,
        "finite_RAO_grid_used": False,
        "independent_tuner_schedule_used": False,
        "retired_P2_graph_used": False,
        "selected_four_S_word_used": False,
        "P3_promoted": False,
        "next_obligation": (
            "machine-execute the already-compact SEA3 theorem domain through a hard phase-continuous "
            "x^s shaping-state/excitation or equivalent hard-window constraint, then generate the joint "
            "translational/rotational response from that same history over all 601 samples"
        ),
    }


def validate_status(d: dict[str, Any]) -> list[str]:
    f: list[str] = []
    if d.get("schema") != SCHEMA or d.get("qualification") != QUALIFICATION:
        f.append("schema/qualification mismatch")
    if d.get("canonical_source") != CANONICAL_SOURCE:
        f.append("canonical source mismatch")
    for key in (
        "SEA3_parameter_domain_compact",
        "compact_transition_relation_is_theorem_domain",
        "compactness_is_not_an_open_obligation",
        "continuum_RAO_set_theorem_retained",
        "continuum_RAO_set_theorem_is_not_finite_window_generator",
    ):
        if d.get(key) is not True:
            f.append(f"{key} is not true")
    rc = d.get("R_lambda_certificate", {})
    for key in (
        "machine_readable_R_lambda_closed",
        "conservative_outer_relation_used",
        "actual_rate_bounded_R_lambda_subset_Rhat",
        "coupled_partition_energy_retained",
        "coupled_peak_steepness_retained",
    ):
        if rc.get(key) is not True:
            f.append(f"R_lambda certificate lost {key}")
    for key in ("rate_constants_fitted_or_invented", "fixed_lambda_word_used"):
        if rc.get(key) is not False:
            f.append(f"R_lambda certificate reintroduced {key}")
    contract = d.get("executor_payload_contract", {})
    if contract.get("raw_gyro_and_corrected_rate_are_distinct_coordinates") is not True:
        f.append("executor payload collapsed raw gyro and corrected body rate")
    if contract.get("payloads_must_repeat_same_transition_witness_id") is not True:
        f.append("executor payload lost transition-witness identity")
    if contract.get("physical_payload_must_repeat_same_joint_response_witness_id") is not True:
        f.append("physical payload lost joint-response identity")
    if contract.get("precomputed_aw_covariance_floor_increment_allowed") is not False:
        f.append("executor payload permits precomputed covariance-floor increment")
    ingredients = d.get("executable_provider_ingredients", {})
    expected = {
        "machine_readable_R_lambda_closed": MACHINE_READABLE_R_LAMBDA_CLOSED,
        "hard_shaping_state_or_excitation_bound_closed": HARD_SHAPING_STATE_OR_EXCITATION_BOUND_CLOSED,
        "joint_translational_rotational_shaping_closed": JOINT_TRANSLATIONAL_ROTATIONAL_SHAPING_CLOSED,
    }
    if ingredients != expected:
        f.append("executable provider ingredient gates drifted")
    if d.get("provider_implementation_closed") is not PROVIDER_IMPLEMENTATION_CLOSED:
        f.append("provider gate mismatch")
    for key in (
        "finite_window_realization_certificate_closed",
        "source_reachable_event_family_materialized",
        "P3_promoted",
    ):
        if d.get(key) is not False:
            f.append(f"{key} must remain false before SEA0 finite-window closure")
    for key in _FORBIDDEN_TRUE_FLAGS:
        if d.get(key) is not False:
            f.append(f"status reintroduced forbidden shortcut {key}")
    return list(dict.fromkeys(f))


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--domain", type=Path, default=DEFAULT_DOMAIN)
    ap.add_argument("--output", type=Path, required=True)
    args = ap.parse_args()
    d = build(args.domain)
    failures = validate_status(d)
    d["validation_pass"] = not failures
    d["validation_failures"] = failures
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json.dumps(d, indent=2, sort_keys=True), encoding="utf-8")
    print(json.dumps({
        "SEA3_compact": d["SEA3_parameter_domain_compact"],
        "compactness_open": not d["compactness_is_not_an_open_obligation"],
        "executable_provider_ingredients": d["executable_provider_ingredients"],
        "provider_closed": d["provider_implementation_closed"],
        "family_materialized": d["source_reachable_event_family_materialized"],
        "next_obligation": d["next_obligation"],
        "failures": failures,
    }, indent=2, sort_keys=True))
    return 0 if not failures else 2


if __name__ == "__main__":
    raise SystemExit(main())