#!/usr/bin/env python3
"""Evaluate the retained reduced MSE objective on pinned vessel CG spectra."""
from pathlib import Path
import csv
import hashlib
import json
import math
import statistics
import numpy as np
trapezoid = np.trapezoid if hasattr(np, "trapezoid") else np.trapz
from scipy.optimize import minimize_scalar
from ou2_dual_mse_coefficients import vessel_spectrum
from model_mismatch_ablation import RECORDS
from sim_dataset import input_provenance

ROOT=Path(__file__).resolve().parents[1]
QEFF=2 * 0.0148**2 / 200  # deployed OU-III strong-observation reduction


def main():
    out=ROOT/'reports/results/ou3_reduced_mse';out.mkdir(exist_ok=True,parents=True)
    data=ROOT/'plots/kalman_ou_ii';points=ROOT/'reports/results/startup_ablation/startup_runs.csv'
    with points.open() as f: raw=list(csv.DictReader(f))
    provenance=input_provenance(data/r.filename for r in RECORDS)
    rows=[]
    for record in RECORDS:
        rr=[r for r in raw if r['family']=='OU-III' and r['arm']=='deployed' and r['input']==record.filename]
        assert len(rr)==5
        tau=statistics.fmean(float(r['tau_applied_s']) for r in rr)
        sigma=statistics.fmean(float(r['sigma_applied_mps2']) for r in rr)/.9
        w,psd=vessel_spectrum(data/record.filename)
        def wave(omega, w=w, psd=psd):
            x=w/omega
            return trapezoid(((1+4*x*x)/(1+x**6))*psd,w)
        def optimum(q, wave=wave):
            result=minimize_scalar(lambda logw: 1.5*q/math.exp(3*logw)+wave(math.exp(logw)),
                                  bounds=(math.log(1e-5),math.log(2.0)),method='bounded',
                                  options={'xatol':1e-12})
            if not result.success:raise RuntimeError(result.message)
            return math.exp(result.x),float(result.fun)
        omega,cost=optimum(QEFF)
        eps=.001
        sensitivity=(math.log(optimum(QEFF*math.exp(eps))[0])-math.log(optimum(QEFF*math.exp(-eps))[0]))/(2*eps)
        m4=float(trapezoid(psd/w**4,w))
        cj=math.sqrt(QEFF)/omega**3 / (QEFF**(1/14)*sigma**(6/7)*tau**(24/7))
        rows.append(dict(spectrum=record.spectrum,hs_m=record.hs_m,input=record.filename,
                         tau_s=tau,sigma_a_band_mps2=sigma,omega_rad_s=omega,kappa=omega*tau,
                         local_amplitude_exponent=6*sensitivity,
                         fixed_shape_period_exponent=2.5+3*sensitivity,
                         wave_fraction=float(wave(omega)/cost),coefficient_diagnostic=cj,
                         negative_fourth_moment=m4,
                         asymptotic_moment_relative_error=9*QEFF/(32*omega**7*m4)-1))
    with (out/'reduced_mse.csv').open('w',newline='') as f:
        writer=csv.DictWriter(f,fieldnames=list(rows[0]));writer.writeheader();writer.writerows(rows)
    text=r'''% Generated by tools/ou3_reduced_mse_study.py.
\begin{table}[t]\centering
\caption{Reduced-MSE minimization on v1.2.1 CG-heave periodograms.
The period exponent is conditional on a fixed-shape dilation of each spectrum.}
\label{tab:adapt-exact-mse-exponents}\footnotesize
\begin{tabular}{@{}llrrrr@{}}\toprule
Spectrum & $H_s$ [m] & $\kappa_\star$ & $p_a$ & $p_\tau$ & $J_{\rm wave}/J$ \\
\midrule
'''
    for r in rows:
        text+=r['spectrum'].replace('PM-Stokes','PM--Stokes')+f" & {r['hs_m']:.2f} & "+' & '.join(f'{r[k]:.3f}' for k in ['kappa','local_amplitude_exponent','fixed_shape_period_exponent','wave_fraction'])+r' \\'+'\n'
    text+=r'\bottomrule\end{tabular}\end{table}'+'\n'
    cs=[r['coefficient_diagnostic'] for r in rows]
    text+=rf'''Using the current five-draw operating points, the diagnostic equivalent
coefficient ranges from \num{{{min(cs):.4f}}} to \num{{{max(cs):.4f}}}.
The deployed $C_J=0.0538$ is retained. A hull with fixed resonance periods
is not a period-scaled family; these local fixed-shape exponents cannot
be interpreted as the derivative across the actual RAO sea-state family.
'''
    (out/'reduced_mse.tex').write_text(text)
    (ROOT/'doc/kalman_ou_iii/w3d-reduced-mse-results-generated.tex-part').write_text(text)
    (out/'manifest.json').write_text(json.dumps(dict(simulation_provenance=provenance,
        q_eff_m2ps3=QEFF,operating_points_sha256=hashlib.sha256(points.read_bytes()).hexdigest(),
        producer_sha256=hashlib.sha256(Path(__file__).read_bytes()).hexdigest(),
        scope='finite-periodogram reduced-model diagnostic; no filter retuning or proof promotion',
        files={p.name:hashlib.sha256(p.read_bytes()).hexdigest() for p in out.iterdir() if p.suffix in ('.csv','.tex')}),indent=2)+'\n')


if __name__=='__main__':main()
