#!/usr/bin/env python3
"""Falsification probe for a source-varying finite S-update gap theorem.

The shipping wrapper changes the S=0 pseudo-update period whenever a pending OU
tune is committed.  Kalman3D_Wave_OU_III then executes

    elapsed = fmod(elapsed, new_period)

before the current sample's pseudo-update test.  A proof that replaces the
actual timer by ``gap <= max(period)+h`` is therefore valid only if the P2 source
language prevents repeated period changes from discarding timer progress.

This producer asks a narrower question.  It finds a high-tau P2 source cell with
an exact 13-sample self edge and checks whether two binary32 shipping periods in
that same cell can form a repeatable no-firing cycle.  The constructed cycle is

    H, H, L, H, L, H, ...

at consecutive 13-sample stage boundaries.  H is the cadence generated by
``tau=11 s``.  L is chosen to equal the binary32 timer value accumulated during
26 samples at H.  Thus the L commit maps that timer value to zero by fmod; one
13-sample L segment followed by one H segment returns to the same timer value.

Important: a positive result is a counterexample in the *current P2 quotient
language*.  It does not claim the continuous tuner can realize the two interior
tau values on every self edge.  The quotient forgets that within-cell relation,
so downstream certificates consuming the quotient must either carry a timer /
within-cell refinement or avoid assuming a finite firing gap that the quotient
does not prove.
"""
from __future__ import annotations

import argparse
import json
import math
import struct
from pathlib import Path

import ou3_p2_correlation_path_memory as CORR
import ou3_source_reachable_matrix_p3 as BASE

REPO = Path(__file__).resolve().parents[1]
DEFAULT_DOMAIN = REPO / "tools" / "ou3_proof_operating_domain.json"
SCHEMA = 1
TARGET_SAMPLES = 635
GAP = 13
TAU_HIGH = 11.0


def _f32(x: float) -> float:
    return struct.unpack("!f", struct.pack("!f", float(x)))[0]


def _set_period(elapsed: float, period: float) -> float:
    y = _f32(math.fmod(_f32(elapsed), _f32(period)))
    if not (math.isfinite(y) and 0.0 <= y < period):
        raise RuntimeError("shipping fmod timer state left [0,period)")
    return y


def _due(dt: float, period: float, elapsed: float) -> tuple[bool, float]:
    """Binary32 transcription of periodic_update_due for float MEKF."""
    dt, period, elapsed = _f32(dt), _f32(period), _f32(elapsed)
    if not (dt > 0.0 and period > 0.0 and math.isfinite(dt) and math.isfinite(period)):
        return False, elapsed
    total = _f32(elapsed + dt)
    eps = _f32(2.0 ** -23)
    tol = _f32(_f32(16.0 * eps) * _f32(max(1.0, period)))
    if _f32(total + tol) < period:
        return False, total
    y = _f32(math.fmod(total, period)) if total >= period else _f32(0.0)
    if not (math.isfinite(y) and 0.0 <= y < period):
        y = _f32(0.0)
    return True, y


def _accumulate_no_fire(elapsed: float, period: float, h: float, samples: int):
    e = _f32(elapsed)
    for k in range(int(samples)):
        fire, e = _due(h, period, e)
        if fire:
            return False, e, k + 1
    return True, e, None


def _period_from_tau(tau: float, ratio: float, pmin: float, pmax: float) -> float:
    requested = _f32(_f32(ratio) * _f32(tau))
    return _f32(min(max(requested, _f32(pmin)), _f32(pmax)))


def _find_high_tau_self_node(rt: dict) -> int:
    gi = rt["gaps"].index(GAP)
    candidates = []
    for s, node in enumerate(rt["nodes"]):
        ti = int(node.get("tau_index", s // 80))
        if ti != 9:
            continue
        if s in rt["labelled_successors"][s][gi]:
            candidates.append(s)
    if not candidates:
        raise RuntimeError("no high-tau exact gap-13 self edge in P2 quotient")
    return min(candidates)


def _cycle_periods(h: float, ratio: float, pmin: float, pmax: float):
    high = _period_from_tau(TAU_HIGH, ratio, pmin, pmax)
    ok, elapsed, first = _accumulate_no_fire(0.0, high, h, 2 * GAP)
    if not ok:
        raise RuntimeError(f"high period fired before cycle reset at sample {first}")
    low = _f32(elapsed)
    tau_low = _f32(low / _f32(ratio))
    if _period_from_tau(tau_low, ratio, pmin, pmax) != low:
        raise RuntimeError("could not realize reset period through shipping tau->period float map")
    return high, low, _f32(TAU_HIGH), tau_low


def _simulate_word(h: float, high: float, low: float):
    elapsed = _f32(0.0)
    samples = 0
    fires = []
    boundaries = []
    segment = 0
    while samples < TARGET_SAMPLES:
        if segment < 2:
            period = high
            tag = "H"
        else:
            period = low if segment % 2 == 0 else high
            tag = "L" if segment % 2 == 0 else "H"
        before = elapsed
        elapsed = _set_period(elapsed, period)
        used = min(GAP, TARGET_SAMPLES - samples)
        start_elapsed = elapsed
        for _ in range(used):
            fire, elapsed = _due(h, period, elapsed)
            samples += 1
            if fire:
                fires.append(samples)
        boundaries.append({
            "segment": segment,
            "period_tag": tag,
            "period_s": period,
            "elapsed_before_setter_s": before,
            "elapsed_after_fmod_s": start_elapsed,
            "samples": used,
            "elapsed_after_segment_s": elapsed,
        })
        segment += 1
    return fires, boundaries, elapsed


def build(domain_path: Path = DEFAULT_DOMAIN) -> dict:
    path = Path(domain_path).resolve()
    rt = CORR.runtime(path)
    sched = BASE.source_schedule()
    h = _f32(rt["clock"]["dt_binary32_s"])
    ratio = _f32(sched["pseudo_ratio"])
    pmin = _f32(sched["pseudo_min_s"])
    pmax = _f32(sched["pseudo_max_s"])
    source = _find_high_tau_self_node(rt)
    node = rt["nodes"][source]
    high, low, tau_high, tau_low = _cycle_periods(h, ratio, pmin, pmax)

    tau_box = tuple(map(float, node["tau_s"]))
    period_box = tuple(map(float, node["pseudo_update_period_s"]))
    values_inside_one_source_cell = (
        tau_box[0] <= tau_low <= tau_box[1]
        and tau_box[0] <= tau_high <= tau_box[1]
        and period_box[0] <= low <= period_box[1]
        and period_box[0] <= high <= period_box[1]
    )
    fires, boundaries, endpoint = _simulate_word(h, high, low)

    # Verify the two-segment reset cycle itself, independent of the 635-sample
    # truncation.  `low` is the actual binary32 timer reached by 26 repeated
    # additions under H; using 26*h here would be a different float operation.
    e0 = _set_period(low, low)
    ok1, e1, _ = _accumulate_no_fire(e0, low, h, GAP)
    e1 = _set_period(e1, high)
    ok2, e2, _ = _accumulate_no_fire(e1, high, h, GAP)
    repeatable = bool(ok1 and ok2 and e0 == 0.0 and e2 == low)

    return {
        "schema": SCHEMA,
        "qualification": "OU3_P3_P2_QUOTIENT_PSEUDO_SCHEDULER_STARVATION_WITNESS",
        "diagnostic_only": True,
        "trajectory_replay_used": False,
        "filter_changed": False,
        "declared_domain_changed": False,
        "P2_correlation_interface_consumed": True,
        "P2_correlation_interface_version": CORR.INTERFACE_VERSION,
        "source_node": source,
        "source_tau_index": int(node.get("tau_index", source // 80)),
        "exact_gap_samples": GAP,
        "exact_gap_self_edge": source in CORR.successors(source, GAP, rt),
        "dt_binary32_s": h,
        "source_tau_cell_s": list(tau_box),
        "source_pseudo_period_cell_s": list(period_box),
        "tau_high_binary32_s": tau_high,
        "tau_low_binary32_s": tau_low,
        "period_high_binary32_s": high,
        "period_low_binary32_s": low,
        "both_periods_and_taus_inside_same_P2_source_cell": values_inside_one_source_cell,
        "shipping_tau_to_period_map_reproduces_low_period_exactly": _period_from_tau(tau_low, ratio, pmin, pmax) == low,
        "shipping_tau_to_period_map_reproduces_high_period_exactly": _period_from_tau(tau_high, ratio, pmin, pmax) == high,
        "shipping_fmod_and_due_binary32_transcribed": True,
        "repeatable_two_segment_no_fire_cycle": repeatable,
        "target_samples": TARGET_SAMPLES,
        "pseudo_firings_in_target_word": len(fires),
        "pseudo_firing_sample_indices": fires,
        "endpoint_elapsed_s": endpoint,
        "boundary_trace": boundaries,
        "finite_gap_theorem_from_period_max_alone": False if repeatable and not fires else None,
        "deployed_filter_starvation_claimed": False,
        "proof_language_starvation_witness": bool(repeatable and not fires and values_inside_one_source_cell),
        "P3_PROMOTED": False,
        "P4_PROMOTED": False,
        "P5_PROMOTED": False,
        "classification": (
            "CURRENT_P2_QUOTIENT_ADMITS_635_SAMPLE_NO_S_FIRING_WORD"
            if repeatable and not fires and values_inside_one_source_cell
            else "NO_STARVATION_WITNESS_FOUND"
        ),
        "next_obligation": (
            "refine the P3 source/timer language so within-cell tau changes and pseudo elapsed are correlated, "
            "or derive a covariance upper that does not assume a finite S-firing gap from cadence_max alone"
        ),
        "failures": [],
    }


def validate(d: dict) -> list[str]:
    f = list(d.get("failures", []))
    if d.get("schema") != SCHEMA or d.get("qualification") != "OU3_P3_P2_QUOTIENT_PSEUDO_SCHEDULER_STARVATION_WITNESS":
        f.append("schema/qualification mismatch")
    for key in (
        "diagnostic_only", "P2_correlation_interface_consumed", "exact_gap_self_edge",
        "both_periods_and_taus_inside_same_P2_source_cell",
        "shipping_tau_to_period_map_reproduces_low_period_exactly",
        "shipping_tau_to_period_map_reproduces_high_period_exactly",
        "shipping_fmod_and_due_binary32_transcribed", "repeatable_two_segment_no_fire_cycle",
        "proof_language_starvation_witness",
    ):
        if d.get(key) is not True:
            f.append(f"{key} is not true")
    for key in (
        "trajectory_replay_used", "filter_changed", "declared_domain_changed",
        "deployed_filter_starvation_claimed", "P3_PROMOTED", "P4_PROMOTED", "P5_PROMOTED",
    ):
        if d.get(key) is not False:
            f.append(f"{key} is not false")
    if d.get("P2_correlation_interface_version") != CORR.INTERFACE_VERSION:
        f.append("lost P2 V1 binding")
    if int(d.get("target_samples", 0)) != TARGET_SAMPLES:
        f.append("target word changed")
    if int(d.get("pseudo_firings_in_target_word", -1)) != 0:
        f.append("constructed word contains an S firing")
    if d.get("finite_gap_theorem_from_period_max_alone") is not False:
        f.append("finite-gap falsification not recorded")
    return list(dict.fromkeys(f))


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--domain", type=Path, default=DEFAULT_DOMAIN)
    ap.add_argument("--output", type=Path, required=True)
    a = ap.parse_args()
    d = build(a.domain)
    vf = validate(d)
    d["validation_pass"] = not vf
    d["validation_failures"] = vf
    a.output.parent.mkdir(parents=True, exist_ok=True)
    a.output.write_text(json.dumps(d, indent=2, sort_keys=True), encoding="utf-8")
    print(json.dumps({
        "classification": d["classification"],
        "source_node": d["source_node"],
        "tau_cell_s": d["source_tau_cell_s"],
        "period_cell_s": d["source_pseudo_period_cell_s"],
        "tau_low_s": d["tau_low_binary32_s"],
        "tau_high_s": d["tau_high_binary32_s"],
        "period_low_s": d["period_low_binary32_s"],
        "period_high_s": d["period_high_binary32_s"],
        "target_samples": d["target_samples"],
        "pseudo_firings": d["pseudo_firings_in_target_word"],
        "repeatable_cycle": d["repeatable_two_segment_no_fire_cycle"],
        "validation_failures": vf,
        "next": d["next_obligation"],
    }, indent=2, sort_keys=True))
    return 0 if not vf else 2


if __name__ == "__main__":
    raise SystemExit(main())
