#!/usr/bin/env python3
"""Source-complete stage/phase full-matrix translation P3 candidate.

This is the first numerical P3 consumer that uses the frozen
``OU3_P2_CORRELATED_STAGE_TRANSFER_V1`` interface over the complete source
history instead of the flat 800-node ancestor hull.

Two monotonicity reductions keep the proof finite without discarding source
semantics:

1. At every certified stage boundary, selected process covariance is at least
   the covariance generated by the immediately preceding complete V1 segment
   starting from zero.  Earlier covariance is positive semidefinite and the
   prediction/measurement Riccati map is order preserving.  Taking the worst
   certified one-segment eigenvalue over all 800 source cells and 13..26 gaps
   therefore gives one common boundary lower ``rho_b I`` valid for every legal
   source history.

2. The older history is needed only for the finite-memory covariance ceiling.
   ``ou3_p3_p2_v1_history_frontier`` enumerates the exact gap-labelled V1
   history family at the four monotone same-history sufficient statistics and
   Pareto-prunes only continuation-equivalent labels.  Each label is converted
   to a covariance upper first; only then are those covariance results enveloped
   for one current source endpoint.

From a boundary lower ``rho_b I`` we propagate the full 4x4 interval covariance
through 0..25 samples of the current staged source node in the fixed physical
scaling z=[v/h,p/h^2,S/h^3,a_w].  This covers every sample phase because the
certified next-stage gap is in 13..26 samples; phase 26 is the next boundary.

The resulting comparison is already post-measurement for the translation block:
we condition on accepted accelerometer and S=0 packets at every sample, which is
stronger than every shipping branch.  Magnetometer has no translation Jacobian
on the declared zero-lever-arm branch.

This file certifies only the translation part of canonical P3.  It deliberately
does not set the canonical P3 flag; H/A attitude/bias blocks must still be joined
without changing the frozen 1e-18 gate.
"""
from __future__ import annotations

import argparse
import functools
import json
import math
from pathlib import Path

from ou3_interval import Interval, symmetric_positive_definite_ldlt
import ou3_p2_correlation_path_memory as CORR
import ou3_p3_correlated_translation_segment as SEG
import ou3_p3_frozen_full_matrix_translation as FROZEN
import ou3_p3_p2_v1_history_frontier as HIST
import ou3_source_reachable_matrix_p3 as BASE

REPO = Path(__file__).resolve().parents[1]
DEFAULT_DOMAIN = REPO / "tools" / "ou3_proof_operating_domain.json"
SCHEMA = 1
PHASES = tuple(range(26))


def I(x: float) -> Interval:
    return Interval.outward_bounds(float(x), float(x))


def _identity_floor(rho: float):
    if not (math.isfinite(rho) and rho > 0.0):
        raise ValueError("strict positive boundary covariance floor required")
    return [
        [I(rho if i == j else 0.0) for j in range(4)]
        for i in range(4)
    ]


def _physical_gate_matrix(Pz, h: float, upper: list[float], delta: float):
    # z=[v/h,p/h^2,S/h^3,a], so physical translation covariance is D Pz D'.
    d = [h, h * h, h * h * h, 1.0]
    A = [
        [I(d[i]) * Pz[i][j] * I(d[j]) for j in range(4)]
        for i in range(4)
    ]
    for i in range(4):
        A[i][i] = A[i][i] - I(delta) * I(float(upper[i]))
    return FROZEN._sym(A)


def _certified_delta(Pz, h: float, upper: list[float]) -> float:
    if len(upper) != 4 or any(not (math.isfinite(float(x)) and float(x) > 0.0) for x in upper):
        raise ValueError("positive finite translation covariance upper required")
    M = _physical_gate_matrix(Pz, h, upper, 0.0)
    if not symmetric_positive_definite_ldlt(M)[0]:
        return 0.0
    hi = min(
        max(0.0, (I([h, h*h, h*h*h, 1.0][i]).square() * Pz[i][i]).lo / float(upper[i]))
        for i in range(4)
    )
    if not (math.isfinite(hi) and hi > 0.0):
        return 0.0
    lo = 0.0
    for _ in range(52):
        mid = 0.5 * (lo + hi)
        if symmetric_positive_definite_ldlt(_physical_gate_matrix(Pz, h, upper, mid))[0]:
            lo = mid
        else:
            hi = mid
    return BASE.down(lo)


@functools.lru_cache(maxsize=4)
def common_boundary_floor(domain_path: Path = DEFAULT_DOMAIN) -> dict:
    """Worst one-complete-segment full-matrix floor over the frozen V1 alphabet."""
    path = Path(domain_path).resolve()
    rt = CORR.runtime(path)
    zero = FROZEN._mat_zero()
    worst = math.inf
    limiting = None
    checked = 0
    for s in range(len(rt["nodes"])):
        for gap in rt["gaps"]:
            # Every (s,g) has at least one exact labelled successor; the P2 V1
            # validator rejects dead kernels.  Starting from zero discards all
            # older process covariance and is therefore conservative.
            images = SEG.segment_images(zero, s, int(gap), rt, path)
            local = math.inf
            for row in images:
                rho = FROZEN.certified_rho(row["posterior"])
                if not rho > 0.0:
                    raise RuntimeError(
                        f"one-complete-segment selected covariance lost strict SPD at source {s}, gap {gap}"
                    )
                local = min(local, rho)
            checked += 1
            if local < worst:
                worst = local
                limiting = {
                    "source_node": s,
                    "gap_samples": int(gap),
                    "rho_z_identity_lower": local,
                }
    if not (math.isfinite(worst) and worst > 0.0 and limiting is not None):
        raise RuntimeError("failed to establish common one-segment boundary floor")
    return {
        "rho_z_identity_lower": BASE.down(worst),
        "limiting_segment": limiting,
        "source_gap_kernels_checked": checked,
        "all_800_sources_checked": checked == 800 * 14,
        "older_process_covariance_discarded": True,
        "Riccati_order_monotonicity_used": True,
    }


@functools.lru_cache(maxsize=8192)
def _phase_images_cached(source_node: int, phase_samples: int,
                         rho_key: float, domain_path: Path = DEFAULT_DOMAIN):
    path = Path(domain_path).resolve()
    rt = CORR.runtime(path)
    t = int(source_node)
    r = int(phase_samples)
    h = float(rt["clock"]["dt_binary32_s"])
    P0 = _identity_floor(float(rho_key))
    if r == 0:
        return (P0,)
    node = rt["nodes"][t]
    return tuple(
        SEG.propagate_subcell(P0, node, r, x, h)
        for x in SEG._node_x_subcells(node, h, SEG.X_SUBCELLS)
    )


def phase_row(source_node: int, phase_samples: int, fr: dict, boundary: dict,
              upper_row: dict | None = None) -> dict:
    t = int(source_node)
    r = int(phase_samples)
    if upper_row is None:
        upper_row = HIST.endpoint_phase_upper(t, 0 if r == 0 else 1, fr)
    upper = list(map(float, upper_row["Sigma_translation_diagonal_upper_envelope"]))
    rho = float(boundary["rho_z_identity_lower"])
    path = Path(fr["path"]).resolve()
    h = float(fr["rt"]["clock"]["dt_binary32_s"])
    images = _phase_images_cached(t, r, rho, path)
    deltas = [_certified_delta(P, h, upper) for P in images]
    delta = min(deltas) if deltas else 0.0
    return {
        "source_node": t,
        "phase_samples_after_stage_boundary": r,
        "phase_time_s": BASE.down(r * h),
        "x_subcells": len(images),
        "same_history_covariance_labels": upper_row["phase_pareto_labels"],
        "Sigma_translation_diagonal_upper_envelope": upper,
        "translation_relative_Riccati_injection_margin_lower": delta,
        "useful_gate": BASE.MIN_USEFUL_DELTA,
        "useful": delta >= BASE.MIN_USEFUL_DELTA,
        "same_history_upper_evaluated_before_endpoint_envelope": True,
    }


def build(domain_path: Path = DEFAULT_DOMAIN) -> dict:
    path = Path(domain_path).resolve()
    domain = json.loads(path.read_text(encoding="utf-8"))
    if domain.get("trajectory_fit") is not False:
        raise RuntimeError("source-complete matrix P3 translation candidate must not be trajectory fitted")
    runtime = domain.get("configured_runtime", {})
    if runtime.get("imu_lever_arm_enabled") is not False:
        raise RuntimeError("translation P3 requires declared zero-lever-arm branch")
    if runtime.get("accelerometer_vibration_guard_proof_branch") != "dormant_transparent":
        raise RuntimeError("translation P3 requires dormant transparent vibration guard")
    if float(BASE.MIN_USEFUL_DELTA) != 1.0e-18:
        raise RuntimeError("canonical useful gate changed")

    fr = HIST.frontier_runtime(path)
    boundary = common_boundary_floor(path)
    rows = []
    worst = None
    pass_count = 0
    # Same-history covariance path maxima change when the current source has
    # appeared at least once, but not with the number of current-source samples.
    # Evaluate only boundary (r=0) and positive-phase (r>0) envelopes per node.
    upper_cache = {
        int(t): {
            0: HIST.endpoint_phase_upper(int(t), 0, fr),
            1: HIST.endpoint_phase_upper(int(t), 1, fr),
        }
        for t in fr["endpoint_nodes"]
    }
    for t in fr["endpoint_nodes"]:
        for r in PHASES:
            row = phase_row(int(t), int(r), fr, boundary, upper_cache[int(t)][0 if r == 0 else 1])
            rows.append(row)
            pass_count += int(row["useful"])
            if worst is None or row["translation_relative_Riccati_injection_margin_lower"] < worst["translation_relative_Riccati_injection_margin_lower"]:
                worst = row

    if worst is None:
        raise RuntimeError("source-complete translation P3 emitted no endpoint phases")
    all_useful = pass_count == len(rows)
    return {
        "schema": SCHEMA,
        "qualification": "OU3_P3_P2_V1_SOURCE_COMPLETE_STAGE_PHASE_TRANSLATION_MATRIX",
        "source_only": True,
        "trajectory_replay_used": False,
        "filter_changed": False,
        "declared_domain_changed": False,
        "zero_lever_arm_branch": True,
        "dormant_transparent_vibration_guard_branch": True,
        "P2_correlation_interface_consumed": True,
        "P2_correlation_interface_version": CORR.INTERFACE_VERSION,
        "full_word_history_sufficient_quotient_consumed": True,
        "flat_800_node_ancestor_hull_used": False,
        "independent_cartesian_tau_sigma_R_S_extrema_used": False,
        "process_covariance_measurement_bounds_same_source_history": True,
        "same_history_covariance_evaluated_before_uniform_endpoint_envelope": True,
        "full_4x4_translation_matrix_retained_inside_source_segments": True,
        "fixed_physical_scaling": "z=[v/h,p/h^2,S/h^3,a_w]",
        "sigma_dependent_metric_switching_used": False,
        "one_complete_segment_common_boundary_floor_used": True,
        "older_process_covariance_discarded_at_each_boundary": True,
        "Riccati_order_monotonicity_used": True,
        "all_current_sample_phases_covered": True,
        "phase_samples": list(PHASES),
        "phase_26_is_next_stage_boundary": True,
        "strongest_accelerometer_and_S_measurements_applied_every_sample": True,
        "magnetometer_translation_jacobian_zero_on_declared_branch": True,
        "useful_gate": BASE.MIN_USEFUL_DELTA,
        "boundary_floor": boundary,
        "full_word_frontier_digest_sha256": fr["frontier_digest_sha256"],
        "endpoint_phase_rows": rows,
        "endpoint_phase_count": len(rows),
        "endpoint_phase_useful_count": pass_count,
        "worst_translation_endpoint_phase": worst,
        "worst_translation_margin_lower": float(worst["translation_relative_Riccati_injection_margin_lower"]),
        "P3_TRANSLATION_CERTIFICATE_ESTABLISHED": all_useful,
        "P3_CANONICAL_PROMOTED": False,
        "P4_PROMOTED": False,
        "next_obligation": (
            "join this source-complete post-measurement translation margin with the retained "
            "source-generated H/A attitude, gyro-bias and accelerometer-bias floors; canonical "
            "P3 remains frozen and may pass only when the worst full H/A margin is >=1e-18"
        ) if all_useful else (
            "retain the same P2 V1/full-matrix theorem interface and refine only the common "
            "boundary lower or endpoint covariance envelope; do not relax the 1e-18 gate"
        ),
        "failures": [],
    }


def validate(d: dict) -> list[str]:
    f = list(d.get("failures", []))
    if d.get("schema") != SCHEMA:
        f.append("schema mismatch")
    if d.get("qualification") != "OU3_P3_P2_V1_SOURCE_COMPLETE_STAGE_PHASE_TRANSLATION_MATRIX":
        f.append("wrong qualification")
    for key in (
        "source_only", "zero_lever_arm_branch", "dormant_transparent_vibration_guard_branch",
        "P2_correlation_interface_consumed", "full_word_history_sufficient_quotient_consumed",
        "process_covariance_measurement_bounds_same_source_history",
        "same_history_covariance_evaluated_before_uniform_endpoint_envelope",
        "full_4x4_translation_matrix_retained_inside_source_segments",
        "one_complete_segment_common_boundary_floor_used",
        "older_process_covariance_discarded_at_each_boundary", "Riccati_order_monotonicity_used",
        "all_current_sample_phases_covered", "phase_26_is_next_stage_boundary",
        "strongest_accelerometer_and_S_measurements_applied_every_sample",
        "magnetometer_translation_jacobian_zero_on_declared_branch",
    ):
        if d.get(key) is not True:
            f.append(f"{key} is not true")
    for key in (
        "trajectory_replay_used", "filter_changed", "declared_domain_changed",
        "flat_800_node_ancestor_hull_used", "independent_cartesian_tau_sigma_R_S_extrema_used",
        "sigma_dependent_metric_switching_used", "P3_CANONICAL_PROMOTED", "P4_PROMOTED",
    ):
        if d.get(key) is not False:
            f.append(f"{key} is not false")
    if d.get("P2_correlation_interface_version") != CORR.INTERFACE_VERSION:
        f.append("translation P3 lost frozen P2 V1 binding")
    if float(d.get("useful_gate", math.nan)) != 1.0e-18:
        f.append("translation P3 useful gate changed")
    if d.get("phase_samples") != list(range(26)):
        f.append("translation P3 does not cover exact 0..25 source phases")
    if int(d.get("endpoint_phase_count", 0)) != 800 * 26:
        f.append("translation P3 does not cover all 800 x 26 endpoint/phase classes")
    b = d.get("boundary_floor", {})
    if b.get("all_800_sources_checked") is not True:
        f.append("common boundary floor did not scan all 800x14 source/gap kernels")
    if not float(b.get("rho_z_identity_lower", 0.0)) > 0.0:
        f.append("common boundary floor is not strict")
    worst = float(d.get("worst_translation_margin_lower", math.nan))
    if not (math.isfinite(worst) and worst >= 0.0):
        f.append("invalid worst translation margin")
    established = bool(
        int(d.get("endpoint_phase_useful_count", -1)) == int(d.get("endpoint_phase_count", 0))
        and worst >= BASE.MIN_USEFUL_DELTA
    )
    if d.get("P3_TRANSLATION_CERTIFICATE_ESTABLISHED") is not established:
        f.append("translation promotion flag does not match unchanged useful gate")
    return list(dict.fromkeys(f))


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--domain", type=Path, default=DEFAULT_DOMAIN)
    ap.add_argument("--output", type=Path, required=True)
    args = ap.parse_args()
    d = build(args.domain)
    vf = validate(d)
    d["validation_pass"] = not vf
    d["validation_failures"] = vf
    args.output.parent.mkdir(parents=True, exist_ok=True)
    # Endpoint rows are useful for diagnosing the limiting source/phase, but are
    # kept in one artifact rather than promoted into canonical P3 automatically.
    args.output.write_text(json.dumps(d, indent=2, sort_keys=True), encoding="utf-8")
    print(json.dumps({
        "boundary_floor": d["boundary_floor"],
        "endpoint_phase_count": d["endpoint_phase_count"],
        "endpoint_phase_useful_count": d["endpoint_phase_useful_count"],
        "worst_translation_margin_lower": d["worst_translation_margin_lower"],
        "worst_translation_endpoint_phase": d["worst_translation_endpoint_phase"],
        "translation_established": d["P3_TRANSLATION_CERTIFICATE_ESTABLISHED"],
        "validation_failures": vf,
    }, indent=2, sort_keys=True))
    return 0 if not vf else 2


if __name__ == "__main__":
    raise SystemExit(main())
