#!/usr/bin/env python3
"""Validated algebraic backend for the canonical OU-III SEA3 P3 word.

This module is *not* a reduced P3 route. It implements the exact full-matrix
bookkeeping required by the canonical proof for one already-enclosed source/
event word. The word assembler must supply the actual interval F, Q, H, R and
PSD covariance-floor increments generated by the complete Normal-Live source.

The backend propagates three matrices on the same event sequence:

    P_k = Psi_k P_0 Psi_k^T + Omega_k.

Prediction:

    P-     = F P F^T + Q
    Psi-   = F Psi
    Omega- = F Omega F^T + Q

Joseph measurement correction:

    S  = H P- H^T + R
    K  = P- H^T S^-1
    A  = I - K H
    P+     = A P- A^T + K R K^T
    Psi+   = A Psi-
    Omega+ = A Omega- A^T + K R K^T

A shipping PSD a_w covariance-floor event adds the same embedded Delta to P and
Omega and leaves Psi unchanged.

For M_delta = Omega-delta P and 0<=delta<=1, the exact same recursions imply

    prediction: M' = F M F^T + (1-delta) Q,
    Joseph:      M' = A M A^T + (1-delta) K R K^T,
    PSD floor:   M' = M + (1-delta) Delta.

Hence once a complete source-reachable prefix has established M_delta >= 0,
*every later shipping event preserves the same delta*. This is an algebraic
identity inside the canonical joint object, not permission to omit events that
are needed to establish the initial strict inequality.

The only theorem-level contraction test exposed here is

    Omega_W - delta P_W >= 0,

checked by outward interval LDL^T on the complete H18/A21 matrix. No D_W/L_W
split, one-step process ratio, determinant/trace scalarization, or blockwise
minimum can pass through this backend.
"""
from __future__ import annotations

from dataclasses import dataclass
import math
from pathlib import Path
from typing import Sequence

from ou3_interval import (
    Interval,
    IntervalMatrix,
    matrix_add,
    matrix_identity,
    matrix_mul,
    matrix_point,
    matrix_sub,
    matrix_transpose,
    symmetric_positive_definite_ldlt,
)
from ou3_interval_linear_algebra import (
    matrix_inverse_gauss_jordan,
    matrix_symmetric_hull,
)

REPO = Path(__file__).resolve().parents[1]
MEKF = REPO / "src" / "kalman_ou_iii" / "Kalman3D_Wave_OU_III.h"
USEFUL_GATE = 1.0e-18


def _shape(A: Sequence[Sequence[Interval]]) -> tuple[int, int]:
    rows = len(A)
    cols = len(A[0]) if rows else 0
    if any(len(row) != cols for row in A):
        raise ValueError("ragged interval matrix")
    return rows, cols


def _zero(rows: int, cols: int) -> IntervalMatrix:
    z = Interval.point(0.0)
    return [[z for _ in range(cols)] for _ in range(rows)]


def _scale(A: Sequence[Sequence[Interval]], c: float) -> IntervalMatrix:
    ci = Interval.outward_bounds(float(c), float(c))
    return [[ci * A[i][j] for j in range(len(A[i]))] for i in range(len(A))]


def _contains_zero(A: Sequence[Sequence[Interval]]) -> bool:
    return all(x.lo <= 0.0 <= x.hi for row in A for x in row)


def _copy(A: Sequence[Sequence[Interval]]) -> IntervalMatrix:
    return [[x for x in row] for row in A]


def shipping_source_parity() -> dict[str, bool]:
    """Bind the algebraic event recursions to the retained shipping source."""
    text = MEKF.read_text(encoding="utf-8")
    return {
        "prediction_adds_attitude_process_Q": (
            "Pext.template block<NA,NA>(0,0).noalias() += Q_AA;" in text
        ),
        "prediction_adds_translation_process_Q": (
            "T sum = Q_LL(i,j);" in text
        ),
        "active_bias_exact_GM_process_present": (
            "const T qd_scale = -T(0.5) * tau_b * std::expm1(-T(2) * Ts / tau_b);" in text
            and "P_BB.noalias() += Q_bacc_ * qd_scale;" in text
        ),
        "pending_aw_floor_applied_before_S_due_check": (
            text.find("apply_pending_aw_covariance_inflation_();") >= 0
            and text.find(
                "applyIntegralZeroPseudoMeas();",
                text.find("apply_pending_aw_covariance_inflation_();"),
            ) > text.find("apply_pending_aw_covariance_inflation_();")
        ),
        "aw_floor_is_PSD_addition": (
            "Pext.template block<3,3>(OFF_AW, OFF_AW) += Delta;" in text
        ),
        "accelerometer_uses_full_Joseph_update": (
            "joseph_update3_(K, S_mat, PCt);" in text
        ),
        "S_zero_update_uses_full_Joseph_update": (
            text.count("joseph_update3_(K, S_mat, PCt);") >= 2
        ),
        "magnetometer_covariance_update_is_Joseph_form": (
            "Pext(i,j) += delta;" in text
            and "KSK_ij += Kia * S(a,b) * Kjb;" in text
        ),
    }


def contraction_preservation_identities() -> dict[str, str | bool]:
    return {
        "definition": "M_delta = Omega - delta P",
        "delta_domain": "0 <= delta <= 1",
        "prediction": "M_delta' = F M_delta F^T + (1-delta) Q",
        "Joseph": "M_delta' = A M_delta A^T + (1-delta) K R K^T",
        "PSD_floor": "M_delta' = M_delta + (1-delta) Delta",
        "positive_semidefinite_inputs_preserve_M_delta": True,
        "may_omit_events_needed_to_first_establish_delta": False,
        "is_exact_algebra_inside_joint_P_Psi_Omega_object": True,
    }


@dataclass
class JointWordState:
    P0: IntervalMatrix
    P: IntervalMatrix
    Psi: IntervalMatrix
    Omega: IntervalMatrix
    events: int = 0
    predictions: int = 0
    measurements: int = 0
    floors: int = 0

    @property
    def dimension(self) -> int:
        return len(self.P)


def initialize(P0: Sequence[Sequence[Interval]]) -> JointWordState:
    n, m = _shape(P0)
    if n == 0 or n != m:
        raise ValueError("P0 must be nonempty square")
    P0s = matrix_symmetric_hull(_copy(P0))
    return JointWordState(
        P0=P0s,
        P=_copy(P0s),
        Psi=matrix_identity(n),
        Omega=_zero(n, n),
    )


def decomposition_residual(state: JointWordState) -> IntervalMatrix:
    rhs = matrix_add(
        matrix_mul(matrix_mul(state.Psi, state.P0), matrix_transpose(state.Psi)),
        state.Omega,
    )
    return matrix_sub(state.P, rhs)


def decomposition_identity_enclosed(state: JointWordState) -> bool:
    return _contains_zero(decomposition_residual(state))


def contraction_matrix(
    state: JointWordState,
    delta: float = USEFUL_GATE,
) -> IntervalMatrix:
    if not (math.isfinite(delta) and 0.0 <= delta <= 1.0):
        raise ValueError("delta must be finite in [0,1]")
    return matrix_symmetric_hull(matrix_sub(state.Omega, _scale(state.P, delta)))


def prediction_contraction_image(
    M_before: Sequence[Sequence[Interval]],
    F: Sequence[Sequence[Interval]],
    Q: Sequence[Sequence[Interval]],
    delta: float,
) -> IntervalMatrix:
    if not (math.isfinite(delta) and 0.0 <= delta <= 1.0):
        raise ValueError("delta must be finite in [0,1]")
    Ft = matrix_transpose(F)
    return matrix_symmetric_hull(
        matrix_add(
            matrix_mul(matrix_mul(F, M_before), Ft),
            _scale(Q, 1.0 - delta),
        )
    )


def joseph_contraction_image(
    M_before: Sequence[Sequence[Interval]],
    A: Sequence[Sequence[Interval]],
    K: Sequence[Sequence[Interval]],
    R: Sequence[Sequence[Interval]],
    delta: float,
) -> IntervalMatrix:
    if not (math.isfinite(delta) and 0.0 <= delta <= 1.0):
        raise ValueError("delta must be finite in [0,1]")
    At = matrix_transpose(A)
    KRKt = matrix_mul(matrix_mul(K, R), matrix_transpose(K))
    return matrix_symmetric_hull(
        matrix_add(
            matrix_mul(matrix_mul(A, M_before), At),
            _scale(KRKt, 1.0 - delta),
        )
    )


def floor_contraction_image(
    M_before: Sequence[Sequence[Interval]],
    Delta_full: Sequence[Sequence[Interval]],
    delta: float,
) -> IntervalMatrix:
    if not (math.isfinite(delta) and 0.0 <= delta <= 1.0):
        raise ValueError("delta must be finite in [0,1]")
    return matrix_symmetric_hull(
        matrix_add(M_before, _scale(Delta_full, 1.0 - delta))
    )


def contraction_identity_enclosed(
    actual: Sequence[Sequence[Interval]],
    expected: Sequence[Sequence[Interval]],
) -> bool:
    if _shape(actual) != _shape(expected):
        return False
    return _contains_zero(matrix_sub(actual, expected))


def predict(
    state: JointWordState,
    F: Sequence[Sequence[Interval]],
    Q: Sequence[Sequence[Interval]],
) -> None:
    n = state.dimension
    if _shape(F) != (n, n) or _shape(Q) != (n, n):
        raise ValueError("prediction F/Q dimension mismatch")
    Ft = matrix_transpose(F)
    state.P = matrix_symmetric_hull(
        matrix_add(matrix_mul(matrix_mul(F, state.P), Ft), Q)
    )
    state.Psi = matrix_mul(F, state.Psi)
    state.Omega = matrix_symmetric_hull(
        matrix_add(matrix_mul(matrix_mul(F, state.Omega), Ft), Q)
    )
    state.events += 1
    state.predictions += 1
    if not decomposition_identity_enclosed(state):
        raise RuntimeError("P/Psi/Omega identity lost after prediction")


def joseph_measurement(
    state: JointWordState,
    H: Sequence[Sequence[Interval]],
    R: Sequence[Sequence[Interval]],
) -> dict:
    n = state.dimension
    rows, cols = _shape(H)
    if cols != n or rows == 0 or _shape(R) != (rows, rows):
        raise ValueError("measurement H/R dimension mismatch")

    Ht = matrix_transpose(H)
    PHt = matrix_mul(state.P, Ht)
    S = matrix_symmetric_hull(matrix_add(matrix_mul(H, PHt), R))
    Sinv = matrix_inverse_gauss_jordan(S)
    K = matrix_mul(PHt, Sinv)
    A = matrix_sub(matrix_identity(n), matrix_mul(K, H))
    At = matrix_transpose(A)
    KRKt = matrix_mul(matrix_mul(K, R), matrix_transpose(K))

    state.P = matrix_symmetric_hull(
        matrix_add(matrix_mul(matrix_mul(A, state.P), At), KRKt)
    )
    state.Psi = matrix_mul(A, state.Psi)
    state.Omega = matrix_symmetric_hull(
        matrix_add(matrix_mul(matrix_mul(A, state.Omega), At), KRKt)
    )
    state.events += 1
    state.measurements += 1
    if not decomposition_identity_enclosed(state):
        raise RuntimeError("P/Psi/Omega identity lost after Joseph measurement")
    return {"S": S, "K": K, "A": A}


def add_psd_floor(
    state: JointWordState,
    Delta_full: Sequence[Sequence[Interval]],
) -> None:
    n = state.dimension
    if _shape(Delta_full) != (n, n):
        raise ValueError("floor increment dimension mismatch")
    D = matrix_symmetric_hull(Delta_full)
    state.P = matrix_symmetric_hull(matrix_add(state.P, D))
    state.Omega = matrix_symmetric_hull(matrix_add(state.Omega, D))
    state.events += 1
    state.floors += 1
    if not decomposition_identity_enclosed(state):
        raise RuntimeError("P/Psi/Omega identity lost after covariance-floor event")


def certify_contraction(
    state: JointWordState,
    delta: float = USEFUL_GATE,
) -> dict:
    if not (math.isfinite(delta) and delta > 0.0):
        raise ValueError("theorem contraction delta must be finite positive")
    M = contraction_matrix(state, delta)
    passed, pivots = symmetric_positive_definite_ldlt(M)
    return {
        "dimension": state.dimension,
        "delta": float(delta),
        "Omega_minus_delta_P_ldlt_closed": bool(passed),
        "ldlt_pivots": [x.as_list() for x in pivots],
        "events": state.events,
        "predictions": state.predictions,
        "measurements": state.measurements,
        "floors": state.floors,
        "decomposition_identity_enclosed": decomposition_identity_enclosed(state),
        "pass": bool(passed and decomposition_identity_enclosed(state)),
    }


def _preservation_self_test() -> dict:
    """Check the three M_delta event identities on point matrices."""
    delta = 0.2
    state = initialize(matrix_point([[2.0, 0.1], [0.1, 3.0]]))

    F = matrix_point([[1.0, 0.1], [0.0, 1.0]])
    Q = matrix_point([[0.02, 0.0], [0.0, 0.01]])
    M0 = contraction_matrix(state, delta)
    expected_pred = prediction_contraction_image(M0, F, Q, delta)
    predict(state, F, Q)
    actual_pred = contraction_matrix(state, delta)
    pred_ok = contraction_identity_enclosed(actual_pred, expected_pred)

    H = matrix_point([[1.0, 0.0]])
    R = matrix_point([[0.5]])
    M1 = contraction_matrix(state, delta)
    info = joseph_measurement(state, H, R)
    expected_meas = joseph_contraction_image(
        M1, info["A"], info["K"], R, delta
    )
    actual_meas = contraction_matrix(state, delta)
    meas_ok = contraction_identity_enclosed(actual_meas, expected_meas)

    D = matrix_point([[0.0, 0.0], [0.0, 0.03]])
    M2 = contraction_matrix(state, delta)
    expected_floor = floor_contraction_image(M2, D, delta)
    add_psd_floor(state, D)
    actual_floor = contraction_matrix(state, delta)
    floor_ok = contraction_identity_enclosed(actual_floor, expected_floor)

    return {
        "delta": delta,
        "prediction_identity_enclosed": pred_ok,
        "Joseph_identity_enclosed": meas_ok,
        "PSD_floor_identity_enclosed": floor_ok,
        "all_event_identities_enclosed": pred_ok and meas_ok and floor_ok,
        "preservation_identities": contraction_preservation_identities(),
        "kernel_identity_test_only_not_P3": True,
    }


def _self_test() -> dict:
    """Arithmetic-kernel test only; this is not an OU-III theorem witness."""
    P0 = matrix_point([[2.0, 0.1], [0.1, 3.0]])
    state = initialize(P0)
    F = matrix_point([[1.0, 0.1], [0.0, 1.0]])
    Q = matrix_point([[0.02, 0.0], [0.0, 0.01]])
    predict(state, F, Q)
    H = matrix_point([[1.0, 0.0]])
    R = matrix_point([[0.5]])
    joseph_measurement(state, H, R)
    add_psd_floor(state, matrix_point([[0.0, 0.0], [0.0, 0.03]]))
    cert = certify_contraction(state, USEFUL_GATE)
    cert["shipping_source_parity"] = shipping_source_parity()
    cert["shipping_source_parity_pass"] = all(cert["shipping_source_parity"].values())
    cert["kernel_self_test_only_not_P3"] = True
    cert["contraction_preservation"] = _preservation_self_test()
    return cert


def validate_backend() -> list[str]:
    f: list[str] = []
    parity = shipping_source_parity()
    for name, ok in parity.items():
        if not ok:
            f.append(f"shipping source parity failed: {name}")
    ids = contraction_preservation_identities()
    if ids.get("positive_semidefinite_inputs_preserve_M_delta") is not True:
        f.append("contraction preservation identity missing")
    if ids.get("may_omit_events_needed_to_first_establish_delta") is not False:
        f.append("preservation theorem was incorrectly turned into event omission")
    try:
        test = _self_test()
    except Exception as exc:
        f.append(f"joint algebra self-test failed: {type(exc).__name__}: {exc}")
        return f
    if test.get("decomposition_identity_enclosed") is not True:
        f.append("joint algebra self-test lost covariance decomposition")
    if test.get("Omega_minus_delta_P_ldlt_closed") is not True:
        f.append("joint algebra self-test did not close positive test matrix")
    if test.get("kernel_self_test_only_not_P3") is not True:
        f.append("kernel self-test was misclassified")
    preserve = test.get("contraction_preservation", {})
    if preserve.get("all_event_identities_enclosed") is not True:
        f.append("M_delta preservation self-test failed")
    if preserve.get("kernel_identity_test_only_not_P3") is not True:
        f.append("M_delta identity test was misclassified")
    return list(dict.fromkeys(f))


if __name__ == "__main__":
    failures = validate_backend()
    print({
        "qualification": "OU3_SEA3_JOINT_P_PSI_OMEGA_ALGEBRA_BACKEND",
        "useful_gate": USEFUL_GATE,
        "contraction_preservation_identities": contraction_preservation_identities(),
        "failures": failures,
        "self_test": _self_test() if not failures else None,
        "P3_promoted": False,
    })
    raise SystemExit(0 if not failures else 2)