#!/usr/bin/env python3
"""Source/phase coverage manifest for the OU-III P5 sample-1 q<8 stage.

V14D is intentionally a focused numerical proof for one source-correlated
sample-1 branch.  A PASS for that branch is therefore not a complete P5 word.
Before lifting the signed-Cayley calculation across the remaining source
family, this producer freezes the exact finite source/phase cover generated by
the same startup proof partition used by the first-accelerometer certificates.

The manifest is semantic only: it does not replay trajectories, run V14D, set
N_H_words, or promote P5.  It records which children enter sample 0 with the
S=0 pseudo measurement due and which enter through the not-due identity branch.
The current V14/V14D algebra explicitly requires the due branch, so not-due
children are listed as a separate numerical obligation rather than silently
excluded.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

import ou3_p5_first_accel_rotation_gauge as RG
import ou3_p5_sample1_signed_cayley_q8_v14d as V14D

DEFAULT_DOMAIN = V14D.DEFAULT_DOMAIN
SCHEMA = 1


def _interval(x):
    return [float(x.lo), float(x.hi)]


def build(domain_path: Path = DEFAULT_DOMAIN, *, source_pieces: int = 4) -> dict:
    path = Path(domain_path).resolve()
    domain = json.loads(path.read_text(encoding="utf-8"))
    if domain.get("trajectory_fit") is not False:
        raise RuntimeError("P5 source-phase manifest must not be trajectory fitted")
    if source_pieces < 1:
        raise ValueError("source_pieces must be positive")

    children = RG._source_phase_children(source_pieces)
    rows = []
    due = []
    not_due = []
    for index, (src, phase) in enumerate(children):
        if phase not in ("due", "not_due"):
            raise RuntimeError(f"unexpected sample-0 pseudo phase {phase!r}")
        row = {
            "source_cell_index": index,
            "sample0_pseudo_phase": phase,
            "tau_s": _interval(src["tau_s"]),
            "sigma_aw_mps2": _interval(src["sigma_aw_mps2"]),
            "R_S_filter_std": _interval(src["R_S_filter_std"]),
            "pseudo_period_s": _interval(src["pseudo_period_s"]),
            "dt_s": float(src["dt_s"]),
            "current_V14D_due_route_eligible": phase == "due",
        }
        rows.append(row)
        (due if phase == "due" else not_due).append(index)

    if not rows or not due or not not_due:
        raise RuntimeError("source/phase cover must contain both due and not-due children")

    return {
        "schema": SCHEMA,
        "qualification": "OU3_P5_SAMPLE1_COMPLETE_SOURCE_PHASE_COVER_MANIFEST",
        "source_generated_not_trajectory_fit": True,
        "source_replay_used": False,
        "filter_changed": False,
        "source_pieces": int(source_pieces),
        "source_phase_child_count": len(rows),
        "due_child_count": len(due),
        "not_due_child_count": len(not_due),
        "due_source_cell_indices": due,
        "not_due_source_cell_indices": not_due,
        "source_phase_children": rows,
        "same_partition_as_first_accel_rotation_gauge": True,
        "current_V14D_requires_sample0_due": True,
        "current_V14D_focused_source_cell_zero_in_manifest": 0 in due,
        "not_due_identity_branch_must_be_certified_separately": True,
        "all_source_phase_children_numerically_closed_here": False,
        "complete_sample1_source_family_promoted_here": False,
        "whole_word_promoted_here": False,
        "N_H_words_set_here": False,
        "P5_SAMPLE1_SOURCE_PHASE_MANIFEST": "PASS",
        "next_obligation": (
            "RUN_V14D_OVER_EVERY_DUE_SOURCE_CHILD_AND_BUILD_THE_CORRESPONDING_"
            "NOT_DUE_IDENTITY_S_PREFIX_Q8_ROUTE_BEFORE_SAMPLE2"
        ),
        "failures": [],
    }


def validate(d: dict) -> list[str]:
    failures = list(d.get("failures", []))
    if d.get("schema") != SCHEMA:
        failures.append("schema mismatch")
    if d.get("qualification") != "OU3_P5_SAMPLE1_COMPLETE_SOURCE_PHASE_COVER_MANIFEST":
        failures.append("qualification mismatch")
    for key in (
        "source_generated_not_trajectory_fit",
        "same_partition_as_first_accel_rotation_gauge",
        "current_V14D_requires_sample0_due",
        "current_V14D_focused_source_cell_zero_in_manifest",
        "not_due_identity_branch_must_be_certified_separately",
    ):
        if d.get(key) is not True:
            failures.append(f"{key} is not true")
    for key in (
        "source_replay_used",
        "filter_changed",
        "all_source_phase_children_numerically_closed_here",
        "complete_sample1_source_family_promoted_here",
        "whole_word_promoted_here",
        "N_H_words_set_here",
    ):
        if d.get(key) is not False:
            failures.append(f"{key} is not false")

    rows = d.get("source_phase_children", [])
    n = int(d.get("source_phase_child_count", -1))
    due = list(d.get("due_source_cell_indices", []))
    not_due = list(d.get("not_due_source_cell_indices", []))
    if not rows or len(rows) != n:
        failures.append("source-phase child list/count mismatch")
    if int(d.get("due_child_count", -1)) != len(due):
        failures.append("due child count mismatch")
    if int(d.get("not_due_child_count", -1)) != len(not_due):
        failures.append("not-due child count mismatch")
    if sorted(due + not_due) != list(range(n)):
        failures.append("due/not-due indices do not partition the source family")
    if set(due) & set(not_due):
        failures.append("due/not-due source indices overlap")

    for i, row in enumerate(rows):
        if int(row.get("source_cell_index", -1)) != i:
            failures.append("source-cell indices are not contiguous")
            break
        phase = row.get("sample0_pseudo_phase")
        if phase not in ("due", "not_due"):
            failures.append("invalid source phase")
            break
        if bool(row.get("current_V14D_due_route_eligible")) != (phase == "due"):
            failures.append("V14D eligibility does not match source phase")
            break
        for key in ("tau_s", "sigma_aw_mps2", "R_S_filter_std", "pseudo_period_s"):
            x = row.get(key)
            if not (isinstance(x, list) and len(x) == 2 and float(x[0]) <= float(x[1])):
                failures.append(f"invalid {key} interval")
                break

    if not failures and d.get("P5_SAMPLE1_SOURCE_PHASE_MANIFEST") != "PASS":
        failures.append("source-phase manifest did not pass")
    return list(dict.fromkeys(failures))


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--domain", type=Path, default=DEFAULT_DOMAIN)
    ap.add_argument("--source-pieces", type=int, default=4)
    ap.add_argument("--output", type=Path, required=True)
    args = ap.parse_args()
    out = build(args.domain, source_pieces=args.source_pieces)
    vf = validate(out)
    out["validation_pass"] = not vf
    out["validation_failures"] = vf
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json.dumps(out, indent=2, sort_keys=True), encoding="utf-8")
    print(json.dumps({
        "status": out["P5_SAMPLE1_SOURCE_PHASE_MANIFEST"],
        "children": out["source_phase_child_count"],
        "due": out["due_child_count"],
        "not_due": out["not_due_child_count"],
        "due_indices": out["due_source_cell_indices"],
        "not_due_indices": out["not_due_source_cell_indices"],
        "next": out["next_obligation"],
        "validation_failures": vf,
    }, indent=2, sort_keys=True))
    return 0 if not vf else 2


if __name__ == "__main__":
    raise SystemExit(main())
