#!/usr/bin/env python3
"""Publish OU-III sensitivity evidence only when its coupling is SpectralMSE.

The committed robustness archive predates the deployed analytical coupling. Its
OFAT rows remain useful and are kept in a separate immutable LaTeX excerpt, but
the archived coupled columns and sensitivity figure must not be relabeled as
current evidence. After a new robustness run is generated by tools/ou_robustness.py,
this helper admits the full sensitivity table and figure into the publication.
"""
from __future__ import annotations

import argparse
import re
from pathlib import Path

CURRENT_TABLE = "w3d-ou-robustness-sensitivity-current-generated.tex-part"
SENSITIVITY_SVG = "ou_robustness_sensitivity.svg"
CURRENT_MARKERS = (
    "deployed SpectralMSE law",
    r"c^{6/7}",
    r"c^{41/14}",
)
RETIRED_MARKERS = (
    r"\sigma_{aw}\tau^3",
    r"\tau,r_S\propto\tau^3",
)


def _table_block_by_label(text: str, label: str) -> str:
    marker = rf"\label{{{label}}}"
    for block in re.findall(
        r"\\begin\{table\*\}.*?\\end\{table\*\}", text, flags=re.S
    ):
        if marker in block:
            return block
    raise RuntimeError(f"cannot locate table {label}")


def _write_if_changed(path: Path, text: str) -> bool:
    if path.is_file() and path.read_text(encoding="utf-8") == text:
        return False
    path.write_text(text, encoding="utf-8")
    return True


def _copy_if_changed(source: Path, target: Path) -> bool:
    data = source.read_bytes()
    if target.is_file() and target.read_bytes() == data:
        return False
    target.write_bytes(data)
    return True


def sync_current_sensitivity(robustness_dir: Path, doc_dir: Path) -> bool:
    publication = robustness_dir / "ou_robustness_publication.tex"
    target = doc_dir / CURRENT_TABLE
    svg_source = robustness_dir / SENSITIVITY_SVG
    svg_target = doc_dir / SENSITIVITY_SVG
    text = publication.read_text(encoding="utf-8")
    analytical = all(marker in text for marker in CURRENT_MARKERS)
    changed = False

    if not analytical:
        # The archive may still contain the historical coupled study for
        # provenance. Do not mirror those columns or its figure into the paper.
        for path in (target, svg_target):
            if path.exists():
                path.unlink()
                changed = True
        return changed

    table = _table_block_by_label(text, "tab:ou_robustness_sensitivity")
    for token in RETIRED_MARKERS:
        if token in table:
            raise RuntimeError(
                f"analytical robustness publication still contains retired coupling: {token}"
            )
    for marker in CURRENT_MARKERS[1:]:
        if marker not in table:
            raise RuntimeError(f"analytical sensitivity table lacks marker {marker}")

    desired = (
        "% Generated only from a robustness bundle using the deployed SpectralMSE coupling.\n\n"
        + table
        + "\n"
    )
    changed |= _write_if_changed(target, desired)
    if not svg_source.is_file():
        raise FileNotFoundError(svg_source)
    changed |= _copy_if_changed(svg_source, svg_target)
    return changed


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--robustness-dir", type=Path, required=True)
    parser.add_argument("--doc-dir", type=Path, required=True)
    args = parser.parse_args()
    changed = sync_current_sensitivity(args.robustness_dir, args.doc_dir)
    print(
        "Aligned analytical OU-III sensitivity publication evidence."
        if changed
        else "OU-III sensitivity publication evidence already aligned."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
