#!/usr/bin/env python3
"""Generate the deterministic last-900 s simulation table from the simulator.

The table this writes used to be hand-typed LaTeX sitting in
``doc/kalman_ou_iii/w3d-sim-charts.tex-part``.  Hand-typed numbers do not
follow the code: the roll column still carried values from before the startup
tilt reference was fixed, so the manuscript reported an error the filter no
longer made.  Every other results table in that document is generated; this one
now is too.

The protocol is the historical deterministic one and is deliberately not the
ten-seed study: one realization per record, default seeds, the final 900 s of a
20-minute replay.  It is reported for continuity, and the paper says so.  Do not
quote it interchangeably with the ten-seed numbers.

Usage:

    python3 tools/ou_sim_table.py \\
        --output doc/kalman_ou_iii/w3d-sim-results-generated.tex-part
"""

from __future__ import annotations

import argparse
import os
import re
import subprocess
import sys
from pathlib import Path
from typing import Any


REPO_ROOT = Path(__file__).resolve().parents[1]

# The eight records the historical table reports, in the order it reported them.
RECORDS = (
    ("JONSWAP", 0.27, "wave_data_jonswap_H0.270_L14.047_A30.00_P60.00.csv"),
    ("JONSWAP", 1.50, "wave_data_jonswap_H1.500_L50.710_A-30.00_P120.00.csv"),
    ("JONSWAP", 4.00, "wave_data_jonswap_H4.000_L112.766_A30.00_P30.00.csv"),
    ("JONSWAP", 8.50, "wave_data_jonswap_H8.500_L202.839_A-30.00_P72.00.csv"),
    ("PM--Stokes", 0.27, "wave_data_pmstokes_H0.270_L14.047_A30.00_P60.00.csv"),
    ("PM--Stokes", 1.50, "wave_data_pmstokes_H1.500_L50.710_A-30.00_P120.00.csv"),
    ("PM--Stokes", 4.00, "wave_data_pmstokes_H4.000_L112.766_A30.00_P30.00.csv"),
    ("PM--Stokes", 8.50, "wave_data_pmstokes_H8.500_L202.839_A-30.00_P72.00.csv"),
)

FLOAT = r"[-+]?[0-9]*\.?[0-9]+(?:[eE][-+]?[0-9]+)?"

PATTERNS = {
    "z_rms_m": re.compile(rf"XYZ RMS \(m\): X={FLOAT} Y={FLOAT} Z=({FLOAT})"),
    "z_pct_hs": re.compile(
        rf"XYZ RMS \(%Hs\): X={FLOAT}% Y={FLOAT}% Z=({FLOAT})%"
    ),
    "angles": re.compile(
        rf"Angles RMS \(deg\): Roll=({FLOAT}) Pitch=({FLOAT}) Yaw=({FLOAT})"
    ),
    "dir_mean": re.compile(rf"dir_deg_gen \([^)]*\): mean_circ=({FLOAT})"),
    "sense": re.compile(
        rf"sense: \+AXIS=\d+ \(({FLOAT})%\) -AXIS=\d+ \(({FLOAT})%\)"
        rf" UNCERTAIN=\d+ \(({FLOAT})%\)"
    ),
}


def run_record(binary: Path, record: Path) -> dict[str, Any]:
    """Replay one record and pull the last-900 s block out of the output."""
    # The child runs with cwd=binary.parent, so a relative binary path -- what
    # the CI step passes -- would be resolved against that directory instead of
    # ours and fail to exec.  Resolve both ends before crossing the boundary.
    binary = binary.resolve()
    record = record.resolve()

    env = dict(os.environ)
    env["W3D_WRITE_TIMESERIES"] = "0"
    # Every record has to be scored, including any that trip a historical gate;
    # the table reports what the filter did, not whether it passed.
    env["W3D_COLLECT_ALL_GATES"] = "1"

    completed = subprocess.run(
        [str(binary), "--input", str(record)],
        cwd=binary.parent,
        env=env,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        check=False,
    )
    out = completed.stdout

    row: dict[str, Any] = {}
    for name, pattern in PATTERNS.items():
        match = pattern.search(out)
        if match is None:
            tail = "\n".join(out.splitlines()[-25:])
            raise RuntimeError(
                f"{record.name}: simulator output has no {name}\n{tail}"
            )
        row[name] = tuple(float(value) for value in match.groups())

    return row


def format_table(rows: list[tuple[str, float, dict[str, Any]]]) -> str:
    lines = [
        "% Generated by tools/ou_sim_table.py -- do not edit by hand.",
        "%",
        "% Single-realization deterministic protocol: default seeds, final 900 s",
        "% of a 20-minute replay.  Not the ten-seed study, and not to be quoted",
        "% interchangeably with it.",
        "% Requires: \\usepackage{booktabs,siunitx}",
        "\\begin{table}[t]",
        "  \\centering",
        "  \\caption{Simulation results (last \\SI{900}{s} RMS window).}",
        "  \\label{tab:sim_results_rms_dir_basic}",
        "  \\setlength{\\tabcolsep}{2.2pt}",
        "  \\renewcommand{\\arraystretch}{1.08}",
        "  \\footnotesize",
        "  \\sisetup{detect-all}",
        "  \\begin{tabular}{@{}l",
        "                  S[table-format=1.6]",
        "                  S[table-format=1.3]",
        "                  S[table-format=2.1]",
        "                  S[table-format=1.2]",
        "                  S[table-format=1.2]",
        "                  S[table-format=1.2]",
        "                  S[table-format=-2.1]",
        "                  l",
        "                  @{}}",
        "    \\toprule",
        "    {Case} &",
        "    {$H_s$} &",
        "    {Z RMS} &",
        "    {Z\\%$H_s$} &",
        "    {R} &",
        "    {P} &",
        "    {Y} &",
        "    {$\\bar\\theta$} &",
        "    {T/A/U} \\\\",
        "    \\midrule",
    ]

    previous_family = None
    for family, hs, row in rows:
        if previous_family is not None and family != previous_family:
            lines.append("    \\addlinespace")
        previous_family = family

        roll, pitch, yaw = row["angles"]
        toward, away, uncertain = row["sense"]
        lines.append(
            f"    {family:<10s} & {hs:.2f} & {row['z_rms_m'][0]:.3f} &"
            f" {row['z_pct_hs'][0]:.1f} & {roll:.2f} & {pitch:.2f} &"
            f" {yaw:.2f} & {row['dir_mean'][0]:.1f} &"
            f" {toward:.1f}/{away:.1f}/{uncertain:.1f} \\\\"
        )

    lines.extend([
        "    \\bottomrule",
        "  \\end{tabular}",
        "  \\vspace{1pt}",
        "  \\footnotesize",
        "  Z RMS is vertical-displacement RMS error in metres; Z\\%$H_s$ is the",
        "  corresponding error normalized by significant wave height.",
        "  R/P/Y are roll/pitch/yaw RMS errors in degrees.",
        "  Direction $\\bar{\\theta}\\in[-90^\\circ,90^\\circ]$ is the circular-mean",
        "  estimated wave direction over the scoring window;",
        "  T/A/U = Toward/Away/Uncertain (\\% of samples).  These are the estimator's",
        "  own FORWARD/BACKWARD/UNCERTAIN classes, which are defined against the axis",
        "  representative it returns and are therefore a commitment rate rather than a",
        "  correctness rate; the truth-referenced travel-sense correctness rate is in",
        "  Table~\\ref{tab:ou_mc_direction}.",
        "\\end{table}",
    ])
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--binary",
        type=Path,
        default=REPO_ROOT / "tests" / "kalman_ou_iii" / "kalman_ou_iii-sim",
    )
    parser.add_argument(
        "--data-dir", type=Path, default=REPO_ROOT / "plots" / "kalman_ou_ii"
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=(
            REPO_ROOT / "doc" / "kalman_ou_iii"
            / "w3d-sim-results-generated.tex-part"
        ),
    )
    args = parser.parse_args(argv)

    if not args.binary.exists():
        raise SystemExit(
            f"missing simulator: {args.binary}\n"
            "build it with: make -C tests/kalman_ou_iii build"
        )

    rows = []
    for family, hs, name in RECORDS:
        record = (args.data_dir / name).resolve()
        if not record.exists():
            raise SystemExit(
                f"missing record: {record}\n"
                "fetch it with: make fetch-sim-data"
            )
        print(f"Replaying {name}", flush=True)
        rows.append((family, hs, run_record(args.binary, record)))

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(format_table(rows), encoding="utf-8")
    print(f"Wrote {args.output}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
