#!/usr/bin/env python3
"""Publish parameter-selection evidence without altering simulation thresholds."""
from pathlib import Path
import json
import statistics

ROOT = Path(__file__).resolve().parents[1]


def main():
    out = ROOT / 'reports/results/rao_parameter_tuning'
    md = '''# Filter retuning on the v1.2.1 vessel dataset

All runs use the pinned 28 ft sailboat RAO records and the existing executable quality gates. Full 1200-second records are scored over their final 900 seconds. Candidate screening used the default draw and, for OU-III, paired training seeds 11 and 23. Validation uses four unseen paired sensor/initialization seeds: 101, 1009, 2027 and 3037, across all eight records (32 cases per family). These are new sensor realizations on the same prescribed wave records, not validation on unseen hulls or sea realizations.

## Selected settings

| Filter | Parameter | Previous | Selected |
|---|---|---:|---:|
| OU-II | Simulator magnetic sigma rescale | 2 | 4 |
| OU-III | Simulator magnetic sigma rescale | 2 | 8 |
| OU-II, OU-III | Gyro-bias random-walk variance | 1e-11 | 1e-10 |
| OU-II, OU-III, TFG | Relative hard-iron ridge | 0.5 | 0.25 |
| OU-II, OU-III, TFG | Minimum hard-iron information | 2 | 0.1 |
| OU-II | Pseudo-measurement MSE ratio | 0.4611 | 0.4 |
| TFG | Simulator magnetic sigma rescale | 1 | 4 |
| TFG | Simulator gyro sigma rescale | 1 | 0.1 |
| TFG | Magnetic refinement start, seconds | 90 | 30 |
| PII adapter | Observer r | 0.125 | 0.08125 |
| PII adapter | Mahony Ki, base/calm/rough | 0.090/0.100/0.070 | 0.0225/0.025/0.0175 |

Minimum information is a calibration-activation parameter; simulation acceptance thresholds are unchanged. Magnetic covariance accounts empirically for calibration/model uncertainty as well as white sensor noise. OU-II retains C_P=0.1116, giving C_V=0.279. OU-III retains C_J=0.0538 and its 5000-second accelerometer-bias time constant. TFG gyro-bias random-walk variance was already 1e-10. NLO retains theta_gain=0.56: the screened alternatives did not show a clear overall improvement. Frequency settings are unchanged.

## Held-out results

Counts are individual threshold violations, not failed records. Metrics are arithmetic means of per-record RMS values. Every failure is retained.

| Filter | Setting | Violations / 32 cases | Yaw RMS, degrees | Roll RMS, degrees | Pitch RMS, degrees | 3-D RMS, m | Worst violation / limit |
|---|---|---:|---:|---:|---:|---:|---:|
'''
    tex = r'''% Generated by tools/rao_tuning_report.py.
\begin{table*}[t]\centering\footnotesize
\caption{Held-out parameter validation: four paired IMU/initialization seeds and eight
vessel records, 32 cases per family. Entries average per-record RMS.
Violations count unchanged executable thresholds, not failed records.}
\label{tab:rao-parameter-validation}
\begin{tabular}{@{}llrrrrrr@{}}\toprule
Family & Setting & Violations & Yaw [deg] & Roll [deg] & Pitch [deg] & 3-D [m] & Worst/limit \\
\midrule
'''
    for family in ('ou2', 'ou3', 'tfg'):
        label = {'ou2': 'OU-II', 'ou3': 'OU-III', 'tfg': 'TFG'}[family]
        for r in json.loads((out / f'{family}-validation/summary.json').read_text()):
            values = [str(r['violations'])] + [f'{r[k]:.3f}' for k in ('yaw_rms_deg', 'roll_rms_deg', 'pitch_rms_deg', 'disp_3d_rms_m', 'worst_ratio')]
            md += '| ' + ' | '.join([label, r['config'], *values]) + ' |\n'
            tex += ' & '.join([label.replace('-', '--'), r['config'], *values]) + r' \\' + '\n'
    tex += r'\bottomrule\end{tabular}\end{table*}' + '\n'
    pii = json.loads((out / 'pii-validation/runs.json').read_text())
    pp = {}
    for name in ('baseline', 'candidate'):
        rr = [r for r in pii if r['config'] == name and r['seed'] != 'default']
        pp[name] = (sum(len(r['failures']) for r in rr), statistics.fmean(v for r in rr for v in r['z_pct_hs']))
    md += f'''\nPII vertical-displacement violations fall from {pp['baseline'][0]} to {pp['candidate'][0]}; mean vertical RMS falls from {pp['baseline'][1]:.3f}% to {pp['candidate'][1]:.3f}% of incident Hs. Its unchanged quality gates test vertical displacement, so this count is not directly comparable with OU/TFG multi-metric counts.

On the default draw, all eight TFG and PII records pass. OU-III retains two failing records (three violations); OU-II retains three (seven violations). NLO retains the PM 1.5 m vertical-displacement failure. The frequency test retains its low-signal cnoidal failure. Passing the default draw does not establish multi-seed reliability.

OU-II improves average errors and worst normalized exceedance but increases held-out violation count from 84 to 86 and failing cases from 29 to 30. OU-III roll RMS increases slightly. These are explicit tradeoffs, not claims of uniformly improved gates. The selected tuning does not make all studies pass.

## Reproduction and provenance

Screen and validation subdirectories preserve aggregate `runs.json` with every candidate, seed, metric, and failure message, plus manifests where generated by the reusable runner. Redundant per-record logs/JSON are omitted after aggregation. Early NLO/PII screens predate the reusable runner and have weaker provenance; the selected PII setting has a separately recorded held-out replay.

The `*-selected-configs.json` files contain overrides relative to the **pre-retuning baseline binaries**, whose hashes are recorded in the experiment manifests. Do not apply these scale factors to the newly retuned defaults: that would scale twice. For a new replay with the selected source defaults, use `*-current-default-replay-configs.json`: baseline overrides restore the old parameter point and the selected arm uses defaults. These reproduce the parameter comparison, not the historical pre-direction binary byte hash.

Baseline source parent was 456430d4d2cb2449dd0ae3c7781f71c5eedf599e, with uncommitted sweep hooks; manifests identify actual binary hashes rather than claiming that parent alone reproduces the instrumented executable. `tools/rao_parameter_tuning.py` and `tools/observer_parameter_tuning.py` rerun explicit configurations without modifying quality gates.

The `selected-source.bundle` preserves local source commit 1cb65a24379b74bf59443701c9ecb3be03f0574d, referenced by the selected study and runtime manifests. It requires parent 456430d4d2cb2449dd0ae3c7781f71c5eedf599e, already in this repository. `git bundle verify` checks that prerequisite; the bundle can be fetched to recover the exact local source revision. Later paper/configuration-check edits are carried by the PR.

The tuning evidence predates direction RAO matching and correction of the v1.2.1 propagation-to reference. Direction measurements from these parameter screens are not publication evidence; use the separate direction ablation and final integrated replay. Attitude/displacement tuning metrics are unaffected by that direction-only branch.

Performance selection does not alter the canonical P3/P4/P5 proof thresholds or imply deployment-domain stability admission. Stability and live-covariance audits are separate obligations.
'''
    tex += r'''Selected covariance and calibration settings improve aggregate errors but do not
make every quality gate pass. OU--II's held-out violation count increases despite
lower mean errors; OU--III roll RMS increases slightly. PII's held-out vertical
violations decrease from 23 to 7, with mean vertical RMS decreasing from
8.375\% to 5.961\% of incident $H_s$. The validation draws change sensor and
initialization errors on the same wave records; they do not cover unseen hulls.
'''
    (out / 'tuning_report.md').write_text(md)
    (out / 'tuning_validation.tex').write_text(tex)
    (ROOT / 'doc/kalman_ou_iii/w3d-rao-tuning-generated.tex-part').write_text(tex)


if __name__ == '__main__':
    main()
