#!/usr/bin/env python3
"""Publish parameter-selection evidence without altering simulation thresholds."""
from pathlib import Path
import json
import statistics

ROOT = Path(__file__).resolve().parents[1]


def current_summary(out, family):
    study = 'ou2-ratio-validation' if family == 'ou2' else 'ou3-validation'
    config = 'ratio_0.3' if family == 'ou2' else 'candidate'
    rows = json.loads((out / 'continuation' / study / 'runs.json').read_text())
    rows = [r for r in rows if r['config'] == config and r['seed'] != 'default']
    return dict(config='selected', violations=sum(len(r['violations']) for r in rows),
                worst_ratio=max(v['ratio'] or 0 for r in rows for v in r['violations']),
                **{k: statistics.fmean(r['metrics'][k] for r in rows) for k in
                   ('yaw_rms_deg', 'roll_rms_deg', 'pitch_rms_deg', 'disp_3d_rms_m')})


def main():
    out = ROOT / 'reports/results/rao_parameter_tuning'
    md = '''# Filter retuning on the v1.2.1 vessel dataset

All runs use the pinned 28 ft sailboat RAO records and the existing executable quality gates. Full 1200-second records are scored over their final 900 seconds. Candidate screening used the default draw and, for OU-III, paired training seeds 11 and 23. Validation uses four unseen paired sensor/initialization seeds: 101, 1009, 2027 and 3037, across all eight records (32 cases per family). These are new sensor realizations on the same prescribed wave records, not validation on unseen hulls or sea realizations.

## Selected settings

| Filter | Parameter | Previous | Selected |
|---|---|---:|---:|
| OU-II | Simulator magnetic sigma rescale | 2 | 4 |
| OU-III | Simulator magnetic sigma rescale | 2 | 8 |
| OU-II, OU-III | Gyro-bias random-walk variance | 1e-11 | 1e-10 |
| OU-II, OU-III, TFG | Relative hard-iron ridge | 0.5 | 0.25 |
| OU-II, OU-III, TFG | Minimum hard-iron information | 2 | 0.1 |
| OU-II | Pseudo-measurement MSE ratio | 0.4611 | 0.3 |
| OU-III | Simulator gyro sigma rescale | 0.05 | 0.01 |
| TFG | Simulator magnetic sigma rescale | 1 | 4 |
| TFG | Simulator gyro sigma rescale | 1 | 0.1 |
| TFG | Magnetic refinement start, seconds | 90 | 30 |
| PII adapter | Observer r | 0.125 | 0.08125 |
| PII adapter | Mahony Ki, base/calm/rough | 0.090/0.100/0.070 | 0.0225/0.025/0.0175 |

Minimum information is a calibration-activation parameter; simulation acceptance thresholds are unchanged. Covariance rescaling is an empirical performance weight, not an estimate of injected sensor noise density. OU-II retains C_P=0.1116, giving C_V=0.372. OU-III retains C_J=0.0538 and its 5000-second accelerometer-bias time constant. TFG gyro-bias random-walk variance was already 1e-10. NLO retains theta_gain=0.56. Standalone frequency tracking uses causal 0.01 Hz DC removal, two 0.8 Hz low-pass poles, and 0.004g zero-crossing hysteresis. PLL coarse smoothing advances by the elapsed detected period. Input noise, output bounds, scoring windows and quality gates are unchanged.

## Held-out results

Counts are individual threshold violations, not failed records. Metrics are arithmetic means of per-record RMS values. Every failure is retained.

| Filter | Setting | Violations / 32 cases | Yaw RMS, degrees | Roll RMS, degrees | Pitch RMS, degrees | 3-D RMS, m | Worst violation / limit |
|---|---|---:|---:|---:|---:|---:|---:|
'''
    tex = r'''% Generated by tools/rao_tuning_report.py.
\begin{table*}[t]\centering\footnotesize
\caption{Held-out parameter validation: four paired IMU/initialization seeds and eight
vessel records, 32 cases per family. Entries average per-record RMS.
Violations count unchanged executable thresholds, not failed records.}
\label{tab:rao-parameter-validation}
\begin{tabular}{@{}llrrrrrr@{}}\toprule
Family & Setting & Violations & Yaw [deg] & Roll [deg] & Pitch [deg] & 3-D [m] & Worst/limit \\
\midrule
'''
    for family in ('ou2', 'ou3', 'tfg'):
        label = {'ou2': 'OU-II', 'ou3': 'OU-III', 'tfg': 'TFG'}[family]
        for r in json.loads((out / f'{family}-validation/summary.json').read_text()):
            if family in ('ou2', 'ou3') and r['config'] != 'baseline':
                r = current_summary(out, family)
            values = [str(r['violations'])] + [f'{r[k]:.3f}' for k in ('yaw_rms_deg', 'roll_rms_deg', 'pitch_rms_deg', 'disp_3d_rms_m', 'worst_ratio')]
            md += '| ' + ' | '.join([label, r['config'], *values]) + ' |\n'
            tex += ' & '.join([label.replace('-', '--'), r['config'], *values]) + r' \\' + '\n'
    tex += r'\bottomrule\end{tabular}\end{table*}' + '\n'
    pii = json.loads((out / 'pii-validation/runs.json').read_text())
    pp = {}
    for name in ('baseline', 'candidate'):
        rr = [r for r in pii if r['config'] == name and r['seed'] != 'default']
        pp[name] = (sum(len(r['failures']) for r in rr), statistics.fmean(v for r in rr for v in r['z_pct_hs']))
    md += f'''\nPII quality-gate violations fall from {pp['baseline'][0]} to {pp['candidate'][0]}; mean vertical RMS falls from {pp['baseline'][1]:.3f}% to {pp['candidate'][1]:.3f}% of incident Hs. These include vertical-displacement and yaw gates: the baseline has 16 vertical and 7 yaw violations; the selected setting has 0 vertical and 7 yaw violations. This count is not directly comparable with OU/TFG multi-metric counts.

On the default draw, OU-III retains two failing records (two violations); OU-II retains two (six violations). Both are the 8.5 m seas. All 20 standalone frequency records pass. Passing the default draw does not establish multi-seed reliability. TFG and PII pass all eight integrated default records. NLO results and remaining failures are reported separately below.

Relative to the pre-RAO parameter point, OU-II's held-out violations change from 84 to 85, and OU-III's from 90 to 85. Relative to the continuation baseline at 942d3a9542ab2b1dc8f909bbfe270ac1328575c1, OU-II improves from 86 to 85 violations, with 30 failing cases unchanged; OU-III improves from 88 to 85 violations and 30 to 28 failing cases. Mean 3-D RMS rises slightly: OU-II 0.375220 to 0.377672 m, OU-III 0.290842 to 0.292620 m. OU-III's held-out mean attitude errors also rise slightly. These are explicit tradeoffs, not uniformly improved performance.

The OU continuation screens use default, 11 and 23 sensor/initialization draws. Its validation reuses the four held-out sensor draws, which were excluded from candidate screening. These draws remain on the same eight prescribed wave records. The larger OU-II joint change (ratio 0.3, magnetic sigma x1.5, bias RW 0.00035) is rejected: violations rise from 86 to 94 despite lower mean errors. `continuation` preserves all 488 OU candidate/baseline replays, including rejected settings, manifests and binary hashes. Its overrides apply to the baseline binaries; the OU `continuation/*-current-default-replay-configs.json` files instead reproduce the retained comparison on the current source defaults.

## Reproduction and provenance

Screen and validation subdirectories preserve aggregate `runs.json` with every candidate, seed, metric, and failure message, plus manifests where generated by the reusable runner. Redundant per-record logs/JSON are omitted after aggregation. Early NLO/PII screens predate the reusable runner and have weaker provenance; the selected PII setting has a separately recorded held-out replay.

The `*-selected-configs.json` files contain overrides relative to the **pre-retuning baseline binaries**, whose hashes are recorded in the experiment manifests. Do not apply these scale factors to the newly retuned defaults: that would scale twice. For a new replay with the selected source defaults, use `*-current-default-replay-configs.json`: baseline overrides restore the old parameter point and the selected arm uses defaults. These reproduce the parameter comparison, not the historical pre-direction binary byte hash.

The OU parameter comparisons used the original PR head PLL; the integrated default and full validation/robustness replays provide evidence for the corrected shared code. The earlier PII screen likewise predates the shared PLL correction.

Baseline source parent was 456430d4d2cb2449dd0ae3c7781f71c5eedf599e, with uncommitted sweep hooks; manifests identify actual binary hashes rather than claiming that parent alone reproduces the instrumented executable. `tools/rao_parameter_tuning.py` and `tools/observer_parameter_tuning.py` rerun explicit configurations without modifying quality gates.

The `selected-source.bundle` preserves local source commit 1cb65a24379b74bf59443701c9ecb3be03f0574d, referenced by the selected study and runtime manifests. It requires parent 456430d4d2cb2449dd0ae3c7781f71c5eedf599e, already in this repository. `git bundle verify` checks that prerequisite; the bundle can be fetched to recover the exact local source revision. Later paper/configuration-check edits are carried by the PR.

The tuning evidence predates direction RAO matching and correction of the v1.2.1 propagation-to reference. Direction measurements from these parameter screens are not publication evidence; use the separate direction ablation and final integrated replay. Attitude/displacement tuning metrics are unaffected by that direction-only branch.

Performance selection does not alter the canonical P3/P4/P5 proof thresholds or imply deployment-domain stability admission. Stability and live-covariance audits are separate obligations.
'''
    tex += r'''Selected covariance and calibration settings do not make every gate pass.
Relative to the continuation baseline, OU--II's held-out violations decrease
from 86 to 85 and OU--III's from 88 to 85. OU--III's failing cases decrease
from 30 to 28; OU--II remains at 30. Mean 3-D RMS increases slightly, from
0.375220 to 0.377672 m for OU--II and 0.290842 to 0.292620 m for OU--III.
OU--III's mean held-out attitude errors also increase slightly. The retained
changes are OU--II's channel ratio 0.4 to 0.3 and OU--III's gyro covariance
sigma rescale 0.05 to 0.01. This empirical weight does not alter injected noise.
The default draw retains two failing 8.5 m records in each OU family.
The larger OU--II joint candidate is rejected because violations rise to 94.
PII's earlier parameter-screen held-out violations decrease from 23 to 7:
vertical violations fall from 16 to zero, while seven yaw violations remain.
Mean vertical RMS decreases from
8.375\% to 5.961\% of incident $H_s$. The validation draws change sensor and
initialization errors on the same wave records; they do not cover unseen hulls.
'''
    nlo = out / 'continuation'
    held = json.loads((nlo / 'nlo-coarse-validation/runs.json').read_text())
    fixed = json.loads((nlo / 'nlo-fixed-validation/runs.json').read_text())
    md += '''\n## NLO after the PLL clock correction

The shared correction exposes gain-scheduling sensitivity in the NLO adapter.
The selected NLO-only coarse-frequency horizon is 120 s; its gain multiplier
remains 0.56 and gain smoothing remains 30 s. The longer crossing average
reduces jitter but also slows acquisition. These stationary records do not
validate rapid sea transitions.

| Configuration | Default failing records / 8 | Held-out failing records / 32 | Mean vertical RMS / Hs, % | Worst vertical RMS / Hs, % |
|---|---:|---:|---:|---:|
'''
    for name, default_fails, rows in (
        ('Original PR head', 1, [r for r in held if r['config'] == 'head']),
        ('Corrected PLL, 4.5 s coarse horizon', 5, fixed),
        ('Selected NLO 120 s coarse horizon', 1, [r for r in held if r['config'] == 'candidate']),
    ):
        vals = [v for r in rows for v in r['z_pct_hs']]
        md += f'| {name} | {default_fails} | {sum(len(r["failures"]) for r in rows)} | {statistics.fmean(vals):.6f} | {max(vals):.5f} |\n'
    md += '''\nThe selected default failure is PM-Stokes Hs=0.27 m: 7.52444% against
the unchanged 7.13% limit. Relative to the original PR head, extreme held-out
errors decrease substantially while failing cases increase from six to nine.
Relative to the corrected PLL's short-horizon default, failures decrease from
19 to nine, but the held-out maximum increases from 8.42239% to 13.6171%.
This is a measured tradeoff, not uniformly improved performance or a passing
NLO regression suite. Gain-only and gain-smoothing screens are retained as
rejected alternatives. The four held-out sensor draws were excluded from
NLO candidate screening and still use the same eight prescribed seas.
'''
    current_pii = json.loads((nlo / 'pii-current-validation/runs.json').read_text())
    failures = [f for r in current_pii for f in r['failures']]
    md += (f"\nThe fresh PII replay after the shared PLL correction has "
           f"{sum('Z RMS' in f for f in failures)} vertical and "
           f"{sum('Yaw' in f for f in failures)} yaw violations over the same 32 "
           f"held-out cases. Mean vertical RMS is "
           f"{statistics.fmean(v for r in current_pii for v in r['z_pct_hs']):.6f}% "
           f"of Hs. Its eight default records pass both unchanged gates.\n")
    (out / 'tuning_report.md').write_text(md)
    (out / 'tuning_validation.tex').write_text(tex)
    (ROOT / 'doc/kalman_ou_iii/w3d-rao-tuning-generated.tex-part').write_text(tex)


if __name__ == '__main__':
    main()
