#!/usr/bin/env python3
"""Publish the current paired startup study without fixed numerical claims."""
from pathlib import Path
import csv
import statistics as st

ROOT = Path(__file__).resolve().parents[1]
DOC = ROOT / 'doc/kalman_ou_iii'
RESULTS = ROOT / 'reports/results/startup_ablation'


def generate(rows):
    def select(family, arm, seed='default'):
        return [r for r in rows if r['family'] == family and r['arm'] == arm
                and (seed is None or r['seed'] == seed)]
    def mean(rr, key): return st.fmean(float(r[key]) for r in rr)
    def worst(rr, key): return max(float(r[key]) for r in rr)
    default = {f: {a: select(f,a) for a in ('deployed','hard-iron-off')}
               for f in ('OU-II','OU-III','TFG')}
    hard = r'''% Generated by tools/startup_publication_sync.py.
\begin{table}[t]\centering
\caption{OU--III hard-iron correction on the v1.2.1 RAO records, default draw,
final 900 s. RMS errors are in degrees.}
\label{tab:mag-hi-yaw}\footnotesize
\begin{tabular}{@{}lrrrrr@{}}\toprule
Case & $H_s$ [m] & Yaw off & Yaw on & Pitch off & Pitch on \\
\midrule
'''
    on = default['OU-III']['deployed']; off = {r['input']:r for r in default['OU-III']['hard-iron-off']}
    for r in on:
        b=off[r['input']]
        hard += f"{r['spectrum'].replace('PM-Stokes','PM--Stokes')} & {float(r['hs_m']):.2f} & " + ' & '.join(f'{float(v):.3f}' for v in [b['yaw_rms_deg'],r['yaw_rms_deg'],b['pitch_rms_deg'],r['pitch_rms_deg']]) + r' \\'+'\n'
    hard += r'\bottomrule\end{tabular}\end{table}'+'\n'
    study = r'''% Generated by tools/startup_publication_sync.py.
All current ablations use the pinned v1.2.1 vessel-response records and the
final 900 s. Each row below reports the arithmetic mean of eight per-record
RMS scores; ``worst'' is the largest record RMS. These means differ from
root-mean-square pooling used by the engine study.

\subsection{Continuous hard-iron correction}
\begin{table}[t]\centering
\caption{Default-draw hard-iron ablation with current deployed startup.}
\label{tab:startup-hardiron}\footnotesize
\begin{tabular}{@{}lrrrr@{}}\toprule
& \multicolumn{2}{c}{Mean yaw RMS [deg]} & \multicolumn{2}{c}{Worst yaw RMS [deg]} \\
Family & off & on & off & on \\
\midrule
'''
    for family, arms in default.items():
        b,a=arms['hard-iron-off'],arms['deployed']
        study += family.replace('OU-','OU--')+' & '+' & '.join(f'{v:.3f}' for v in [mean(b,'yaw_rms_deg'),mean(a,'yaw_rms_deg'),worst(b,'yaw_rms_deg'),worst(a,'yaw_rms_deg')])+r' \\'+'\n'
    study += r'''\bottomrule\end{tabular}\end{table}

\subsection{TFG feature attribution}
TFG retains both startup policies, allowing matched feature-off replays.
The OU wrappers retain only their deployed proxy startup, so no numerical
comparison to a removed OU startup implementation is reported.
\begin{table}[t]\centering
\caption{TFG default-draw feature ablations. Bias is mean accelerometer-bias RMS.}
\label{tab:tfg-ablation}\footnotesize
\resizebox{\columnwidth}{!}{%
\begin{tabular}{@{}lrrrrr@{}}\toprule
Arm & Yaw [deg] & Roll [deg] & Pitch [deg] & 3-D [m] & Bias [m/s$^2$] \\
\midrule
'''
    for arm,label in [('deployed','Deployed'),('hard-iron-off','Hard iron off'),('refinement-off','Mag refinement off'),('staged-startup','Staged startup')]:
        rr=select('TFG',arm)
        study += label+' & '+' & '.join(f'{mean(rr,k):.4f}' for k in ['yaw_rms_deg','roll_rms_deg','pitch_rms_deg','disp_3d_rms_m','accel_bias_3d_rms_mps2'])+r' \\'+'\n'
    study += r'''\bottomrule\end{tabular}}\end{table}

\subsection{Calibration-draw sensitivity}
The five draws are default, 11, 23, 202 and 3033. Each changes the initial
magnetic offset and distortion while holding the paired realization fixed.
'''
    for family in ('OU-II','OU-III'):
        a=select(family,'deployed',None);b=select(family,'hard-iron-off',None)
        bm={(r['input'],r['seed']):r for r in b}
        n=sum(float(r['yaw_rms_deg'])>float(bm[r['input'],r['seed']]['yaw_rms_deg']) for r in a)
        study += f"For {family.replace('OU-','OU--')}, mean yaw RMS changes from {mean(b,'yaw_rms_deg'):.3f} to {mean(a,'yaw_rms_deg'):.3f} degrees; {n} of {len(a)} pairs worsen.\n"
    study += 'These finite draws do not prove uniform calibration improvement.\n'
    return hard,study


def main():
    with (RESULTS/'startup_runs.csv').open() as stream: rows=list(csv.DictReader(stream))
    assert len(rows)==192, 'full startup matrix required'
    hard,study=generate(rows)
    for name,text in [('w3d-hard-iron-results-generated.tex-part',hard),('w3d-startup-results-generated.tex-part',study)]:
        (DOC/name).write_text(text)
        (RESULTS/name.replace('.tex-part','.tex')).write_text(text)


if __name__=='__main__':main()
