#!/usr/bin/env python3
"""Generate the deterministic last-900 s simulation table for the TFG filter.

This is the TFG counterpart of ``tools/ou_sim_table.py`` and exists for the same
reason: a results table that is typed by hand stops following the code.  The
record list is imported from that module rather than copied, so the two filters
are always scored on the same eight records in the same order -- a table whose
rows had drifted apart would invite exactly the cross-filter comparison it could
not support.

Two differences from the OU-III table:

* a 3D column is reported.  The OU-III manuscript discusses 3D error in prose;
  for this filter it is one of the headline numbers, because the geometric
  formulation is meant to couple the horizontal channels to attitude and that is
  where any coupling benefit would show.
* the direction columns are omitted.  The TFG orchestrator does not carry the
  wave-direction estimator, so the simulator emits NaN for those fields.
  Reporting them would be reporting the absence of a feature as a measurement.

The protocol is the historical deterministic one and is deliberately not a
multi-seed study: one realization per record, default seeds, the final 900 s of
a 20-minute replay.

Usage:

    python3 tools/tfg_sim_table.py \\
        --binary tests/kalman_tfg/kalman_tfg-sim \\
        --data-dir plots/kalman_tfg \\
        --output doc/kalman_tfg/tfg-sim-results-generated.tex-part
"""

from __future__ import annotations

import argparse
import os
import re
import subprocess
import sys
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT / "tools"))

# Same eight records, same order, as the OU-III deterministic table.
from ou_sim_table import RECORDS, FLOAT  # noqa: E402

PATTERNS = {
    "z_rms_m": re.compile(rf"XYZ RMS \(m\): X={FLOAT} Y={FLOAT} Z=({FLOAT})"),
    "z_pct_hs": re.compile(rf"XYZ RMS \(%Hs\): X={FLOAT}% Y={FLOAT}% Z=({FLOAT})%"),
    "d3": re.compile(
        rf"3D RMS \(m\): ({FLOAT}) \(3D % of max \|disp_ref\|_3D = ({FLOAT})%"
    ),
    "angles": re.compile(
        rf"Angles RMS \(deg\): Roll=({FLOAT}) Pitch=({FLOAT}) Yaw=({FLOAT})"
    ),
}


def run_record(binary: Path, record: Path) -> dict[str, Any]:
    """Replay one record and pull the last-900 s block out of the output."""
    # Resolve both ends: the child runs with cwd=binary.parent, so a relative
    # binary path -- which is what the CI step passes -- would otherwise be
    # resolved against that directory and fail to exec.
    binary = binary.resolve()
    record = record.resolve()

    env = dict(os.environ)
    env["W3D_WRITE_TIMESERIES"] = "0"
    # Score every record, including any that trips a gate.  The table reports
    # what the filter did, not whether it passed.
    env["W3D_COLLECT_ALL_GATES"] = "1"

    completed = subprocess.run(
        [str(binary), "--input", str(record)],
        cwd=binary.parent,
        env=env,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        check=False,
    )
    out = completed.stdout

    row: dict[str, Any] = {}
    for name, pattern in PATTERNS.items():
        match = pattern.search(out)
        if match is None:
            tail = "\n".join(out.splitlines()[-25:])
            raise RuntimeError(f"{record.name}: simulator output has no {name}\n{tail}")
        row[name] = tuple(float(value) for value in match.groups())
    return row


def format_table(rows: list[tuple[str, float, dict[str, Any]]]) -> str:
    lines = [
        "% Generated by tools/tfg_sim_table.py -- do not edit by hand.",
        "%",
        "% Single-realization deterministic protocol: default seeds, final 900 s",
        "% of a 20-minute replay.  Not a multi-seed study.",
        "% Requires: \\usepackage{booktabs,siunitx}",
        "\\begin{table}[t]",
        "  \\centering",
        "  \\caption{TFG simulation results (last \\SI{900}{s} RMS window).}",
        "  \\label{tab:tfg_sim_results}",
        "  \\setlength{\\tabcolsep}{3pt}",
        "  \\renewcommand{\\arraystretch}{1.08}",
        "  \\footnotesize",
        "  \\sisetup{detect-all}",
        "  \\begin{tabular}{@{}l",
        "                  S[table-format=1.2]",
        "                  S[table-format=1.4]",
        "                  S[table-format=2.2]",
        "                  S[table-format=2.2]",
        "                  S[table-format=1.2]",
        "                  S[table-format=1.2]",
        "                  S[table-format=2.2]",
        "                  @{}}",
        "    \\toprule",
        "    {Case} & {$H_s$} & {Z RMS} & {Z\\,\\%$H_s$} & {3D\\,\\%} &",
        "    {Roll} & {Pitch} & {Yaw} \\\\",
        "    {} & {\\si{m}} & {\\si{m}} & {} & {} &",
        "    {\\si{deg}} & {\\si{deg}} & {\\si{deg}} \\\\",
        "    \\midrule",
    ]
    for label, hs, row in rows:
        z_rms = row["z_rms_m"][0]
        z_pct = row["z_pct_hs"][0]
        d3_pct = row["d3"][1]
        roll, pitch, yaw = row["angles"]
        lines.append(
            f"    {label} & {hs:.2f} & {z_rms:.4f} & {z_pct:.2f} & {d3_pct:.2f} & "
            f"{roll:.2f} & {pitch:.2f} & {yaw:.2f} \\\\"
        )
    lines += [
        "    \\bottomrule",
        "  \\end{tabular}",
        "\\end{table}",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--binary", default="tests/kalman_tfg/kalman_tfg-sim")
    parser.add_argument("--data-dir", default="plots/kalman_tfg")
    parser.add_argument(
        "--output", default="doc/kalman_tfg/tfg-sim-results-generated.tex-part"
    )
    args = parser.parse_args()

    binary = (REPO_ROOT / args.binary) if not Path(args.binary).is_absolute() else Path(args.binary)
    data_dir = (REPO_ROOT / args.data_dir) if not Path(args.data_dir).is_absolute() else Path(args.data_dir)
    output = (REPO_ROOT / args.output) if not Path(args.output).is_absolute() else Path(args.output)

    if not binary.exists():
        print(f"simulator not found: {binary}", file=sys.stderr)
        return 1

    rows: list[tuple[str, float, dict[str, Any]]] = []
    for label, hs, name in RECORDS:
        record = data_dir / name
        if not record.exists():
            print(f"record not found: {record}", file=sys.stderr)
            return 1
        rows.append((label, hs, run_record(binary, record)))
        print(f"scored {name}", file=sys.stderr)

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(format_table(rows), encoding="utf-8")
    print(f"wrote {output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
