name: kalman-tfg-paper

on:
  push:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  paper:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Compile TFG LaTeX paper
        id: latex
        continue-on-error: true
        uses: xu-cheng/latex-action@v4
        with:
          root_file: "*.tex"
          working_directory: doc/kalman_tfg
          work_in_root_file_dir: true
          latexmk_use_lualatex: true
          latexmk_shell_escape: true
          args: "-shell-escape"
          extra_system_packages: "inkscape ghostscript graphviz ncurses"

      - name: Compile TFG LaTeX paper, retry
        if: steps.latex.outcome == 'failure'
        uses: xu-cheng/latex-action@v4
        with:
          root_file: "*.tex"
          working_directory: doc/kalman_tfg
          work_in_root_file_dir: true
          latexmk_use_lualatex: true
          latexmk_shell_escape: true
          args: "-shell-escape"
          extra_system_packages: "inkscape ghostscript graphviz ncurses"

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v6
        with:
          name: latex-pdfs-kalman_tfg
          path: doc/kalman_tfg/**/*.pdf
          if-no-files-found: error

      - name: Upload PDF to release
        if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: doc/kalman_tfg/*.pdf
          tag: ${{ github.ref == 'refs/heads/main' && 'vTest' || github.ref_name }}
          overwrite: true
          file_glob: true
